### ISSUE TITLE
Determine string equality rules

### ISSUE THREAD

**Issue by erendrake** [KSP-KOS/KOS#1006]
We currently have some poorly defined rules for how string math works. i think we should decide how we want strings to behave as a group and make it happen

we currently support the following operations 

* Add - concatenation of left then right
* Subtract - exception
* Multiply - exception
* Divide - exception
* Power - exception
* **GreaterThan - length comparison?** 
* **LessThan - length comparison?**
* **GreaterThanEqual - length comparison?**
* **LessThanEqual - length comparison?**
* NotEqual - case insensitive equality check
* Equal - case insensitive equality check
* **Min - length comparison?**
* **Max - length comparison?**

**Bold** my emphasis on operations that i think need addressing

**Comment by abenkovskii** [comment]
> * Multiply - exception

In Python `"abc" * 4` = `"abcabcabcabc"`. We can implement this behaviour in kOS.

> length comparison?

It looks like it was intentional but in my view this @marianoapp's design decision is wrong and we should change it. If we leave string equality case insensitive we probably should also make other string comparisons case insensitive too. But then we'll have to add their case sensitive alternatives. 
For those alternatives I like two variants:
* `a caseequal b.`, `a casegrater b.` - @Dunbaratu's idea
* `a:caseequal(b).`, `a:casegrater(b).` // I like this one more because it defines the new operation only for strings and doesn't provide some weird options like this: `42 casegrater true`

**Comment by Dunbaratu** [comment]
Greater-than and less-than should definitely not be based on string length.  That's NEVER going to seem right to anyone.  It should be either alphabetical or asciibetical.

While I still really dislike the idea that equality is defaulted to case-insensitive and you go out of your way to make it sensitive and would like once again to say that's a bad idea and it should be the other way around (normally it's sensitive, go out of your way to make it insensitive), it's even worse to have an internal disagreement within kOS itself as to what equality means.  Therefore whichever way it ends up being, the meaning of greater/lesser should be using the same exact convention as the meaning of equal/notequal. i.e. if we go with the mistake of making equality be case-insensiive, then at least make that mistake consistent with itself and make it so that greaterthan/lessthan should match it and use the same convention.  This means that "AAA" is less than "aaa" if and only if "AAA" does not equal "aaa".  Similarly, if "AAA" = "aaa", that should also mean that "BBB" > "aaa" (a normal asciibetical check would make it go the other way around, because it puts all capitals before all lowercases.)

One last futile attempt to explain why I do not like defaulting to case-insensitive:  Because when you see a raw low level operator used, as in ```x = x``, you'd expect that to be a "more raw" sort of check than a similar check done with a method, as in ``x:method(x)``.  But @abenkovskii's suggestion of using a method for case-sensiive checking does the exact opposite of that.  It makes the operator a more cooked check than the method is.

So at the very least, if we have have to make the case-sensitive check the one that is not the default, at least make it an operator like ``a =case= b`` so it's on equal footing with the '=' operator and doesn't come across giving the illusion that its more cooked than the cooked case-insensitive operator is.  Something really rubs me the wrong way about having to pay the execution expense of going through OpcodeGetMethod, and then OpcodeCall call to obtain the operation that is in fact the cheaper simpler one.
