### ISSUE TITLE
[documentation] It's not mentioned in the docs that List's are compared by reference, not by their contents

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#1012]

**Comment by Dunbaratu** [comment]
It *sort* of is mentioned, but admittedly not very well.

It's not mentioned within the documentation for the list class, but there is a generic mention made that for all things that have suffixes, you are dealing with variables that contain references to them rather than having variables that contain their values, as is common in Java and C# and several other languages.

That contains the implication that equality checking will be shallow, not deep, but it doesn't explicitly describe it in detail, that's true.

It's not good enough to just say that in one place, I admit.
