### ISSUE TITLE
Raw controls for pitch and roll seem to be reversed.

### ISSUE THREAD

**Issue by yump** [KSP-KOS/KOS#1014]
This script tests the effects of applying positive yaw, pitch, and roll control inputs.  (It must, of course, be run in space.)

    @lazyglobal off

    function rot_att_rate {
    	return -ship:facing * ship:angularvel.
    }
    
    function zero_facing {
    	print "Aligning vessel with R(0,0,0)".
    	set ship:control:neutralize to true.
    	lock steering to R(0,0,0).
    	wait 8.
    	unlock steering.
    	sas on.  //SAS has better damping than lock steering.
    	wait 2.
    	sas off.
    	lock steering to R(0,0,0).
    	wait 5.
    	unlock steering.
    }
    
    function test_control {
    	parameter rotvec.
    	print "Initial facing is " + ship:facing.
    	print "initial attitude rate is " + rot_att_rate().
    	print "applying ship:control:rotation " + rotvec.
    	set ship:control:rotation to rotvec.
    	wait 1.
    	print "After 1s, facing is " + ship:facing.
    	print "After 1s, attitude rate is " + rot_att_rate().
    }
    
    zero_facing().
    test_control(v(1,0,0)). //positive yaw
    print " ".
    zero_facing().
    test_control(v(0,1,0)). //positive pitch
    print " ".
    zero_facing().
    test_control(v(0,0,1)). //positive roll
    print " ".

Output looks like this:

    Aligning vessel with R(0,0,0)
    Initial facing is R(0.002,-0.005,359.994)
    initial attitude rate is V(-0.000388246815418825, -0.000314757227897644, 0.000654640607535839)
    applying ship:control:rotation V(1, 0, 0)
    After 1s, facing is R(0,20.087,0.005)
    After 1s, attitude rate is V(0.000647060398478061, 0.67379766702652, -0.000465724238893017)
    
    Aligning vessel with R(0,0,0)
    Initial facing is R(0,0.017,0)
    initial attitude rate is V(-0.000100604658655357, -0.000654641014989465, 0.000715939735528082)
    applying ship:control:rotation V(0, 1, 0)
    After 1s, facing is R(336.641,359.985,-0.004)
    After 1s, attitude rate is V(-0.782880663871765, -0.000456628418760374, -0.00141100632026792)
    
    Aligning vessel with R(0,0,0)
    Initial facing is R(0.009,-0.002,0.001)
    initial attitude rate is V(-0.000648427463602275, -0.000137292488943785, 6.74702278047334E-06)
    applying ship:control:rotation V(0, 0, 1)
    After 1s, facing is R(359.983,359.991,299.838)
    After 1s, attitude rate is V(0.00213213032111526, -0.00186076725367457, -2.01752686500549)

Observe that a positive yaw input causes an increase in the ship:facing "yaw" angle, but positive pitch and roll inputs cause their respective angles to decrease.

Edit: Presumably, the pilot pitch and roll controls are also reversed.

**Comment by akrasuski1** [comment]
Also, kOS is said to use degrees everywhere - I just tested it, and it seems that `angularvel` output is in rad/s.

**Comment by Dunbaratu** [comment]
Man, fixing this would break all raw steering scripts for everyone, but you can't deny that it's bad for the rotation of the ship to not match the rotation of the universe.

One could argue that it could be right if *all* 3 directions were reversed - that's a matter of rotating the universe vs rotating an object in the universe.  But when only 2 of 3 are, that's basically a swapping of left handed vs right handed thinking.

I don't relish the backlash that fixing this would cause.

@erendrake, can you check this?  Raw control inputs was your thing and you'd be better positioned to see what's up and whether or not it's wrong.

My first inkling was to label this as not-a-bug because it looked like a misunderstanding of the fact that SHIP:STEERING's pitch,yaw,roll are referencing the universe's axes, not the ship's.  But then I see that you begin by orienting the ship along the universe's axes, aligning it with R(0,0,0) first, and then seeing if the ship direction change matches the universe direction change when changing on input at a time.

Like I said, an argument could be made that there exists an interpretation where it's right if all 3 axes are inversed, but not when it's only 2 out of 3.

**Comment by Dunbaratu** [comment]
> Also, kOS is said to use degrees everywhere - I just tested it, and it seems that angularvel output is in rad/s.

Can you make that a separate issue?

**Comment by akrasuski1** [comment]
Yup, just did it.

**Comment by yump** [comment]
I ran into this when I was writing a [attitude controller](https://github.com/yump/kos-scripts/blob/master/new-generic/libpilot.ks#L108) with the raw controls and found that it was necessary to do unnatural things to the signs to make it work.  It seems likely that anyone making a raw steering script would notice the same thing, so the lack of other complaints may indicate that there aren't many raw steering scripts out there depending on the behavior.

However, finding the necessary pitch, yaw, and roll corrections by rotating the target direction by the inverse of the ship's facing may not be a common approach.  If I had tried to synthesize them from `forevector`, `starvector`, and `topvector`, I can easily imaging being bamboozled by the trigonometry and overlooking it.

**Comment by evg-zhabotinsky** [comment]
Well, as might seem obvious from kOS code, raw attitude controls work this way just because they are passed to KSP as is. Why KSP works this way is entirely different and mostly unrelated question.

There is, in fact, the same inconsistency with fore and starboard RCS controls (positive values decrease corresponding velocity components). But is was spotted and now kOS inverts these controls before sending them to KSP (or after receiving them, for pilot controls).

Pitch and roll inconsistency was not spotted this way for whatever reason.

------

Another explanation might be that **it is natural** that positive pitch, yaw and roll values rotate ship right, up and clockwise respectively, much like *it is natural* for positive starboard, top and fore values to accelerate ship right, up and forward.

This argument, however, is not quite meaningful in context of autopilot programming, where mathematical consistency is more important.
(Using degrees instead of radians is also natural, but meaningless in this context, buy the way. But this is another story.)

------

**Another reason to invert pitch and roll positive directions.**
This is also for autopilot programming convenience.

[This Wikipedia article](http://en.wikipedia.org/wiki/Torque) contains some related theory.
Torque vector is parallel to rotation axis and its length is equal to applied torque.
In case of KSP's left-handed coordinate system, it points towards you when you see torque being applied in clockwise direction.

When you try to rotate ship **down**, **right** and **counter clockwise**, vector of applied torque points **right**, **up** and **forward**, that is, **along x, y and z axes** in ship coordinates (or world coordinates, if `ship:facing = D(0,0,0)`).

More precisely, **if pitch and roll controls will be inverted**, positive pitch, yaw and roll will rotate ship down, left and counter clockwise respectively, and corresponding torque vectors in ship coordinates will be `(maxTorque * pitch, 0, 0)`, `(0, maxTorque * yaw, 0)` and `(0, 0, maxTorque * roll)`.

And because you can just sum torque vectors together, the **vector of total torque applied to ship with attitude controls** in ship coordinates will be `maxTorque * (pitch, yaw, roll)`, or `maxTorque * rotation`.
If pitch and roll will be inverted, that is. Otherwise you'll have to add two minus signs.
And if someone will finally make `rotation` be `(pitch, yaw, roll)` and not `(yaw, pitch, roll)`, since it's total nonsense.

All this, obviously, applies to vacuum only. In atmosphere, of course, things will be a bit more complicated.

------

**Arguments NOT to invert anything**
* It's natural for positive rotations to be up, right and clockwise.
* Current behavior is specified in documentation, and this change will break backwards compatibility.

Are these arguments heavy enough to prevent change? I don't know.
Does anyone *really* need this change? I don't know either.

**Comment by yump** [comment]
The extra minus signs are confusing for people writing autopilots, because when your would-be autopilot causes the ship to spin wildly, the usual troubleshooting step of reversing the feedback doesn't work.  You have to reverse *some* of the feedback, which is a much less expected failure mode.  Plus, there are 8 possible combinations instead of just 2.

It's also a performance consideration for people who feel like increasing config:ipu is cheating.  Getting your autopilot update cycle under 200 instructions with the sign fixup in there can be a bit troublesome.  If my benchmarking script is correct, the obvious approach:

    set rot:y to -rot:y.
    set rot:z to -rot:z.

costs 14 instructions, while inverting the yaw and then the whole vector:

    set rot:x to -rot:x.
    set rot to -rot.

gets it down to 11.

I propose adding ship:control:nativerotation and ship:control:pilotnativerotation, which would use V(-pitch, yaw, -roll).  That solves the backwards compatibility problem, and makes the lives of new autopilot writers easier if the documentation strongly recommends their use in new code.

I think I have gotten familiar enough with the codebase to implement this.

**Comment by Dunbaratu** [comment]
> I propose adding ship:control:nativerotation and ship:control:pilotnativerotation

As bad as breaking backward compatibility is, I don't think it's as bad as having two different variants of the system JUST for backward compatibility.  I'd rather just break compatibility than have these two different variants.

But I am going to be examining this in detail later.  I just haven't given it priority because, as a breaking change, I don't want it to end up in the next 0.17.3 update.  It should go in a more major version number update after that.

**Comment by ianjirka** [comment]
Small suggestion:
(purposely setting aside API naming for a moment)
Have both variants in 18.x, with the old one deprecated.  On compile /run, print a warning to the console that the given library/program uses deprecated functions.
In 19.x remove them.
If you're feeling extra nice, provide wrappers as part of the community library and have the warning point to appropriate docs.

This approach should be sustainable and a reasonable balance for existing code plus not cluttering up the system over time - as far as these thing to anyway.  Other suggestions like @newbehavior or adding an operating mode to the SPU break down after you do this a few times.

Good to see a willingness to evolve without being willy-nilly about it.

Cheers

Ian Jirka
GrimerX

Sent from my Windows Phone
________________________________

**Comment by yump** [comment]
Heh, [good thing I didn't start in on the documentation yet](https://github.com/yump/KOS/tree/nativerotation-localwork).  It did shave my autopilot update cycle down to 187 instructions from 198. With the correct (pitch, yaw, roll) order, I was able to use ship:angularvel for the derivative directly, and avoid calling an expensive function that turns rotations into vectors.  That brought it down to 141 instructions.

I agree that replacing the current raw controls is better than keeping them for compatibility.  There are only two Google results for "ship:control:rotation" that aren't bogus or part of this repository.

**Comment by hvacengi** [comment]
@Dunbaratu didn't you test this on your live stream and determine that the directions were not reversed?

**Comment by Dunbaratu** [comment]
@hvacengi Yes. This should be closed.
