### ISSUE TITLE
Radians instead of degrees.

### ISSUE THREAD

**Issue by akrasuski1** [KSP-KOS/KOS#1021]
`angularvel` for vessel is in rad/s.
`meananomalyatepoch` for orbit is in radians.

**Comment by Dunbaratu** [comment]
> meananomalyatepoch for orbit is in radians.

Already fixed in develop, but not yet released.

> angularvel for vessel is in rad/s.

But this is new.

**Comment by akrasuski1** [comment]
I have no means of checking this, but it is likely that angularmomentum is in wrong units as well.

**Comment by Dunbaratu** [comment]
AngularMomentum sort of can't be changed to degrees, like it or not.  This is because it's calculated using radians precisely because doing so causes the units to cancel out in the equation and be entirely missing from the final number.  The final number never even mentions the kind of rotational measure that was used to calculate it.  During the calculation of Angular Momentum, you must convert your angular velocity (which IS in degrees or radians and the units matter) into lengths of radius because angular momentum is basically unrolling from the world of angular measures back into the world of linear measures - you're trying to compare the rotation rate to the average lever arm distance of the object's mass from its own center (which is what goes into rotational inertia)

In other words, if using degrees for your angular velocity, you had to convert those degrees into radians in the first place before calculating angular momentum.  Once calculated, the units divide away and drop off and you're left with a measure that doesn't mention the units of rotation anymore.

When making use of angular momentum in a calculation, if you work in degrees you have to perform a conversion, if you work in radians you don't, and that can't really be changed in kOS without basically introducing a new physics nomenclature for what the words "angular momentum" actually mean.  The fact that they presume the units are in radians to begin with is embedded into the very definition of the term, and the means by which it's calculated. We can't just convert that one.

Angularvel, on the other hand, can be made into degrees.

**Comment by akrasuski1** [comment]
Fair enough. Although the 'real' units for angular momentum are kg*m^2 * rad/s, the *rad* term is skipped almost always - so I understand your issues. We can just make angularvel using degrees, and make angularmomentum stay the way it is.

**Comment by Dunbaratu** [comment]
In reading this old issue I noticed the docs still refer to ANGULARVEL in a few places as being a direction instead of a vector.  Not closing because that documentation still needs fixing.

**Comment by erendrake** [comment]
Closed by #1341
