### ISSUE TITLE
Variable parameter count?

### ISSUE THREAD

**Issue by evg-zhabotinsky** [KSP-KOS/KOS#1031]
I have found that reaction to passing wrong number of parameters **when running a program** is inconsistent. (Calling functions works as expected.)

Passing too many arguments usually ignores first arguments and everything works.
Passing too few is more funny.

It often shows the proper error message (BTW it is quite misleading, stating things like "Too few arguments were passed **to print**").

It sometines complains about unbound instances.
I get something that prints as "$argpart" (not sure, could not get it while writing this) moderately often.

Running program with 1 parameter declared from terminal with no parameters consistently results in that only parameter being zero. I even thought it is the way all unspecified parameters are marked.

------

Alternative fix/suggestion: report missing parameters as some predefined value (null?) and allow testing for it (both for programs and functions). That way it will be possible to implement functions with variable parameter count. Not sure if it is possible with your bytecode.

**Comment by abenkovskii** [comment]
1. Yes. The the wrong number of arguments passed to a function or to a program is an undefined behaviour because it causes stack misalignment.
2. Your idea is nice but I'd prefer `parameter param_name default expression.` syntax.
3. We can change our bytecode if we want. And we are doing it from time to time.

**Comment by evg-zhabotinsky** [comment]
Ignore the "alternative fix" words i've written.
You still need to figure out if the parameter was specified or not, and this is broken for programs.
Maybe there should be two separate issues?

**Comment by abenkovskii** [comment]
> Maybe there should be two separate issues?

No. In my view it's two sides of the same problem.

**Comment by Dunbaratu** [comment]
Calling a program and calling a function use slightly different techniques, under the hood.  Once upon a time there was no checking for program parameters at all.  It just let the stack get misaligned without mentioning anything and then whatever other error that happened to cause later is the error you saw - usually involving something not being the expected type (because the stack misalignment made it pop the wrong item from the stack into the variable in question).

This problem was dealt with for functions when functions were added, by adding an extra padding stack parameter, a string called "$<argstart>" that gets put on the stack to mark where the boundary between other stuff and the passed arguments are, and then popping it back off when returning from the function.  But not all of that approach got back-ported into the run program code.  The run program code pops the "$<argstart>" to avoid stack mismatch, but it doesn't have all the work to check the number of args.


One very ugly problem is that ages ago, Kerboscript got defined to allow (and I find this a very bad idea, but it was how the language was defined before I got my hands on it) a mishmosh of DECLARE PARAMETER statements mingled with actual code.

For example, it is legal to rewrite this:
```
declare parameter x.
declare parameter y.
declare parameter z.
print x/3.
print y*2.
print z+y+2-x.
```
as this instead:
```
declare parameter x.
print x/3.
declare parameter y.
print y*2.
declare parameter z.
print z+y+2-x.
```
You don't need to do all your `declare parameter` statements up front at the top.  You can wait until just before you need the variable, and then do it then.

This ugly fact is why the misalignment can't be detected until the end of the section, after the execution has finished.  Until it hits the end, it doesn't yet know whether there's enough declare parameter's to match the number passed in.

And that means that in the case of a mismatch, it can end up trying to use the mismatched parameters before it realizes they're mismatched, so instead of the mismatch error, you get a type conversion error where you tried to use a string like an integer, or something like that.

**Comment by abenkovskii** [comment]
We can add `assert parameters end.` command and recommend our users to declare parameters before calculating anything.

**Comment by evg-zhabotinsky** [comment]
IDEA!
------
Make every function accept **exactly one parameter - a list!**
And turn multiple parameters into syntactic sugar.

That is, `run prog(arg1, ..., argN).` will actually work like `run prog(list(arg1, ..., argN)).` in current syntax.
And `DECLARE PARAMETER X.` will work like `LOCAL X IS PARAMETERS[number]. SET number TO number + 1`, where `number` is amount of times `DECLARE PARAMETER` was already seen in this function. And of course `PARAMETERS` and `number` will be initialized to proper values at function start.
`number` should not be exposed to user (maybe variable with invalid name?), or, better, only exist during compilation (is it possible?). In latter case, it might be useful to check list length on function start.
`PARAMETERS` definitely should be exposed, maybe as `PARAMETERS()` or `DECLARE PARAMETERS X.` instead.

Allowing to pass that argument list directly will also be useful, but I am not sure about syntax.
For programs, `runlist prog(list).` looks reasonable, but I am not sure about functions.
Maybe `calllist(function, list).`?

Such solution will both fix problems with wrong argument count and allow functions with variable argument count (and thus with with default parameter values).
It will also allow to generate argument lists programmatically.
(Possible use: program that copies program specified by first argument from to 1, switches to 1 and then runs that program with remaining arguments.)

------

Side note: it might also be useful to add syntactic sugar for returning lists and storing their elements into several variables. (a-la tuples in Lua or Python).

**Comment by hvacengi** [comment]
@evg-zhabotinsky forgive me if I'm telling you something you already know, but you can already use lists to pass your parameters to functions or programs, and for returns from functions.  In fact, since lists accessed by reference, it used to be the only way to get data back when running a program.  But if you like that method, you're certainly able to do it with kerboscript now.

I'm not a fan of forcing people to use lists.  Later in the comment it sounds like you're not in favor of it either, but that's what the opening of the comment sounds like, so I wanted to be clear.  I don't like to create more objects than needed, so an extra wrapper around parameters (especially something like 1 or 2 parameters) just doesn't feel right.

There has been discussion of user defined structs, which might do what you want as well, but I don't know where that is on the roadmap right now.

As for the builtin functions: we're working on getting argument counts handled and expressed a little better, which includes some more detailed messages.

@abenkovskii if adding a way to assert the parameter list is done, why not just provide an option to assert the expected parameter count?  `assertparam 2.` would throw an exception if 1 or if 3 parameters are passed to the program.

**Comment by evg-zhabotinsky** [comment]
Well yes, I wanted to write about extra overhead, but somehow forgot that.
So, "tl;dr":
What I suggested is basically to force using lists to solve problems with argument count for a bit of overhead, and cover this slightly ugly solution with syntactic sugar, with ability to ignore the sugar on both caller and callee sides for extra flexibility.

**Comment by abenkovskii** [comment]
> `assertparam 2.`

How I see it:
```
function foo {
  parameter a.  // throws an exception if <argstart> is popped
  parameter b.
  assert(paramend(), "too many parameters passed").
  ...
}
function bar {
  assert(paramcount() = 3).
  ...
}
```

**Comment by Dunbaratu** [comment]
I don't know why this didn't auto-close when the PR above was merged.  Was an enhancement but is now done.
