### ISSUE TITLE
kOS nametag module removable via MM

### ISSUE THREAD

**Issue by kaufman-bryce** [KSP-KOS/KOS#1064]
Certain other mods are playing silly buggers with certain OTHER mod's parts, the result of which is that those parts no longer have the KOSNameTag module on them.

Specifically, SETI overrides most of Procedural Parts by running a `!MODULE,* { }` and then rebuilding the appropriate modules itself. Because SETI loads after KOS, this removes the nametag as well. There may be other mod combinations that do this to other parts, I don't know.

Easy solution is to change the `@PART[*]:FOR[KOS]` to `@PART[*]:FINAL` in kOS's MM file. This will ensure that all parts always have a nametag under any circumstance.

**Comment by hvacengi** [comment]
That's a little frustrating.  IMO their mod should only delete values that the modify, not outright delete them all (which is opening the door for major failures if something is missed, or a part gets changed).

It is my understanding that final is intended to be used in an instance where no other mods are expected (or essentially allowed) to modify it, or when it needs to modify something that is added by another mod.  I'd say this satisfies both conditions.  I'm not sure that `:FOR[KOS]` is really doing anything anyways, I always thought that FOR was used to set NEEDS to true, but that it was also configured internally based on the mod's folder or dll name.

Have you tested this already @kaufman-bryce? I want to say that MM is able to delete modules from within a save file, in which case the value of the nametag may not persist when you launch KSP the next time.  If the name tags persist, I'll modify the patch so that we can avoid this issue.  If they don't persist, then it will have to be a request to the manager of SETI.  (name tags don't do much good if they revert to blank every time you start the game)

If I have some time during the day I'll test this.  Otherwise I won't be able to test for a couple of days.

**Comment by kaufman-bryce** [comment]
I have tested this, and persistence is a non-issue as modules are only added/removed from saves when they are loaded; the only way to lose the tag would be to revert back to the existing MM patch.

The `:FOR` tag causes the patch to be applied at the same time the associated DLL loads. It interacts with the `:NEEDS` tag as a way of ensuring patches are applied in the correct order. I.E. if mod A is trying to alter mod C, it needs the `:NEEDS[C]` tag because folders are processed alphabetically and C doesn't exist yet when A's MM patches are parsed.

**Comment by hvacengi** [comment]
Thanks for clarifying (I couldn't find any of that on a quick search of the MM wiki, so I'm glad you know).

I'll get it into a PR shortly (unless you want to yourself).  I think we're shooting for a release pretty soon, so it should be taken care of going forward.

Thanks for the catch!

**Comment by erendrake** [comment]
I am reluctant to move our patches to final because the nature of the kOSTag patch is quite invasive and the only reason i was ok with adding a module to every part it is that users or other modders could remove it in a later pass like `FINAL` if they wanted to. I dont think this is a kOS issue at all, it is a SETI issue.
