### ISSUE TITLE
Quickstart tutorial is obsolete and fails in KSP 1.0's aero model

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1072]
The documentation's quckstart tutorial is confusing for new players I think because it describes being able to perform a crude launch by going straight up to 10km, then turning 45 degrees, etc - the sloppy way that used to work prior to KSP 1.0.

There's no way that a new user, unaware of the way KSP used to behave in its early access days, would find that tutorial believable anymore.

We need a new quickstart for the new areo model.  Its got to be really simple but still not flip in new stock areodynamics.

Suggestion: instead of claiming it will work with "any" rocket, we instead specify the exact rocket build the tutorial is designed for.  Then we can still hardcode the steering angles but guarantee a successful launch with the example craft.  (Then the tutorial can even go on to try the same program on a second rocket design, known to fail with those steering angles - maybe it has a smaller TWR and thus doesn't have the same flight curve so hardcoding the same steering points will point it off prograde and cause a flip.  It could do this as a teaching moment explaining why it's better to write the script more generically, as a lead-in for a more smooth launch script as a future part 2 to the tutorial.)

**Comment by eblume** [comment]
There are related atmospheric documentation issues in http://ksp-kos.github.io/KOS_DOC/structures/celestial_bodies/atmosphere.html#atmospheric-math

Particularly, this equation:

    Number of Atm’s = (Atm’s at sea level) * ( e ^ ( - sea_level_alt / scale ) )

Seems to be a bit wrong. I'm brand new to atmospheric equations but plan on writing a lib_atmosphere for KSLib, and will try to update these docs with my findings (along with newly tuned ascent profiles, if I can manage that, for the tutorials.)

**Comment by Dunbaratu** [comment]
It's referring to how stock used to work before 1.0.  It's completely wrong now.

**Comment by eblume** [comment]
Ok, thanks for letting me know before I wasted too much time on those calculations. :)

I did some searching for details on the new aerodynamic/atmospheric model and there's a lot of forum conjecture but I'm having trouble tracking down official word or verified claims. Do you know of some place I can find better info or should I begin an investigation with in-game modeling?

**Comment by hvacengi** [comment]
Honestly, if I need to know how the game calculates something, I look at the decompiled source of the assembly.  If you download ILSpy, you can open Assembly-Csharp.dll and see the classes.  There is some code that is hidden, and some that is decompiled in a way that doesn't make much sense, but it reveals how the game actually runs.  For instance, in game the pressure at a given altitude is apparently:
`return this.atmospherePressureSeaLevel * Math.Pow(1.0 - this.atmosphereTemperatureLapseRate * altitude / this.atmosphereTemperatureSeaLevel, this.atmosphereGasMassLapseRate);`
on celestial bodies without an atmospheric curve and:
`return (double)Mathf.Lerp(0f, (float)this.atmospherePressureSeaLevel, this.atmospherePressureCurve.Evaluate((float)(altitude / this.atmosphereDepth)));`
for normalized atmospheric curves, and:
`return (double)this.atmospherePressureCurve.Evaluate((float)altitude);`
for all other cases.

I just used that info as an example since it was referenced above.  Honestly, that curve might be the curve of exponents of e.  But it shows the level of data available.

**Comment by eblume** [comment]
Would it be a better idea, instead of tracking down all the specific ways of calculating pressure for a given altitude, to modify kOS to expose this as a suffix of `Atmosphere` or `Body` (the former seems more appropriate)?

I've not done much C# coding and absolutely no KSP modding so this is probably beyond what I could be able to contribute, but I'm willing to try if it isn't a bad idea.

**Comment by erendrake** [comment]
@space-is-hard 's new quickstart should be up here http://ksp-kos.github.io/KOS/tutorials/quickstart.html
