### ISSUE TITLE
Fully automated science

### ISSUE THREAD

**Issue by tomekpiotrowski** [KSP-KOS/KOS#1075]
If I'm not mistaken currently there is no way to fully automate the science gathering process using kOS. After you run for example `module:doevent("observe materials bay")` a window pops up and a user intervention is required. Specifically there is no way to Transfer Data back to Kerbin programmatically. 

Has anyone ever tried to tackle that problem? I saw that it was mentioned briefly in #60. Or does clicking few buttons simply does not bother anyone enough? :)

**Comment by erendrake** [comment]
I went into the code a few updates ago and it was going to be quite hard to get around the need for a user to click the window. This seemed fine to me because we had a solid workaround with actiongroups and AGX that could be coupled with a few mouse clicks that were not time critical. 

It might be easier to do now and if so i think its a great idea. @tomekpiotrowski do you know of other mods that automate science gathering in this way so we can "learn from" their code :)

**Comment by tomekpiotrowski** [comment]
Ok, looks like I have it working more or less. I'll try to post a testable PR in a couple of days.
