### ISSUE TITLE
Raising negative numbers to a power sometimes results in NaN

### ISSUE THREAD

**Issue by Forkk** [KSP-KOS/KOS#1086]
Raising a negative number stored in a variable to any power seems to always result in NaN, while raising a negative literal to any power works fine.

For example, the below code causes a "tried to push NaN into the stack" error.
```
set a to -0.1337.
print a ^ 0.4.
```

This code, however, works fine.
```
print -0.1337 ^ 0.4.
```

I would expect both of these examples to work fine without returning NaN, but that doesn't seem to be the case.

**Comment by Biotronic** [comment]
The reason here is the precedence of operators. Your first example is equivalent to `(-0.1337)^0.4`, while the second is `-(0.1337^0.4)`.

The second example gives a result of ~ `-0.44715`, which is representable in Kerboscript's type system. The first on the other hand, is the [complex number](https://en.wikipedia.org/wiki/Complex_number) `0.138 + 0.425i`, where `i` is the [imaginary unit](https://en.wikipedia.org/wiki/Imaginary_unit). This does not fit in a single [floating point](https://en.wikipedia.org/wiki/Double-precision_floating-point_format) variable.

It's theoretically possible that Kerboscript will add support for complex numbers in the future, but in this case the cause of your problems is much more likely a bug in your own code than a missing feature in kOS.

**Comment by Forkk** [comment]
Fair enough. I guess I somehow forgot that raising to 0.4 would actually be taking a root. I would expect that the unary minus operator should have a higher precedence than exponents, though, shouldn't it? Regardless, that is a separate issue.
