### ISSUE TITLE
When reading ship:control:pilotmainthrottle and zeroing the throttle, the variable doesn't zero out

### ISSUE THREAD

**Issue by mariohm1311** [KSP-KOS/KOS#1087]
That was a long title. Basically I have this: 

clearscreen.

until altitude > 90000 {
	list engines in engineList.
	set shipThrust to 0.
	for eng in engineList {
		if eng:ignition {
			set shipThrust to shipThrust + eng:thrust.
		}
	}
	set twr to (shipThrust/(ship:mass*9.81)).
	print "Throttle level: " + (ship:control:pilotmainthrottle*100) at(0,0).
	print "Current thrust: " + shipThrust at(0,1).
	print "TWR: " + twr at(0,2).
}

wait until altitude > 90000.

It reads the engines' thrust and gets the Throttle level, the thrust, and the TWR. But if I throttle down to 0, the readings don't zero out.

**Comment by hvacengi** [comment]
What happens if you move the clearscreen command into the loop?  `print ... at ...` does not clear any of the trailing characters, so any hanging decimals will still display.  That is to say, if you type `print "0123456789" at (0,0).  print "x" at (0,0).` the display would read "x123456789".
```
until altitude > 90000 {
    clearscreen.
    list engines in engineList.
    set shipThrust to 0.
    for eng in engineList {
        if eng:ignition {
            set shipThrust to shipThrust + eng:thrust.
        }
    }
    set twr to (shipThrust/(ship:mass9.81)).
    print "Throttle level: " + (ship:control:pilotmainthrottle100) at(0,0).
    print "Current thrust: " + shipThrust at(0,1).
    print "TWR: " + twr at(0,2).
}
```

**Comment by mariohm1311** [comment]
Yeah, it's that. But how can I make only the numbers update without making the screen flicker (as it's deleting and writing each cycle).

**Comment by space-is-hard** [comment]
Print a bunch of spaces afterwards. They'll overwrite the now-unneccessary digits.

**Comment by hvacengi** [comment]
To expound on @space-is-hard's suggestion: `print "                    " at (0,0).` will clear 20 characters.  So:
```
clearscreen.
until altitude > 90000 {
    list engines in engineList.
    set shipThrust to 0.
    for eng in engineList {
        if eng:ignition {
            set shipThrust to shipThrust + eng:thrust.
        }
    }
    set twr to (shipThrust/(ship:mass9.81)).
    print "                    " at (0,0).
    print "Throttle level: " + (ship:control:pilotmainthrottle * 100) at (0,0).
    print "                    " at (0,1).
    print "Current thrust: " + shipThrust at(0,1).
    print "                    " at (0,2).
    print "TWR: " + twr at(0,2).
    wait 0.001.
}
```
How much blinking are you getting?  I use the clearscreen technique frequently without issue?  I just added a "wait" command to your loop, it is possible that the code execution was pausing mid screen update because you hit the max instruction limit, which could cause a blink.  Try adding a wait using the clearscreen technique, because it looks like this should be under 200 instructions per loop.  I usually recommend using `wait 0.` or `wait 0.001` in `until` loops anyways, since you won't have any ksp data change until the next physics frame anyways.  It prevents you from wasting instructions on stale data.  That will be a bigger deal when we implement electricity usage based on instructions.

**Comment by Dunbaratu** [comment]
Am I to understand that the issue is named incorrectly in the title, and it's just a matter of the script's display not clearing the numbers from the screen?  (That there isn't really a bug here and this issue should be closed as a not-a-bug)?

**Comment by erendrake** [comment]
@Dunbaratu i think you are right
