### ISSUE TITLE
[1.0.4][0.17.3] alt:radar works on Kerbin - broken on Mun

### ISSUE THREAD

**Issue by baloan** [KSP-KOS/KOS#1091]
Can do ```print(alt:radar).``` on Kerbin manually. Also used in ltoa.ks. And my ship is getting there.
![alt_radar](https://cloud.githubusercontent.com/assets/651799/8580977/fc7fd9e4-25bd-11e5-8e0a-d80d901332f5.PNG)

**Comment by space-is-hard** [comment]
Works for me:
http://i.imgur.com/R7CFVlT.png

Can you post a link to the script in question?

**Comment by baloan** [comment]
1. Take https://github.com/baloan/mt-kos/tree/master/ships from https://github.com/baloan/mt-kos/tree/master/ships
2. Take all scripts from https://github.com/baloan/mt-kos/tree/master/script
3. Goto Vehicle assembly building, select the ship
4. Then ```run kamc0.```.
I'm also encountering random errors - mostly during warpto periods. Maybe this error is related. Then it would not be reproducable. Since the breakdowns occur at different stages of the scripts I don't think it is one of those embarrassing variable collisions...

**Comment by space-is-hard** [comment]
Could you also replicate the error and then post your .log file?

**Comment by Dunbaratu** [comment]
I'm reasonably sure the problem is described incorrectly.  It's not because Mun differs from Kerbin, but because your code did something by the time you got to the Mun than it hadn't done yet when you were still at Kerbin.

Specifically, I think it's this:
In aponode.ks, and in perinode.ks you have this line:
```
      declare parameter alt.
```
This is most likely hiding the built-in variable ALT.

If this is the case it would mean the actual bug is that after aponode.ks and perinode.ks are done running, it should have removed ALT from memory and it shouldn't still be around hiding access to the underlying built-in variable ALT, but somehow it is.

**Comment by space-is-hard** [comment]
It seems that you've got `alt` set as a variable somewhere. `alt:radar` is an alias, and `alt` isn't actually its own structure that you can have suffixes on. The only reason `alt:radar` gives you your radar altitude is that it's a specifically defined alias. This means that it's still possible to assign a value to a variable named `alt`, which the code is then attempting to call a suffix on.

**Comment by baloan** [comment]
Log file is at http://ksp.baldev.de/kos/issue-1091
The issue happens at 22:01:47.051.

**Comment by baloan** [comment]
Sounds reasonable, Dunbaratu. This was never an issue in previous versions. Just upgraded to 0.17.3.

**Comment by hvacengi** [comment]
One thing that doesn't make sense to me though is that it should have gotten cleared away because it's a local variable.  Does setting the local variable mess up the binding of alt internally?

@baloan If you go back to the space center and resume the flight (without executing the code that sets alt to a number) is `print(alt:radar).` still an error on the mun?

**Comment by Dunbaratu** [comment]
If you've just moved to 0.17.3, I'd recommend changing a lot of these utility programs to be functions instead.  The system handles them a bit nicer because they get to have local variables.  I suspect having  a local parameter called 'alt' for a function wouldn't cause the same problem.  For backward compatibility we had to leave all the variables in programs' main code in the same global space as each other to accommodate all the old programs that expected that behavior.  I'd have rather made a "file scope" for each program but that would have broken scripts like yours even worse.

**Comment by hvacengi** [comment]
Ah, that's why, the local doesn't behave the same from `run` as it does in a function.

**Comment by Dunbaratu** [comment]
> Ah, that's why, the local doesn't behave the same from run as it does in a function.

But if that's what's happening, then it's still a bug - it's supposed to, or so I thought.  Then again I don't think I ever tested this with old versions to know if it did.  The bug surfaced because the code changed "alt:radar" from a clunky weird alias (that, oddly was being captured in the same code that made everything lowercase) into an actual real suffix of an actual variable, like it LOOKS like it is.

**Comment by Dunbaratu** [comment]
The old design was this:

* alt_radar is the actual bound variable name
* alt:radar gets search-replaced by doing the equivalent of s/alt:radar/alt_radar/g on the code during the lowercasing step.

That got really messy when we had to ditch the lowercasing code and instead only lowercase the identifiers and nothing else.

So the new design is this:

* alt_radar is deprecated.  Users have to replace it with alt:radar.
* alt:radar is no longer dealt with by an ugly search-replace.  Now alt is an actual bound variable and it has a suffix :radar.

Until the above change was done, 'alt' was safe for users to use as an identifier without it messing up alt:radar because alt:radar wasn't *Really* a suffix of alt like it looks like it is.

**Comment by baloan** [comment]
> If you've just moved to 0.17.3, I'd recommend changing a lot of these utility programs to be functions in
instead.

> You cannot call functions from the interpreter interactive command line if they were declared inside of script programs.

As long as functions cannot be called from the interpreter this is really not an option. One big plus of kOS is that I can interactively call aponode() and exenode() to change orbits.

**Comment by Dunbaratu** [comment]
not the bug it was described to be.
