### ISSUE TITLE
Boot files can be larger than the drive they're set to load on

### ISSUE THREAD

**Issue by space-is-hard** [KSP-KOS/KOS#1094]
![screenshot1](https://cloud.githubusercontent.com/assets/10237092/8637817/afefebde-2872-11e5-866b-057eb22aab6c.png)

**Comment by hvacengi** [comment]
I can add the free space check to the initialization code. I'll have to look a little bit to make it so that we can throw an exception logging it to the terminal without breaking the fixed update (because we need to let the user know why the file isn't there when they expect it). Should we maybe look for a way to alert the user to this in the VAB?

**Comment by hashashin** [comment]
If the boot file is larger than the disk just don't show it in the boot file chooser in the VAB?
