### ISSUE TITLE
Function arity broken in recursive contexts

### ISSUE THREAD

**Issue by gisikw** [KSP-KOS/KOS#1100]
Was helping out someone on the subreddit, and discovered that the arity check on a function is bypassed when a function is called recursively. Repro case follows:

```
FUNCTION foo {
  PRINT "foo".
}
foo(5)
```
^ correctly throws "args passed didn't match params declared"

```
FUNCTION foo {
  PRINT "foo".
  foo(5).
}
foo()
```
^ this will run until it stack overflows

And the very odd case:
```
FUNCTION foo {
  PRINT "foo".
  foo().
}
foo(any, arbitrary, number, of, arguments).
```
^ also runs until it stack overflows

In short, it appears whenever recursion is used, the arity check is bypassed, both in and out of the function context.

**Comment by Dunbaratu** [comment]
The check happens at the end of the function, when returning.  Therefore if you do infinite recursion, since none of the function calls ever reach the end and return, you end up never executing the check.

Add a base case to terminate the recursion and you'll get the args check happening at the innermost nest level of the recursion - the first time one of the function calls actually tries to return.

The two stack overflow examples would have stack overflowed anyway even if the argument count had been correct, due to the infinite recursion.

So I don't consider that a big deal, given that if someone had code like the examples you show, that has two errors in it: 1 - It calls a function with the wrong number of arguments, and 2 - it has infinite recursion without a base case, then they would still eventually detect both errors, just in the opposite order.  They wouldn't discover the wrong number of arguments until they corrected the infinite recursion, as opposed to discovering the two problems in the opposite order, but still having to correct both of them before having working code.


The reason the check is at the bottom is that you're allowed to have varying arguments with code like so:

```
// consume args until a 0 is found:
local sum is 0.
local val is 0.
until val = 0 {
  parameter nextval.
  set val to nextval
  set sum to sum + val.
}
```
Because this is allowed, the check waits until the end to see how many parameter statements there were.  I doubt anyone is using this ability, though, and it's a bit clunky, so I may consider changing it to a fixed number of parameters and only allowing parameter statements at the outermost level.

varying args could be implemented by use of a LIST structure instead, for programs that want that.

**Comment by gisikw** [comment]
Aha! That's sneaky, but a clever way to shoehorn in optional arguments :) Personally, I can't think of a real use case, unless missing parameters were auto-initialized to 0 or something (allowing flags like `HAS_BURNT_OUT(autoStage = 0 || 1)`). Still, that's clever!

I'll close this out, since it's "works as intended" :)

**Comment by Dunbaratu** [comment]
I'm still not entirely happy with the current situation as it allows stack misalignment to not be detected until it's too late, after it assigned the wrong argument to a parameter.  This leads to a lot of confusion over the cause of an error.  You get type errors like trying to take a suffix of an integer, where the reason for the error is that argument 2 is being placed in argument 1's position because the number of arguments doesn't match.  But the fact that they don't match isn't detected until the bottom, so it's the type mismatch that causes it to error out first.  This is causing a lot of unnecessary confusion so I may remove this ability entirely and put the check up at the top where it belongs.

**Comment by gisikw** [comment]
That makes sense to me. I did double-check the docs, and there isn't a mention of a technique for managing arbitrary function arity, so I don't many folks have scripts based on it. As you said, passing in lists as arguments offers the same dynamic behavior, so it should be an easy enough switch for the few who do.
