### ISSUE TITLE
Make orbit's LAN useful by exposing Reference Direction to scripts, and making an AN vector.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1116]
Read this user's problem:

http://forum.kerbalspaceprogram.com/threads/130163-Finding-normal-vector-to-arbitrary-orbit?highlight=kos

RIght now the longitude of the ascending node is a useless suffix of ORBIT because it's an angle measured from a super secret Reference Direction that scripts CANNOT find out what it is.

We need to do two things to fix this:

(1) Expose users to a vector that represents the current Reference Direction of the solar system, expressed in whatever the current Ship-Raw coords are rotated to at the moment. There seem to be hints from user-community docs at the "antaid" site that Planetarium.Right might be the KSP solar system's Reference Direction.

This value, it should be stressed, is NOT a property of any particular orbit.  It's a global game property of the solar system as a whole, even though its value expressed in ShipRaw coords will keep changing as the X and Z axes keep rotating in that lovely KSP wacky way every time you land/liftoff from a body.  But the point is it should not be a suffix of ORBIT or of anything else.

(2) While we're at it, we should just make an ascending node vector suffix for orbit.  ORBIT:ANVECTOR or something like that.  It would be the vector pointing from the orbit's SOI body's center toward its ascending node (either a unit vector, or the actual distance to the orbit at that point if we think we can calculate that fast enough).  We could calculate this ourselves by use of the LAN combined with the reference direction mentioned in (1) above.

Why we need both (1) and (2) - (2) is way nicer and simpler as an orbit suffix, but it doesn't help in the scenarios where the orbit doesn't really exist yet because it's not attached to a current object, as in the case of the user who's post I linked to at the top.  For that user they'll need (1) in order to calculate what the LAN means because there is no way to obtain an ORBIT without a vessel or body to get it from.  (Besides, what would the concept of the "current" position of such an orbit be?  Without that defined, much of the data of Orbit is not specifiable.)

**Comment by Dunbaratu** [comment]
oops.  I clicked the wrong thing.  re-opening.

**Comment by chippydip** [comment]
While this seems like a good idea for convenience, it's pretty easy to calculate these values with the current API. Getting your current "reference longitude" is a simple matter of adding a couple orbital angles:

    local refLon is MOD(OBT:LAN + OBT:ARGUMENTOFPERIAPSIS + OBT:TRUEANOMALY, 360).

This works just fine for a ship on the launchpad that needs to figure out how long to wait to line up with the ascending or descending node of the target orbit. That's enough to match orbits for a launch contract (except for the degenerate cases of  equatorial and polar orbits where the Longitude of Ascending Node or Argument of Periapsis are listed as "Undefined" in the contract, but that's a separate problem).

If you really wanted the actual reference vector or a vector pointing to the ascending or descending node of the target orbit they are simple enough to calculate from the above. Magnitude of the AN and DN vectors is a bit trickier, but it's at least theoretically possible if you really needed that value for some reason.

**Comment by Dunbaratu** [comment]
to repeat myself:

> but it doesn't help in the scenarios where the orbit doesn't really exist yet because it's not attached to a current object,


Besides, you're arguing a moot point.  It's already been implemented.

**Comment by chippydip** [comment]
Oh, I wasn't trying to argue that the reference direction shouldn't be added, just pointing out that the use case linked in the OP is totally doable in the current version of kOS if anyone stumbles on this issue when trying to write a launch script targeting contract orbits.

> but it doesn't help in the scenarios where the orbit doesn't really exist yet because it's not attached to a current object,

This is totally irrelevant since the underlying direction is a global constant. Any orbit can be used to calculate the reference direction and they should all give the same result. Since a kOS processor can't exist without a ship, and a ship always has an orbit (even when landed), that's probably the most straight-forward way to calculate it (and matches what `REFERENCEVECTOR` would return), but it's not a requirement. You can just as easily calculate the vector in any other reference frame if you need that for some reason.

Even with this addition it's still probably more convenient to use the calculation I showed above since in most cases what you really care about is the longitudinal offset angle between your current location and either the ascending or descending node, which is just `targetLan - refLon` (modulo 180 degrees for AN or DN). Using the new `REFERENCEVECTOR` you'd need to get an "up" vector at 0 longitude for your current SOI, `VANG` that with the `REFERENCEVECTOR` to calculate the reference-to-SOI longitudinal offset, and then add that to your current longitude to get the refLon. Seems easier to just add 3 angles and be done with it.

That said, `REFERENCEVECTOR` may be more useful if you're trying to calculate a transfer to a different SOI in such a way that you inject at the correct inclination and LAN in order to avoid a more costly inclination adjustment burn once in the target SOI (I haven't tackled this case yet myself). But even if the angle method turns out to be more convenient there, having options is rarely a bad thing.

**Comment by Dunbaratu** [comment]
Sorry, accidentally edited your comment instead of replying to it.  I hate the fact that github doesn't have a "quote" button and instead you have to manually cut and paste rather than get a quoted section that you can then trim down.  It wasn't my intent to remove what you said, but there's no undo for the edit so I can't get it back.


>Even with this addition it's still probably more convenient to use the calculation I showed above since in most cases what you really care about is the longitudinal offset angle between your current location and either the ascending or descending node, which is just `targetLan - refLon` (modulo 180 degrees for AN or DN). Using the new `REFERENCEVECTOR` you'd need to get an "up" vector at 0 longitude for your current SOI, `VANG` that with the `REFERENCEVECTOR` to calculate the reference-to-SOI longitudinal offset, and then add that to your current longitude to get the refLon. Seems easier to just add 3 angles and be done with it.

BODY:GEOPOSITIONOF( referencevector ):LNG is the planetary longitude that corresponds to the current reference vector.
