### ISSUE TITLE
SHUTDOWN doesn't take effect immediately.

### ISSUE THREAD

**Issue by bfrobin446** [KSP-KOS/KOS#1120]
Based on Reddit discussion at https://www.reddit.com/r/Kos/comments/3g3nfq/this_very_short_script_i_wrote_to_abort_the_whole/ , `SHUTDOWN` takes effect only at the end of the physics tick where it executes.

The desired and intuitive behavior is for SHUTDOWN to immediately abort any code that's running, so the final state is deterministic.

**Comment by hvacengi** [comment]
I just realized that we assigned this issue but never commented on it.  Thanks for the report @bfrobin446.  I'm working on fixing this behavior for the next release.  I expected it to be very simple (just do the same thing that happens when you press Ctrl-C) but it turns out that breaking mid-execution presents a few challenges I wasn't expecting.  But I think I'm on the right track now.
