### ISSUE TITLE
nextnode:orbit:apoapsis overflow

### ISSUE THREAD

**Issue by Spanyesz** [KSP-KOS/KOS#1126]
Hi!

If i make a node with a high apoapsis the nextnode:orbit:apoapsis display a negative number.
![node](https://cloud.githubusercontent.com/assets/13894500/9397562/465c8056-479e-11e5-8ead-0e689698163e.png)

**Comment by Dunbaratu** [comment]
The negative number (see important footnote) is telling you you're on a hyperbola orbit, rather than an ellipse orbit.  In other words, an escape trajectory.  This is because it's telling you what your apoapsis of your orbit relative to the current body (Kerbin) is, not relative to the Sun.  I suspect what you have is *really* two orbit patches following your maneuver node - one that is still in Kerbins' SOI, followed by a transition to the Sun's SOI when you escape Kerbin, and you're reading the Kerbin patch of it, not the Sun patch of it - what happens when you go one more "nextnode" into the future and try it's apoapsis?

Basically, when you run the math for "what is the biggest radius from planetary center this orbit has?", and there is no such answer because it's an escape orbit and won't be coming back, the correct answer, really, is infinity - apoapsis is infinity because it won't be ever coming back down.  But the math that's usually used to calculate it will return a negative number, not infinity, because that's what happens when you plug in the same formula but the orbit is really a hyperbola now rather than an ellipse.

(In a sense, the negative number is the math formula's way of telling you it's hit a weird case where what you're asking for is an invalid concept in Euclidean space.  "What is the apoapsis of my hyperbolic orbit" is a thing that's physically impossible, which is reflected in the fact that the math gives a negative number for a value that is meant to represent a scalar magnitude of a vector, and negative magnitude vector isn't a thing.)

**Important footnote** - Periapsis and Apoapsis are returned in terms of distance from planet surface rather than distance from planet CENTER, and it's actually when the RADIUS measure of apoapsis - to the center, not to the surface - goes negative that it means you have a hyperbola orbit (escape orbit).  It's when the sum (apoapsis + body:radius) goes negative that you're in an escape orbit, not merely apoapsis alone.  But this mathematical case would only ever come up if you're under the planet's sea level.  This isn't as impossible as it seems, because some bodies do in fact have craters that dip below their "sea level".  There's one spot I know of on the Mun that lets you land "under" zero altitude, in the center of the northern crater of the twin craters formation.

**Comment by Dunbaratu** [comment]
@Spanyesz - can you test my guess above about what's happening (try going one more nextnode into the future) and see if I'm right about what you're encountering?  If so, I'd like to mark this issue as closed.

**Comment by Spanyesz** [comment]
After i left the SOI of Kerbin it works as you described - when reach an escape trajectory the number goes to negative -   but when im under SOI of Kerbin in a geosynchronous orbit i create the node adjust the deltav and setting up an escape still provides positive number 

![apo_pl](https://cloud.githubusercontent.com/assets/13894500/9466133/b6863060-4b32-11e5-8183-f1b5bbc8295b.png)

**Comment by hvacengi** [comment]
It's difficult to diagnose your issue without having the specifics of exactly where your nodes are.  I just ran a test on my local machine.  There are 6 values that I am interested in:
```
print ship:obt:apoapsis.
print ship:obt:body.
print nextnode:orbit:apoapsis.
print nextnode:orbit:body.
print nextnode:orbit:nextpatch:apoapsis.
print nextnode:orbit:nextpatch:body.
```
When you have a node that results in a change in SOI, there are 3 states: initial, escaping, and final.    In the most recent image you sent, the apoapsis aligns with an orbit that is around the sun. When I run the above code from low kerbin orbit, my printout looks like this:
![screenshot9](https://cloud.githubusercontent.com/assets/2975036/9467397/6237423e-4b09-11e5-8d79-480eefc86740.png)

Please note though that due to the nature of patched conics, it is possible to escape without having a hyperbolic orbit and the associated negative apoapsis, and in fact you can see that result here:
![screenshot8](https://cloud.githubusercontent.com/assets/2975036/9467424/925ef27c-4b09-11e5-8922-309ed3d71d7f.png)

If at the time of the screenshot you were on an escaping kerbin orbit and the maneuver node is locate on the orbit around the sun, it is behaving as it should.  In that instance (already escaping) you don't need to use a maneuver node to get the next orbit patch, just use `ship:obt:nextpatch` but keep in mind it will not account for any maneuver nodes you might have scheduled.  You can use the orbit object's `hasnextpatch` suffix to determine if there is a transition, however I would recommend checking the next patch's body at that point, as you would also have a patch available for a fly by of another body (such as the mun).

**Comment by Spanyesz** [comment]
I wrote a script which try to make a node at the periapsis and adjust the apoapsis to the periapsis, for example under the Mun's SOI, but it makes a bit difficult when the apoapsis is a negative number, jowever i solved this problem, the second one is i try to wrote a script to encounter other bodies and make a node where the apoaps is near the body's altitude and after that adjusting the position of the node to encounter the targeted object
