### ISSUE TITLE
RENAME not respected on RUN

### ISSUE THREAD

**Issue by gisikw** [KSP-KOS/KOS#1129]
It appears that once a file has been run with a given name, and subsequent attempts to run a file using the same token end up re-executing the first file with that name. I'm assuming there's some cache-invalidation missing somewhere? Repro case provided below:

```
PRINT "Running test script".

SET foo TO "Foo".
SET bar TO "Bar".

LOG "PRINT foo." TO foo.ks.
LOG "PRINT bar." TO bar.ks.

// Test normal behavior
PRINT "Running foo.ks:".
RUN foo.ks.
PRINT "Running bar.ks:".
RUN bar.ks.

// Test file execution via Strings
PRINT "Running foo.ks as exec.ks".
RENAME "foo.ks" TO "exec.ks".
RUN exec.ks.
RENAME "exec.ks" TO "foo.ks".

PRINT "Running bar.ks as exec.ks".
RENAME "bar.ks" TO "exec.ks".
RUN exec.ks.
RENAME "exec.ks" TO "bar.ks".
```

And the output:
```
Running test script
Running foo.ks:
Foo
Running bar.ks:
Bar
Running foo.ks as exec.ks
Foo
Running bar.ks as exec.ks
Foo
```

**Comment by TDW89** [comment]
duplicate of #719 related to #409 

the run looks at weather it has already run the program previously and if so executes the already compiled version to save time.

you can deliberately ignore this behavior by using lib_exec.ks from kslib (or similar scripts)

https://github.com/KSP-KOS/KSLib/blob/master/library/lib_exec.ks

**Comment by gisikw** [comment]
Whoops! Did a search for RENAME and turned up a similar but not quite-the-same issue. Will go ahead and close this.

In the future, hopefully possible to SHA the sourcefile or something as a cache-invalidation check?

**Comment by TDW89** [comment]
@gisikw if you are trying to log strings to a file (and keep them as strings) you might find `spec_char.ksm` from kslib too. it is a modified compiled file to `set quote to ".` so you can do `log "print " +quote +"Foo" +quote +"." to foo.ks.`

**Comment by Dunbaratu** [comment]
@gisikw I agree that the "already compiled" check isn't so great.  It's currently based on just the filename.  The difficulty of doing it more reliably is that the whole point of the check was to make it so that you don't interact with the filesystem unnecessarily - but to do any sort of timestamp and/or checksum check requires opening up the filesystem and getting to the file.

**Comment by TDW89** [comment]
Would it be possible to have the "already compiled" flag removed from a file by the rename the log and the delete commands so that if a script edited a file then the updated one was used and just not support editing a file external to ksp while the script is running. (depending on how it is done it may also not pick up on changes to a file by other cores) That way it wouldn't need to access the file system to see if a change had been made
