### ISSUE TITLE
Wheelsteering slightly broken, does not process heading instructions correctly.

### ISSUE THREAD

**Issue by pgodd** [KSP-KOS/KOS#1141]
lock wheelsteering to 180.  Does not work.
lock wheelsteering to 180.1.  Does work.

**Comment by Dunbaratu** [comment]
In looking at the code, wheelsteering isn't the only one of the LOCK controls that's not properly handling unexpected types.  They consist of if/else ladders testing for various types of value to lock to, without a final catch-all 'else' to respond to what happens when a script uses a stupid type it doesn't understand (like locking throttle to a string, for example).  Instead of showing a useful error describing the situation, it just silently fails.

So there's that to fix too, along with making wheelsteering work with integer values.

**Comment by Dunbaratu** [comment]
Why was this re-opened?  What went wrong?

**Comment by erendrake** [comment]
I still havent merged the PR, i thought i had and it wasnt associated. It was my bad for closing prematurely :P
