### ISSUE TITLE
Key-value store

### ISSUE THREAD

**Issue by tomekpiotrowski** [KSP-KOS/KOS#1168]
Some of my scripts need data to be stored between executions. Up till now I've been using `log "set ..." to file. ... run file.` to store simple data in a file, but that's less than ideal. I thought about providing a simple API that would allow the user to store key-value entries in a file on the volume. That file could use JSON internally. The API would look more or less like this:

```
store:put("phase", "parking_orbit").
store:put("list_data", list(25, 15, 25)).

store:has("phase").
store:get("list_data").
```

Alternatively we could provide a lower level File API, that would let users create/read/write to files.

Thoughts?

**Comment by Dunbaratu** [comment]
I figure reading a text file and reading user input keys is really the same thing, and should be addressed together.

Then when it can be done low-level, that's when it's time to consider layering things like this on top of it.

**Comment by erendrake** [comment]
@tomekpiotrowski we have been working on an associative array type for users. that coupled with the list type would let us have a full bi-directional serialization between a JSON file stored on the disk and these two types in memory. 

I think that could be a pretty cool tool for ingesting data into kOS from the archive

**Comment by tomekpiotrowski** [comment]
@erendrake Yes, I know, and I've been thinking about that as well :)

@Dunbaratu I'm not sure if the lower level stuff is that necessary in our case. Most people manage without storing anything and storing simple key-value entries covers majority of any use cases I can think of. I think very few people actually need proper, low-level file access. To be honest I'm not sure if it's worth spending time on. Limiting ourselves to serializing stuff to JSON could save us a lot of effort. Or is there something I'm missing?

Anyway, I'm willing to put some time into this (if I have some to spare), so if we decide on what to do here I can give it a shot.

**Comment by Dunbaratu** [comment]
Here's why it's not as simple as you're both implying:

The associative arrays can store any data type as their value.
They can use any data type as their key.

To automagically transform any arbitrary associative array into a file or visa versa first requires reliable serialization of all types kOS variables can hold.

i.e. How do you print a VesselTarget to a file?  How do you read a PartValue from a file?  The fact that we didn't handle serialization of these things well at all is why we removed the load/save of program state when you switch scenes.

It would require limiting the associative array to a small subset of the possible data values - simple ones like strings and numbers - to make it easy to implement.

@tomekpiotrowski low level file access IS user input access.  They're the same thing, really.  So it's not "lets make low level file access for low level file access's sake".  It's "When we implement user input from the keyboard stream, lets do it generically enough that it also works on streams coming from files just like streams coming from user key events."

**Comment by Dunbaratu** [comment]
We probably could read/write an assoc_array provided we did so with the caveat that it will barf and throw an error if you include any type in it that is outside a restricted list.  Some types would be easy to serialize:
int. float, string, vector (a tuple of 3 floats), direction (again, a tuple of 3 floats), latlng (a body name, and 2 floats for lat,lng).

But anything more fancy than that probably can't be easily written out without a lot more work (the sort of work we need to do to re-enable load/save of the vessel with code in mid-execution).

**Comment by Dunbaratu** [comment]
While we're on the subject, the ability to do a dump of a 2-D array as a CSV file would be very handy for a lot of the people who like to make spreadsheet graphs of data taken from kOS.

**Comment by erendrake** [comment]
@Dunbaratu Of course it wont be able to reconstitute objects that are dumped as string values. I dont think it needs to to solve user problems. 


If the types you are writing to file dont Implement the new `IDumper` we simply take its to string value and when you are loading it off of the disk you have its string value. That would allow for a simple syntax like 

    SET FOO TO LOADFILE("TESTING").

and it would be able to deserialize testing.json off of disk into an in memory structure, that seems good enough to me.

**Comment by Dunbaratu** [comment]
@erendrake, The inability to reconstitute objects from a string dump should not be classified as a user problem.  It's kOS's problem.  It's why we had to disable the OnSave and OnLoad resuming feature for the time being.

I'm looking at this as how to leverage the two identical tasks with the same code - user dumps values to a file in a way that can be parsed back in, and kOS saves variable state in persistent.sfs in a way that can be parsed back in.  They're really the same problem, and it would be a shame to write two different versions of solving it.  But since it's a big problem we can't solve all at once, let's at least make the first steps toward it use the same extensible architecture as will be used in the later steps when it's all in place.

I think it needs a different interface from IDumper.  (Isn't there already a stock seralizable interface definition in C#?)

The reason I think it needs to be different from IDumper is that the needs of human-readable dumps and machine-readable dumps aren't always exactly the same.  In those cases where they are, you can just have the serializable method call the dumper method, but in cases where they aren't, you have the ability to have it do something else.

So the idea is that if WRITEFILE encounters any type within the collection that does not implement the seralizable interface, it's an error, and we have the eventual goal of having every KOS type that can exist in the stack implement the interface, but don't have to implement all of them at once in order to get something useful out for users to use it on the few types that are easy to implement it for.

We would have to maintain a list in the documentation of which types the load/writefile works with, versus which it does not, with the goal of eventually not needing that list anymore once every KOS type implements the serializable interface in the nebulous future.

The ones that are easy for a first release target are the ones where the content contains no references to other objects, and is just primitive data (int,float, double, string (techincally not a primitive but close enough)), or at least tuples of primitives (vector, rotation, rgb color, etc).

It gets a little bit interesting when you want to store a collection of collections.  If ``foo["abc"]`` is itself
another associative array, ``bar``, and you write foo and then load it back in, it will probably construct a new copy of what bar looked like for foo["abc"] to point at, rather than having it point at the existing bar like it used to.  This may seem like it's too complex an issue to think about for a first pass, but remember that this is basically how a 2D array is made in kOS so if people are dumping data and loading it, they're definitely going to be doing so with table data like that, so it's going to come up sooner rather than later.

**Comment by tomekpiotrowski** [comment]
I've been doing some research into this. Seems like we can do this in one of 2 ways:

1) Use an external JSON serializer library. For example [fullserializer](https://github.com/jacobdufault/fullserializer).
2) Use ConfigNode. This would not require external dependencies, but would not output JSON. Another problem is that it seems it's not possible to read a ConfigNode from a string. The Load method reads from a file.
