### ISSUE TITLE
FlightCtrlParam.SteerByWire sometimes disables steering lock

### ISSUE THREAD

**Issue by thexa4** [KSP-KOS/KOS#1198]
This seems to happen because the setter hook hasn't been called before SteerByWire gets called.
A working solution seems to be to add an instance variable isInitialized = false that is set to true once the value has been set and check that variable before setting enabled to false.

**Comment by hvacengi** [comment]
Thanks for reporting this issue.  Out of curiosity, how often do you run into this issue?  I'm guessing you are using a debug build as well, since the current release shouldn't be disabling steering at all if the value is not set (or is set to an incorrect type).

On my first cursory read through of the code, I expected that this should either be not possible at all, or should be happening all the time.  I'll have to look at how the steering value trigger is initialized.  If the value of the trigger is set only at the beginning of the execution loop (during all other trigger execution) we should be running into this issue all the time since the autopilot call back has to be called between fixed updates.  If the value is set initially when the trigger is set up, then we should never run into this problem.  There must be something else happening behind the scenes that I am not aware of from a cursory review.

**Comment by thexa4** [comment]
Yes, I'm rebuilt the plugin from source. It only happened on some of the locks but seemed to be deterministic, the value was still reset on the same position in the script, even after a revert flight, restart and rerun.

It wasn't easy to see how the locks were actually processed so I am not really sure what is causing this to happen only some times.

**Comment by hvacengi** [comment]
Any chance you could share the source of the script where you run into the issues, along with your configuration (IPU setting, and the KSP setting for physics frame duration)?  I've never run into this during my testing of the new steering code (which has been a lot of hours), so having your code might help reproduce the issue.

Unless your modifications were in the compiler, program builder, opcode, or cpu execution, I don't think you could have caused the issues there.

You might also try updating to the most recent develop branch, since the new steering calculations just got pulled last night.

**Comment by thexa4** [comment]
It doesn't seem to happen in the new version.
It's reproducible with https://github.com/thexa4/KOS/tree/bug/flightctrlparam and the following savegame:
http://delftelectronics.nl/flightctrlparam.zip (remotetech save, there's a ship on the platform that boots automatically)
Usually during or after one of the orbit change burns the lock gets reset and the ship keeps waiting for alignment.

IPU setting: 250, Physics DeltaT: 0.04

**Comment by Dunbaratu** [comment]
@hvacengi, is this issue still relevant after we released your newer steering on Nov 25?  I'm trying to close old dead issues if I can.

**Comment by hvacengi** [comment]
I guess it depends on if @thexa4  was able to reproduce it again after that release.  In any event, I'm in the middle of a modification to make sure that the steering manager and it's information has more robust persistence and handling of game events.

**Comment by Dunbaratu** [comment]
well don't forget to link to this issue number when you do that PR so we can get it cleaned out.

**Comment by thexa4** [comment]
I haven't been able to reproduce it in later commits. Can be closed if needed.
