### ISSUE TITLE
Cannot open terminal (same as issue 699, but that one was closed)

### ISSUE THREAD

**Issue by DavidB1024** [KSP-KOS/KOS#1207]
Hello, I just installed KOS and have the same problem as issue 699:
The SCS does not show the 'open terminal' button.

I tried switching between 32 bits/64 bits KSP. Also did a fresh install of KSP with KOS. Did not help.
My other mods are: MechJeb2 and Environmental Visual Enhancements

Any thoughts/clues are appreciated.
Thanks!
David

**Comment by space-is-hard** [comment]
Can you check to see if your installed version of KSP API extensions is up-to-date?

**Comment by DavidB1024** [comment]
Where can I find that information?

**Comment by erendrake** [comment]
@DavidB1024 it would be helpful if you could share your log. Instructions on finding it are here

http://forum.kerbalspaceprogram.com/threads/92229-How-To-Get-Support-(READ-FIRST)

**Comment by Dunbaratu** [comment]
@DavidB1024 - I'd like to point out that for this particular bug report, showing the log isn't just a thing that "would be helpful" - it's actually even more than that.  It's actually literally necessary in this case to get any sort of action at all on this bug issue.

The reason is that you're reporting a bug that none of us are having.  If we can't make it happen in front of our own eyes it's not possible to figure out what's wrong.  The next best thing, barring that, is to show the error log because it may contain a dump of at least which part of the code is bombing out with an error.  It is highly likely that what you are seeing is happening because some part of the code is "quitting early". due to an error, and not reaching the part where it was supposed to do its work.

If that is the case, the error log *should* contain, buried inside it, a clue as to where that "quitting early" is happening.

Oh, and please try to post the WHOLE log, even though it's large.  You may have to use a third-party site like pastebin or something like that to do so.  It's far better to let us dig through the log to find the relevant part than to have you trim it down in a way that requires you to make a guess as to what messages are relevant and which ones aren't.  You may end up trimming out the one line that held the vital clue and not realize it.

**Comment by DavidB1024** [comment]
Thanks for your responses!
Here is the log: https://www.dropbox.com/s/fxdj1j5oropnmm5/output_log.txt?dl=0

**Comment by hvacengi** [comment]
Looking through the log, it appears that you are indeed suffering from the same issue as #699.  kOS does not appear to be installed fully, since the kOS dll is never loaded.  How did you install the mod?  

I recommend removing it and then reinstalling kOS, making sure that you download the newest version ( currently 0.17.3 https://github.com/KSP-KOS/KOS/releases/tag/v0.17.3).

**Comment by DavidB1024** [comment]
I copied the KOS folder into the KSP\Gamedata folder, but, to be honest, I was not completely sure whether I did the right thing. I saw the comment on the KOS.dll file in the #699 post, but couldn't find the KOS.dll file in the donwload.

I have the latest version (0.17.3.) installed, afaik.

**Comment by hvacengi** [comment]
Within the GameData\kOS\Plugins folder you should have 4 files, and potentially one folder
* ICSharpCode.SharpZipLib.dll
* kOS.dll
* kOS.Safe.dll
* KSPAPIExtensions.dll
* PluginData [folder, but not necessarily there until kOS actually loads]
I just checked the zip at the page I linked above, and each of these files are in the folder.  It is possible that your source has a bad copy of the zip, or that there was an error in download/unzipping.  Where did you download your zip file from?

**Comment by Dunbaratu** [comment]
Did you attempt to compile the code yourself and something didn't work, or perhaps did you just copy the github repository folder sources without a compile, thinking that's how you're supposed to install it?

If you''re not planning on doing development of the mod, then just copying the resources folder from github isn't how you're supposed to install it.

The reason I suspect this might be what happened is that:

1 - You said you aren't sure if you did it right,

and

2 - Looking at the log it appears as if the only kOS DLL you have is kOS/Plugins/ICSharpCode.SharpZipLib.dll.  This happens to be the only DLL that is present in the github source repository even before any of our C# code has been compiled.  I suspect that is probably not a coincidence.

The way it was meant to be installed was by going to the 'releases' page, here: 
https://github.com/KSP-KOS/KOS/releases

And clicking on the button "Latest Release" which gets you a ZIP file of the compiled file, and you're supposed to get the files installed by unzipping that file into your KSP main folder (the zip contains the GameData folder in its file's pathnames.)

**Comment by DavidB1024** [comment]
@Dunbaratu, Earlier this week, I intended to get the "ready-to-go" version, which installs just by copying the folder into GameData. Somehow, I got the "wrong one".

When I take a look at the link you mention (https://github.com/KSP-KOS/KOS/releases) I get a ZIP file that contains 4 dlls in the GameData\kOS\Plugins folder, as @hvacengi remarked.
So'll take that last one.

Thanks all for your help.

**Comment by Dunbaratu** [comment]
I'm going to mark this as closed.
