### ISSUE TITLE
Setting Yaw let's pilot input work anyway

### ISSUE THREAD

**Issue by Maverickwoe** [KSP-KOS/KOS#1209]
Hi !
First time I'm posting something on kOS here.
I believe there is an issue or I haven't been able to understand what I'm doing wrong if it is not.

I'm using SET SHIP:CONTROL:YAW to 0.
because I want to use the yaw inputs of the pilot to do something else.
But it seems that, anyway, the plane will activate a yaw if I press D or A even if I don't want it to.
I'm sure the SET SHIP:CONTROL:YAW to 0. works because when I put it to 1, the tail fin visually tries to yaw but it seems that the yaw input from the pilot is taken into account anyway.
Whereas with Roll, and Pitch, it works perfectly.
The consequence is my vessel being destabilized when I input D or A.

Could you have a look at this issue please ? Or tell me where I'm wrong.
Cheers !
otherwise, Awesome mod! I love it.

**Comment by ozin370** [comment]
Maybe "SET SHIP:CONTROL:YAW to 0." isn't being set every physics tick? Just a guess.

**Comment by Maverickwoe** [comment]
Thanks Ozin for the proposition.
The script is indeed called every 0.2s to limit CPU but then why would the PITCH and ROLL commands not be affected by the pilot inputs, while YAW would be ?
I checked in my script again, SET SHIP:CONTROL:YAW to 0. is called at the same frequency than SET SHIP:CONTROL:PITCH or ROLL.
So I guess it is not that ?

**Comment by Dunbaratu** [comment]
If yaw is being treated differently from pitch and roll, then that's a bug.  I don't actually think it's wrong to let manual control override the autopilot script, but if it only happens on yaw and not the others, then that's a sign it's wrong.

**Comment by hvacengi** [comment]
I just took a quick look at the code, and I'm guessing this issue isn't specific to `YAW`.  The code is implemented such that a setting of 0 (or technically, anything between +/-0.00001) is considered "neutral" and returns control back to the pilot.  I imagine this is so that you don't need to neutralize all of the controls, without exposing a `NEUTRALIZEYAW` suffix.  In the case being reported here, @Maverickwoe is trying to prevent user input to yaw.  The best work around I can think of would be to oscillate the yaw control just over the threshold mentioned above (toggle positive/negative every tick).  I'm not sure of a good "fix" since It looks like this functionality has been around a while.

**Comment by Maverickwoe** [comment]
Thanks guys !
I was suspecting the 0 as inhibition indeed. I guess I'll do the oscillating control to cancel out player input then. Thanks for the advice.
