### ISSUE TITLE
Inter-CPU and inter-vessel communication

### ISSUE THREAD

**Issue by tomekpiotrowski** [KSP-KOS/KOS#1225]
Looks like there is consensus among kOS developers that we want this feature in the next release so it might be useful to have a place to discuss it. I know @Dunbaratu and @erendrake had some ideas regarding how we could go around implementing it.

So the goal is to provide means for kOS processors to send messages to each other within one vessel and to other vessels (respecting any RemoteTech constraints where appropriate).

Most importantly I think that we will have to provide two similar, but separate mechanisms. I realize that it would be preferable to have one, more general solution, but for the moment I don't see how we could make it work. Primarily because inter-vessel messages can't be addressed to a specific CPU - we can't assume vessels know about each other's CPUs. On the other hand inter-CPU messages need to have a specific CPU set as recipient. Inter-vessel messages need to be persisted, inter-CPU not necessarily, and inter-cpu communication doesn't have to worry about the connection between the sender and recipient.

**Inter-CPU** in this model is actually very simple to implement. We need a simple FIFO queue for every CPU and an API for the sender and the receiver to access that queue.

**Inter-vessel** would require a separate queue (one per vessel) and (probably) a separate API for that queue. The contents of that queue would be persisted. RemoteTech would be used here to check the connection and delay.

I have actually taken the liberty of implementing inter-CPU as described above, the interface is as follows:

Receiver:

```
CORE:MESSAGES:EMPTY.
CORE:MESSAGES:PEEK.
CORE:MESSAGES:POP.
CORE:MESSAGES:PUSH(msg).
```

and sender:

```
PROCESSOR:SENDMESSAGE(msg).
```

Example code:

```
// This code runs on 'first'
SET SECOND_PROCESSOR TO PROCESSOR("second").
SECOND_PROCESSOR:SENDMESSAGE("launch").
SECOND_PROCESSOR:SENDMESSAGE(10).

// This code runs on 'second'
WAIT UNTIL NOT CORE:MESSAGES:EMPTY.
SET MESSAGE TO CORE:MESSAGES:PEEK. // read 'count sheep'

IF MESSAGE = "launch" {
  CORE:MESSAGES:POP. // remove 'count sheep' from the queue
  WAIT UNTIL NOT CORE:MESSAGES:EMPTY. // make sure the count is available
  SET COUNT TO CORE:MESSAGES:POP. // read '10'

  PRINT "Commencing countdown!!!".

  UNTIL COUNT = 0 {
    PRINT " # " + COUNT + " # ".
    SET COUNT TO COUNT - 1.
    WAIT 1.
  }

  PRINT "!!! LAUNCH !!!".
  ...
}
```

Note that we currently don't have serialization or parsing so we can't send `launch 10` as one message, but @erendrake indicated that serialization will be the next order of business after this.

**Comment by ozin370** [comment]
I am also very curious as to what would be possible to send. Could we get the possibility of sending structures such as lists, vectors, parts, etc? In particular lists, as that would make it possible to send more than one value at a time.

**Comment by Dunbaratu** [comment]
The key thing that makes a system where you can send *any* generic arbitrary data tough is the references (the managed memory language equivalent of a pointer).  i.e. I send ``ship:partstagged("my name")[0]`` to another vessel, then switch active vessels over to it so it can receive the message and act on it.  The other vessel is more than 2.5km away, so switching over to it unloads my ship as it loads the other one.  Now the reference to that part is referring to a KSP object that was *supposed* to have been deleted, but it wasn't because the reference sitting in the message queue kept it from getting orphaned.  When the other vessel tries using that part handle, it finds that it throws all sorts of errors as it tries querying its suffixes.

Thus anything sent probably needs to be just primitives.  Maybe a structure of primitives, like a list of integers, or a tree of strings is doable, but what's probably best to avoid is allowing things like sending a list of handles to KSP objects (vessels, parts, bodies, orbits, maneuver nodes, or anything like that).

**Comment by Dunbaratu** [comment]
I think I have a design idea that might be a workable compromise that answers some of my concerns raised in the slack, while not throwing away the work that @tomekpiotrowski has already done.

My primary dislike of the system of having scripts needing to directly manipulate two different queues, one for local and one for remote incoming messages, are these:

1 - The script code is slightly different if it's reading its own CPU queue versus if it's reading the global vessel queue, making it a bit messy to make a server that reacts to both.
2 -  The fact that if you design your own router in user-land to move messages from the global vessel queue to the CPU queues (see argument in slack chat that's not been repeated here), it has to throw away all messages where the receiver isn't ready yet, in order to dig through the queue to get to the one that is ready to be processed.  I do not like this behavior.

But what if we DO allow the technique of having two queues, and moving things from the vessel queue to the CPU ones like the router would do, however we don't require people to write their own router to do so, since that should be the OS's job (us), and we will implement the router logic as part of the API we provide. I will describe below one proposal for how to do it:

So all I propose is that the vessel queue allows a script to register with it the desire to be given all the traffic of a given type.  Then the vessel queue will know to move all messages of that type out of the vessel queue and into that CPU's own private message queue for it.  Thus the script only has to read its own CPU queue after it has set this up.  The OS (not a script program) will move the traffic that that script asked for to it's own queue.  

This convenience wrapper allows the script to not care about the difference between the two queues anymore once it has told the OS to pass on messages of the desired type to it.

However, I do view it as just being a convenience wrapper, in that a program COULD still be written to manipulate the vessel queue on its own if a player thinks they have a better way they'd prefer to do it.  We provide both the "let me see the raw vessel queue" and the "manage it for me and give me the messages I asked for on my own queue instead" interface.

So the inter-vessel comms would *allow* programs to get at the raw representation if they want to, but not make it mandatory for them to - they could just say "OS, please redirect traffic of types foo and bar to my own queue and I don't care who gets the rest of the messages that are of other types."    This would be like an internet server doing a Listen() on port 12345, telling the OS "I know you get all sorts of messages all the time, but I'm only interested in the ones that are on port 12345.  I don't care what you do with the other messages, maybe other  processes might be reading them, maybe not, I don't care.  Just send me the stuff you're getting that's been tagged as being for port 12345."

It's pretty much the same thing as the router idea from slack, but with the change that the OS does it, not a user script.  This buys a few things I like, such as a more sophisticated manipulation of the vessel queue than is possible from the limited API that a script would be allowed to use.  We could violate the "must only consume at front" rule of queue access if it becomes necessary, in a way we probably wouldn't want to allow userland script code to do.

Also, it takes the burden off the script writer of doing a job that is essentially, the OS's responsibility.

**Comment by tomekpiotrowski** [comment]
@ozin370 For now only scalars, but serialization will be one of the very next features after this, so it will be possible to send more complex messages and save/load data structures to disk.

**Comment by ozin370** [comment]
@Dunbaratu Couldn't you simply throw an exception if trying to send such a structure to a packed/unloaded vessel? 

Alternately have a separate broadcast functionality, allowing other vessels that are unpacked to listen in, and expanding on the available structures that can be sent.

**Comment by AlchemistCH** [comment]
Sending (or just reading) something to an unloaded vessel is as much as manipulating configNode of a saved PartModule (warning: you can't use that on a loaded part - ask the PartModule directly). 
That's how RemoteTech interfaces antennas on unloaded crafts (something I developed for them)

Therefore it is a good starting point - if it can be packed into a configNode, it can be sent even to an unloaded ship. So why not to make the message itself to be a config node? And it allows multilevel complexity, so sending structures (lists, lexicons) is not a problem.  Of course, if somebody tries to send a reference to a Part or PartModule, what should be sent is something that allows to identify the object (vessel and part identificators).

**Comment by bryan-lunt** [comment]
I'd be happy if we could just send raw byte arrays between machines. Of course, ideally a message could be any fundamental type (int, string, etc).

I think it would be nice to at least have the option of dealing with incoming messages in an interrupt (I guess you call them triggers).

ON MESSAGE {
    foo.
}

Would be called if there are messages remaining in the queue.

**Comment by bryan-lunt** [comment]
Just for reference (though I'm probably exposing my ignorance) I think this class allows RemoteTech to pass/delay any arbitrary data. A good question is "can it do it from any node in the network to any other, or only from mission control(s) outward?"

https://github.com/RemoteTechnologiesGroup/RemoteTech/blob/develop/src/RemoteTech/FlightComputer/Commands/ExternalAPICommand.cs

**Comment by tomekpiotrowski** [comment]
Seems like I'm done with my other PRs so it's time to get back to comms...

First of all everything took longer than I expected and now it seems like it's better to wait for 1.1 before we work on this. Obviously 1.1 will have some form of stock RemoteTech and that can change a lot.

For anyone interested I have a fairly well functioning version of comms in one of [my branches](https://github.com/tomekpiotrowski/KOS/commit/3fee50b7d9cb8c12172c6bc7c48150048e351ffc) that I have implemented a few weeks ago (it's not based on current kOS). It still needs some work - user API is not final and couple of smaller features are missing. But all the basic stuff is there: cpus and vessels have queues (priority queues sorted by message's arrival time), those queues handle messages with delays and their contents are stored in the save file (serialized to ConfigNode). RemoteTech delays are handled as well. Message queues store messages that have already arrived and those that are supposed to arrive later, but only the former are visible to the user of the API.

There are a couple of things that I'd like to discuss however.

**API**

Currently the user api is as follows:

*Inter-CPU*:

```
// sender

SET MESSAGE TO "HELLO". // can be any serializable value
SET P TO PROCESSOR("other").
P:SENDMESSAGE(MESSAGE).

// receiver

WHEN NOT CORE:MESSAGES:EMPTY { // one could use 'WAIT UNTIL' as well
  SET RECEIVED TO CORE:MESSAGES:POP. // or do something else...
  PRINT "Sent by " + RECEIVED:SENDER:NAME + " at " + RECEIVED:SENTAT. // same ship obviously
  PRINT RECEIVED:CONTENT.
}
```

*Inter-vessel*:

```
// sender

SET MESSAGE TO "HELLO". // can be any serializable value
SET C TO VESSEL("SOMEVESSEL"):CONNECTION.
PRINT C:DELAY.
C:SENDMESSAGE(MESSAGE).

// receiver

WHEN NOT SHIP:MESSAGES:EMPTY {
  SET RECEIVED TO SHIP:MESSAGES:POP. // or do something else...
  PRINT "Sent by " + RECEIVED:SENDER:NAME + " at " + RECEIVED:SENTAT.
  PRINT RECEIVED:CONTENT.
}
```

As we discussed previously each CPU has its own queue. Every vessel has a separate queue as well.

In certain cases it may require the user to react to messages in both of these queues. I personally don't think this would be troublesome. However I'm perfectly willing to include an API that would allow to redirect messages from vessel's queue to CPU's queue if one is proposed (@Dunbaratu).

Any other ideas regarding the API?

**Accessing other vessel's volume**
Currently there is no way of directly copying files between two vessel's. We probably should provide some kind of an interface to access other vessel's volumes, so the user could do something more or less like this: `COPY FILE.KS TO VESSEL("othervessel"):VOLUME("processortag").` Other approach would be to introduce some kind of a serializable `FileValue` that user's could send themselves in messages and handle any volume-related operations in their own kerboscripts like so:

```
SET F TO OPENFILE("FILE.KS").
SET MESSAGE TO LEXICON().
MESSAGE:ADD("OP", "COPY").
MESSAGE:ADD("FILE", F).
MESSAGE:ADD("TARGET", "FILENAME.KS").
VESSEL("other"):CONNECTION:SENDMESSAGE(MESSAGE).
```

But it seems to me like something that only advanced users could handle.

**Should vessel's with no power receive messages?**

I think that vessel's with no power should not be able to receive messages. Even after the power is restored the queue should be empty, because there was no powered antenna that could receive the message. To make things realistic we should look at power at the time the message is received not sent. This means the message would be added to the vessel's queue, but we would have to somehow schedule a power check at the moment the message is supposed to arrive (don't know how to do that yet).

**Comment by ozin370** [comment]
I'm pretty hyped for this addition, was kind of hoping to see it implemented in some form pre 1.1 patch :D 

The API looks good to me.

And not strictly related, but perhaps it would be handy if a cpu could initialize a program on another cpu (on the same vessel). ```someCPU:run(test.ks,param)```, maybe with the addition of a new cpu suffix that returns the name of the program being currently run. ```someCPU:program```

**Comment by tomekpiotrowski** [comment]
I was hoping to do it before 1.1 as well, but looks like it's not going to happen. We're currently working on other PRs and there's a limited number of them that we can merge per unit of time.

We have an undocumented `RUN ... ON ...` syntax, but I never worked properly and probably will be removed in the future. However we do have a solid workaround that does pretty much the same thing:

```
SET P TO PROCESSOR("otherprocessortag").
COPY MY_PROGRAM.KS TO P:VOLUME.
SET P:BOOTFILENAME TO MY_PROGRAM.KS.
P:ACTIVATE.
```

It seems like many people are asking about this specific functionality. Maybe I'll add a separate chapter in the docs just for this.

**Comment by AlchemistCH** [comment]
Another thought that correlates with message system - typing into console with a program already running. 
One thing is the way console applications ask for user input, but with message system it could be even more interesting.
Of course, the way to do it is probably to send what user types to the core as message and let the script deal with it (if you want user input at this phase, place message processing function into the script).

But here's another thought that gives vast possibilities - some function that works as "if this message can be interpreted as a valid command - do this command". 
As a result (if supported by the script) the played would be able to adjust some script variables on the flight (perfect for test flights!), or even call some secondary functions.
And another possibility for this functionality - a script that just initializes user function libraries and then only waits for messages and executes them - now that's the way to call custom functions right from the console. or from other cores and ships

**Comment by tomekpiotrowski** [comment]
Of course you wouldn't be able to type at the console when a program that is waiting for messages is running. The easiest way to go around that would be simply to have more than one core.

Other functionalities that you mention could be implemented by users using kerboscript, so they don't require the kOS devs to provide anything specifically to support them.

I actually thought it would be realistic to disable the console completely when there are no kerbals on board. Think about it. In real life control centers send commands to space probes and the probe handles them. We should have a KSC mainframe and send a message from it to the probe. As you mention, the probe could have the capability to interpret certain messages as kerboscript commands of course. Although I'm afraid this amount of realism could be a bit too much for an average kOS user.

**Comment by AlchemistCH** [comment]
Is there any technical reason to forbid typing into the console with program running? (other that current inability of the program to process such messages) If this input gets turned into messages that the core will process when the script gets to the corresponding command.

For roleplay reasons we can always assume that in case of automated craft the console already is the console of the mission control mainframe, sending commands and receiving output as messages.

I mean why to force using (from another core or mainframe console) commands like 
`TargetCore:SendMessage("Gear ON.").`
instead of just typing
`Gear ON.`
into a console already connected to the core in question (it doesn't have to be an actual screen and keyboard directly plugged into that core

**Comment by TDW89** [comment]
Not sure how helpful it is now that [lib_exec.ks](https://github.com/KSP-KOS/KSLib/blob/master/library/lib_exec.ks) doesn't work but there is a lib file for imputing stings into a running script [lib_input_string.ks](https://github.com/KSP-KOS/KSLib/blob/master/library/lib_input_string.ks) it's not ideal it uses an on-screen keyboard and the script is on hold while you type. It was also written before string functions were in kOS so could probably do with some updating. (i'll get round to that at some point) but the lack of lib_exec hampers it's use as that was the method for executing strings as code.

**Comment by hvacengi** [comment]
We've talked about the dynamics of sending messages that directly effect another core in the slack chat.  The current concept is that it will be up to the script on the 2nd core to implement doing actions based on the message content.  Instead, you'll need to interpret the commands and execute based on them locally.  There are various reasons for this, but one that sticks out to me is that the message queue will not be dependent on the vessel being in physics range ("Loaded").

As an example, you could send the 2nd core, located on an unloaded ship, a message of "do:intercept:ship1".  Then set the 2nd ship as active (or the next time you "fly" that ship).  The 2nd core might have a script something like this:
```
wait until ship:unpacked.
if core:messages:empty {
    run subcommand.
    delete subcommand.
}
else {
    set msg to core:messages:dequeue.
    set array to msg:split(":").
    if array:length > 1 {
        if array[0] = "do" {
            set command to array[1].
            if command = "intercept" {
                if array:length > 2 {
                    set target to array[2].
                }
                log "" to subcommand.
                delete subcommand.
                log "run intercept.ks" to subcommand.
                reboot.
            }
        }
    }
}
```
You just add `if` statements for any command you want to send, and add the appropriate logic to set up the file to run on reboot.  You could even add some fancier logic in there that checks if the "subcommand" file exists, and waits for a command if it doesn't, letting it work when in physics range as well.

@AlchemistCH there isn't any technical reason why we cannot support input during script operation, besides "it isn't implemented".  It's actually been discussed a few times.  I think at this point it's on the list of things that will wait to see what happens with KSP 1.1 and the updates to the UI.  But even at that point, it will probably be explicitly called, kind of like `Console.ReadLine`.  So input would be locked out unless you call a method that enables it (though enabling input doesn't necessarily have to block the rest of the script execution).

@TDW89: You can circumvent the issue preventing lib_exec.ks using `random()` to seed the file string so that it is unlikely to repeat.  This limitation is due to a complication in how the compiler interprets the `run file.ks.` command.  I've looked at that section of code in the compiler, and I don't expect it to change explicitly any time soon, though we may figure out a way to remove an existing program from memory.
