### ISSUE TITLE
Refactorize the FlightControlManager class to separate the RT2 code

### ISSUE THREAD

**Issue by marianoapp** [KSP-KOS/KOS#123]
We should refactorize the class to separate the RemoteTech2 code from the rest of the code and place its own class in the AddOns\RemoteTech2 namespace.
This could probably be achieved by extending the FlightControlManager class and using the factories to instantiate the correct object.

**Comment by hvacengi** [comment]
While not quite the same as the original discussion, I'm planning a refactor of the flight controls to move them into a VesselModule.  The goal is to make it so that instances are managed naturally over the life of a "Vessel".  It also means that objects that are tied directly to a vessel (rather than directly to a processor) are associated with that vessel instead of the processor.  We may be able to clean up some things in `SharedObjects` as well.  I'm also expecting that it could prove beneficial when threading support comes in KSP 1.1, since we could handle some of the thread unsafe components in a single instance.
