### ISSUE TITLE
0.18.0 hang on game loading

### ISSUE THREAD

**Issue by dcrockwell** [KSP-KOS/KOS#1230]
This is on OSX. Have video of failure if interested.

**Comment by hvacengi** [comment]
Can you please post your log file?  The error given in this forum thread: http://forum.kerbalspaceprogram.com/threads/68089-1-0-4-kOS-Scriptable-Autopilot-System-v0-18-0-2015-11-05?p=2278219&viewfull=1#post2278219 indicates that we omitted the KSPAPIExtensions.dll file.  There will be a release today fixing that issue.  If you have a different issue loading KSP, we'd rather know it before releasing so that we can fix both in one update.

**Comment by dcrockwell** [comment]
My case is exactly the same as that case. I've already reverted back a version and lost the logs. If there's anything else I can do to help, let me know.

**Comment by dcrockwell** [comment]
Works with 0.18.1. Closing.
