### ISSUE TITLE
[Bug]: 0.18: "Resources" and "Stage Only" not properly registering

### ISSUE THREAD

**Issue by EhevuTov** [KSP-KOS/KOS#1231]
With 0.18, my code no longer works properly(worked fine in 0.17.x):

```WHEN STAGE:SOLIDFUEL < 0.01 THEN {
	PRINT "DROPPING BOOSTERS".
	STAGE.
}```

I think this might be a potential bug.

Moments after lift-off, my staging increments instead of waiting for the fuel to run low. It appears that the "Resources" aren't registering properly in the UI. If it's wonky in the UI, I'm assuming it's wonky in the back-end which would mean that my code logic is correct, just the STAGE:SOLIDFUEL is not registering properly.

Attached pics:

Pic 1) you will see how my solid boosters are fired, but not registering in the Resources window properly with "Stage Only" on.

Pic 2) you will see when I click off "Stage Only", Solid Fuel shows.

Pic 3) when I click "Stage Only" back on, Solid Fuel shows, when it wasn't before in Pic 1. Moments later, my next stage fires even though `STAGE:SOLIDFUEL < 0.01` is not true.

![screenshot14](https://cloud.githubusercontent.com/assets/1071470/10998867/fac2b064-845d-11e5-9c1b-12c41bea572d.png)
![screenshot15](https://cloud.githubusercontent.com/assets/1071470/10998869/fcd5ff8c-845d-11e5-8be7-9fb163e66669.png)
![screenshot16](https://cloud.githubusercontent.com/assets/1071470/10998873/feebde18-845d-11e5-8c7e-f19751c3d68a.png)

**Comment by hvacengi** [comment]
Have you tried having kOS print the solid fuel amount to the terminal so that you can track what kOS is reporting the `stage:solidfuel` value to be?  It's odd that it would work initially and then stop working.  Which makes me wonder if your `when` trigger isn't getting registered until the point where you see the staging, and thus `stage:solidfuel` is never returning the correct value.  I won't have the ability to test this myself until this afternoon (EST) but if you could do a little legwork I may be able to track down the problem more quickly.

Your output log might also be helpful, though there shouldn't be anything there unless an exception gets thrown (which you should also see on the terminal).

**Comment by hvacengi** [comment]
Nevermind, found the issue.  Just another case of a squad method not doing what I expect.  I've got a PR submitted to fix the bug (I think).

**Comment by EhevuTov** [comment]
When I do a `print`, it prints a `o` or something that looks like a zero, but I don't think it's a zero. I think it might be a symbol for a null value(the font is too weird for me to tell the difference).

If your `SOLIDFUEL` IS ONLY IN one stage, then a workaround is:

```WHEN SHIP:SOLIDFUEL < 0.01 THEN {
	NOTIFY("DROPPING SF BOOSTERS").
	STAGE.
}```

Thank you for your work @hvacengi. I really appreciate the time you've put into this and your other fixes. It helps a lot with smooth staging.

**Comment by hvacengi** [comment]
Yeah, I saw that zero value (definitely a zero on my screen) which is how I knew something was messed up.  But everything looks good in my develop copy now.  Hopefully this will make it into today's patch.
