### ISSUE TITLE
ProgramBuilder.ReplaceLabels error with compiled scripts

### ISSUE THREAD

**Issue by chippydip** [KSP-KOS/KOS#1253]
I tried to pre-compile my library scripts to save on load times, but ran into these errors:

    ProgramBuilder.ReplaceLabels: Cannot add label steering`0-default, label already exists. Opcode: push $steering
    ProgramBuilder.ReplaceLabels: Cannot add label throttle`0-default, label already exists. Opcode: push $throttle

Deleting the compiled versions and letting kOS auto-compile works just fine.

(kOS 0.18.1 with KSP 1.0.5)

**Comment by Dunbaratu** [comment]
Can you give the text of the scripts themselves?

**Comment by chippydip** [comment]
Sure thing: https://www.dropbox.com/s/4di57l43w7avng2/kOS_1253.zip?dl=0

**Comment by hvacengi** [comment]
I'm betting this is the same issue as #691.  That exception is the one I updated when we fixed it so compiled scripts didn't throw an exception when calling another compiled script (PR #1216).  I'll look through the scripts a little later, but my guess is that you have two compiled scripts both trying to use `lock throttle to...` and `lock steering to...`.

**Comment by chippydip** [comment]
Yeah, I have a `mission.ks` script that loads both of the libraries (which both have a bunch of throttle and steering locks), makes a few calls into the library functions, and then at the end locks throttle and steering to default values.

**Comment by Dunbaratu** [comment]
ReplaceLabels has been through a few changes.  Is this still happening?  I think this was fixed but it didn't get closed.

**Comment by hvacengi** [comment]
No, this has not been fixed.  The issue is that when you create a new lock, it inserts a dummy declaration at the beginning of the program with a default value of zero.  
```
archive/boot.ks        10:1   0033 y`0-default push $y 
archive/boot.ks        10:1   0034 @0063 return 0 deep 
```
The dummy declaration is inserted by the compiler based on whether or not the variable already exists.  Since the variable may well not exist when compiling the ksm file, the dummy declaration gets compiled into the ksm file.  But this dummy variable uses a label instead of an instruction pointer, and must go through the "replace label" process.  so if you lock to the same variable before running the ksm file, or in another ksm file, the label collides.

In my opinion, the answer is to remove the default value.  It is always `0`, even when the lock is for a different type like a vector.  I'm sure the initial reason was so that you didn't get a "no variable declared" error if you accessed the lock before it was set up, but we don't have any similar protection with other variables and you could just as easily get a "that suffix doesn't exist" or "can't add scalar and vector" errors with the default value.
