### ISSUE TITLE
Error calling PartModule:DOACTION

### ISSUE THREAD

**Issue by etherealmachine** [KSP-KOS/KOS#1260]
I'm getting an error "method not found GameVariables.UnlockedActionGroupsCustom" trying to call DOACTION on a PartModule. The PartModule in question is a RemoteTech antenna, and the action is just "activate". It looks like the offending code might be: https://github.com/KSP-KOS/KOS/blob/f54c5f0336da54b66904ef97c97e5437d6d64734/src/kOS/Suffixed/Career.cs#L111. The error occurs both with and without the custom action groups VAB/SPH upgrade. This is on kOS 0.18.1, KSP 1.0.5.

**Comment by SirDiazo** [comment]
This issue is actually a simple fix, it's actually so simple that there are no code changes required.

Once kOS is recompiled against the new KSP 1.0.5 .dll files, this error will go away. The UnlockActionGroupsCustom and UnlockedActionGroupsStock were moved in version 1.0.5 and kOS can no longer find them in KSP 1.0.5

However, as soon as kOS is compiled against KSP 1.0.5, it will find the new location of these methods and everything will be fine again.

My own mods affecting action groups ran into this issue, for the kOS devs the exact issue is that the method signature changed from UnlockedActionGroupsCustom(Float) to UnlockedActionGroupsCustom(Float,[bool]) so even though only passing a float is still valid it still counts as a method signature change so kOS can't find the method. For reference, the brackets mean that if the bool is not present, a default value of true is used, the bool itself is true to check the VAB, false to check the SPH.

**Comment by Dunbaratu** [comment]
@SirDiazo I expected it was an out of date DLL issue but I was still going to take the time consuming effort to try to reproduce it with different versions of the DLL to prove it.  Thanks for posting so I don't have to waste my time doing that.

@etherealmachine a new release of kOS for KSP 1.0.5.x is probably about a day or two away.  The only hang-up is that we're a team of about 5 people around the world doing this in spare time and it can be time consuming getting everyone's schedules to sync so we're all online together for a few hours to push out releases.  We have all the code ready its just the mechanical steps of getting a release out that we have to do - regenerating the docs, typing up a verbose change log, and all team members giving it the thumbs up.

**Comment by etherealmachine** [comment]
Thanks for the super fast response, I anxiously await the kOS release. @SirDiazo, are there online docs with the KSP API, or do you just know from having a dev environment set up and actually checking the DLL? I figured it was a DLL sync, but couldn't find docs on what had changed.

**Comment by SirDiazo** [comment]
I know because two of my mods (AGX and AutoActions) also tried to call this method and ran into the very same error and in looking into what the new 1.0.5 .dll file has showed this to be the problem.

The issue is I can't figure out why Squad did this. You pass UnlockedActionGroupsCustom a float, not a facility identifier, so having a bool to differentiate between the two facilities make no sense as you have to already make that distinction in your own code to get the float for the correct facility.

Well, issue for the future anyway, not actually an issue in the here and now of this kOS bug report.

**Comment by hvacengi** [comment]
Fixed we released 0.18 compatible with 1.0.5.
