### ISSUE TITLE
Add config for career limits when possible

### ISSUE THREAD

**Issue by chippydip** [KSP-KOS/KOS#1262]
Career limits fall into two categories, those "inherited from the stock KSP game" and those "invented by kOS". The former, related to patched conics, sounds like they are probably enforced by the underlying game engine and couldn't be changed even if you wanted to. The latter, on the other hand, were a conscious decisions by kOS devs to gate those abilities behind upgrade costs.

While I understand the rationale for making those limits the default, it would be nice if they could be tweaked based on personal preference. Action groups are mostly a convenience feature--they don't let you do anything that you couldn't do manually through the right-click menu. Tags definitely fall into the same category as a convenience feature. The DOACTION limit, on the other hand, makes certain things not just less convenient, but completely impossible until the VAB/SPH has been upgraded.

DOACTION is technically limited until you have custom action groups but in practice once you have default action groups you can essentially by-pass the limit by binding actions to those groups and then activating them via script. On top of that, there's no limit on DOEVENT calls, which seems inconsistent (but is nice to be able to auto-open the kOS console from a boot script).

The DOACTION/DOEVENT inconsistency makes it so that if other mod authors convert an event into an action to make it easier for users by allowing them to bind to action groups they actually end up making things harder for anyone trying to use their mod with kOS. I noticed this while trying to find the best way to deploy antennae for a set of early game RemoteTech satellites. Apparently they used to be deployable via DOEVENT, but are now only available via a DOACTION call.

I can activate the antennae manually via right-click either immediately or after a timed delay using the RemoteTech computer, but the fact that I can't do this through kOS is more frustrating than fun to me.

Currently I can circumvent the DOACTION limitation using CustomBarnKit to unlock custom action groups from the start (though, this still doesn't work due to #1260) or setup action groups in a sandbox game and then copy the craft to my career game and trigger the action groups via script. Neither of these is ideal, it would be much nicer if I could just toggle a value in a kOS config file to disable the DOACTION limitation.

Obviously different people will have different opinions on career limits, so making them configurable when possible seems like an easy way to allow people to setup kOS however it's most fun for them.

**Comment by Dunbaratu** [comment]
DOACTION isn't a limit invented by kOS.  The limit is there to begin with in stock.  If a PartModule has a hook that is only available via an action group, then you'd be unable to access it in the stock game if you can't bind it to an action group, and thus allowing it in kOS would be a back-door escape around that stock limit.

If you can access something manually via the rightclick menu in flight, then it is emphatically NOT just a KSPAction but is also a KSPEvent as well.

If you are seeing something you are able to activate manually during flight with the rightclick menu and that thing is NOT appearing as available through either DOEVENT or SETFIELD, then *THAT* is the bug to be reporting.  It's supposed to be.

**Comment by SirDiazo** [comment]
Reading this, I think the core issue is that a lot of commands have both a KSPEvent in the right-click menu and a KSPAction for using the action groups.

Then in early career you can't access the KSPAction because action groups are locked, but you can still access the KSPEvent with the mouse leading to a disconnect in how things are controlled on the vessel.

Then the Remotetech antenna thing with comm delays and vessels out of control happens and turns this from a relatively minor issue into something that can cause permanent, unplanned, loss of vessels in flight.

As far as I can tell, this boils down to how career mode is supposed to work. My best guess is that Squad went "Okay, we've got a kerbal in the cockpit, allow the player to control everything manually." So we still have access to all the commands via KSPEvent, but lose the 'automation' of action groups.

This is just about the polar opposite of kOS which is all about automation and writing scripts.

I don't know where kOS is in the tech tree but the two immediate solutions that come to mind are to either just say that if you have a kOS computer unlocked, you have action groups unlocked as well, or to limit kOS via VAB/SPH upgrades rather then the tech tree so if you have access to kOS you have action groups available as well.

**Comment by chippydip** [comment]
Interesting! So, if something shows up in the right-click menu and is bindable to an action group that means it has both an event and an action that do the same thing? And it would also be possible to have a bindable action that doesn't show up in the right-click menu?

When I tried to use `p:GETMODULE("ModuleRTAntenna"):DOEVENT("activate")` I got an error. Looking at the list of fields/events/actions on ModuleRTAntenna I think there was a "deactivate" event and a couple actions ("activate", "toggle", and "deactivate" if I remember correctly). I'll have to check this evening to see if there's an activate event on some other module for the Communotron-16 or if the deactivate event is mis-named or something like that.

**Comment by SirDiazo** [comment]
Yes, Events in the right-click menu and Actions are two completely different objects.

In most of the stock code, the Event is where everything happens and the Action Object is a one-line method that calls the equivalent Event.

As you noted, this means they can be named different things even though they perform the same action. As Event and Action names are just string objects their names are whatever made sense to the programmer writing them, there is no standard that I have ever noticed.

**Comment by Dunbaratu** [comment]
Remotetech is also specially rude in that the mod messes around with the rightclick menus of ALL other partmodules in rather rough ways that shove aside what other mods are trying to do.  They tend to *replace* existing KSPEvents with their own when you manually open up a menu in the game, in order to try to deny people the ability to control the ship manually.  This can end up hiding the functionality from our scripts as well as from the human player, as RemoteTech only supplied other mods with a way around their lockout of the main controls, not a way around their lockout of the UI interface lockout they do.

**Comment by chippydip** [comment]
So, I think I figured out what happened. I was initially testing in the console, printing things as I went to make sure I had the part names correct and ended up running this:

    print SHIP:PARTSDUBBED("Communotron 16")[0]:GETMODULE("ModuleRTAntenna"):DOEVENT("ACTIVATE").

Which gave me an "Object reference not set to an instance of an object" error (with the caret seemingly pointing to the quote before "ACTIVATE") so I assumed it didn't work.

I then re-ran the command without the `print` which gave me a "No EVENT called ACTIVATE was found on ModuleRTAntenna, containgin: ..." error.

Activating the antenna removes that event and replaces it with a "Deactivate" event instead, so when I got the first error I didn't realize the command had actually executed, which led to further confusion.

Since this was really a PEBKAC error, I guess I'll go ahead and close the issue.
