### ISSUE TITLE
FileInfo gives less info than other docs say it should

### ISSUE THREAD

**Issue by crafty-geek** [KSP-KOS/KOS#1278]
The `TimeSpan` page talks about being able to get (system) created/modified times from `FileInfo` objects, but the `FileInfo` page lists no such fields.  Being able to compare `:MODIFIED` fields on `FileInfo`s would make updating libraries on a craft awesomely smooth, so I would hope the info gets exposed to the scripter (as opposed to the docs getting changed to reflect current reality).

Docs: [`TimeSpan`](https://ksp-kos.github.io/KOS_DOC/structures/misc/time.html), [`FileInfo`](https://ksp-kos.github.io/KOS_DOC/structures/misc/fileinfo.html#structure:FILEINFO)

**Comment by Dunbaratu** [comment]
The decision was made to remove the timestamp info because of how archive files are stored on the real computer's filesystem with real-world timestamps, while the local volumes would have to use in-game-clock timestamps (for example when the game is paused, the OS's clock keeps moving for its files but the in-game clock doesn't).  To make them consistent would be a royal pain given that we want to let people edit the scripts in archive out-of-game with their own text editors.

**Comment by crafty-geek** [comment]
And there's a compelling reason not to just have all timestamps use OS
clock time?

**Comment by Dunbaratu** [comment]
Roleplay mostly?   If the only thing you care about is which file is later than which other one, it would work.  If you want to know how LONG it's been since a file was changed, in-game, then it doesn't, because you don't want to count the time that passed while the universe was paused.

**Comment by hvacengi** [comment]
Using the OS clock would require exposing the OS clock itself in game as well.  Which might not be so bad (it could be handled on `KUNIVERSE`).

Honestly, in my scripts, I just assume that the libraries are old.  So any time it boots with a connection to the KSC, my scripts copy the library files over.

**Comment by erendrake** [comment]
Closed by #1341
