### ISSUE TITLE
boot scripts run too soon - before all the parts of the vessel have been fully activated in physics

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1280]
KSP activates full physics on the vessel parts one a a time, so it's possible for the kOS computer to be up and running and starting the boot script before the other things are all ready to work.

thus a boot script like so fails to move the gear:
```
// this is boot.ks
gear off.
wait 0.1. 
gear on.
```
but throw a long wait in front and it works:
```
// this is boot.ks
wait 2.
gear off.
wait 0.1. 
gear on.
```

**Comment by hvacengi** [comment]
I did a bunch of searching to try and deal with this very issue in a previous release.  KOS checks to see if the vessel is loaded before executing, but that flag is true as soon as it starts loading parts rather than after iterating through all of the parts.  The only way to detect if a vessel has actually fully loaded into physics is by checking to see if it's packed or unpacked.  But if we waited until the vessel was unpacked before running the boot script, other use cases would prevent the boot script from running when it should (such as power being restored when coming out of a shadow in timewarp, a vessel coming into physics range, etc.).  I only see 2 other alternatives:
* Do a parts walk to find out if all parts are loaded, then set a cached bool true.  This is expensive, but as long as we cache the value the walk should only walk the parts a couple times and only at the very beginning.
* Introduce a delay in the boot sequence itself.  If it is consistently one or two physics frames before all parts are loaded, we can simply wait that many fixed updates frames before executing the boot script.  In my previous testing however, this doesn't appear to be consistent.  I suspect that the part load is spread across multiple physics ticks depending on how long it takes.

I have a plan to revise the boot sequence a little bit to help handle the logical states a little better.  In that update, I planned on moving the boot logic out of the `SetMode` method and into the fixed update using a new state of `BOOT`.  I could easily add that parts walk before executing the boot.

In the mean time, my work around has been to put `wait until ship:unpacked.` at the top of most of my scripts.  If you only want to do it during the prelaunch condition (so that it won't interfere in the above cases) you could modify it to `wait until ship:status <> "prelaunch" or ship:unpacked.`

Waiting until the ship is unpacked also has the added advantage of ensuring that KSP doesn't change the value of the pilot throttle, since it sets it to 0.5 during the unpack method at prelaunch.

**Comment by SirDiazo** [comment]
What I have used in the past is the Vessel.holdPhysics bool.

The advantage to this is that .holdPhysics is a flag that tells you when KSP things the vessel can be modified and when it can't, not just on vessel load/launch.

So conditions such as time-warp set .holdphysics to true because any commands issued to KSP will not affect the vessel.

Note I'm not sure what happens under physical time-warp, I assume .holdphysics stays false but that's just based on the name of the bool.

**Comment by hvacengi** [comment]
My only question is: When is `holdPhysics` first set to false?
Your comparison to time-warp worries me that it may be analogous to unpacked.  It is possible that it has less constraint that `unpacked`, for instance a ship that is loaded may have `holdPhysics` set to false even though it isn't within the unpack distance.  But if it behaves the way you say it does during time-warp, then it probably won't fix the issue of rebooting scripts during timewarp (scripts do need to be able to run during timewarp, since they can abort it).  I'll take a look at that value however, and see if I can make it work in conjunction with the other state information.

Thanks for the heads up.

**Comment by SirDiazo** [comment]
I think there's two similar but different issues here.

1) kOS tries to run boot scripts as soon as it's `part`, not the vessel loads.

2) Not all commands are valid under time warp. Scripts need to be runnable during timewarp in order to disable it, but trying to activate the Gear action group while under timewarp won't do anything. (Not sure how kOS currently handles this.)

In case 1, the .holdPhysics bool works because I believe that when the Vessel object is created to be populated with Part objects, .holdPhysics instantiates to true. Then once all parts are loaded and things are ready to go is the trigger for .holdPhysics going false. (the vessel 'sags' on the launch pad).

Case 2 I'm not so sure about and don't really have a comment on.

**Comment by hvacengi** [comment]
I just did a little digging with ILSpy to figure out how `HoldPhysics` works.  It's a public property for an obfuscated bool variable on the `Vessel` object. As near as I can tell by analyzing that variable, the only times it is set to true are in `Vessel.Initialize` and `Vessel.Load`.  I decided to add a suffix for `HOLDPHYSICS` and test it's values.  Here are the results of my very quick test:
* When launching a new vessel, `HOLDPHYSICS` starts as true, and moves to false when the ship is successfully unpacked.  The value for `UNPACKED` is the opposite of `HOLDPHYSICS` for each tick.  There are a number of ticks that pass before `HOLDPHYSICS` is set to false.
* When loading a ship which is already landed on the planet, the value for `HOLDPHYSICS` behaves the same as when launching.
* When loading a vessel in orbit, the value of `HOLDPHYSICS` appears to be false initially, at least by the time of the first physics tick when kOS executes the boot script.
* During time-warp, either on the surface or in orbit, `HOLDPHYSICS` remains false, while `UNPACKED` changes to false.  This is the only time I saw the two not have opposite values.  Physics warp behaves the same way.

So, based on the above testing, it looks like we could indeed use `HOLDPHYSICS` to control boot scripts.  Since it is unaffected by time-warp, it shouldn't give an issue with scripts recovering from power shortages in time-warp.  I'll have to do some more testing to figure out how it affects vessels that come into physics range (at that point between loaded and unpacked) but this may be the magic bullet that I was looking for.

Thanks again for pointing it out.
