### ISSUE TITLE
Open brace and open paren halt execution in strings

### ISSUE THREAD

**Issue by gisikw** [KSP-KOS/KOS#1285]
Using an unclosed paren or brace within a string expression causes execution to freeze.

```
print "(". // No output
1/0.       // Still no output
).         // Now, it crashes
```

Same with the open brace, and when used as part of an expression (not simply a print issue)

```
set x to "{". // No output
print x.      // No output
print "}".    // Outputs {, then }
```

## Workaround
Using the terminating paren/brace as a no-op expression gets the parser to behave correctly, i.e.
```
set x to "BODY(Mun)":split("(")[0]. ")".
print x. // "BODY"

print "{". "}". // Prints "{"
```

**Comment by Dunbaratu** [comment]
I'm surprised it doesn't barf and instead hangs.  If it was a problem, I'd expect it to fail utterly, not get stuck, since this:
```
       (".
1/0.
)
```
isn't a valid thing to be printing.  It must be coming from somewhere other than the actual parser.

**Comment by Dunbaratu** [comment]
Confirmed.  I was able to reproduce the problem.  Weird.  Looks like I need to fire up TinyPG and carefuly examine the parse tree it produces on this input syntax.

**Comment by Dunbaratu** [comment]
Interestingly, if you do this:
```
print "(".
print "stuff".
print ")".
```
Then it *does* print correctly like so:
```
(
stuff
)
```
However, it doesn't print any of that out until *after* it encounters the lastmost line.  If you type those lines in one at a time interactively, you end up with this:
```
print "(".
print "stuff".
print ")".
(
stuff
)
```
When since it was interactive, it shouldn't have waited until the last line .  IT should have been printing the strings out immediately like this:
```
print "(".
(
print "stuff".
stuff
print ")".
)
```

**Comment by Dunbaratu** [comment]
Verified that the TinyPG parse tree is actually correct here.  It is separating the 3 print statements as 3 different statements, and isn't parsing the stuff between parens as a unit.  So.... whatever it is is broken *after* the parse... I suspect because it *does* perform the code correctly eventually, but too late, that it's got something to do with the system that allows you to continue an incompleted command on the next line in the interpreter rather than calling it an error.

**Comment by Dunbaratu** [comment]
Problem analysis:

This is only a problem in the live interpreter, not in executing a program file.  In executing a program, it's *correct* to wait until the end of the program's compilation before doing anything.  But in the interactive interpreter, it tries to compile and execute statements one at a time.  There is a check in ``kOS.Screen.Interpreter`` that tries to catch the special case where the command shouldn't be compiled yet because it isn't done and would be an error if you tried.  It's intended for cases like this:

- User types: ``if x = 0 {``  <-- interpreter doesn't do anything yet.
- User types: ``  set x to 1.``  <-- interpreter doesn't do anything yet.
- User types: ``}``  <-- NOW the interpreter tries to compile what you typed so far and run it.

That check is performed by this method in ``kOS.Safe/Compilation/KS/KSScript.ks``:

```

        public override bool IsCommandComplete(string command)
        {
            char[] commandChars = command.ToCharArray();
            int length = commandChars.Length;
            int openCurlyBrackets = 0;
            int openParentheses = 0;

            for (int n = 0; n < length; n++)
            {
                switch (commandChars[n])
                {
                    // match curly brackets
                    case '{':
                        openCurlyBrackets++;
                        break;

                    case '}':
                        openCurlyBrackets--;
                        break;
                    // match parentheses
                    case '(':
                        openParentheses++;
                        break;

                    case ')':
                        openParentheses--;
                        break;
                }
            }

            // returns true even if you wrote extra closing curly brackets/parentheses
            return (openCurlyBrackets <= 0)
                && (openParentheses <= 0);
        }
```

As you can see, it's just performing a dumb lexical look at the content of the string without much regard to the "real" parsing complexities, and thus it saw the "(" and thought it was an expression parenthesis opener in need of a closer.

This check is ONLY performed from the interpreter, NOT from executing a program file.
