### ISSUE TITLE
manuever node tutorial gives incorrect information about burn duration

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1297]
**Problem 1 : Tsiolkovsky delta-V not mentioned - crude version is claimed to be the real thing:**

The maneuver node tutorial uses the crude approximation of burn time to achieve delta-V of just dividing maxthrust by mass to get accelleration, and then assuming accelleration is a constant.

The proper calculation that takes into account the Tsiolkovsky rocket equation should be at least alluded to, along with the fact that the value present in the tutorial is just a crude approximation.

It doesn't have to use the complex real calculation - the crude one is fine for tutorial purposes.  But it shouldn't be making false claims to users that that *IS* the actual burn time, which is what it's doing right now, and that sort of makes us look like we don't know what we're talking about when someone who knows a thing or two reads it.

**Problem 2 : The example is unnecessarily complex for steering**

It tells people to do this:
```
set np to lookdirup(nd:deltav, ship:facing:topvector). //points to node, keeping roll the same.
lock steering to np.
```
It could just tell people to do this:
```
lock steering to nd:deltav.
```
And then it would also auto-update if the XYZ axes of the universe happen to rotate while waiting for the burn.

**Comment by hvacengi** [comment]
I agree that the rocket equation should be mention, so that the user knows to go look for a better calc once they start looking for ways to improve accuracy.  We may want to consider providing a `STAGE:ISP` suffix to the users to help with this too.  I've always preferred the current path, where users must iterate through engines to calculate ISP, but a more accessible method might be an easy tie in to this reference.

As for problem two, technically `lock steering to nd.` would the the easiest syntax.  I'm not sure that it's well documented, but a maneuver node is (and was before the recent revision) a valid steering value type.  I did not test it extensively when removing the maneuver node, but I'll make sure to do so now.  It may null ref, or it may just end up pointing at `v(0, 0, 0)`, or something more "Kerbal".

**Comment by hvacengi** [comment]
Close via #1341
