### ISSUE TITLE
Some ScienceExperimentFields suffixes don't work with Orbital Science mod

### ISSUE THREAD

**Issue by tomekpiotrowski** [KSP-KOS/KOS#1307]
Originally reported here: https://www.reddit.com/r/Kos/comments/3vzhcw/dmagics_orbital_science/

**Comment by mcortez** [comment]
I've sent an opening request over to DMagic, hopefully he'll be amenable to tweaking his code.

http://forum.kerbalspaceprogram.com/index.php?/topic/59009-105-dmagic-orbital-science-new-science-parts-v1091-11112015/&do=findComment&comment=2315756


If he isn't, I think just calling his DeployExperiment() method should work.  The way he has his module laid out, the science is stored and ready to be transmitted before the dialog box is even displayed.  His event handler for dealing with "Save Data" is empty, because the data is already saved.  

Thanks for looking into this!!!

**Comment by DMagic1** [comment]
These new methods will still require some kind of reflection call to use, but that shouldn't be difficult if you want to add such a thing.

They should handle collecting and storing science data in all cases. There is a potential issue with the built-in delay for several of the experiments, but that basically will just require waiting a bit between collecting data and trying to do anything with it.

**Comment by tomekpiotrowski** [comment]
I know that we will have to use reflection, but such a call wouldn't happen often so it would not be a performance hit.

I will submit a PR to Orbital Science that introduces the necessary change and will be already tested with our code.

**Comment by tomekpiotrowski** [comment]
@DMagic1 I have submitted a PR to KOS that makes use of your new methods. No extra changes in Orbital Science were required to make everything work properly. Thanks for helping out!
