### ISSUE TITLE
clear a file

### ISSUE THREAD

**Issue by dcrockwell** [KSP-KOS/KOS#1309]
I'm using a file to dump CSV data from each flight to plot, but I have to manually go into the file and delete the previous flight's data on each flight.

Is there a way to clear a file?

**Comment by hvacengi** [comment]
I just delete the file when I need to clear it.  That doesn't work well if you're using another program to effectively stream the file data (since removing the file would likely thrown an error in the other program) but if you're just opening the csv file after the mission, `delete datalog.csv` would work.  The bigger trick is that it's a long process right now to find out if a file exists (which will be fixed eventually) so really I typically do this `log "\\" to datalog.csv.  wait 1. delete datalog.csv.`.  You can probably safely remove the wait, but I keep my script folder synced using dropbox, and the file is usually locked until it has been uploaded.

**Comment by dcrockwell** [comment]
Even clearing the data in the file would be a big help.

```
CLEARFILE data.txt.
```

I have the CSV streaming the file into LiveGraph, so deleting the file doesn't work right. Either it doesn't actually delete silently, or it's unable to create a new log of the same name.

**Comment by TDW89** [comment]
not sure if this will work with streaming but it might.
```
switch to 1.
log "" to datalog.csv.
switch to 0.

//then to clear datalog.csv
copy datalog.csv from 1.
```
it may be a bug but copy does not produce the file already exists that rename does it just overwrites the file it may be fast enough that it wont interrupt streaming.

**Comment by Dunbaratu** [comment]
I think that regardless of the existence of these workarounds, it's still a good idea to add a clear file functionality to the system.

**Comment by dcrockwell** [comment]
@TDW89 Cool workaround. I'm going to try it out now :)

**Comment by dcrockwell** [comment]
It's weird, but @TDW89's code didn't work.

```
SWITCH TO 1.
LOG "" TO datalog.csv.
SWITCH TO 0.
COPY datalog.csv FROM 1.
````

Results in:

```
Object reference not set to an instance of an object
At interpreter history, line 20
COPY datalog.csv TO 0.
                    ^
```
