### ISSUE TITLE
Update documentation to remind users not to not feed PIDloop() a long function

### ISSUE THREAD

**Issue by benetherington** [KSP-KOS/KOS#1365]
If you update a PID with a function that takes longer than a tick to run, PIDloop will return 0. I suggest adding a note in the documentation to this effect.

**Comment by hvacengi** [comment]
Can you give a little more information and background?  Do you mean that you pass a lock object or a function evaluation to the update suffix?  Does this behavior change if you first set a variable to that function/lock and then pass the variable to `PIDLoop`?  In that instance, what happens to the value if you print it to the screen?

I'd like to see the script that is generating this error for you, since it shouldn't happen.

There is built in protection against inflating values if the time step is greater than one second, but that was more for the sake of the steering code it was originally written for.  Even in that instance, the proportional component will be calculated, it's just that the derivative and integral are not updated (leaving them the same as the previous update).

**Comment by benetherington** [comment]
Okay, so this came up when I was trying to write a function to limit my throttle to a certain acceleration. I wanted to be able to pass in a "requested" throttle and have the function return either my requested throttle if it was safe or the result of a PID loop that looked at acceleration. I wrote something like the following:

```
function acceleration {
  local last_vel to ship:velocity:surface:mag.
  local last_time to time:seconds.
  wait .01.
  return abs( ((ship:velocity:surface:mag - last_vel) / (time:seconds - last_time)) / 9.81 ).
}
global just_one_G_controller to pidloop().
lock throttle to just_one_G_controller:update( time:seconds, acceleration()-2 ).
until ag1 { print just_one_G_controller:output. }
```

Clunky but a good place to start. If you run this, you'll just get 0s from just_one_G_controller(). If you refactor acceleration() to allow delta time to be saved in a variable and just return the last value if no time has passed, just_one_G_controller() wakes back up. The following might be pseudocode, I don't remember if it worked in the commit I grabbed it from.

```
function time_rememberer {
  parameter new_time.
  local spit_time to old_time.
  if new_time <> "last" { set old_time to new_time. }
  return spit_time.
}

function current_acceleration {
  if ( time:seconds - time_rememberer("last") ) > 0.0001 {
    global current_acc to abs( ((ship:velocity:surface:mag - last_vel) /
                                            (time:seconds - time_rememberer("last"))) / 9.81 ).
        time_rememberer(time:seconds).
        set last_vel to ship:velocity:surface:mag.
  } 
  return current_acc.
}
```

**Comment by hvacengi** [comment]
Ah, the problem isn't with PIDLoop then.  In the first version of the code, you attempt to wait inside of the function `acceleration`.  Because it is being evaluated within the `lock throttle` structure, it is run as a trigger instead of main line code, and all triggers ignore `wait`s.  You can find this documented here: http://ksp-kos.github.io/KOS_DOC/language/flow.html#wait

A simple revision to the original code that should work would be:
```
global last_vel to ship:velocity:surface:mag.
global last_time to time:seconds.
function acceleration {
  local dv is ship:velocity:surface:mag - last_vel.
  local dt is time:seconds - last_time.
  set last_vel to ship:velocity:surface:mag.
  set last_time to time:seconds.
  return abs( dv / max(dt, 0.001) / 9.81 ).
}
global just_one_G_controller to pidloop().
lock throttle to just_one_G_controller:update( time:seconds, acceleration()-2 ).
until ag1 { print just_one_G_controller:output. wait 0.001. }
```
All triggers like these are evaluated exactly once at the beginning of each physics tick.  Other locks (like `lock h to alt:radar.` are evaluated only when called, but throttle and steering are evaluated every time.  KSP has a weird thing though where occasionally physics will tick, but time won't move, which is shy I added that call to `max` to guard against division by zero.  I also added a wait to your `until` loop because your otherwise printing that output until you hit the IPU limit (default 200), and waiting will make it so you only print once per tick.

**Comment by hvacengi** [comment]
Upon another reading of the documentation, that note is not exactly clear about the triggers not accepting a wait command.  We do need to fix that.  While it does say "The WAIT command only causes mainline code to be suspended. " the context implies that triggers are unaffected by mainline waits, not necessarily that triggers will ignore waits in their own context.

It is explicitly detailed here: http://ksp-kos.github.io/KOS_DOC/tutorials/designpatterns.html#minimize-time-spent-in-when-then-blocks But that requires you infer from the documentation that `lock steering` and `lock throttle` are the same as `when` blocks.  Maybe an update to this section of the documentation, and make the previously cited note point to this page?
