### ISSUE TITLE
Enhancement: import lexicon as variables 

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KOS#1375]
Not sure if import is the right word, but a way of saying:
for each item in this lexicon create / set a variable / pointer named after the key to the value, would be useful.

not a major feature as it doesn't add anything new, just makes the code easier to read / write.

an example would be:

```
set control_map to lexicon().
 lex:add("controls",ship:control).
 lex:add("input_gap",0.5).
 lex:add("last_input",0).
 lex:add("shift",false).
 lex:add("w",false).

set controls_to check to list("w").


function rising_input_check {
 parameter
 control_map,
 controls_to_check.

local active_controls is list().

 if controls_to_check:contains("w"){
  if not control_map["w"] and control_map["controls"]:pilotpitch < 0 {
   active_controls:add("w").
   set control_map["w"] to true.
  } else if control_map["w"] and (time - control_map["last_input"] > control_map["input_gap"] or not control_map["controls"]:pilotpitch < 0) {
   set control_map["w"] to false.
  }
 }
```
becomes
```
function rising_input_check {
 parameter
 control_map:import,
 controls_to_check.

local active_controls is list().

 if controls_to_check:contains("w"){
  if not w and controls:pilotpitch < 0 {
   active_controls:add("w").
   set w to true.
  } else if w and (time - last_input > input_gap or not controls:pilotpitch < 0) {
   set w to false.
  }
 }
 ```

**Comment by Dunbaratu** [comment]
I think this is a bad idea. 

Problem 1: You're allowed to have more than one lexicon with the same key name:
```
set lex_aaa["x"] to 1.
set lex_bbb["x"] to 2.
print `x`.  // how is this supposed to be an alias for BOTH of the above two DIFFERENT values?
```

Problem 2: This can break existing code that was just fine and wasn't doing anything wrong at all:
```
set x to 1.
set lex_aaa["x"] to 2.
print x + ", " + lex_aaa["x"].
```
Prior to this enhancement that would print `1, 2`.  After this enhancement it would print `2, 2` because now the script would clobber the existing value in `x` when it used the string `"x"` as a key in a lexicon.

So, I would be very dead set against implementing this, for both of the above two reasons.

**Comment by tomekpiotrowski** [comment]
Thanks for your suggestion, but I would agree with @Dunbaratu. This will probably never be implemented.

@Dunbaratu: I guess we can close the issue?

**Comment by hvacengi** [comment]
@Dunbaratu I think that the suggesting relies on the call to `import`, not that every random lex would import a variable.  So in your example, you would need to be called like this in order to clobber:
```
set x to 1.
set lex_aaa["x"] to 2.
print x + ", " + lex_aaa["x"]. // "1, 2"
lex_aaa:import.
print x + ", " + lex_aaa["x"]. // "2, 2"
```
I'm not saying that this distinction changes your mind, I just want to make sure that it isn't dismissed for something it isn't.

For my two cents: what I uncomfortable with is that it treats string keys as "special citizens".  It falls under the same debate we once had about exposing string keys as suffixes on lexicons.  Both would be very un-generic behaviors for a generic collection.

**Comment by Dunbaratu** [comment]
@hvacengi You're probably right, but it's still super ugly and I don't want to see it implemented.  Two Lexicons can have the same key and if you want to import both of them it still clashes then.  Also identifiers have much more restrictive rules than lexicon keys.  Lexicon keys could be any string, even one with spaces in it, while identifiers can't have spaces.  Also Lexicon keys don't even have to be strings at all.

**Comment by TDW89** [comment]
yep your right i hadn't thought about how messy it could get.
