### ISSUE TITLE
Enhancement/Disscussion LABELS and JUMPS (aka GOTO)

### ISSUE THREAD

**Issue by GER-Space** [KSP-KOS/KOS#1377]
I know that most programmers will crucify me, but it would be sometimes really nice to have labels and a goto call.

It would make a state persistend boot_script more readable and easier to write.

actual I have to write: 
```
if get_my_state() = 10 {
   do stuff
    set_my_state (20).
}
if get_my_state() = 20 {
 ...
    set_my_state (30).

}
```
with Labels and GOTO:
```
goto get_state().

::10 
do stuff.
set_my_state(20).
::20 
do_stuff.
set_my_state(30).
::30 
```

**Comment by tomekpiotrowski** [comment]
Crucifixion would definitely be an acceptable response ;)

I personally think there is no good reason to include this behavior. Especially now when we're gonna have delegation you could write something like this:

```
set l to lexicon().
l:add(10, do_stuff@).
l:add(20, do_stuff2@).
...
l[get_state()]:call.

```

Which is short and sweet.


Btw, JPL Programming Guide discourages the use of GOTO.

**Comment by hvacengi** [comment]
If we were going to do something like this, I'd rather it was implemented as a `switch... case... case...` type syntax.  But looking at @tomekpiotrowski's example, that's essentially what he did using a lexicon.  

Really both goto and switch are just some form of syntactical sugar to make it a little easier to write the program.  You can do the same thing with a function, it's just a little more verbose:
```
function goto {
    parameter line.
    if line = 10 { set_my_state(20). return do10(). }
    if line = 20 { set_my_state(30). return do20(). }
    if line = 30 return do30().
}
goto(get_state()).
```

I agree it probably won't get implemented, but we'll see if any one else weighs in on the discussion with an opinion before saying for sure.

**Comment by GER-Space** [comment]
The (mis-)use of a lexicon as a Switch is really cool.

**Comment by Dunbaratu** [comment]
In general, if someone is asking for "goto", what that request *really* means is "your language doesn't provide me with enough coverage of algorithmic flow using the flow keywords.  Please implement more flow keywords."

If there's a useful case you have to resort to GOTO to cover, it probably means the real fix is to make kerboscript more rich and have it provide whatever flow structure you're trying to use GOTO for.

And it looks like what you're really saying here in this specific case is "I wish I could make a switch/case statement".

I don't agree with the sentiment that GOTO is always evil, but in our special case with kerboscipt, it's too much of a royal PITA to implement.  You might think "but how , it's the simplest thing in the world to implement - just do a jump."  Except remember that for kerboscript, I have to manage the scoping rules at *runtime*, and variables don't exist until at *runtime* you assign them a value.  Every time you do a `break` from a loop, I have to make sure the compiler is smart enough to understand what leaving the current braces will mean to the variable scoping.  If the only kind of "goto" you can do in a loop is "escape to bottom of current braced body, i.e. break" then this is easy.  It's effectively a stack pop (it's a bit more complex than that, to handle lexical scoping rather than rumtime stack scoping, but not much more complex.  It's still pretty simple.).  But if you can do a goto jump to *just about anywhere*, then I have to work out the ugly scoping details of what that sudden jump from one set of braces into another actually means.  Not impossible, but frankly, I don't want the headache of bothering

To throw another wrench into the works, look at this example:
```
goto jumphere.
if x = 0 {
  local foo is time:seconds.
::jumphere
  print "time is " + round(foo,0) + " seconds.
}
```
In that case, by jumping into the middle of the section with the braces, it totally skipped past the `local foo` declaration and therefore *didn't actually make a local foo exist at all*, which will barf when it tries to use it.

Because of all the runtime stuff happening in kerboscript, a goto is a nasty rats nest from OUR side of things, the implementers.  That's even leaving aside all the usual complaints about what it means to the language *users*, it's a PITA for us language *implementers* in this case, much more so than it would be in most (compile-time binding) languages.

Now, I *had* toyed with the idea of making an assembly-like language for kOS that lets you program in the raw Opcodes, and that would definitely have raw goto jumps in it if I ever implemented it.  The main reason I haven't is that doing so would make the VM specification into an API promise stated publicly, which would massively hinder our ability to change it whenever we feel like it.

**Comment by GER-Space** [comment]
Thanks for the clarification and the Ideas for a better workaround. I have no intention for creating pain and I think your time is better spend anywhere else than with implementing GOTO. 

At least it is now documented for everybody why it is 
a) not needed 
b) not easy done

**Comment by Dunbaratu** [comment]
If you want a switch statement, make that a separate issue for discussion.  That might be more doable.

**Comment by tomekpiotrowski** [comment]
`switch` is already discussed here: #860
