### ISSUE TITLE
Scope nesting

### ISSUE THREAD

**Issue by benetherington** [KSP-KOS/KOS#1387]
I think this is a bug, but might be a feature request.

Scope nesting is noted to not work in WHEN and ON, but it doesn't appear to work with IF, either. Consider the following code.

```
function target_time_to_ap {

  local m_constant to 0.0058.
  local b_constant to 19.7.

  if ship:altitude < (60-b_constant)/m_constant {
    return m_constant(ship:altitude)+b_constant.
  } else {
    return 60.
  }
}
```

The first branch of the IF statement throws an undefined variable error (for `m_constant`) unless the "constant" variables are set to global scope.

**Comment by benetherington** [comment]
Nope. Had issues with this in the past, but this code doesn't show the behavior, as the issue is with a missing `*` for the multiplication in the first IF branch.

**Comment by Dunbaratu** [comment]
Even though this is closed, there may still be a real issue hiding under the hood here.
The issue being not that kOS is doing something wrong in making your program not work, but that it's doing something wrong in reporting the reason **why** it doesn't work to you.

It failed when doing a lookup for a *function* called ``m_constant``, but there is a *variable* called ``m_constant`` and it gave the message as if there was no such thing as ``m_constant`` at all.  It only failed to find a thing called ``m_constant`` because it was using a search criterion of "it has to be a function or it's not really a hit".  Thus the message for it not existing at all and the message for it existing but as a different kind of thing ended up being in the same 'else' condition of the code.  That could probably be improved, or at the very least the message could be made better.  "There is no function called m_constant" might be a clearer message.

**Comment by benetherington** [comment]
Yes, I've considered opening a ticket for that exact issue. Not sure how many "the error may be with KOS itself" issues are unsolvable. I'll keep an eye out and get example code up if I can!
