### ISSUE TITLE
Request: accessable mission elapsed time

### ISSUE THREAD

**Issue by benetherington** [KSP-KOS/KOS#1388]
MET doesn't start until the first stage is activated, and seems like a handy thing to have access to.

**Comment by hvacengi** [comment]
I believe this is already available as `missiontime`, however a search of the docs returned no reference.  It must be a variable that never made the documentation transition.

**Comment by benetherington** [comment]
Bingo, thank you.

**Comment by ozin370** [comment]
You can also log a value to a file and read it later using the LOG command. Handy if you want to reset the timer or set a custom one.

**Comment by Dunbaratu** [comment]
In documenting this, I realize it's stupid that it's not a vessel suffix.  Because the actual result it gives is
`shared.Vessel.missionTime` so it's clearly something the game tracks separately per vessel.

But fixing that isn't what I'm trying to do right now, so I'll leave it as is and just document it.

This is one of those old global bindings from before we took over the mod and tried to make it a bit more object-oriented.
