### ISSUE TITLE
Give kOS.Safe.Encapsulated.Structure some generic suffixes

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1408]
Now that PR #1400 is merged, we can start working on the suffixes intended for all user objects (which now all inherit from `kOS.Safe.Encapsulated.Structure`).

This issue superceeds the idea in issue #1237, which I just closed and marked as duplicate of this.

I was about to just jump in and get started on this myself, but in light of what I said in reaction to the KASM PR that arrived on our doorstep out of the blue a few days ago with no previous discussion or issue for it, I thought I should follow my own advice and start with an issue first before implementing it.

It is my hope that we can have at least part of this for the 0.19.0 release, otherwise all that refactoring work for `Structure` has no benefit the end-user can see yet and it feels like we didn't do much this release.  I want at least a few suffixes the end-user can see so there is something to announce with that refactor.

To that aim, I'd like to get a PR for this in very fast - in a day or two at most, which is why I want to break up the suffixes in terms of what can be done quickly now versus what takes a bit more work.  Discuss if you disagree with my ordering of what to do first, or if you think there are other good suffix ideas I've missed.

Text below this line is subject to being edited based on what's said in the comments to follow if people disagree or object:

-----

Ideas of Suffixes to implement, in order from probably easiest to probably hardest:

[ ] `:TOSTRING` - Essentially already exists anyway.  Just needs a user-visible suffix wrapped around it.  The only way people have to obtain it now is to concatenate with a string`("" + thing)`.
[ ] `:HASSUFFIX` - `anyobject:hassuffix("suffixname")` returns boolean.  True if the object has such a suffix name on it, false if it doesn't.  Should also support Vessel Resource suffixes, since it's called on an instanced object, not the class itself, so by then we now know which Resources it has.
[ ] `:TYPENAME` - returns a string (because we don't have enums in kerboscript) for the type of this object. (note (1))
[ ] `:ISTYPE("name here")` returns boolean true if the object is the given type *or is a class derived from it*, like asking if a ScalarIntValue is a "Scalar" should return true. (note (1))
[ ] `:ISSERIALIZABLE` - true if @tomekpiotrowski 's JSON outputter can work with this type.
[ ] `:SUFFIXNAMES` - a LIST() of all the suffix names as strings, but without the full signature info.
[ ] `:SUFFIXHELP` - a string dumping suffix signature info as best as we can, maybe without the descriptions for now, but descriptions could be added later. (note (2))

Notes:

(1) I'm still waffling on what the correct string to use for `:TYPENAME` and `:ISTYPE` should be.  Right now scripts don't see things like `VesselTarget` except in exception messages from time to time.  Instead they see the word just `Vessel`, as a constructor like `set ves to vessel("that ship").`  Similarly for `list()` rather than `ListValue`, and so on.  This would seem to imply that we should be using those strings not the C# names, in which case we should add that as a mandatory member of `Structure` - all structures must name themselves with a property string.

(2) It may be a good idea to reserve the term `:SUFFIXES` for use later but not implement it yet.  My idea for this is that once we have a `SuffixDelegate` as is a kind of `KOSDelegate`, then we can add a `:HELP` to KOSDelegate so that you can always dump the signature data about a delegate (even user ones?).  Once we have that, then I imagine that `:SUFFIXES` would be a LIST() of all the suffixes of the object rendered as KOSDelegates so you can then ask for their HELP one at a time.  This is why I'm reluctant to add the description info to SUFFIXHELP, as it would really belong here instead, and we're not ready to implement this with 0.19.0 yet.

**Comment by hvacengi** [comment]
Regarding the `:TYPENAME` suffix: It isn't just an issue with constructors, but also with our documentation.  I'd suggest adding an abstract method onto the `Structure` class definition:
```
public abstract StringValue GetKOSTypeName();
```
This would force all sub-classes to define their own function for it, rather than us having to maintain a centralized list of everything (granted, some one tried to make said list at some point here: https://github.com/KSP-KOS/KOS/blob/develop/src/kOS/Utilities/Utils.cs#L183 ).  Also, not all structures have constructor functions (there is no `orbit(lan, ... ta)` function) so we don't really want to be tied to that as our reason.

There are a few complicating issues with some of our factory method classes like `PartValue` (`EngineValue`, `DockingPortValue`, `SensorValue`) and `PartModuleFields` (`GimbalFields`, `ScienceExperimentFields`).  Because you'd like `ISTYPE` to return true for parent classes, that means that we would need to construct an inheritance graph.  It probably isn't that difficult to do in reflection (`GetType().BaseType.InvokeMember` or using `GetMethod` would probably work just fine, and could be implemented directly from the `Structure` class) but if you are averse to using reflection for this, each class will need to implement a nearly identical method that calls `base.IsType`.  

I'm having a hard time clarifying why the reference to `base` is a big deal in terms of both initial labor and future code maintenance, so if the next few sentences don't make sense, I can try to rephrase them later: When I say nearly identical, I mean that it would repeat the same logic regarding `base` each time, but that we would be unable to leave it in a method defined on `Structure` because `base` will only refer to the parent class of the class defining the method.  So a `IsType` method defined on `Structure` will always see `base` as `Object`, even if the instance itself is a `VesselTarget` type.  So all current classes would need to copy the same logic, and we would need to remember to implement it on all future classes as well.

**Comment by Dunbaratu** [comment]
> There are a few complicating issues with some of our factory method classes like PartValue (EngineValue, DockingPortValue, SensorValue) and PartModuleFields (GimbalFields, ScienceExperimentFields). Because you'd like ISTYPE to return true for parent classes, that means that we would need to construct an inheritance graph. 

Why?  We already have this:
```
 public class EngineValue : PartValue
```

So with reflection we don't need to maintain our own graph.  It's in the system already.

I get what you mean about base, but I wasn't planning to use it that way anyway.  C# is annoying in that it doesn't allow you to BOTH implement a method AND make it mandatory for derived classes to override your implementation.  You can make it abstract, but only if you don't then implement a version of it in the base class.  Thus the recursion of calling base.IsType() up the chain can't be given a base case to stop the recursion if you simultaneously want to make IsType() be mandatory to override, which is annoyingly restrictive.  Either the recursion up the chain gets a base case, XOR you can make the calls mandatory to implement.  You can't do both, which is exactly what we would need here to do it that way.

**Comment by hvacengi** [comment]
> Why? We already have this:
Yes, we already have C# inheritance, but we need to have that *and* have a way to recursively read the user facing type string for each class, and its parents.  I'm not sure that I consider that portion of reflection easy, but it should certainly be doable.

**Comment by Dunbaratu** [comment]
I suspect we should be able to do something just like the `base.method()` call, but using reflection at runtime to call it so that it's the base of the instance class not the base of the defined class, thus we can still do it all with one method in `Structure` so long as it operates on it at runtime rather than the `base....` construct which is a compile-time thing.

**Comment by Dunbaratu** [comment]
Some of the first few suffixes here are easy to get started on, though, so I'll start adding a few of the easy ones just to ensure  that the 'suffixes everywhere' paradigm is working right.

**Comment by Dunbaratu** [comment]
It turns out Structure already has a TYPE suffix.  How long has that been there?  I'd like to change the name to TYPENAME to indicate that you're getting a string, not a Type object similar to C#'s GetType() gives.

**Comment by hvacengi** [comment]
I mentioned in slack that I couldn't remember if I had removed that suffix or not.  I used it while testing the encapsulation to double check the type.  It is undocumented, do with it as you wish.

**Comment by Dunbaratu** [comment]
Ah okay - it's only been there since Jan 20 according to git blame - so I can change it before end-users see it.

**Comment by Dunbaratu** [comment]
C#'s inability to override static things is really annoying here, by the way.

**Comment by hvacengi** [comment]
What about a static constructor, which adds the type definition pair to the dictionary?  Though, that may call the inherited static constructor as well.  I'm not really sure, I've only used them a couple times.

**Comment by Dunbaratu** [comment]
The difficulty is the sentence in C# docs that claims a static constructor is called when the first instance is made. We may have static types that we haven't instanced yet but we still need their names in the lookup table.
