### ISSUE TITLE
Fix serialization of OrbitInfo

### ISSUE THREAD

**Issue by tomekpiotrowski** [KSP-KOS/KOS#1410]
Looks like some OrbitInfo data will not survive serialization/deserialization (nextPatch, previousPatch etc).

**Comment by hvacengi** [comment]
Right now, there is no way for the user to create an arbitrary `orbit` value.  So, that gives us two directions to go with this issue.
- 1 Instead of serializing and deserializing based on the orbital parameters, the values can be based on  the `orbitable` identifier (I'd prefer based on raw ID rather than name) and a time value.  Then when you recreate the orbit we can use the same method as `orbitat` to recreate the value complete with patches and association with the original object.  This probably requires adding a time component to the `OrbitInfo` class, which would probably help with issue #1367.  I would continue to include the parameters with the serialized object, for the sake of use with external programs.
- 2 Simply acknowledge that `orbit` values will be disassociated upon serialization.  At the same time, we should give the user a way to create arbitrary orbits, since that is essentially what the serialization methods would be doing anyways.

Option 1 has the advantage of maintaining the link between the current ship and the orbit instance.  While not identified in the issue, the other thing broken currently when deserializing is changes to orbital parameters based on physics updates.

Option 1 does have the disadvantage of not being tolerant of reverts, recovery, or significant changes in situation.  For example, deserializing a orbit that referenced a ship that no longer exists would be an error.  Also if the orbit is stored before performing a maneuver that changes your sphere of influence, or adjust the transition time, the value would be an error.  In these instances, we could fall back to using stored parameters and returning a disassociated orbit.  That would be a bit of a hybrid between options 1 and 2.

Option 2 has the advantage of not depending on a orbitable in orbit at all in order to access the information.  Also being able to define an arbitrary orbit value may help users when targeting very specific parameters for contracts.

Option 2's primary disadvantage is that it creates a first class orbit which auto updates with the game, and a 2nd class orbit that is static and never changes.  Obviously, we'd need to add a suffix to differentiate the 2 conditions, but this will probably be very confusing to some users.

**Comment by Dunbaratu** [comment]
If you do this:
```
set o to ship:obt.
print "Ap value from obt object is: " + o:apoapsis.
print "Ap value from ship now is: " + ship:obt:apoapsis.
```
Then the two should be printing the same number.

But then if you thrust the ship a few seconds to raise the Ap, and then do the last two lines again:
```
print "Ap value from obt object is: " + o:apoapsis.
print "Ap value from ship now is: " + ship:obt:apoapsis.
```
are they still that same number as each other, or did doing that cause them to become different numbers from each other now?

In other words, ignoring serialization for a second, how does the already existing Orbit object work?  Is it a snapshot in time of what the orbit looked like at the time the `:obt` suffix was executed, or does it retain remembrance of the fact that it's part of that orbiting item and thus it auto-updates with it?

**Comment by hvacengi** [comment]
I did not test with apoapsis, but with a ship on the pad I performed the following test earlier today:
```
set o to ship:obt.
print o:lan. // prints the current LAN
wait 5.
print o:lan. // printed a new value
wait 10.
print o:lan. // printed yet another value
```
Where it may break down is in the case of `nextpatch`, since I doubt that the KSP `Orbit` object of the next patch is the same exact instance if you change your current trajectory to cancel the next transition and then reacquire it.  That is to say:
```
// on a ship with a mun encounter
set o2 to ship:obt:nextpatch.
print o2:periapsis.
// do something to loose the encounter
print o2:periapsis. // maybe error?  Maybe the last periapsis 
                           // value before loosing the encounter?
// do something to get the encounter back
print o2:periapsis. // I'd expect this to be the same as the 
                           // 2nd call above, and not be the current next patch periapsis.
```
I can test that tonight.

**Comment by tomekpiotrowski** [comment]
@hvacengi I've just tested your scenario. Surprisingly o2 gets updated even after you re-establish an encounter.

**Comment by Dunbaratu** [comment]
IMO, this must either be fixed, or at least just have `OrbitInfo` stop claiming it's a `SerializableStructure` prior to releasing v0.19.0.  If it's too ugly to find a fix quickly, that's fine, so long as OrbitInfo stops being serializable.  There's plenty of not-serializable classes and it's not a big deal to have one more.

**Comment by tomekpiotrowski** [comment]
I totally agree, I have already added it to 0.19 milestone so that we don't miss it before release.

**Comment by Dunbaratu** [comment]
> Surprisingly o2 gets updated even after you re-establish an encounter.

I just had a read through KSP's `Orbit` class in ILSpy and there seems to be no hidden, obfuscated, or private members that maintain a link from the  orbit to the ship or body it's attached to.

So I suspect what must be happening is this:  When you ask for `Vessel.Orbit`, you are getting a reference to the `Orbit` instance that's inside the vessel class, and **it's a mutable object**.  `Vessel` must be editing its own orbit object, and then you see the edits immediately in your own `Orbit` object because it's just a reference to the same `Orbit` object.

Thus, what happens if you do `set o to vessel("othership"):obt.`,  and then crash and destroy othership?  What will `o` be then?  Will it still work?  Will it be a stale reference to a bogus orbit object now that's just waiting for you to orphan it so it can garbage collect it?

If KSP's own `Vessel.Orbit` is a mutable object the vessel keeps editing, then that means our own kOS `ship:obt` is returning a mutable object to the script too.  That may make the very notion of saving it to disk and bringing it back sort of wrong no matter how we do it.

Perhaps the fix is to detect if our `OrbitInfo` is the kind that came from a vessel, and if so don't serialize its fields at all - just remembet which vessel GUID it came from and re-obtain it on loading?  That would match the behavior users are seeing in kOS scripts then , where the orbit object keeps changing.

This probably also answers the question people have "how on earth can a value like trueanomaly be a feature of the orbit?  Isn't it a feature of the current vessel's position ON that orbit?"  The answer would be "the vessel keeps updating the field on it's own orbit object.".

**Comment by Dunbaratu** [comment]
Remember that this entire issue doesn't need fixing for 0.19.0, just the one line: 

> or at least just have OrbitInfo stop claiming it's a SerializableStructure prior to releasing v0.19.0.

That's all that's needed for the 0.19.0 milestone label to go away.  The rest of this issue can be dealt with later.  It's probably better practice anyway for people not to serialize the orbit directly, and instead serialize the  vessel with its GUID (already supported) and then reconstruct the orbit object from the vessel.
