### ISSUE TITLE
NavBall mode access

### ISSUE THREAD

**Issue by AlchemistCH** [KSP-KOS/KOS#1448]
We currently have SAS modes controllable from the script, however the behavior of SAS is dependent on the navball mode (surface, orbit or target) to which there seems to be no access currently implemented.
We probably need to implement it, even if most people use the steering manager anyway.

**Comment by hvacengi** [comment]
Hm, I thought we already had an issue for this, but apparently not.

@erendrake had worked on this at one point and couldn't get it to work.  The deal is it's handled within the UI code, and was not easily accessible for a direct "set to x" type of operation.  We had to instead cycle through the modes.  And even then, it still wasn't working right.

This may end up waiting until the Unity 5 release, because we don't know how anything UI related is going to change in the KSP code.

I'm gonna tag @SirDiazo in here too, cause he seems to come up with all of those UI based fixes for his AGX mod anyways.  (No need to jump in if you don't have something to add, just thought I'd bring it to your attention)

**Comment by SirDiazo** [comment]
Not sure about setting the current mode, but to view the current mode (as shown just above the velocity display on the UI):
`if (FlightUIController.speedDisplayMode == FlightUIController.SpeedDisplayModes.Surface)`
returns true if in Surface speed mode.

No clue how to go about setting the navball mode though, never looked at that.

Note that if it's like the SAS buttons, the UI is decoupled from the command so you have to set the navball mode, then ALSO set the UI to match that mode.

**Comment by hvacengi** [comment]
Thanks for sharing what you know on the issue!  If we get it figured out, we'll be sure to let you know in case you want to get it included with your mods too.

**Comment by hvacengi** [comment]
It looks like we should be able to interact with this from `FlightGlobals.SetSpeedMode(FlightGlobals.speedMode);` in KSPv1.1.  I'm not sure if this is the method @erendrake previously tried, but I'm hoping it's a new method.

**Comment by djungelorm** [comment]
Yep that's the way to do it - just got this working in my own mod thanks to your comment :) And you can get the current value with `FlightGlobals.speedDisplayMode`

**Comment by SirDiazo** [comment]
Having run into this myself, I will confirm that FlightGlobas.speedDisplayMode replaces FlightUIController.speedDisplayMode in KSP 1.1

**Comment by hvacengi** [comment]
I'll throw this on the 1.0.0 milestone just so that we have a chance to keep it on the docket.  It may get moved to a later release, but at least we won't forget about it.
