### ISSUE TITLE
WriteLn should add '\n' instead of Environment.NewLine

### ISSUE THREAD

**Issue by tomekpiotrowski** [KSP-KOS/KOS#1452]

**Comment by hvacengi** [comment]
I already have an internal fix in my merge review.  But I went the other direction with it.  I removed the call to `Archive.ConvertToWindowsNewlines(content);`
Before
```
        public override bool Write(byte[] content)
        {
            if (!fileInfo.Exists)
            {
                throw new KOSFileException("File does not exist: " + fileInfo.Name);
            }

            byte[] bytes = Archive.ConvertToWindowsNewlines(content);
            using (FileStream stream = fileInfo.Open(FileMode.Append, FileAccess.Write))
            {
                stream.Write(bytes, 0, bytes.Length);
                stream.Flush();
            }

            return true;
        }
```
After:
```
        public override bool Write(byte[] bytes)
        {
            if (!fileInfo.Exists)
            {
                throw new KOSFileException("File does not exist: " + fileInfo.Name);
            }

            using (FileStream stream = fileInfo.Open(FileMode.Append, FileAccess.Write))
            {
                stream.Write(bytes, 0, bytes.Length);
                stream.Flush();
            }

            return true;
        }
```
What I like about this is that a user who calls `file:write` using a string that they manually added `\r` to using `char` does not get converted to be `\r\n`.

There is still an issue where copying a file to the archive will also use the conversion.  In this instance however I think it is a safe assumption to convert `\r` to `\r\n`, in part because there would be an easy workaround by reading the lines and writing them to another file with `\r` line endings.

I don't see any conflicts in doing this, but let me know what you think.  If my solution is acceptable, I'll merge it when I merge the 2 pending PR's I have ready.

**Comment by tomekpiotrowski** [comment]
Sorry I couldn't reply sooner, I had a busy day yesterday.

I thought about it a bit and I think I'd prefer to stick to my solution.

Currently the idea is that everywhere in kOS all newlines as represented as `\n`. It is only when reading/writing from/to real hard drive (archive) that the conversion between `\n` and `\r\n` happens. This has an advantage of simplifying all our work with files in kOS - we can assume that all newlines are `\n`.

Your solution moves the point where the conversion happens one step back. This would mean that we would have to convert in other places as well. For example, as you said, copying a file from HardDisk to Archive would require a conversion. Also, any further changes in this part of code would require the developer to look out for potential problems with this.

Granted that users would be able to insert `\n` manually if they wanted to (which they can't do now because it would be automatically converted to `\r\n`), but a such a file, when copied from HardDisk to Archive, would have all those `\n` converted to `\r\n` anyway. That could be very confusing to the user and we would have to address that before releasing IMO. Btw, I think that the probability of anyone ever needing that functionality is low enough to safely ignore it for now.

**Comment by hvacengi** [comment]
OK, I'll switch my local fix to use `\n` and convert that value.  I'm going to leave comments in around it explaining how to change it if we ever want to allow users to write `\n` directly.

I think I can summarize this issue with the statement "I hate dealing with line ending characters!" :smile:
