### ISSUE TITLE
Add a `Set` structure

### ISSUE THREAD

**Issue by tomekpiotrowski** [KSP-KOS/KOS#1481]
This is something that's missing from our collections. I think it should be easily doable.

**Comment by Dunbaratu** [comment]
So, basically, a Bag?  All you care about is if an item exists inside or not, not what order things are in.  Sure, that sounds reasonable.

**Comment by hvacengi** [comment]
I interpreted it not as a bag, but as a unique collection, one without duplicates. Perhaps that would make it an unordered list as well. But I envisioned it being backed by a `HashSet` which I think is still ordered. The down side is that I think you normally get an exception thrown if you attempt to add a duplicate item to a unique collection, and since we have no way to handle exceptions we might want to consider returning a boolean to signal if the operation worked.
