### ISSUE TITLE
characters in terminal are rectangular blocks 

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KOS#1513]
from the forums:
This in game terminal looks like this:
![img](http://i.imgur.com/G23YsL3.png)

**Comment by Dunbaratu** [comment]
"From the forum" - can you show a link to the post in question?  I can't seem to find it.
I wonder if they got it installed correctly.  That looks like it's just using generic garbage for the font image so maybe the file didn't load.

**Comment by TDW89** [comment]
[This one](http://forum.kerbalspaceprogram.com/index.php?/topic/61827-105-kos-scriptable-autopilot-system-v0191-201635/&do=findComment&comment=2444092) and the one two below it. I have also just tested the release and got the same thing.

**Comment by TDW89** [comment]
Ok tracked down the issue.
If the ingame graphics settings are set to half or quarter res then the character textures don't load properly.

**Comment by Dunbaratu** [comment]
Well that sucks.  I just had a google around and found that it's because I have the "mipmap" option set to 'true' on the font texture - that means it will attempt to do anti-aliasing on the image, which if you have low texture quality and a very tiny texture like the 8x8 image, just melts the entire texture into a homogeneous blur.  

Two possible solutions;  1: Use an unnecessarily large font_image.png file that stores each pixel in a big 8x8 pixel block so that at 1/8 quality it still samples all the proper information from it, which might put a larger burden on the graphics having to draw a 64x64 texture 2000 times across the face of the terminal where it currently draws an 8x8 one.  2: Turn Mipmapping off in the texture, which then punishes all the people who have good settings by removing the smoothing of the font for them too..

**Comment by Dunbaratu** [comment]
I went with option (2) because as it turns out it does *not* punish high res people - it still works just fine.
