### ISSUE TITLE
Alternative to WAIT inside WHEN/THEN and ON triggers?

### ISSUE THREAD

**Issue by AlchemistCH** [KSP-KOS/KOS#1522]
The way it's currently possible to bypass the inability to `WAIT delaytime.` inside a trigger is to save a timestamp somewhere and create another `WHEN` trigger with condition based on the time: 
`WHEN TIME:SECONDS>=timestamp+delaytime THEN`
This way the new trigger will be called after the set amount of time and will continue the triggered sequence.
(and with cases of `WAIT UNTIL` you can just create the new trigger with the very expression)

As alternative, it could be useful to have a command that allows this to be done without multilevel triggers. A command (`DELAY`? `SUSPEND`? the same `WAIT` keyword?) would suspend the trigger body execution at this position (so that mainline and other triggers can execute in the meantime) and create another trigger (with timestamp or boolean expression) which will continue this trigger body from right after this command.

The primary need for this functionality is in multistage trigger sequences. For example, LES sequence could look like this:
```
ON ABORT
{ if LES_allowed()  //check it hasn't been jettisoned
{
UNLOCK steering. 
SAS OFF. 
decouple_capsule().
ignite_LES().
DELAY 1.5.
jettison_LES().
DELAY 3.
DELAY UNTIL chute_deployment_conditions().
CHUTES ON.
}}
```

**Comment by Dunbaratu** [comment]
This may become moot if we get thread interruption working later in Unity 5.  One of the things I'd like to be able to do with that is get rid of the IPU limit for triggers - it would make it possible to interrupt in the middle of a trigger and pick up where it left off, leaving the mainline code stuck while it does so.

**Comment by hvacengi** [comment]
The problem is that each trigger is treated as it's own atomic method, but there is no independent instruction pointer.  So attempting to wait during a trigger body is really complicated.  Also, as triggers are analogous to hardware interrupts on microprocessors or events on modern higher level languages, they are expected to do one thing, and then return control back to the main thread.  If I recall correctly, the arduino does not even update the clock variable while you run code in an interrupt.

This may become more possible once some threading comes into play in the execution, but I still would prefer that triggers remain "small" in execution.  I'd rather not teach new programmers to include tons of logic inside of triggers/events/interrupts when they really should be kept short as much as possible.  In high level programming, something like this would be handled inside of an independent thread.

With the new delegates however, you could make a delay function which accepts a delegate and a delay number.  Then that function could manage your timing `when` loops.

You could also run the script as a normal sequencial loop on a 2nd processor.  With the new EC model, that won't be a huge power drain.  Then the code on the primary processor becomes:
```
on abort {
  if LES_allowed() {
    unlock steering.
    sas off.
    shutdown.
  }
}
```
and on the "escape processor"
```
wait until abort and LES_allowed().
decouple_capsule().
ignite_LES().
wait 1.5.
jettison_LES().
wait 3.
wait until chute_deployment_conditions().
chutes ON.
```

**Comment by AlchemistCH** [comment]
Yeah, the particular case of LES is supposed to interrupt the main sequence anyway. Something in the lines of "cancel this entire program completely and run that one".  Other cases where delayed components of a trigger sequence could be useful may be not that extreme, however.

Also the actual code for LES I've tested recently looks like this. And yes it works exactly as intended
```
// setting up LES parts
set LEStower to ship:partstagged("LES")[0]. //escape tower
set LESdec to ship:partstagged("LES_dec")[0]:getmodule("ModuleDecouple"). //LES decoupler
set capsDec to ship:partstagged("Caps_Dec")[0]:getmodule("ModuleDecouple"). //capsule decoupler
set PLF to ship:partstagged("PLF")[0]:getmodule("ModuleProceduralFairing"). //Payload fairing
set lp to ship:partstagged("DrogueChute").
set drogues to list().
set i to 0.
until i>=lp:length
{
drogues:add(lp[i]:getmodule("moduleparachute")). //drogue chutes
set i to i+1.
}
set lp to ship:partstagged("MainChute").
set mainchutes to list().
set i to 0.
until i>=lp:length
{
mainchutes:add(lp[i]:getmodule("moduleparachute")). //main chutes
set i to i+1.
}

set LESenabled to true. // starting state - change after dropping LES

//abort procedure
When (abort and lesenabled) then //abort sequence
{print "aborting".
unlock steering.
SAS off.
if PLF:hasevent("deploy")
{PLF:doevent("deploy").
print "Fairings deployed".}
capsDec:doevent("decouple").
print "capsule decoupled".
LEStower:activate.
print "LES ignition".
set lestimestamp to time:seconds.

When time:seconds>lestimestamp+1.5 then
{
LESDec:doevent("decouple").
print "LES decoupled".
set lestimestamp to time:seconds.
When ((time:seconds>lestimestamp+2)and(alt:radar<6000)) then
{
print "drogues armed".
when drogues[0]:getfield("safe to deploy?")="safe" then
{
set i to 0.
until i>=drogues:length {
if drogues[i]:hasevent("deploy chute") {drogues[i]:doevent("deploy chute").} 
set i to i+1.}
print "drogues deployed".
set lestimestamp to time:seconds.
When ((time:seconds>lestimestamp+0.5)and(alt:radar<2000)) then
{
print "main chutes armed".
when mainchutes[0]:getfield("safe to deploy?")="safe" then
{
set i to 0.
until i>=mainchutes:length {
if mainchutes[i]:hasevent("deploy chute") {mainchutes[i]:doevent("deploy chute").}
set i to i+1.}
print "main chutes deployed".
}
}
}
}
}
}
//put the ascent profile below here...
```

**Comment by TDW89** [comment]
@AlchemistCH not sure if this helps but if you are looking for a way to say "cancel this entire program completely and run that one" then this might work.
```
on abort {
 set core:bootfilename to "abort_script.ks".
 reboot.
}
```

**Comment by hvacengi** [comment]
@TDW89 I like that idea even more!  That gets the advantage of outright interrupting the exiting operation, while not requiring a 2nd processor!

**Comment by Dunbaratu** [comment]
**An Epiphany**

I just had a realization of a refactor that makes triggers work "right", and be totally doable today without them being a separate thread.  They could be interruptable by `wait`, and could take longer than 1 update to finish.  Finishing an update while still inside a trigger would just have the semantic meaning of "the main program still hasn't resumed yet because you are currently still in the trigger."  Also, a trigger could interrupt another trigger this way, and the system wouldn't get confused - it would just resume the first trigger where it left off when the second trigger interrupted it.

How to do all this?

A trigger in kOS should be conceptually thought of as a a serial (not parallel) subroutine call - just one that may happen and interrupt you at any point rather than where you explicitly told it to in the main code.

So for that to work *properly*, what would make a heck of a lot more sense would be to actually implement it *AS* a subroutine - as in: have it push a return pointer onto the stack, telling it where to jump back to when it's done, and when you return at the bottom of the body, pop the return pointer back off the stack and go back to where you came from.  In other words, piggyback it on top of the already existing function call system, and call it the same way you'd call a void function.

Then all we'd need to do that's magic "do before the main code" in the FixedUpdate is *just* running the conditional check expressions of triggers and *not* their actual bodies.  Because their actual bodies would *NOT RUN DURING THE PRE-MAIN* part of the update at all.  When during the trigger condition checks, a true condition is seen, then the CPU would just set up the call stack to push the context record for the subroutine, and then reset the current instruction pointer to the trigger body's start, just like a normal subroutine call does.  The actual execution of the body of the trigger doesn't happen until it starts executing the normal main body of the code ... because.... it has just set up the main flow so it will be starting the trigger's body *IN* the main code like a normal subroutine.  If two trigger conditions turn true at once, that would work too, because it would just treat it like one trigger had called the other one.  The second trigger's 'function return' would come back to the start of the first trigger, who's return would come back to the main code again.
