### ISSUE TITLE
Loosing control if SAS is on and RT connection lost

### ISSUE THREAD

**Issue by Patrykz94** [KSP-KOS/KOS#1524]
Just noticed that if SAS is on, in stability assist mode, and ship goes out of range of Remote Tech, kOS looses control over Pitch, Yaw and Roll.
It did not happen in the previous version I used which was 0.18.1.
Not sure if this is mostly an issue with kOS or RemoteTech.
Edit: I'm using Cooked Control

**Comment by hvacengi** [comment]
This is a known limitation, and is due to the method that RemoteTech has to use to prevent other mods from controlling the vessel.  It's documented here: http://ksp-kos.github.io/KOS_DOC/commands/flight/systems.html?highlight=RemoteTech though it is not explicit that all forms of SAS control will fail with RemoteTech.  In order to control attitude with RemoteTech installed you will need to leave SAS off.

**Comment by Patrykz94** [comment]
OK now that I think about it, back when I wrote the program, my probe cores had 160km range and by that point I may have disabled SAS. Now in the new install they only have 3km range so this happens.

**Comment by hvacengi** [comment]
I'm going to tag this as "won't fix" and close the issue, simply because it's a known issue.  I'm not sure if we need a documentation update.  Please re-open this issue if you think we need to modify the docs.
