### ISSUE TITLE
[KSP1.1] Toolbar button doesn't display

### ISSUE THREAD

**Issue by hvacengi** [KSP-KOS/KOS#1573]
In KSP 1.1 the toolbar button never displays.  This is an issue with the `ApplicationLauncher.Ready` flag being set to false during the `Awake` call.  @Dunbaratu has already perpared a fix using `GameEvents.onGUIApplicationLauncherReady`

Once we got the launcher working, we found that the window spawns in a position that overlays the other toolbar buttons.  The position will need to be adjusted as well.

While we're at it, it might be nice to make it so the window will persist while the mouse button is hovering over the window, rather than requiring the button be toggled.  Right now, hovering over the button will display the window, but moving the cursor over the window will cause it to disappear.  This part can be split into a separate issue if not easily done at the same time.

**Comment by Dunbaratu** [comment]
I'd say please move the last point to a new issue.  I have a branch I can make a PR for that takes care of the first two and gets us back in business.

The hovering is slightly messy for the following reason: There's a few pixels of margin in between the launcher button and the KOS control panel.  As the mouse moves from the launcher button to the panel, it briefly steps over this margin and is in neither of the two windows.  This generates a "mouse no longer hovering" event on the button, a few GUI 'ticks' before it would then have created the "mouse now hovering over panel window" event.  The system cannot quickly tell the difference between "mouse is leaving the button but will soon be over the panel" and "mouse is leaving the button and will not be moving over the panel".  The solution, which is totally doable but I didn't want to bother just yet because the other problems are very broken and need fixing NOW, is as follows:
Create a small timer delay on the closing of the window when the applauncher button loses mouse-hoveryness. Don't close the KOS control panel for a quarter second or so, so there's time to move the mouse over the control panel and cross that small margin of gap before it goes away.

**Comment by hvacengi** [comment]
Closed via #1573
