### ISSUE TITLE
[kOS 0.19.3] 'impossible FromPrimitiveWithAssert(<null>) was attempted'

### ISSUE THREAD

**Issue by pellinor0** [KSP-KOS/KOS#1592]
I ran across this error while updating a script with compiled locks to steering/throttle. It does not occur for uncompiled libraries. 

relevant part from the log:
http://pastebin.com/QfwqbnTe

edit: current state of the scripts
https://github.com/pellinor0/kOS-MissionFramework/tree/kos1592

**Comment by hvacengi** [comment]
Can you try redefining your lock function like this:
```
function lockSteering {
    parameter x. // global variable or lock
    global steering_del is x.
    lock Steering to steering_del:call().
}
```
I'm not at a place where I can test this out myself because I'm preparing to leave town.  I tested the compiled steering and locks with dedicated functions, but did not test with _local_ variables (parameters are local).  Technically according to the documentation that lock object should be "local" too, but I don't know what the effect of that is for scoping.

I'll tag @Dunbaratu to ask if he could look into this while I'm out of town.

**Comment by Dunbaratu** [comment]
You appear to be trying to use a LOCK as a delegate.  While that might work because locks are sort of like user functions under the hood, it's not documented as such.  Is there a reason you can't switch it to just being a regular function?  It would make things a lot cleaner.  For example instead of things like this:
```
    lock st002 to Heading(90+headCorr, ppp).
    lockSteering(st002@).
```
try something like:
```
   function st002 { return Heading(90+headCorr, ppp). }
   lockSteering(st002@).
```

**Comment by pellinor0** [comment]
Actually there is no reason to use this construction any more. It was a workaround for locking the Steering from compiled code. This worked in 0.19.2 and it looks like it broke in the new version. 

Thanks for your help! From the error I could not tell if it was caused by the kOS update or the code changes I made to get the script running this far. 

I changed everything to a simple 'lock steering' and now it works again. So my problem is resolved, feel free to close the issue if you don't want to investigate this further.
