### ISSUE TITLE
[kOS 0.19.3] Incorrect results when subtracting decimal values.

### ISSUE THREAD

**Issue by Patrykz94** [KSP-KOS/KOS#1600]
I noticed that when subtracting values that have a decimal point, the result is slightly off.
It doesn't seem to be happening while adding, just when subtracting.

Here is a screenshot:
http://imgur.com/d9gDjup

**Comment by Dunbaratu** [comment]
That's a well known problem with floating point numbers.  There's literally nothing we can do about it and you'd find the same result from pretty much any language unless the language rounds numbers off by default when it prints them.

Here's an example from old fashioned C:
the program:
```
#include <stdio.h>
int main(int arc, char** argv)
{
    double x = 7455.7;
    double y = 7455.5;

    printf("x - y = %25.18lf\n", (x - y));
}
```
The result:
```
x - y =      0.199999999999818101
```
(The qualifier "25.18" in the print statement means "print the value using 25 characters, 18 of which come after the decimal point."  It's necessary to make it print out the *real* value in C because the default tries to round it off to about 8 places after the point if you don't change it, and that masks what's really going on because that rounding will turn 0.199999999999818101 into 0.20000000.)

**Comment by Dunbaratu** [comment]
Basically, if you really need the value printed to within a certain limited width, then explicitly round it in kerboscript with the `round()` function.

**Comment by Patrykz94** [comment]
Ok, never noticed that before. Thanks for the explanation.
