### ISSUE TITLE
Display console freeze KSP UI

### ISSUE THREAD

**Issue by Verbalinsurection** [KSP-KOS/KOS#1601]
HI,
On a fresh installed KSP 1.0.5 and 0.19.3 KOS, when I click on the display console buton, nothing appear and all the commands are unavailable. The game continue to work, but all keyboard input don't work and right click on the part doesn't show all the menu.
Even more strange, when I click on the recover vessel buton, and return to the menu, all the choice "new game, settings etc." can't be clicked.

I have this mod on my install : 
- **AIES Aerospace** `AIESAerospace-Unofficial 1.6.1`
- **Contract Configurator** `ContractConfigurator 1.9.11_KSP1.0.5`
- **Docking Port Alignment Indicator** `DockingPortAlignmentIndicator 6.2`
- **Kerbal Alarm Clock** `KerbalAlarmClock v3.5.0.0`
- **Kerbal Attachment System** `KAS 0.5.5`
- **Kerbal Inventory System** `KIS 1.2.6`
- **Kerbal Planetary Base Systems** `KerbalPlanetaryBaseSystems v1.0.6`
- **kOS: Scriptable Autopilot System** `kOS 0.19.3`
- **KSP AVC** `KSP-AVC 1.1.5.0`
- **KW Rocketry** `KWRocketry 2.7.0-community`
- **KW Rocketry - Community Fixes** `KWRocketry-CommunityFixes 0.4.10`
- **MechJeb 2** `MechJeb2 2.5.6.0`
- **MechJeb and Engineer for all!** `MechJebForAll 1.2.0.0`
- **Module Manager** `ModuleManager 2.6.20`
- **PlanetShine** `PlanetShine 0.2.4.2`
- **PlanetShine - Default configuration** `PlanetShine-Config-Default 0.2.4.2`
- **RasterPropMonitor** `RasterPropMonitor v0.24.2.1`
- **RasterPropMonitor Core** `RasterPropMonitor-Core v0.24.2.1`
- **RCS Build Aid** `RCSBuildAid 0.7.7`
- **RemoteTech** `RemoteTech v1.6.9`
- **SCANsat** `SCANsat v14.9`
- **Surface Mounted Lights** `surfacelights 1.2.2`
- **Transfer Window Planner** `TransferWindowPlanner v1.4.0.0`
- **TriggerAu Flags** `TriggerAu-Flags v2.7.4.0`

**Comment by hvacengi** [comment]
We will probably need more information to be able to work on this.  Most importantly we'll need a copy of your log file (preferably uploaded to a file host like dropbox) from `Kerbal Space Program\KSP_Data\output_log.txt`.  We'll also need to know the details of you installation (operating system, laptop/desktop, etc).  

The first thing I'd try to do is remove all other mods, and then add them back in one at a time to see if it is due to one of those mods, or some combination.

If I had to guess, I'd figure it as an issue with RemoteTech, though the version listed should be fine.

You can also see if the window will pop up by clicking on the computer icon from the kOS toolbar window.

**Comment by Verbalinsurection** [comment]
Thanks for your help

Ok, so I remove all the mod, did no work.
If this can help : same problem if I try with telnet, connect to telnet server is ok, but when I enter the number of KOS system (1) telnet freeze.

My system : 
- Desktop computer
- Windows 7 64
- Intel I7 920
- AMD Radeon 8500 HD
- 6 Go DDR3
Yes, little old but I have run KOS without problem in the past (1 year ago I think).
Here my output_log : https://dl.dropboxusercontent.com/u/12242397/output_log.txt

Click on the KOS icon toolbar no work.

**Comment by hvacengi** [comment]
```
DivideByZeroException: Division by zero
  at kOS.Screen.TermWindow.LoadFontArray () [0x00000] in <filename unknown>:0 

  at kOS.Screen.TermWindow.Awake () [0x00000] in <filename unknown>:0 
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
UnityEngine.GameObject:.ctor(String, Type[])
kOS.Module.kOSProcessor:InitObjects()
kOS.Module.kOSProcessor:OnStart(StartState)
Part:ModulesOnStart()
:MoveNext()
```
It looks to me like your font texture might not be loading correctly.  Can you make sure that `GameData\kOS\GFX` has a file in it titled `font_sml.png`?

**Comment by hvacengi** [comment]
```
Texture load error in 'O:\#Steam\steamapps\common\Kerbal Space Program\GameData\kOS\GFX\font_sml.png': Couldn't open file O:\
```
Well I guess there's part of your problem, there's an error opening the font's file.  Check to see if you can open the file directly (by double clicking on it to view it in a photo program).  Otherwise you may need to check the permissions on the folder, or there may be an odd issue with locating the folder on a different drive.  `O:` isn't a network drive, is it?

**Comment by Verbalinsurection** [comment]
Thanks for the help.

The file exist, I can open it directly and the path is good. Security on the folder and file is the same as the other (auth user can read / write)

The drive is a SSD, no network.

The # char in the path can cause problem with KOS ?

**Comment by hvacengi** [comment]
No, it doesn't look like it's an issue with kOS itself.  KSP itself is what throws the error about loading the texture.  In fact I found another error further down:
`Texture load error in 'O:\#Steam\steamapps\common\Kerbal Space Program\GameData\Squad\Strategies\Icons\UnpaidResearchProgram.png': Couldn't open file O:\`
I would suspect you're right that the `#` character is the issue, just with KSP itself.  Either that of KSP doesn't think it has permission for your `O:` drive.

**Comment by Verbalinsurection** [comment]
:)
So, I have to move my steam folder to a new folder, I'll try that, thanks ;)

**Comment by hvacengi** [comment]
You can try it really quickly by just moving the Kerbal folder into your drive's root.  If that works, then try moving the whole steam folder.

**Comment by Verbalinsurection** [comment]
Congratulation and thanks, you solved my problem.
After the move to a new folder without the #, no problem :D

**Comment by Dunbaratu** [comment]
I didn't even realize that '#' was a valid filename character in the first place.
I think the problem is because the filename path is used to build a `file:///` style URL, because Unity only knows how to load textures by WWW methods, not direct file methods (at least that was true in Unity4 when that code was written).  I think it's more that '#' is a special URL character than that it's a special KSP or kOS character.

**Comment by Verbalinsurection** [comment]
Thanks for the reply :)
Yes, it's a bad habit, I use # for keep in first place important folder in explorer list.

**Comment by Dunbaratu** [comment]
Yeah it may be a good habit to pick a different "force alphabetical" character than "#".
Here's what '#' means in a URL:
```
http://www.some.web.site/some/path#some_name
```
means "go get the file ``/some/path`` from ``www.some.web.site`` and display it, but instead of displaying it from the top, jump down to the line of text tagged with an anchor point called``some_name`` (i.e. a topic heading further down the page).

So the problem in your filename was that everything after the `#` was taken to be the name of a place to go inside the file called just `0:`.

**Comment by Verbalinsurection** [comment]
10 years of habit to change, starting today :)
