### ISSUE TITLE
PIDLoop integral accumulator

### ISSUE THREAD

**Issue by marianoapp** [KSP-KOS/KOS#1608]
I was looking [here](https://github.com/KSP-KOS/KOS/blob/c3e842cd53a11ca4e7eace167ce554055dc62381/src/kOS.Safe/Encapsulation/PIDLoop.cs#L155) at the `Update` method of the PIDLoop and I noticed that is using `ITerm` as the integral accumulator instead of `ErrorSum`. Is like that by design and I'm missing something or is just a typo?

The current implementation has a couple of problems:
* The `ResetI` method is not actually resetting the accumulator.
* When the output is saturated the accumulator `ITerm` is set to the new value of `iTerm`, basically resetting most of the accumulated error.

**Comment by hvacengi** [comment]
Hm, you're right.  How have we made it this long with the incorrect integral term being reset.  

Yes, it is intentional to sum using ITerm rather than `ErrorSum`.  Mostly because it was easier for me early in development (my initial loop didn't even have a term for ErrorSum).

The saturation reset behavior is also intentional.  The idea behind that is that I didn't want to accumulate the additional error that pushed us beyond our output limit.  So anything that was beyond saturation is discarded.  Once the proportional and derivative components approach zero the integral can once again begin summing.  I saw this somewhere in my research as a way to mitigate integral windup.  Is this presenting a major issue for one of your loops?

I'm in that code right now anyways as I update the steering code for version 1.1, I'll straighten out the `ResetI` method.  You can see those changes here: https://github.com/KSP-KOS/KOS/pull/1544/files?diff=split

**Comment by marianoapp** [comment]
I haven't used a PIDLoop in any script yet, but I was looking into it. I checked the code to see if it was using trapezoidal or rectangular integration and that's when I found these other things.

> The saturation reset behavior is also intentional. The idea behind that is that I didn't want to accumulate the additional error that pushed us beyond our output limit. So anything that was beyond saturation is discarded.

Yes, when you reach saturation you have to stop accumulating but you shouldn't remove all the error already accumulated up until that point.

When you do this:
```
if (Output > MaxOutput)
{
	Output = MaxOutput;
	if (Ki != 0 && LastSampleTime < sampleTime)
	{
		iTerm = Output - Math.Min(pTerm + dTerm, MaxOutput);
	}
}
```
And then later make `ITerm = iTerm` you are replacing all the accumulated error in `ITerm` with the value of `iTerm`, which will always be smaller or equal to `MaxOutput` since you changed its value to `iTerm = Output - Math.Min(pTerm + dTerm, MaxOutput)`.

**Comment by hvacengi** [comment]
Right, but we aren't eliminating the entirety of the accumulated error unless you've saturated the proportional and derivative turns as well.  So if you are at 1/3 saturation on the proportional term, and 0 saturation on the derivative term, I'm effectively clamping the iTerm to 2/3 of full saturation.

I'm not saying it's necessarily the "right" way, just a technique I picked up somewhere.  It relies on the presumption that you cannot in an instant go from saturated proportional component to zero proportional component, allowing the integral term to wind back up as the proportional term winds down.  I'll have to go back through notes in order to find my strong rational.  I'll also ask @mthiffau to check in to the discussion as the guy I generally defer controls logic to since.

I'm open to changing it if needed, but I'd want to make sure to have a good discussion about it and to do a lot of testing.  The structure was only exposed because I needed to write it for the steering code and it seemed reasonable to offer it to the end users.  But that means that it is rather focused on the constraints of the steering logic.
