### ISSUE TITLE
Ctrl+C abort doesn't clear context

### ISSUE THREAD

**Issue by hvacengi** [KSP-KOS/KOS#1610]
Found in @Dunbaratu's stream that aborting the current program using `[Ctrl]+[C]` does not properly clear out old variables.  This was made evident by an attempt to call a function throwing an exception about the function being from a different context, rather than complaining about an undefined variable.

**Comment by Dunbaratu** [comment]
Further detail:  It was triggered thusly:

In the program, make a delegate of a named function in a lexicon like so:
```
set hooks to lexicon(
  "hook1", hook1@,
  "hook2", hook2@
).
```
Where hook1 and hook2 are named functions further down in the same file.

Then, put an infinite loop in that program and run it and kill it with control-C rather than letting it end normally.
Then, run that program a second time.
On the second run, it will complain when you attempt to do ``hooks["hook1"]:call().``, falsely claiming that you're attempting to call a function in program context that was created in the interpreter (it wasn't.  It's just having something leftover from the previous run, and we have to find it.)

It's important to note this ONLY happens when you abort with Control-C, and NOT when it aborts from an exception (so when it fails the second time, since that failed with an exception, it will work again on the third time, where you press ctrl-C again to abort, so it will fail on the fourth time, but work on the fifth, and so on.)

**Comment by Dunbaratu** [comment]
Well, first off the message is incorrect.  It's actually one program context trying to call a delegate from an old stale program context, but the message claims it's trying to call a delegate from the interpreter context any time it's not equal to the programmer context:

This is the relevant code from CPU.cs:
```
        /// <summary>Throw exception if the user delegate is not one the CPU can call right now.</summary>
        /// <param name="userDelegate">The userdelegate being checked</param>
        /// <exception cref="KOSInvalidDelegateContextException">thrown if the cpu is in a state where it can't call this delegate.</exception>
        public void AssertValidDelegateCall(IUserDelegate userDelegate)
        {
            if (userDelegate.ProgContext != currentContext)
            {
                throw new KOSInvalidDelegateContextException(
                    (currentContext == contexts[0] ? "the interpreter" : "a program"),
                    (currentContext == contexts[0] ? "a program" : "the interpreter")
                    );
            }
        }
```
If the delegate's context isn't the current one, and the current one is a program context rather than interpreter context, it's *assuming* that must mean the delegate's context is the interpreter, and that's not true in this case.  So step 1 will be fixing this misleading message.
