### ISSUE TITLE
It won't let me run the scripts

### ISSUE THREAD

**Issue by JustJack42** [KSP-KOS/KOS#1631]
I tried it with other scrips I had made.

**Comment by JustJack42** [comment]
When I tried to run the script "launch_sequence" it gave feedback saying "The given key is not present in the dictionary. (Cannot show kos error location - error might really be internal. See kos devs.) Object reference not set to an instance of object.

**Comment by hvacengi** [comment]
In order to do any kind of troubleshooting we'll need substantially more information.  We need the output_log.txt file showing the error, as well as the source script file.  Please give us as much information as possible.  I recommend hosting the files on a service like Dropbox, Google Drive, or Pastebin.

**Comment by hvacengi** [comment]
Closing do to lack of information.
