### ISSUE TITLE
Locking the steering unlocks throttle.

### ISSUE THREAD

**Issue by th3b0s5** [KSP-KOS/KOS#1655]
This is the code, I'm using the stock ship in your tutorial.

lock throttle to 1.0 .
print "throttle locked".
print "waiting for 3 sec".
wait 3.
lock steering to up. // throttle unlocks right here.
print "steering locked".	
print "waiting for 3 sec".
wait 3. 
print "staging".
stage.
wait until ship:altitude > 70000.
---- code end

**Comment by hvacengi** [comment]
I am unable to replicate using your code and the tutorial craft file when running with stock + kOS.  Could you please provide log files, and identify what version of KSP and kOS you are using, along with any mods you may have installed?

**Comment by th3b0s5** [comment]
I have uploaded the log, kOS file and a video showing my problem.

https://drive.google.com/open?id=0B5zv-UZbKhAxa29Semt4c2pPNU0

**Comment by hvacengi** [comment]
kOS version 0.20.1 requires KSP version 1.1.2, updates to steering code require new methods that were provided in the latest KSP update.  Your log file shows an error when attempting to access this new method, which prevents the other controls (including throttle) from being updated.  It appears that you are still running KSP 1.1.0.

It was not explicitly stated in the release notes that the latest version of KSP was required.  Our typical practice is not to support anything besides the latest version of KSP.  I'm sorry, but in order to clear this error you will either need to update KSP or downgrade to kOS 0.20.0.

**Comment by th3b0s5** [comment]
Thanks
