### ISSUE TITLE
"Volume out of reach" error with RemoteTech installed but disabled

### ISSUE THREAD

**Issue by sshilovsky** [KSP-KOS/KOS#1679]
I've remotetech "enable" setting off and I get the error above. The boot script is loaded and starts running, but when it tries to load another script while being away from the launch site, causes this error.

Enabling remotetech back solved my issue.

**Comment by hvacengi** [comment]
We have a pending pull request to support the newest API for RemoteTech.  It will include recognizing when RT is disabled.  Previous versions of RT did not offer this option.

**Comment by GER-Space** [comment]
this is a Bug with CONFIG:RT = TRUE and Remotetech disabled. 

This is the reverse problem of the bug #1639 

Perhaps we sould get rid of CONFIG:RT and let KOS check if it's there and enabled.

**Comment by hvacengi** [comment]
Well this specific bug will be fixed as soon as I merge a PR (still testing).  One thing that the config flag does is allow the user to change their level of integration.  With the flag set to false and RemoteTech installed, you still get restrictions to the controls (even more so, since you need to have local control to operate the controls) but things like delay in keyboard input and connection restricted access to the archive are disabled.

**Comment by GER-Space** [comment]
I was using 1.0-pre1 for testing. was there the allready PR merged?

**Comment by hvacengi** [comment]
No, the PR is sitting on my computer being tested.  It should be merged tonight, barring any errors.

**Comment by hvacengi** [comment]
I believe that even if this wasn't fixed by #1640 it should at least have been fixed by #1850.  I'm going to close the issue for now.  If this is still an issue please reopen for continued troubleshooting.
