### ISSUE TITLE
Empty anonymous user function causes stack overflow

### ISSUE THREAD

**Issue by jboecker** [KSP-KOS/KOS#1713]
I have been playing around with the anonymous user functions in the 1.0.0 pre-release. Absolutely love that feature!

I tried creating an empty function with `{}`. Calling that function results in a stack overflow. `{ return. }` works. I would expect both forms to be equivalent.

Here's a test script:
````
print "Variant 1:".
function foo {
}
local f is foo@.
print f().

print "Variant 2:".
local g is { return. }.
print g().

print "Variant 3 -- this does not work:".
local h is {}.
print h().

````

Output:
````
run test.
Variant 1:
0
Variant 2:
0
Variant 3 -- this does not work:
Stack overflow!!
At 1:/test, line 13
print h().
````

**Comment by Dunbaratu** [comment]
Ahhh.
I think I can guess the problem.  We secretly insert a "return 0" in functions where one is missing, and "return" with no args is secretly really a "return 0".  That gives us the freedom to always assume the presence of a return value unconditionally so we don't have to write different code when calling a void function from when calling other functions (which we *can't* do because we aren't a compile-time binding language - we don't know the function prototype until runtime when it's being called).

Chances are, the anonymous functions don't insert that secret "return" in them like normal functions do.  It should be fixable.  Thanks for finding it.

**Comment by Dunbaratu** [comment]
In examining this, I'm seeing it's even worse than that.  It fails to have a return opcode at all.
That means it's only "working" because of where the anon function is located in the program - it's falling through past the end of the anon function, never hitting a return (and then getting to the part later on where it tries to call it, so it jumps back upward to it again, etc etc, until it runs out of stack.)
