### ISSUE TITLE
Trying to call a function with the wrong number of arguments results in infinite error messages instead of just one

### ISSUE THREAD

**Issue by jboecker** [KSP-KOS/KOS#1714]
In the v1.0.0-pre-1, the following code snippet prints the correct error message (too many arguments) over and over until you interrupt the program with Ctrl+C.
````
function f {
}
f(42).
````

**Comment by Dunbaratu** [comment]
I just tested trying to re-create this and I couldn't.

Then it occurred to me to try it interactively at the terminal instead of in a program.  And THEN it happened.

So the problem only occurs when you do it at the interactive prompt, not in a program.

**Comment by Dunbaratu** [comment]
In testing, I have come to the conclusion that it's *any* error inside an interpreter function that does it, not just the wrong number of args error.  

For example, this does the same thing:

```
function divzero {
  set x to 1 / 0.
}
divzero().
```
You get the error message about dividing by zero spamming the system in a neverending loop.

The problem seems to be related to what happens when an exception tears the execution thread away from where it was in the system and leaves things behind in an unfinished state, and how we try to reset to a "known" state.  We do that by just killing the program entirely and returning you to the interpreter.  But.... if you already *are* in the interpreter when it happens, we seem to leave the program right where it was, and worse yet, with the instruction pointer still sitting on the same instruction so it will end up trying to execute the same instruction next time (thus the endless loop of exceptions).
