### ISSUE TITLE
Can't run programs from within KSM files

### ISSUE THREAD

**Issue by ozin370** [KSP-KOS/KOS#1716]
(1.0.0 prerelease)
To reproduce:

test.ks:
```
print "woo".
run test2.
```

test2.ks:
`print "hoo".`

then do the commands:
```
compile test.ks.
run test.ksm.
```

Thanks to hvacengi for helping me narrow this down.

**Comment by hvacengi** [comment]
@Dunbaratu I did some debugging with Ozin yesterday to look into this issue.  It appears that when running the ksm file, it gets an error that a label doesn't exist for the boilerplate code ("0_LR00").  Attached is the excerpt from the log file.
[KSP.log.txt](https://github.com/KSP-KOS/KOS/files/359669/KSP.log.txt)

Interestingly, it appears that the label actually does exist in the program, as it exists in the list of the program that has been labeled so far.

I generated the included specific exception by inserting the attached code at line 235 of ProgramBuilder.cs so that I could see the label causing the issue.
```csharp
                if (!labels.ContainsKey(opcode.DestinationLabel))
                {
                    // This is one of those "should never happen" errors that if it happens
                    // it means kOS devs screwed up - so dump the partially relabeled program
                    // to the log just to help in diagnosing the bug report that may happen:
                    //
                    Utilities.SafeHouse.Logger.LogError("=====Relabeled Program so far is: =========");
                    Utilities.SafeHouse.Logger.LogError(Utilities.Debug.GetCodeFragment(program));

                    throw new Exceptions.KOSCompileException(LineCol.Unknown(), string.Format(
                        "ProgramBuilder.ReplaceLabels: No such label {0} exists.  Opcode: {1}", opcode.DestinationLabel, opcode.ToString()));
                }
```

**Comment by Dunbaratu** [comment]
On a related note, I think that we get bugs in ReplaceLabels often enough that we should probably have a refactor that wraps the whole thing in a try/catch that if it does throw a problem like "key is not present in the dictionary", we will dump the pre-relabled version of the program to the output_log so we can see what it was working with.  Thus when users hit the problem out "in the field" we have more information than we do now.

**Comment by hvacengi** [comment]
That's a fair point.  We added a `ContainsKey` check and error message for adding labels, but never did for accessing labels.  Maybe we handle both in the same try /catch instead?  If the two halves will be handled separately, I think I'd prefer that the snippet above was added to the code instead of a try catch.  From a performance stand point, cascading `try/catch` blocks are pretty expensive because the runtime has to unwind the call stack every time to create the exception.
