### ISSUE TITLE
list lists directory's

### ISSUE THREAD

**Issue by Efratror** [KSP-KOS/KOS#1729]
In V1.0.0 pre-release if U make a list of the files in a directory like so:

`LIST files in foo.`

the list also contains the directory's that are in the current path.
[documentation](http://hvacengi.github.io/KOS/commands/list.html?highlight=list) doesn't mentions anything about it. So is it possible to only get the scripts for a list?

**Comment by hvacengi** [comment]
At least for the time being you can use `volumeitem:isfile` instead: http://hvacengi.github.io/KOS/structures/volumes_and_files/volumeitem.html#attribute:VOLUMEITEM:ISFILE

We'll need to look at how the list is made and decide if the documentation needs to be revised to reflect a `VolumeItem` instead of a `VolumeFile`, or if the list generation should ignore directories.  Presumably if we ignore the directories, we need to provide a method for listing directories separately.

**Comment by Efratror** [comment]
Isn't it possible to give the list function an optional argument so you can set it to a list with or without directory's?

In the documentation you mentioned, in the table there is said that the :isfile suffix is a scalar but it's a boolean wright?

**Comment by hvacengi** [comment]
The table is incorrect, it is a boolean.  It must have been a copy/paste error, because the suffix detailed description correctly shows boolean.

Adding optional arguments is... not as simple as it sounds for things that aren't called like functions.  The compiler scans for a pattern, and then does some magic to turn it into a function call under the hood.  It may be doable.  Probably, it won't be done before we do the next release though.  We already planned on revisiting listing files anyways to allow users to list files in arbitrary directories.  So I would expect this to be all handled in that same revision.

**Comment by hvacengi** [comment]
Closed via #1761
