### ISSUE TITLE
Terminal window does not appear and control is not returned to KSP.

### ISSUE THREAD

**Issue by kosstarter** [KSP-KOS/KOS#1730]
I ran KSP (v1.1.3) with several mods including kOS. At a certain moment, te terminal window would not appear and  I no longer had any keyboard control on KSP (mouse still functioned).
I did a complete new install of KSP. First addition was kOS. With CKAN i added several mods, every now and then, i checked if the terminal window appaered (which it did).
After adding 26 mod's in total, i started programming for kOS. It worked fabulous!
This morning i tried to have the terminal window open automatically whenever a craft is launched, using a boot.ks i created. I used two hints i found in REDDIT:
`CORE:PART:GETMODULE("kOSProcessor"):DOEVENT("Open Terminal").`
and
`core:doevent("Open Terminal").`
The result was the same as i described above. I removed the boot.ks script and (after starting KSP again) tried to open the terminal window. No matter what i try no terminal window appears. By the way, i'm not using the three mentioned mods. I removed all modified files within KSP/mods from today. I removed the plugindata from kOS but nothing helped.
You can find my KSP.log file here: https://dl.dropboxusercontent.com/u/14923883/KSP.log

I have created a fresh KSP environment with some mods and it works now for the time being.
Is there a command by which i can set the location of the terminal window? (or log the location to file?)

**Comment by hvacengi** [comment]
I've walked through most of you log file (still reading though).  It doesn't appear that kOS sees your boot.ks file, are you sure it's in the right spot?  (or maybe you added the boot file towards the end of your testing?)

What wasn't immediately clear to me from the initial description was that this appears to happen only after a while of playing.  It appears you're able to access and interact with the terminal fine initially, is that correct?  Does exiting KSP and reloading fix the issue again?  How about returning to the space center and then back to the vessel in flight?

When did the UI stop responding?  Immediately before you quit?  It looks like kOS was still operating at that point, still continuing to adjust throttle and steering, is that accurate?

Side note: Without looking at the script that you're running, I can tell that you're calling `lock throttle to ...` and `lock steering to ...` repeatedly.  It floods the log with messages saying that the flight controls are being enabled.  For various reasons, you should not create a `lock` like that from within a loop, but instead lock to a variable and then update that variable as needed:
```
set tset to 1.
lock throttle to tset.
until tset < 0.1 {
    set tset to tset * 0.9.
    wait 0.
}
```

**Comment by kosstarter** [comment]
I took the precaution of making a rar file of the complete KSP environment. That enables me to quickly reuse kOS again. It is correct that kOS can't find the boot.ks file as i renamed it to prevent further troubles. The problems starts whenever a boot.ks is executed. From that moment on the terminal window refuses to appear, even when i close KSP and restart it. (i've done so many times). It only appears again after i reïnstall KSP and the mods. With the mouse, i can click on RECOVER VESSEL (in KSP). That usually freezes KSP completely. I have to kill the KSP process in Windows (no other way works). When i start KSP again and try to open the terminal, the window does not appear, although kOS says it's open. Closing it, opening it. Still the terminal window will not appear. After deleting the complete KSP environment and extracting the rar with the compressed environment, i can start KSP again and now the terminal window will appear again (until i use a boot,ks). I did remove the CORE: statement but it seems that command is not the problem. The same problem occurs whenever there's a boot.ks.
There's not much in the current boot.ks, just the setting of some default stuff:
//boot.ks
// This program sets the initial values of an SSTO
//Set the ship to a known configuration\
wait 2.
SET TVAL TO 0.
SAS off.
RCS on.
lights on.
brakes on.
lock throttle to TVAL. 
gear on.
TOGGLE AG10.

I even tried a boot.ks with only the SAS, RCS en AG10 statements but even then the problem occurs again.
I'm using kOS v0.20.1, KSP 64b, 8 GB memory, W7

**Comment by kosstarter** [comment]
Sorry, I didn't mean to close the thread.

**Comment by hvacengi** [comment]
When you re-install the environment, do you still have the boot.ks file installed, does using the boot file work for a short time and then fail?

The log file that you uploaded, does that include the failure in it?  It looks like the last "flight" kOS was working, and at least controlling the throttle, then you reverted to the editor, then went to the space center, then went to the main menu and presumably quit.  So I'm interested to know if kOS is still working in the background to isolate if the issue is with the screen or kOS itself.

If you install only kOS and use the boot file, does the same issue present itself?

**Comment by kosstarter** [comment]
I don't get it. I tried it again. Restored KSP, added a boot.ks and launched a craft. What?!No problem, the window appeared. I added a wait 2. statement in the boot.ks and launched again. Again, no problem.
I even added the CORE:PART:GETMODULE("kOSProcessor"):DOEVENT("Open Terminal"). statement and launched again. And once again, no problem. Frankly, i need to pick up my jaw from the floor because i'm flabbergasted.

**Comment by Dunbaratu** [comment]
If you can't get it to happen again, can you close the issue?  (it can be re-opened again later if you get it to occur in a repeatable way).

**Comment by kosstarter** [comment]
A.f.a.i.k. the only thing different is that the UI in KSP is at 100% in stead of 80% which i usually do.
I'm closing this issue until it happens again.

**Comment by kosstarter** [comment]
I'm reopening the issue.  
Yesterday i closed KSP/kOS correctly and shutdown the computer. This morning, right from the start the problem occurs again. The same happened yesterday. 
I recover the craft, and KSP freezes.

**Comment by kosstarter** [comment]
Could these problems be related to KSP 64 bits?

**Comment by hvacengi** [comment]
The log file you provided originally appears to to only have normal exceptions (exceptions due to script errors, or timewarp issues).  More notably, I can't seem to any issues with recovering vessels or reverting, or KSP itself freezing.  It appears you were able to open the terminal each time in that file as well, though it's hard to confirm in the log file.

A) Have you tried using the release candidate of kOS for KSP 1.1.3?  That would at least eliminate the error I saw for attempting to call timewarp.  It would also tell us if the issue has been fixed already (which might explain why I can't reproduce it).  If you need (or want), I can make a build available for you to test with the absolute latest build.  In fact, I may just post a dropbox link to that tonight when I get home, and add a few extra debug messages.

B) I know you've reverted back, but could you try v0.20.1 again, and this time send the output_log.txt for first time that the window fails to open as well as from the subsequent attempt(s) to open KSP?  If there is something persistent across loading of KSP, it should be an error visible when kOS loads.

C) Can you confirm that the issue only first appears when you attempt to use a boot file?  If so, can you please upload the exact file you were attempting to boot when the error occurs, as well as the exact craft file?  I'll revert my install entirely to v0.20.1 and whatever mods you have installed and attempt to mimic your system as closely as possible.

**Comment by kosstarter** [comment]
I've tested several options. I now run less mods and am running KSP 1.1.3 32 bits. Under those conditions, the mentioned problems do not occur.
A) Where can i find the the release candidate (if you prefer you can send the dropbox link to the latest build)
B) I am now using the WARPTO command. 
C) It now appears to be the combination of KSP 64 bits and kOS, so i don't think it will be necessary for you to mimic my system.

**Comment by hvacengi** [comment]
Has this continued to be an issue following the release of kOS v1.0.0?

**Comment by kosstarter** [comment]
I've installed a KSP 64b yesterday with several mods. Sofar (in careermode) i haven't had the same problem.
I will close this issue until it happens again.
