### ISSUE TITLE
KOS 1.0 - :istype not pulling inherited types

### ISSUE THREAD

**Issue by gisikw** [KSP-KOS/KOS#1734]
:istype structure suffix not catching inherited types. Direct type checks still work.

Repro:
```
print ship:istype("Orbitable"). // False
print mun:istype("Orbitable"). // False
print mun:istype("Body"). // True
```

**Comment by gisikw** [comment]
Ref https://www.reddit.com/r/Kos/comments/4t9f1r/v100pre1_possible_problem_with_delegates/

**Comment by hvacengi** [comment]
By adding some debugging, it looks like the "Orbitable" option isn't even being loaded.  If I were to guess, it's probably related to `Orbitable` being abstract, since the new `AssemblyWalkAttribute` skips abstract classes, I think.  I'm not really sure that I have a good reason to be skipping those cases anymore, so it should be a quick fix.

**Comment by Dunbaratu** [comment]
It's definitely something unique to `Orbitable` (meaning the title should change, because the title implies incorrectly that it's just generically all inherited types, which it's not.  If you try testing whether ``:istype("Part")`` is true for a DockingPort, for example, it works.)

**Comment by hvacengi** [comment]
Which further leads me to think the issue is the abstract class (since `Part` is not abstract).  I think the abstract guard is left over from when we registered based solely on inheritance and we wanted to make sure that we didn't try to instantiate an abstract class.  I think it will be a matter of editing 2, maybe 4 lines.
