### ISSUE TITLE
Add a way to disable "first pitch/yaw then roll" steering feature

### ISSUE THREAD

**Issue by PhoenixBlack** [KSP-KOS/KOS#1777]
It's hard to fathom why this conditional exists and it seems completely out of place, but for sake of backwards compatibility, could you please add a way to bypass the conditional at SteeringManager.cs, line 710?

`if (Math.Abs(phi) > 5 * Math.PI / 180d)`

It is very hard to understand why would one suddenly stop steering on roll channel just because given vehicle is in a transitional motion over a large span, but it's completely wrong. When doing atmospheric reentry, this deprives vehicle of *incredibly* vital roll control at times (when arbitrary threshold is reached).

**Comment by Dunbaratu** [comment]
If you don't understand why it does this, then try changing the line of code, recompiling, and seeing how it flies without it there and you'll see why it was added.  Trying to steer all 3 axes at once causes it to steer in a funny narrowing spiraling arc toward the destination instead of straight to it.

What might make sense more is to let you pick which one axis will be the "last one" where it lets the other two happen first.  Thus you could have one that goes "roll and pitch, then yaw", if you want (probably better for aircraft).

What does not make sense, however, is to let it do all 3 at once.  Try it and see what happens.

**Comment by PhoenixBlack** [comment]
It's nonsensical to steer only two axes out of three at a time. If the trajectory the orientation takes to reach target attitude is 'in spirals', then the attitude error is calculated wrong (I did not check kOS code to see how).

If attitude error is calculated as a quaternion (as difference between two *orientation* quaternions), then the resulting *rotation* quaternion will define the target error on all axes (more specifically, converting quaternion to vector will yield the errors to feed into PID loops on three axes).

This works, I've written autopilots which successfully respond to commands and steer on all three axes (if you'd like to, I can put up the implementation somewhere, but it simply boils down to "convert rotation quat to vector, derive error from that").

What I don't understand is why someone thought this is how steering is supposed to work!

**Comment by Dunbaratu** [comment]
I've never had any problems with re-entry steering under the current system.  The question I have is, why is it impossible for your craft to work with steering to the vector first, then rolling after it gets there?  What problem is this causing?

**Comment by Dunbaratu** [comment]
By the way, you have access to direct control over the ship controls if you want to use that and cook your own steering algorithm.  The cooked steering is meant for people who want some degree of automation rather than doing everything themselves.  If you are an expert in how to do it yourself, then by all means you can just ignore the crutch of cooked steering and just have your script control the controls in a raw way - you can pick the yaw deflection, pitch deflection, and roll deflection of the controls are at any given moment yourself and adjust them as you see fit.  This is how I do my airplane flights because the default steering assumes rockets where you want to yaw to steer instead of an airplane where you want to bank to steer.

**Comment by Dunbaratu** [comment]
I do think it would make sense to make the 5 degree threshold settable to make it wider than 5 degrees or narrower than 5 degrees if desired (setting it super wide being effectively the same thing as it not being there at all).

**Comment by PhoenixBlack** [comment]
I know I can do my own steering, there are two points in this issue:
1) Steering in kOS is apparently done wrong (it should not swirl around if you do 3-axis control)
2) There's no way to disable the 5-degree dead zone limit (let me disable it even if it causes swirling!)

The steering is broken because it doesn't control all three axes at once in all conditions, which is contrary to what one would expect from steering.

 The default cooked steering is sufficient to control the vehicle with banking and everything involved (just gotta feed it correct quaternion/rotation), so there's no reason to implement custom steering when the kOS one simply has a weirdness in it.

Here's the reentry itself, with all the typical maneuvers required. Since the ship is under active iterative guidance, it has to adjust both angle of attack (drag modulation) and bank angle (vertical speed modulation) at the same time. In this specific case, the profile was such that built-in command rate limits were enough to not have it spin out of control during reentry (only slightly).

https://www.youtube.com/watch?v=z8q_3LaEIDE

You can see it still has problems during latter portion of the flight. Currently it only yaws and pitches, but the firmware DOES support banking to turn - it's simply ignored by the steering because error is usually bigger than 5 degrees (worse yet is when it lingers around 5 degrees, so roll keeps turning on and off, giving self-induced roll oscillation tot he vehicle).

Setting the range through a command or a parameter would be an intermediate solution, though it doesn't change the fact that steering is supposed to work on three axes.

**Comment by Dunbaratu** [comment]
> but the firmware DOES support banking to turn

It supports banking to a new banked orientation IF you give it one explicitly.  That's not the same thing as what I was talking about when I said it's bad for airplanes because it doesn't do banked turns.  It doesn't do banked turns, as in, given a start orientation of HEADING(90,0) and an ending orientation of HEADING(180,0), it sees no difference in bank between the two - they're both wings-level flight - so it attempts to perform the turn by purely yawing alone, no roll.

**Comment by PhoenixBlack** [comment]
No, I'm saying that firmware I wrote does support banking turn. It generates custom rotation for the target attitude, but kOS is unable to steer to that attitude properly due to this 5 degree dead zone.

There's an explicit `*R(x,y,z)` in there that adds banking.

At least giving an option to widen or remove this deadband would help to great extent, as no matter how wrong the attitude error calculation is, it would still work for small attitude differences.

**Comment by Dunbaratu** [comment]
Correct, it's a useful thing to let users do "no matter how wrong the attitude error calculation is", even if that ends up being "not at all wrong".   It's still a useful thing to let people override if they want.

**Comment by PhoenixBlack** [comment]
Eagerly awaiting on information about the progress of this change. I want to finally get rid of shuttle flipping around (if it's unlucky) during transition from one phase to the other (and during the landing). And finally add roll control on approach/landing to reduce the G's.

https://www.youtube.com/watch?v=7xEpTHoBIVc

The stuff works almost perfectly now, apart from lacking proper roll control in certain phases of flight.
