### ISSUE TITLE
First wait after boot not actually waiting

### ISSUE THREAD

**Issue by darkbushido** [KSP-KOS/KOS#1785]
My boot file includes ```ADDONS:RT:HASCONNECTION(SHIP)```  and when I dont have a connection my frame rate suffers. I will add logs to this once i get home.

**Comment by Dunbaratu** [comment]
I suspect RT's own check for the connection might have to perform an exhaustive search of all the vessels before it can conclude none of them can help relay a connection.

**Comment by darkbushido** [comment]
My appoligies on how long this took to get.
https://gist.github.com/darkbushido/5a11598a079b7aac696c1547a3c6d2ac

**Comment by hvacengi** [comment]
More than just logs, we would also need a copy of your script and preferably a copy of your save with which to test.  The log only shows us what the game and various mods choose to output.  Without some context, it's very difficult to analyze a 5MB log file.

As @Dunbaratu pointed out, repeatedly calling `hasconnection` is most likely an expensive operation, and so should be limited only to times where you actually need the connection.  Are you calling every tick, or even worse more than once per tick?

**Comment by darkbushido** [comment]
the boot script is https://gist.github.com/darkbushido/613ce664088a1df91cd983950ff83fef
the performance drop happens https://gist.github.com/darkbushido/613ce664088a1df91cd983950ff83fef#file-boot_basic-ks-L41
a save showing the issue can be found here
https://www.dropbox.com/s/fxvaybk3dyfvup7/kos-rt-test.zip?dl=0

**Comment by hvacengi** [comment]
Hm, so this is more tricky that you would believe.  The issue doesn't appear to be with RemoteTech, but instead with the `wait` execution itself.  In fact, removing every reference to RemoteTech in the script provides the same results.  Running your script without any edits, the cpu is rebooting constantly.  Unless I add the line `wait 0.` to the beginning of the file. (or any additional `wait` for that matter.  For some reason, it appears that the code is ignoring the very first `wait` that the script encounters.

We're making some modifications to the wait code, so I'll try running this example through the updated code and see if the issue is fixed, or if further troubleshooting is needed.

**Comment by hvacengi** [comment]
Just tested using PR #1787 and the wait issue went away.  So we (really @Dunbaratu, not me) must have inadvertently fixed the bug.

**Comment by hvacengi** [comment]
(Renaming the issue to be more in line with the actual issue.)

**Comment by darkbushido** [comment]
sweet thanks for looking into it.
