### ISSUE TITLE
addition changes type

### ISSUE THREAD

**Issue by Gotbread** [KSP-KOS/KOS#1792]
![koserr9](https://cloud.githubusercontent.com/assets/19180639/18026289/f33432ec-6c41-11e6-8c76-27c46903da9a.png)

This simple program takes a scalar argument and adds it to another scalar from global scope. The screenshots show both are scalar in type. Yet the addition creates a string instead of a scalar.

another program which simply "set ret to 5." gives a ret:typename of scalar, as intended.

Edit:

The value "ret" converts into string even before the function ends.

```
set ret to _param + parent_body.radius.
print _param:typename.
print parent_body:radius:typename.
print ret:typename.
```
gives:
```
scalar
scalar
string
```

**Comment by Efratror** [comment]
I've tried to replicate your bug with the following code:

```
set _param to 10.
set parent_body to kerbin.
set ret to _param + parent_body:radius.
print ret:typename.
```
output:

> Scalar

Correct me if i'm wrong but i think you made a typo in `set ret to _param + parent_body:radius.` you use parent_body(dot)radius instead of parent_body(colon)radius. When you use an undefined variable kOS assumes its an empty string. So it doesn't change the type of a scalar to a string but it is in fact a string. Take a look at the [lazy global directive](https://ksp-kos.github.io/KOS/language/variables.html#lazyglobal-directive) to make typos a thing of the past.

**Comment by Gotbread** [comment]
It was indeed a typo. Thats what i get for mixing languages...
