### ISSUE TITLE
Increase limit of machine code instructions

### ISSUE THREAD

**Issue by Gotbread** [KSP-KOS/KOS#1796]
I tried compiling a large file (>2400 lines) and the resulting .ksm file cannot be run, giving the error:

![koserr10](https://cloud.githubusercontent.com/assets/19180639/18077295/f3d5df08-6e84-11e6-8e5b-534cbaca146d.png)

The relevant files are:
https://dl.dropboxusercontent.com/u/4344199/Utilityupper.ks
and
https://dl.dropboxusercontent.com/u/4344199/Utilityupper.ksm

The exact code does not matter. I shortend the file a bit while playing around with the limit, and copied
the last function a few times to increase the size. If you remove the last function, the compiled file runs fine.

**Comment by Dunbaratu** [comment]
(I requested that @Gotbread submit this issue during the stream when he described what was happening when he tried this.  I suspect the error is in some way related to how we write label strings using 4-digit label padding by default (i.e. instruction # 23 coming out as label @0023).  I would expect that the correct behavior when it goes past the 4-character limit would be to just add a character so you get @12345 and it doesn't break, it just has the effect of not printing out nicely aligned with the other shorter numbers.  But it seems to be hitting something that isn't handling it somewhere in our code.

**Comment by hvacengi** [comment]
Are you saying that this is only a problem with the compiled ksm file, or do you get the same error when running the ks file itself?

**Comment by Gotbread** [comment]
running the .ks file itself works fine. only running the compiled .ksm file results in the problem. While i was debugging i used the .ks file, when things finally worked i compiled the file to shorten startup times. Smaller .ksm files work normal, only big ones have this issue

**Comment by hvacengi** [comment]
I've been poking around this code for a little bit this morning, so I thought I'd report my findings.

The exception itself has the following stack trace:

```
System.ArgumentException: An element with the same key already exists in the dictionary.
  at System.Collections.Generic.Dictionary`2[System.Int32,System.Collections.Generic.List`1[kOS.Safe.Compilation.IntRange]].Add (Int32 key, System.Collections.Generic.List`1 value) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Compilation.DebugLineMap..ctor (System.IO.BinaryReader reader) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Compilation.CompiledObject.UnPack (kOS.Safe.Persistence.GlobalPath path, System.String prefix, System.Byte[] content) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Persistence.FileContent.AsParts (kOS.Safe.Persistence.GlobalPath path, System.String prefix) [0x00000] in <filename unknown>:0 
  at kOS.Function.FunctionLoad.Execute (kOS.SharedObjects shared) [0x00000] in <filename unknown>:0 
  at kOS.Function.FunctionBase.Execute (kOS.Safe.SafeSharedObjects shared) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Function.FunctionManager.CallFunction (System.String functionName) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Execution.CPU.CallBuiltinFunction (System.String functionName) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Compilation.OpcodeCall.StaticExecute (ICpu cpu, Boolean direct, System.Object destination, Boolean calledFromKOSDelegateCall) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Compilation.OpcodeCall.Execute (ICpu cpu) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Execution.CPU.ExecuteInstruction (IProgramContext context, Boolean doProfiling) [0x00000] in <filename unknown>:0 
```

I added code to print the line numbers that were already in the dictionary, and a few of them look not right, leading me to believe that there's some kind of misalignment when reading the file:

```
kOS: Error adding line 158, line already exists
Line 0 with 2 ranges
Line -25600 with 0 ranges
Line 158 with 164 ranges
Line -26328 with 41 ranges
Line 15383 with 25 ranges
Line 16713 with 73 ranges
[... snip ...]
```

I also added the line `set x to 1/0.` to the bottom of the test file, so that I could determine the largest label in use:

```
File                 Line:Col IP   label   opcode operand
====                 ====:=== ==== ================================  
[... snip ...]
0:/help/Utilityupper.ks 2028:9   7892 @7862   push renametostation 
0:/help/Utilityupper.ks 2028:47  7893 @7863   push $renametostationfunc* 
0:/help/Utilityupper.ks 2028:47  7894 @7864   storeglobal 
0:/help/Utilityupper.ks 2095:1   7895 @7865   popscope 1
0:/help/Utilityupper.ks 2096:5   7896 @7866   push $x [begin my additional code]
0:/help/Utilityupper.ks 2096:10  7897 @7867   push 1 
0:/help/Utilityupper.ks 2096:12  7898 @7868   push 0 
0:/help/Utilityupper.ks 2096:11  7899 @7869   div <<--INSTRUCTION POINTER--
0:/help/Utilityupper.ks 2096:11  7900 @7870   store 
[... end ...]
```

So while this program is close to rolling over the label count it isn't quite there yet.

In an effort to make sure that it isn't directly tied to the line count, I then removed the empty lines from the file (and changed nothing else).  As expected, the error remained.

I tried commenting out the contents of multiple functions to see if it was tied directly to instruction counts, and it appears to be independent of the instruction count.  I commented the contents of all 3 final `GetDockingPort` functions (leaving the functions themselves) and still encountered the error even though commenting only one of the functions entirely clears the error.  I tried commenting the functions out of order and it doesn't appear to matter which function itself is commented.

At this point I'm suspicious of something funny in how the function section either gets written or read from the ksm file.

I have not yet tried splitting the file into two files, but that is obviously the best chance for a work around.

**Comment by Dunbaratu** [comment]
I added a debug dump in the place where the values are packed in the first place during the compile (not when they're read), and got this:

```
eraseme DebugLineMap Unpack(): wrote lineNum=0, countRanges=258
eraseme DebugLineMap Unpack(): wrote lineNum=4, countRanges=1
eraseme DebugLineMap Unpack(): wrote lineNum=5, countRanges=1
```
These mean "line 0 has 258 different ranges of VM opcodes that point back to it.  Line 4 has 1 range of VM opcodes that point back to it.", and so on.

The problem is that there's a hardcoded assumption that countRanges will fit in one byte - that there just can't possibly be a case where there are more than 255 different individual chunks of the VM code that all came from the same line of source code.  Note, this isn't just a section consisting of 255 opcodes coming from one line of source.  This is 255 different **sections of** VM opcodes that have gaps between them, coming from one line of source.

That's very strange, but I suspect it's the reason for the problem.  the value 258 doesn't fit and overflows.  so a value of only 3 gets stored instead of a value of 258.  So on reading it only expects 3 ranges, and then expects another header after that.  So after those 3 ranges it tries to read the next "header", but it's not really a header, it's just another of the ranges - that's where the misalignment is coming from.

I could just increase it to 2 bytes and handle it, but I think that will bloat the KSM file so I'm first going to try to find out why on earth it's getting 258 instructions from a single line.

The line in question happens to be the opening '{' line that wraps the whole file, so it might be assigning lots of the code inside the brace section to just being from the "brace" line itself and that's why it's happening.

**Comment by Dunbaratu** [comment]
Okay culprit found.

Every OpcodeLabelReset that gets inserted gets a dummy line number of zero, indicating that it's not coming from a "real" line number because it didn't come from the original compile, but from the KSM compile.

When there's lots and lots of OpcodeLabelResets, that results in lots of opcodes being falsely attributed to "line 0" (which isn't a real line anyway, the file actually starts counting at line 1, not line 0).

**Comment by hvacengi** [comment]
So if line 0 doesn't exist, is there a way for us to simply ignore that line when creating the `DebugLineMap`?  Those opcodes just get replaced anyways, and the new opcode should have it's own copy of the proper information.  Or am I over-simplifying it?

**Comment by Dunbaratu** [comment]
I implemented a fix already (PR coming any second now - just deleting all my debug print lines first).

The fix I did was that when CompiledObject.PackCode() detects a need to insert an OpcodeLabelReset, I just have it inherit the line number for that new OpcodeLabelReset from the next opcode (the one it's resetting things on behalf of).
