### ISSUE TITLE
Escaping the file system

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KOS#1799]
related to #778 
Done it again (only tested on windows as of now) more details in slack

**Comment by Dunbaratu** [comment]
Slack has a limited duration on its history.  After a few weeks those messages fall off the end of the queue and can't be seen again.  Therefore "more details in slack" isn't a very good idea for describing a github issue, which should remain viewable for posterity.

**Comment by TDW89** [comment]
@Dunbaratu fair point. The reason I reported it like that is I'm fairly certain I was told last time that I should making too much info on potential security issues public.

The issue is that `cd("0:\")` maps to `C:\` once there you can get anywhere you want.
You are not able to write anywhere the you don't have permission for but you can walk the file system and and open, edit and create files you have access to.

**Comment by Dunbaratu** [comment]
Good point about the security issue not being public, and I understand now why you didn't want to say much about it on github.

That being said, I think losing the description of the issue altogether (because it's only on Slack) would be a worse situation than having the security issue become publicly known.  The issue does exist now, whether people are aware of it or not.  Keeping it secret probably only would benefit those who would exploit it (making it less likely for users to be careful about what they download and run because they didn't know the problem existed).

**Comment by nevercast** [comment]
This is an open issue from 2016. Is this issue resolved? I'd like to think this was followed up and just not closed.

**Comment by Dunbaratu** [comment]
Yeah I haven't been able to do this in ages.  Let me run a quick test and then I'll close it if it's not happening.

**Comment by Dunbaratu** [comment]
Yeah I can't reproduce the problem anymore.  This is an old issue and the directories system has seen a lot of changes since then.
