### ISSUE TITLE
Can't reference named functions inside anonymous functions

### ISSUE THREAD

**Issue by gisikw** [KSP-KOS/KOS#1801]
Was trying to set up a named-function workaround for managing steering within anonymous functions (which at the moment are necessary to prevent collisions from higher scope).

```
local fn is {
  function foo { print "foo". }
  foo().
}.
fn().
```

Results in `Undefined Variable Name 'foo'.` on the `foo()` function call. Referring to named functions from an outer scope works as expected:
```
function foo { print "foo". }`
local fn is {
  foo().
}.
fn()
```
`"foo"`

**Comment by TDW89** [comment]
Not that it fixes the bug but this works as a workround:
```
local fn is {
  global foo is { print "foo". }.
  foo().
}.
fn().
```

**Comment by Dunbaratu** [comment]
@gisikw Every so often I do a twitch broadcast of a "creative" stream in which I peel back the cover of the kOS development process and let people see a bit of what goes on under the hood.  One goal is to show people a bit more of the philosophy behind how software maintenance on a shared team project works.  Anyway, the reason I'm mentioning it is that I think this issue you found with anon functions is a good one to use for the next time I do it because: (1) As the person who did anon functions in the first place I'm probably the one who'd end up fixing it anyway regardless of whether I show it on stream, and (2) I *think* this issue is well-defined and non-controversial enough to "fit" within one twitch stream, all the way from start to finish.  (Often addressing an issue gets sidetracked into a matter of which of many possible solutions should be the "right" one, and that ends up being a discussion first before anything gets implemented.  I think this is one won't end up being that way.)

I have no idea what your schedule is like, but I'd like to accommodate it and stream this while you're around if possible.

**Comment by gisikw** [comment]
I do have a pretty tight schedule, but I can try to make that work. What time did you have in mind?

**Comment by Dunbaratu** [comment]
Afternoon (not evening) Wednesday, or any time Thursday.

**Comment by gisikw** [comment]
Hmm, I can be around after 8pm central on Thursday, but not earlier. Wednesday afternoon I can try, but can't make a firm promise. Day job kinda restricts my availability before evenings.

**Comment by Dunbaratu** [comment]
I'll plan for after 8pm central on Thursday then.
