### ISSUE TITLE
Support for more Unicode characters

### ISSUE THREAD

**Issue by khaiduk** [KSP-KOS/KOS#1844]
I created font_sml.png with support for more characters. It is able to handle (with only minor changes in source code) box drawing charaters and some national characters.

![All characters](https://cloud.githubusercontent.com/assets/2662789/19418340/32d5c198-93c2-11e6-9247-0e7252eda90a.png)

Some characters are from MrOnak's font_sml.png (https://github.com/KSP-KOS/KOS/issues/159).
Improvments can be done, such as moving box-drawing characters to Box Drawing Unicode block, but for it would require better solution for holding font data - maybe something like Unifont hex format.

Here is some live example:
![Sample usage of extended font_sml.png](https://cloud.githubusercontent.com/assets/2662789/19418313/a9dc31ec-93c1-11e6-82e0-ff8b79861c66.png)

**Comment by Dunbaratu** [comment]
My reason for not having done this earlier is the conflict between codepage 437 and Unicode.  Those box-drawing characters being at that position of the code is not true in Unicode, where they are much higher up.  If I did a thing like this and released it then people would start writing scripts that assume things like ``char(129)`` and ``char(130)`` are box drawing chars, and this assumption would break if we ever got the ability to just use a normal monospace unicode font.  The only reason we have to use this image texture template method is because KSP ships without a monospace unicode font and Unity didn't allow you to add your own fonts unless you had the full paid version.

But there's a possibility of changing that in the future.  There's an alternate way the entire terminal could be implemented where it would use a proper unicode font.   The hope that we may do that some day is sort of why we haven't supported this yet - because the char() codes would be all different once it's fully supported.

But I realize that putting off support for a thing now, in favor of a far-off feature that may come 'some day' is really annoying, so let's try to come up with a possible solution here that would be future-compatible.

All we'd have to do to be able to use this idea as a temporary stopgap would be to change how the system reads the font image PNG file so it doesn't presume all the pictures are consecutive adjacent codes.  If we offered the ability for the image file to contain "skips" or a mapping of some sort (i.e. the image at position 133 isn't really char(133) but some other number.) then we could support this now but not break future compatibility.

How about a secondary file alongside the PNG that contains this information?  Maybe some cheap text table format that just says things like:
```
139 9472
197 9532
```
etc to mean "position 139 is really unicode 9472" and so on.

**Comment by khaiduk** [comment]
I was thinking about approach simillar to [GNU Unifont's hex format](https://en.wikipedia.org/wiki/GNU_Unifont#The_.hex_font_format), except for 8x8 character size, rather than 16x8, something like this:

```
00B1:CFCF03CFCFFF03FF
2500:00000000FF000000
253C:18181818FF181818
```

There would be only 1 file to keep track of, but it's harder to visualize how the font looks like and edit it.

I like the idea of additional file with mapping Unicode number to position in image, but I think it would be better to keep character coordinates:

```
9472 8 11
9532 12 5
```

**Comment by Dunbaratu** [comment]
I like these ideas.  Let's keep the conversation going over the next day or two and settle on a solution and do it.

One thing to keep track of about this is that we need the lookup to be extremely *fast* once it's loaded in memory (it's okay for it to take a bit of time to load up front from the file, but once it's loaded it MUST be an almost instantaneous lookup to get from character code to the right portion of the image texture.)  This is because it redraws the whole terminal roughly 10 to 20 times per second, and re-executes the bitblt-ing that often.  I'm even considering accepting the RAM inefficiency of a sparsely populated array just to map from unicode name (as the array index) to where it is in the texture.  (i.e 65536 items in the array, most of which are unpopulated).  Even the relatively fast time of a hashcode lookup might be worth avoiding here because of how often the code gets re-run.

**Comment by khaiduk** [comment]
I tested how static array performs against C# Dictionary, measuring `TerminalGui()` executon time while running script:
`SET TERMINAL:WIDTH TO 255.SET TERMINAL:HEIGHT TO 160. SET I TO 10000. UNTIL I < 0{ PRINT "X" AT (FLOOR(RANDOM()*255),FLOOR(RANDOM()*160)). SET I TO I-1.}`. Static array performs a bit better (21 milliseconds array vs 24 milliseconds Dictionary in my configuration). Since we have only one `fontArray` table and half megabyte is not that much compared to gigabytes of RAM, we can use static array.

**Comment by Dunbaratu** [comment]
Yeah I don't think the waste of memory is a big difference overall, especially as we can make sure to design it to use static data in the class.  That way it only exists once for the whole mod, not once per terminal.

So basically we'd map each unicode number to an array entry at that index which contains the index into the image file.  I'd still prefer it to just store one number, the overall index, instead of the x/y numbers separately.  (i.e. position at row 10, col 6, for an image file with 16 images per row, would be stored as just the single number 10*16+6 = 166.)  My reason for this is it allows us to more easily store a "consecutive run" in the side-file that maps the numbers.  We could just say in the file something that means "starting at image 166, that's really Unicode 0x253c.  Now keep counting consecutively upward from there until I tell you to make another jump at a later image index."  Thus we wouldn't need the little file on the side to store the index of *each and every* character, just the indeces of the starts of consecutive chunks.

We'd have to enforce the rule (this rule already exists, I'm just being explicit) that the format of the image file has to remain constant throughout (i.e. each character cell is the same size, each row has the same number of characters on it) for such an idea to work.  Else we'd need to type out the x/y coords of each and every single character in the image file.

**Comment by Dunbaratu** [comment]
EDIT: Another idea  that might make it easier to manage the data would be to allow multiple different PNG files for different ranges of characters, so we could have the mapping say "this unicode char is stored at character position N within file F."  What that would buy us is the ability to break up different sections of the font into separate files so we don't get a messy large tall  image to work with.

**Comment by hvacengi** [comment]
Given the direction this conversation is going, I want to ask an important question: does this mean that we would no longer be looking to upgrade the terminal to use a traditional font file with the new Unity 5 UI?  Because if that's still a plan, I think I'd rather we focused our attention there since it would in essence accomplish the same thing without having to re-invent a font rendering system (admittedly it does require re-inventing the window system, so there is some definite trade-off).  I suppose as long as the new system does not exclude the ability to make that migration in the future, it probably doesn't matter much.

I'd have to look up the specifics, but isn't there something about how textures are stored internally that makes squares better than rectangles?  And don't they like powers of two for dimensions?  However the image files are handled should make sure to take that into account.  We should also see if we would still be able to dynamically define these textures if the source image is stored as a dds file.

Because `Texture2D` is a class and therefore a reference type, the array/list/dictionary will only store the reference to an independently defined object.  That's an important distinction, because that means that an array holding blank spaces will only have the additional memory overhead of the extra references (defaulted to null references) instead of that of blank textures.  A reference is significantly fewer bytes of memory than a texture, so the larger array should not have a dramatic impact on memory usage so long as it isn't frequently re-allocated.  I'd have to think about the implications for a GC memory walk though.  Mono's GC basically marks each object as "unreachable" and then walks all known objects marking there references as "reachable" and then removing anything that is still "unreachable" after the walk.

On a separate note, kOS used to have a boot animation?  I'd kind of like to bring that back!  Though the terminal is hidden by default I suppose, so there's no good way to see it (the boot script should run after the animation is complete).

**Comment by Dunbaratu** [comment]
> because that means that an array holding blank spaces will only have the additional memory overhead of the extra references (defaulted to null references) instead of that of blank textures. 

Not an array of references to the textures.  An array of numbers describing what sub-portion of the single image texture contains the one character image that goes with that code.

(i.e. if unicode char 0x543c has its picture stored at the 342nd char block inside the font image, then the array would have an entry at index 0x543c containing the integer 342.  (Then to work out where in the image that 342 is in x/y terms, you use the fact that each image is 8x8, and that there's 16 of them per row, so you go ``y = (342/16)*8``, and ``x = (342%16)*8``.))

This wouldn't really be all that different from what we already do now, so implementing it wouldn't take long at all.  We already do the above logic of ``y=(N/16)*8``, ``x=(N%16)*8`` to find a sub-section of the big fontimage.  The only difference is that before that N was the ASCII code itself, and with my proposal we'd have to start from M as the Unicode, and do the array lookup to find the N you use in the formula, since we don't want an image containing 65536 different characters in it to accommodate all of Unicode.  The purpose of the lookup between unicode and index into our char image is to make it so we don't need lots of blank empty space to accommodate all the unimplemented characters.

The idea is that going to the new system is probably going to take some time and this would let us get there faster as a stopgap, and here's someone who gave us a PR that we can't accept at all if we use the new system.

**Comment by Dunbaratu** [comment]
I suppose I could spend a few days researching how I could use the new GUI to get a feel of how hard the change would be, but I just think it's not going to be easy given how much of our current system is tied to the current gui terminal model - the ScreenBuffer, SubBuffer, TermWindow, etc would all need to be redesigned from scratch, I suspect.

**Comment by hvacengi** [comment]
So the array/dictionary memory conversation is exclusively for the sake of the initial loading of the font information to construct the font array (which is the `Texture2D[]`)?  In that case, I don't know that it will matter.  The column/row data (and by extension the proposed file/column/row data) is only processed once per terminal window current, during `Awake`.

Or are you some how proposing that we no longer store a single `Texture2D` for every character?  So that the call to `GUI.DrawTexture` in `ShowCharacterByAscii` some how does a clipped texture (I think that would use `GUI.DrawTextureWithTexCoords`)?  That would probably decrease the memory footprint.  The textures are stored in memory with some form of compression iirc, and a large texture with similar shapes ought to be compressed better than a single texture with one shape.  But it does slow down our array lookup.  So at that point the question becomes: which is faster? (using an array lookup to determine and index, and then infer x/y coordinates from the index, then display the texture clipped, or just do a single array lookup to the texture of the desired character but each character is an independent texture).

**Comment by Dunbaratu** [comment]
> So the array/dictionary memory conversation is exclusively for the sake of the initial loading of the font information to construct the font array (which is the Texture2D[])? In that case, I don't know that it will matter. The column/row data (and by extension the proposed file/column/row data) is only processed once per terminal window current, during Awake.

I just had a look at the TermWindow code.

My earlier ideas were based on me forgetting that I changed how the font image works in the code quite a few months back.  Once upon a time there was no such thing as ``private Texture2D [] fontArray;``.  Instead there was just the single ``private Texture2D fontImage`` image file, and as it rendered a char image it had to"pan" to the right offset within the single image file to paste the rectangular sub-region of it that had the desired letter image.  It never cut the image up into a different single one per letter like it does not.  That change had to be done to accommodate the newer feature of scaling of the letters for "zooming" the terminal.  After fighting with Unity for a long time trying to get it to scale as it rendered a rectangular sub-region of the larger image file, I gave up and just decided to cut it into individual images so each image can be scaled in its entirety, which Unity was more "agreeable to".

I has simply forgotten I had made that change and was operating on the notion that it was still all in one big single Texture2D when I proposed the extra lookup array to find the right portion of the big Texture2D to pull the letter from on the fly during rendering.  Yes, you're right that given how it works now, there's no need for that extra step.  We can just have an array of references to the individual Texture2D's and use nulls for the missing ones, now that they are all individual separate images.

**Comment by Dunbaratu** [comment]
I was thinking about this and just remembered that I had a stub of some code that worked out how to load a monospace TrueType font file (Which the game does not ship with).  Originally Unity didn't allow people to use their own fonts unless they shell out the money for the professional version.  That changed a few versions ago and I experimented with being able to load any TrueType Font file I feel like and I was a able to do it.  (It involves making an "asset bundle" out of the font file, and asset bundles used to require the professional version of Unity.)

It occurs to me we may have a solution halfway between using the actual Unity 5 GUI system and continuing to use our old texture map system.

We could just use a font file, but still keep much of the rest of it using the "legacy GUI" system.

If we do that, and we use a font file that has all the unicode characters populated into it, we'd also have the advantage that it would let us make smaller letters easier to read.  (an actual font will render with some aliasing making it possible to have letters be a bit smaller than 8x8 and still look okay).  It will also scale up better when making the font larger, since it won't just be a bitmap image.
