### ISSUE TITLE
No scientific e?

### ISSUE THREAD

**Issue by Bosek** [KSP-KOS/KOS#1846]
According to wiki you can use scientific notation: https://ksp-kos.github.io/KOS/math/scalar.html#scientific-notation
But in game:
![image](https://cloud.githubusercontent.com/assets/6001235/19459242/ce201378-94d1-11e6-9852-60229e98ec02.png)

KSP version 1.2

**Comment by hvacengi** [comment]
If you type it as `1.23 e 5` , `1.23e+5`, or `1.23e 5` it will work.  The issue is probably that a lack of space or symbol does not qualify as a "word boundary" when parsing the number.  For the time being my recommendation will be to always include the plus/minus operator.

I'll ping @Dunbaratu as he better understands the parsing engine.

**Comment by Bosek** [comment]
`1.23 e 5` and `1.23e+5` works. Wiki probably needs an update. Thank you for help!

**Comment by Dunbaratu** [comment]
Yeah the way the parse rule is designed, it looks like the +/- symbol is mandatory when it's all run together.  That might actually be fixable.  Re-opening as I think this could be fixed.

**Comment by hvacengi** [comment]
I think I actually fixed this as part of the review of #1883 (commit 244a40ecb890711c601eee4f30faddc12593f075 ) I'll wait for a little bit to confirm before closing.  @Bosek can you confirm if this has been fixed for your use case?

**Comment by Dunbaratu** [comment]
I have just confirmed that it's fixed, by the way, @hvacengi
