### ISSUE TITLE
(1.2 first prerelease) Terminal not working/displaying

### ISSUE THREAD

**Issue by KingHandspider** [KSP-KOS/KOS#1853]
Playing with the most recent version of KSP 1.2
have the most current version of kOS installed (prerelease)
Mods: Surface Lights, Airplanes Plus, kOS (buh)
made a new craft, slapped a terminal on it, launched it, tried on both launchpad + runway, tried in a new save file (both were sandbox), rclicked each time to open terminal, game controls are invalid as normal, but no terminal appears.

**Comment by Dunbaratu** [comment]
> game controls are invalid as normal

Why are you claiming this is normal?

Anyway, this description is unhelpful.  Can you find any exceptions in your log?  They can be found quickly among the long log by searching for ``  at`` (that's two spaces, then the word 'at'.  It works because all the exception messages contain a phrase like "  at {localtion here}", and it's one of the only places you'll see two spaces and a lowercase 'at'.

**Comment by KingHandspider** [comment]
sorry, when i said it was normal I meant that the flight controls were disabled as usual when the terminal window is active. (i.e. typing "W" while terminal is open doesn't cause the craft to pitch down, but inputs a "W" into terminal), also i forgot to mention: OS X version 10.11.3, MacBook Air, steam version of KSP

here are the exceptions, in order:
DivideByZeroException: Division by zero
  at kOS.Screen.TermWindow.LoadFontArray () [0x00000] in <filename unknown>:0 
  at kOS.Screen.TermWindow.Awake () [0x00000] in <filename unknown>:0 
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
UnityEngine.GameObject:.ctor(String, Type[])
kOS.Module.kOSProcessor:InitObjects()
kOS.Module.kOSProcessor:OnStart(StartState)
Part:ModulesOnStart()
<Start>c__Iterator38:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

DivideByZeroException: Division by zero
  at kOS.Screen.TermWindow.LoadFontArray () [0x00000] in <filename unknown>:0 
  at kOS.Screen.TermWindow.Awake () [0x00000] in <filename unknown>:0 
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
UnityEngine.GameObject:.ctor(String, Type[])
kOS.Module.kOSProcessor:InitObjects()
kOS.Module.kOSProcessor:OnLoad(ConfigNode)
PartModule:Load(ConfigNode)
Part:LoadModule(ConfigNode, Int32&)
ProtoPartModuleSnapshot:Load(Part, Int32&)
ProtoPartSnapshot:Load(Vessel, Boolean)
ProtoVessel:LoadObjects()
Vessel:Load()
Vessel:MakeActive()
FlightGlobals:setActiveVessel(Vessel, Boolean)
FlightGlobals:SetActiveVessel(Vessel)
FlightDriver:Start()

DivideByZeroException: Division by zero
  at kOS.Screen.TermWindow.LoadFontArray () [0x00000] in <filename unknown>:0 
  at kOS.Screen.TermWindow.Awake () [0x00000] in <filename unknown>:0 
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
UnityEngine.GameObject:.ctor(String, Type[])
kOS.Module.kOSProcessor:InitObjects()
kOS.Module.kOSProcessor:OnStart(StartState)
Part:ModulesOnStart()
<Start>c__Iterator38:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by hvacengi** [comment]
That means you have it installed in the wrong location.  As a result, kOS can't find the texture we use to display the fonts.  the "kOS" folder should be located within the "GameData" folder such that it's right next to the "Squad" folder.  Try checking your installation to make sure everything is in the right place.

**Comment by KingHandspider** [comment]
![screen shot 2016-10-23 at 8 20 29 pm](https://cloud.githubusercontent.com/assets/23019595/19631172/4d54ba82-995e-11e6-8886-23645eef9493.png)
the one next to Squad folder is kOS

**Comment by hvacengi** [comment]
Like I said, you should have a folder "kOS" (contained within the game data folder you have shown) next to the "Squad" folder.  You should never have a folder entitled "GameData" within "GameData".  So it looks as if you have more than just kOS incorrectly installed.  

You should unzip our file directly inside of the KSP directory, or better yet use CKAN to install mods because it should put them into the correct folder for you.  A correct installation of kOS will have a "kOS" folder next to the "Squad" folder, and the "ModuleManager.x.x.dll" ("x.x" depending on the version) should be next to it as well.

**Comment by KingHandspider** [comment]
*coughs* thanks. (i feel kinda dumb at this point)
