### ISSUE TITLE
New GameEvents for communication (AGX link)

### ISSUE THREAD

**Issue by SirDiazo** [KSP-KOS/KOS#1939]
Going to link the forum here: http://forum.kerbalspaceprogram.com/index.php?/topic/153112-ksp-122-gameevents-extension/&do=findComment&comment=2934715

I'm thinking about using the new GameEvents system for inter-mod communication with AGX going forward as it (in theory) should be much simpler to use.

The issue I'm running into is that I don't know how to handle data requests with it, such as when kOS checks an action group's state. 

The best answer I've come up with is 2 game events that pass the data request/result via confignode but that breaks things up because there will be a (very short) break between kOS passing AGX the data request and AGX then passing the data payload back.

I'm not sure that is actually workable however so I wanted to get some more people looking at this issue to see if we could come up with something.

Note that if anything does happen on this front, it is quite a long ways out and the current reflection system kOS uses will stay active for a significant transition period with anything I end up adding on this front. (If I add anything, the more I explore changing over to gameEvents, the more complex it looks.)

**Comment by hvacengi** [comment]
>The issue I'm running into is that I don't know how to handle data requests with it, such as when kOS checks an action group's state.

That's an excellent point.  The delay would present an issue.  If we take an example script:
```
// do something
if ag50 {
    print "ag50 is true!".
}
```
We would need to enforce the "get" of `ag50` to wait at least one physics tick for the responding event (assuming that events are not dispatched immediately).  That's actually very doable, because we recently added support for opcodes to support execution over more than one physics tick, making the get action essentially wait until the data is returned.

But that presents an issue when using `on` like this:
```
on ag50 {
    print "ag50 toggled! " + ag50.
}
```
Because the trigger will request the value of `ag50` essentially every physics tick, it will pause all execution until the action group event returns (meaning that it ends up requesting `ag50` every other tick assuming it only takes one tick for the event to return).  Triggers block other triggers and mainline code from executing.

I'll post this suggestion to the forum page as well shortly, but is there any reason that the event is required to return a `ConfigNode` based structure?  Could you instead create a base event that returns a commonly known reference type, like a list?  That would allow you to create an event that serves as an "initialization" or "heartbeat" event, that simply gives out the reference to the list.
```
public static EventData<string,ConfigNode> onAGXInitRequest;
public static EventData<string,List<bool>> onAGXInitReturn;
```
Under this structure, an object would subscribe to the `onAGXInitReturn` in a method that stores the reference to the list.  Then it would fire the `onAGXInitRequest` event to signal to AGX that it needs to pass out the reference.  AGX would then fire the `onAGXInitReturn` event, passing with it the reference to an internal list of the state of each action group.  Then AGX would update the values for the actiongroup list (without creating a new list) allowing for instant action group status inspection.  You could even go so far as to implement `IList<bool>` in your own class, allowing you to simply respond to the standard list methods without needing to change your own implementation.

**Comment by SirDiazo** [comment]
Alright, what I opening this issue for has been dealt with on the forum thread.

Once I'm at a point where I have actual code for kOS to potentially integrate with I'll open another issue at that time. 

The timeline on this is going to mostly likely be week(s) so I'm not sure when that will happen.

**Comment by SirDiazo** [comment]
Nevermind, as soon as I actually though about what I was going to post the issue resolved itself.
