### ISSUE TITLE
Steeringmanager settings don't get reset to defaults on CPU boot.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#1955]
Let's say you do something like this to disable the YAW portion of the steeringmanager:
```
set steeringmanager:yawpid:Kp to 0.
set steeringmanager:yawpid:Ki to 0.
set steeringmanager:yawpid:Kd to 0.
```
(My terrain leveler for rover driving does this.)

Well, it turns out that settings like this one (and possibly lots of others) don't actually reset to the defaults when you reboot the CPU.  If you leave the scene and reload it, then the steeringmanager goes back to its default state, but if you just reboot the CPU (without reloading the scene) these settings still persist.

If it's hard to auto-reset them on CPU boot (because maybe multiple CPU's on the same vessel borrow the same steeringmanager and one CPU might reboot but the other doesn't?)  then maybe providing a quick "back to factory defaults" method on steeringmanager might be a good idea.

**Comment by hvacengi** [comment]
This behavior was actually intentional, because the steering manager itself (the actual object, not the fictional concept as a component of the kOS processor) is associated with the vessel and not the processor.  That is to say, setting the constants in a script on one processor affects the steering manager's behavior when used from a script on a different processor.  I even wanted to make the values persist across sections, but `VesselModule`s did not support fields when I wrote that code (I think it's now possible).  A "reset to default" suffix should be very doable.  I've wanted to check to make sure the docking/staging logic anyways since it's supposed to copy steering manager values in those instances.  I can work on this.

**Comment by Dunbaratu** [comment]
@hvacengi  : Should we add this to milestone 1.1.0 ? (The part where you said you can make a "reset to default" call.)

**Comment by Dunbaratu** [comment]
Although this is mentioned in PR #1954, it's not actually solved by it, (the part about making a "reset to default" call).

**Comment by Dunbaratu** [comment]
Moving out of milestone v1.1.0 because of the unavailability of hvacengi right now.
