### ISSUE TITLE
Update GUI docs

### ISSUE THREAD

**Issue by hvacengi** [KSP-KOS/KOS#2017]
While I will be merging #2006, I noticed that there are a few outstanding added suffixes to document, and that the documentation doesn't implement the preferred `.. attribute::` syntax following the suffix table.  Before formal release it would be good to at least walk the structures to make sure all of the suffixes are documented, but it would be really nice to add the additional suffix documentation since the directive is what allows `:attr:` linking to work.

**Comment by Dunbaratu** [comment]
The docs tables were missing the detail sections below them in waz's original submission.  I documented a few of the ones I understood well, but stopped when I realized I was in danger of saying something false by accident since I was documenting some suffixes (related to appearance and skinning) that I didn't fully understand myself.

Now I think I could revisit them. as I understand them better now.

**Comment by Dunbaratu** [comment]
This should have auto-closed with PR #2043 but it didn't seem to auto-associate.
