### ISSUE TITLE
terminal overlay scaling obscures terminal on large windows

### ISSUE THREAD

**Issue by jberkman** [KSP-KOS/KOS#2020]
usually when you scale buttons and other UI elements, the "inside" is scaled and the beveled edges aren't. for the kOS terminal overlay, the whole thing is stretched and at large window sizes can obscure the terminal.

see upper left corner in attached screenshot.

![screenshot846 copy](https://cloud.githubusercontent.com/assets/1633584/26063617/5e314174-3943-11e7-82b2-777bb79f4d23.png)

**Comment by Dunbaratu** [comment]
I've known about this for a while but hadn't bothered to fix it because the last thing in the world I'd want to do when playing is make the terminal waste even more screen real estate than it already does, and I assumed everybody else was the same way.  Since you have to stretch the terminal very large before this problem happens, I figured it wouldn't be something anyone would really encounter.

But I guess these days with displays more than 4000 pixels across, people are going to start stretching it wide just to get it to be legible at all, so it's become a problem.

I suppose the terminal could just get rid of the curved corner effect entirely.  Alternatively, we could make it a 9-segment display so the corners don't stretch.   But we've also gotten complaints from people saying it doesn't make any sense for it to look like a terminal *anyway* since it can be stretched.  That it makes more sense for it to just look like some kind of GUI window running a terminal emulator.  I'm not sure which solution to go with right now.

**Comment by hvacengi** [comment]
In theory, couldn't we also put the stretched border behind the text?  That would still give the visual appearance of a rounded screen without compromising the text itself.  It would also mean that we keep the look for smaller displays while still being functional for larger ones.
