### ISSUE TITLE
kOS.version inconsistency

### ISSUE THREAD

**Issue by plumdog** [KSP-KOS/KOS#2054]
Currently KSP_VERSION_MAX is 1.0.99 even though KSP_VERSION is 1.3.0

I believe this should be upped to 1.3.99 and I believe this is why CKAN is not finding a version compatible with KSP 1.3, but kOS v1.1.1 does show if I ask CKAN to show me mods compatible with 1.0 only.

**Comment by plumdog** [comment]
(More generally, assuming the above is valid, it might be worth adding a check that the versions is `kOS.version` make sense, though I reckon that is beyond the scope of this issue.)

**Comment by Dunbaratu** [comment]
Good catch.  You were right.  But now I have to go through the whole release checklist again, and increase the version number to v1.1.2 just for this one small nearly irrelevant change (every new change we want CKAN to notice needs a new github tag, and that means a new version number.  IF we just update the ZIP file of an existing tag, CKAN doesn't re-read the info.  So to change this one line means re-doing a lot of manual steps to re-release.

But thanks for catching it.  It's hard to notice when the CKAN info is wrong because it's *normal* for CKAN to take a half a day or so to notice the change - so I can't immediately test if it worked after making a release.

**Comment by plumdog** [comment]
Yup, CKAN found the update when I refreshed it.

However, it is still getting slightly confused because one of the tags is tagged as `v.1.1.1` and the leading `.` mucks up the tag ordering in CKAN so it thinks that's the latest release. Not sure if this is something that should be sorted here or in the [CKAN registry](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/kOS.netkan).

But regardless, the original issue is resolved, so if the above is ignorable, then this can be closed.

**Comment by Dunbaratu** [comment]
it may be possible to remove the offending tag from github entirely, but I won't know until I'm back home in a few hours.
