### ISSUE TITLE
Log spam with Timing0 threw during FixedUpdate

### ISSUE THREAD

**Issue by jrens** [KSP-KOS/KOS#2059]
Log gets spammed with
```
[ERR 19:02:02.811] Timing0 threw during FixedUpdate: System.NullReferenceException: Object reference not set to an instance of an object
  at kOS.Module.kOSVesselModule.CacheControllable () [0x00000] in <filename unknown>:0 
  at (wrapper delegate-invoke) Callback:invoke_void__this__ ()
  at (wrapper delegate-invoke) Callback:invoke_void__this__ ()
  at (wrapper delegate-invoke) Callback:invoke_void__this__ ()
  at Timing0.FixedUpdate () [0x00000] in <filename unknown>:0 
```
Version: 1.1.0 according to kOS.version
Not sure what triggers it as it doesn't always affect the same vehicle.
[KSP.log.zip](https://github.com/KSP-KOS/KOS/files/1101835/KSP.log.zip)

**Comment by hvacengi** [comment]
It's possible this could be related to #2051.  I haven't read through the entirety of your log file yet, but the first instance of this timing issue appears to occur immediately after the ship docks.  In which case it's possible that the `parentVessel` method is null even though it shouldn't be, or that the event didn't properly get unsubscribed.  I'm not sure why you seem to get an ever increasing number of wrapper delegates in the middle of the execution, but we'll look into it.  `parentVessel` is the only thing that isn't null checked (why would we, it should only be null when `Timing0` isn't subscribed).  We'll have to add more null checks and verify that the events are properly getting unsubscribed.

**Comment by jrens** [comment]
I'm not 100% certain that it is docking, unless that could persist across scene changes. The last massive stream of errors came from one ship approaching the other pre docking. I've certainly had this happen at a ground base which I can't dock with.
Let me know if I can collect any other info for you.

**Comment by hvacengi** [comment]
If it doesn't seem to necessarily be related to docking, and you have a quick save where this is readily reproducible (and a list of required mods) that would cut down on my time to check out the error.  I can debug kOS/KSP while they are actually running, and observe exactly what order the various steps are being executed.  

Otherwise, I'll have to just shoot in the dark.  Does the error happen fairly regularly for you, such that I could give you a test build of KSP to see if it fixes the issue?

**Comment by jrens** [comment]
Only recently noticed the framerate hit was because of the log spam. I'm tailing the log files so as soon as I spot something I'll quicksave and send that your way.
Would be handy to have a debug log with filename / line numbers.
Just had a thought (trying to read the code). As far as I know all instances have occurred with multiple ships involved though not necessarily docked. Is it possible switching between ships could cause it to skip OnAwake?

**Comment by hvacengi** [comment]
At first glance it looks as if it's more likely that KSP calls `OnDestroy` but then keep using the same reference to our vessel module.  We check `parentVessel.loaded` before hooking events.  So if the event is firing, `parentVessel` referenced a real value at some point in the object's life cycle.  The only problem there is that `UnHookEvents` should have also been called from `OnDestroy` which would prevent the timer event from executing.

Maybe it means that KSP is changing the vessel type in between creation and destruction.  We could fix that by adding a boolean `signalHackEnabled`, set when hooking events, that we check instead of the vessel type when unhooking.

**Comment by jrens** [comment]
Again two ships. Was on eva.
[savefile.zip](https://github.com/KSP-KOS/KOS/files/1114416/savefile.zip)

**Comment by Mihara** [comment]
I'm experiencing the same problem as well. The interesting part is that there are no kOS CPUs anywhere in the vicinity every time the issue pops up.

In my case, it seems to be at least somewhat related to EVS getting locked up -- clicking on anything causes a vessel switch...

**Comment by hvacengi** [comment]
Tomorrow I'll post a link to a compiled version of the pull request I just posted (see above).  If you two would be able to test and verify it fixes the issue for your instances, I would appreciate it.

**Comment by Dunbaratu** [comment]
> Tomorrow I'll post a link to a compiled version of the pull request I just posted

This pull request is a hard one for me to test because it's a timing/race issue, where "it doesn't break when I try it" isn't proof in the slightest that the fix did anything.

I'd like to wait for that test from the person who *did* have the issue before merging the pull request.

**Comment by jrens** [comment]
Happy to test. I get it fairly regularly and I now know what I'm looking for.

**Comment by hvacengi** [comment]
https://dl.dropboxusercontent.com/u/19195825/kOS/Releases/kOS-v1.1.2.1beta.zip

That should be the develop branch plus the changes from my PR.  @jrens let me know if this seems to work for you.
