### ISSUE TITLE
Errors creating a gui element with a value from a lexicon and assigning a callback in one command.

### ISSUE THREAD

**Issue by poisonbl** [KSP-KOS/KOS#2079]
Below is a simplistic example of what I'm seeing here attempting to create a button, assign the callback in the same command, while sourcing the button text from a lexicon. It also has the two workarounds I found to get past it (which will hopefully help make sense of what it's doing weirdly).

edit: note, tested on kOS v1.1.0 here, haven't tried newer yet.

```
function lex_where_string {
  local l is lex("label","Hello World").
  local g is gui(200,200).
  local callback is { print "Hello!". clearguis(). set done to true. }.
  // Cannot use Lexicon where String is needed
  set g:addbutton(l["label"]):onclick to callback.
  //                ^
  g:show().
}

function too_many_args {
  local l is lex("label","Hello World").
  local g is gui(200,200).
  local callback is { print "Hello!". clearguis(). set done to true. }.
  // Incorrect number of arguments. Expected 1 argument but found 2.
  set g:addbutton(l["label"]:tostring()):onclick to callback.
  //                                  ^
  g:show().
}

function workaround_1 {
  local l is lex("label","Hello World").
  local g is gui(200,200).
  local callback is { print "Hello!". clearguis(). set done to true. }.
  // Break the value out of the Lexicon.
  local val is l["label"].
  set g:addbutton(val):onclick to callback.
  g:show().
}

function workaround_2 {
  local l is lex("label","Hello World").
  local g is gui(200,200).
  local callback is { print "Hello!". clearguis(). set done to true. }.
  // Break the callback asignment out to its own command.
  local field is g:addbutton(l["label"]).
  set field:onclick to callback.
  g:show().
}

// And to call each:
lex_where_string().
too_many_args().
workaround_1().
workaround_2().
set done to false.
wait until done.
```

**Comment by Dunbaratu** [comment]
This one is weird.
When it encounters the source code ``L["label"]``, this is what the compiler generates in all cases except the problem case:
```
push $l 
push label 
getindex 
call <indirect> 
```
But specifically in the problem case and the problem case only, it's generating this:
```
push $l 
push label 
call <indirect> 
```
(The getindex instruction is missing).
I think it might be related to the fact that it's part of the lefthand side of a SET expression instead of a get instruction, but I'm having a hard time finding somewhere else besides the GUI system where we can do anything of the form to test this on:

``set thing:method( collection[index] ):suffix to value.``

**Comment by Dunbaratu** [comment]
The reason for my suspicion is this part of ``Compiler.cs``:
```
                if (!(compilingSetDestination && isLastIndex) || (!atEnd))
                {
                    AddOpcode(new OpcodeGetIndex());
                }
```
That's literally the only place in the entire compiler where the string ``OpcodeGetIndex`` appears, so it's the only place such an instruction ever gets created.  And it has this check for ``compilingSetDestination`` in it, which is probably causing it to get skipped.

Now I need to figure out why on earth I put that in there in the first place (what was the case it was trying to fix).  I suspect it was there to fix the case of ``set thing[index] to value.`` where the indexed thing was the thing being set (rather than part of the expression that eventually gets to the thing being set, as is happening here).
