### ISSUE TITLE
Controls not really neutral?

### ISSUE THREAD

**Issue by marccardinal** [KSP-KOS/KOS#2092]
I have a control program that ends with the following:

```
set ship:control:translation to v(0,0,0).
set ship:control:rotation to v(0,0,0).
unlock all.
set ship:control:neutralize to true.
rcs off.

print "Waiting for neutral".
until ship:control:neutral { }
print "Ship is neutral".
  
wait until false.
```

Except at the end of the program, after a while in `wait until false`, it looks like kOS is inducing a yaw to the ship and it starts spinning. If I hit ctrl-c it goes back to neutral.

If the control are neutral, why would kOS be affecting my yaw?

**Comment by Dunbaratu** [comment]
What happens if you replace ``unlock all`` with an explicit ``unlock steering`` ?
I've seen problems with ``unlock all`` in the past not doing what it should.

**Comment by hvacengi** [comment]
Unlock all shouldn't really have any effect, I don't think.  Not unless you have a `lock steering` somewhere earlier in the script.

But doing anything with the `neutralize` suffix should reset all of the controls.  Can you also try printing the value of `ship:control:yaw` after controls were neutralized?

How do you mean "kOS is inducing a yaw to the ship and it starts spinning".  Does the yaw UI slider visibly move to show you the yaw, or do you just see the ship spinning faster and faster until you press `ctrl+c`?

Since I'm in the middle of modifying other parts of this logic already, I might as well see if I can fix this at the same time.

**Comment by marccardinal** [comment]
I did a few experiments yesterday and might have found the cause of the issue. I have been working on an auto docking script and it looks like if there is any RCS activity at the time of docking it will impact the vessel in a hidden way. My guess is that when that happens at the time that the vessels get treated as one then kos might think that everything is neutral while its not.

My work around is to simply drift for the last meter... so this might not be an issue worth solving at the moment.

**Comment by hvacengi** [comment]
That's interesting.  I wonder if it means that our control object is causing the issue, or if it's some how being broken by KSP itself.  I could see an instance where our control object doesn't let go of the controls, and then it becomes inaccessible because that "vessel" doesn't exist anymore.  In that case, the fix I'm working on for better handling of the vessel docking/staging/reverting may fix this issue too.  If it's something cause by KSP itself I don't know how we would end up fixing it.

After the next release, I may ask you to test your script that caused the issue and see if it gets fixed.

**Comment by marccardinal** [comment]
Certainly! Looking forward to it.

**Comment by pand5461** [comment]
A workaround may be to release controls once target is within the acquirerange of the docking port or when port status changes to "PreAttached". That way you're sure that vessels are really going to dock.
Or reboot after docking.

**Comment by marccardinal** [comment]
Indeed, I have setup a coasting phase where I release all controls prior to docking and that seems to be working well.
