### ISSUE TITLE
All Opcodes should have a summary comment including stack effect

### ISSUE THREAD

**Issue by tsholmes** [KSP-KOS/KOS#2187]
This will make it easy to see what each opcode does without having to read through the code.

**Comment by Dunbaratu** [comment]
Just to add a few more descriptions from the discussion in the slack:

The minimum information each comment needs is:

- Effect on the stack, as portrayed by "here's what the top of the stack should have on it before this executes, and here's what the top of the stack will have on it after this executes."  (Note that if the opcode merely peeks at a value on the stack instead of popping it, this is unusual enough that it needs to be explicitly mentioned in text - merely showing the same thing on the "before" and "after" pictures doesn't necessarily make this clear that it's the exact same thing.  (It might look like it was consumed and replaced with a similarly named thing if it wasn't explicitly called out that it's just a peek.))
- Arguments (anything that is an ``[MLField]``) and what they mean.

**Comment by Dunbaratu** [comment]
We should also look into what (if any) tagging in the XML would guarantee that the stack picture doesn't just word-wrap in with the rest of the text, since ``<br/>`` doesn't seem to always be obeyed.  I'm sure there's a spec for it somewhere and hopefully it mentions something we can use.
