### ISSUE TITLE
WHEN statement not working in ANONYMOUS functions

### ISSUE THREAD

**Issue by lucaelin** [KSP-KOS/KOS#2228]
First of all, thank you for such a wunderful mod! I've had quite a lot of fun with it recently!

But while extending my library today, I noticed the following code would not print "hi":
```
set f to {
  when true then {
    print "hi".
  }
}.
f().
wait until false.
```
On the other hand, this one does:
```
function f {
  when true then {
    print "hi".
  }
}.
f().
wait until false.
```
And even this does work:
```
function f {
  when true then {
    print "hi".
  }
}.
set x to f@.
x().
wait until false.
```

Is there a reason for this, that I'm just unable to comprehend, or is there something broken?
Thanks a lot for your time and effort!

**Comment by Dunbaratu** [comment]
I think this is due to this section in ``kOS.Safe/Compilation/KS/Compiler.ks`` :+1: 
```
        private void PreProcessStatements(ParseNode node)
        {

            lastNode = node;

            NodeStartHousekeeping(node);

            switch (node.Token.Type)
            {
                // statements that can have a lock inside
                case TokenType.Start:
                case TokenType.instruction_block:
                case TokenType.instruction:
                case TokenType.if_stmt:
                case TokenType.fromloop_stmt:
                case TokenType.until_stmt:
                case TokenType.for_stmt:
                case TokenType.declare_function_clause:
                case TokenType.declare_stmt:
                    PreProcessChildNodes(node);
                    break;
                case TokenType.on_stmt:
                    PreProcessChildNodes(node);
                    PreProcessOnStatement(node);
                    break;
                case TokenType.when_stmt:
                    PreProcessChildNodes(node);
                    PreProcessWhenStatement(node);
                    break;
            }
        }
```
Because anonymous delegates are essentially assignment statements (set foo to expr, where expr is the anonymous delegate body), this tree walk fails to descend far enough to find the expr of "set foo to expr" to hit the point where it runs PreProcessWhenStatement(node) on that part.

The fix may be to just simply have this method descend all the way to the leaf nodes of the compiler rather than trying to cut off the search at certain parts of speech like it does now, ignoring whatever speed penalty that might incur (if any), since with anonymous delegates, ANY EXPRESSION could be a chunk of code, and thus the when statement could appear at any depth down the parse tree.
