### ISSUE TITLE
Error after program quit if both interpreter and program have "lock steering".

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2356]
(This is messy.)

Lock Steering from the interpreter interfers with Lock Steering from a program, if Lock Steering is left on while the program is invoked, and the program does its own Lock Steering.

Interestingly, the error is only thrown when the program ENDS, not while it's running.

To re-create it, use any craft at all.  Make a program that contains a lock steering, EVEN IF that lock steering is never actually invoked, as in the example below:
Make the following small example program:
**Filename "test_bug.ks"**:
```
// ______ filename test_bug.ks ______
print "---program starting---".
wait 5.
print "---program ending---".
if false {
  // Note this line NEVER actually runs because it's in an "if false",
  // but its presence still causes the bug, probably because of how
  // the compiler builds the boilerplate for it at the top of the opcodes:
  lock steering to north.
}
```
Then at the interpreter, run these things in this order:
```
lock steering to heading(90,0). wait 2. run test_bug.ks.
```
This causes you to see:
```
---program starting---
---program ending---
Program ended.
```
(as expected), but then as soon as the program ends, it does this:
```
lock steering to heading(90,0). wait 2. run test_bug.
                                         ^

 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

kOS.Safe.Exceptions.KOSNotInvokableException: Attempted to make a function call on a non-invokable object:
   steering
  at kOS.Safe.Execution.CPU.GetVariable (System.String identifier, Boolean barewordOkay, Boolean failOkay) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Execution.CPU.GetValue (System.Object testValue, Boolean barewordOkay) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Compilation.OpcodeCall.StaticExecute (ICpu cpu, Boolean direct, System.Object destination, Boolean calledFromKOSDelegateCall) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Compilation.OpcodeCall.Execute (ICpu cpu) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Execution.CPU.ExecuteInstruction (kOS.Safe.Execution.ProgramContext context, Boolean doProfiling) [0x00000] in <filename unknown>:0 
```

There are things in place to prevent a delegate from a "stale" program context from getting called.  Those protections are being triggered  in some way as the program ends and returns control back to the interpreter.

Note, the interpreter's steering updater ``$steering*`` function is NOT being called while the program is running (this seems correct), but as soon as the program ends, it tries calling it again and it complains like this.

**Comment by Dunbaratu** [comment]
During the same run that I had these problems, I also had this weird effect earlier, doing something similar (having an interpreter's lock steering active when a program got invoked):
I had done this (note, the actual land_it_vary program is kind of complex, so I don't know if I want to post it here since I'm not 100% sure it's the same bug):
```
lock steering to srfretrograde. wait until altitude < 20_000. stage. run land_it_vary(2,0,0,0.01,0.8,spot).
```
Without giving all the details, ``land_it_vary`` is a complex lander program that ends when the ship lands.

What I saw happen was this:  After land_it_vary had landed (kOS's standard "Program Ended" message had printed), a few seconds later all of a sudden the ship **throttled up again and took off, even though no program was running**.  The behavior of the throttle was not fixed when it did this.  It was wavering up and down in *exactly* the way it normally did under the PID control of the script.  I know it seems impossible, but it was acting as if it was running some parts of the program again, but not quite correctly.  

I wonder if it may be the same bug - if there's a race condition if the call to ``$steering*`` happens right when the program ends when switching from the program context to the interpreter context where things might be in a sort of in-between state where not everything is cleaned up yet.

Normal behaviour:  When the program ends and switches back to interpreter context, the lock steering that was in the interpreter context re-asserts itself.  (The interpreter's ``$steering*`` and ``$throttle`` updater triggers start being invoked again, when they weren't during the program's run).  Maybe when the interpreter's ``$steering*`` trigger gets invoked again right after the program ends, the global ``$steering*`` variable is still set to something from the old program's code instead of the interpreter's code.  If the ``$steering*`` is keeping some reference pointing to the old program context, it wouldn't garbage collect properly and the list of opcodes might still be present and getting invoked by the ``$steering*`` call that's jumping the instruction pointer to some random junk spot of the old program's code.  The behaviour I was seeing was baffling and could only be explained by old program code being executed again after the program had quit.  Maybe this was why??

**Comment by evandisoft** [comment]
When I comment out:
if (userFuncObject.IsSystemLock()) 
      BuildSystemTrigger(userFuncObject);

At Compiler.cs at line 595, the bug stops happening
I don't fully understand the code yet, but this might be helpful or might not.

**Comment by evandisoft** [comment]
Disclaimer: I spent all day on this. Now I'm certain I know how it works.

I think this part in CPU.cs is the deal:
in function RestorePointers() in CPU.cs
```C#
if (globalVariables.Contains(item.Key))
{
    // if the pointer exists it means it was redefined from inside a program
    // and it's going to be invalid outside of it, so we remove it
    globalVariables.Remove(item.Key);
    deletedPointers++;
    // also remove the corresponding trigger if exists
    if (item.Value.Value is int)
        RemoveTrigger((int)item.Value.Value, 0);
}
```

Systemlocks (throttle/steering) are "system pointers". They are intended to only be stored globally. When you create a  new context, the old "pointers" are saved. When you go back to the old context, if you have any globals matching any old pointers, all the old pointers are destroyed.

So when I disabled that if clause it "worked". However, it wouldn't work in general. Without that if clause, a third layer of nesting would erase your outmost pointers. **I think the behavior you want requires a scoping mechanism." This is a mechanism that relies on variables having a "*" suffix and then getting copied over manually to another scope. That wasn't readily apparent to be part of the architecture.

Also, the reason the "lock" in the disabled "if" clause worked anyway is because the entire parsed tree gets "preprocessed" in Compile.cs/PreProcess() and when that happens a 'store $steering*' was being called before the program even started running it's main body. This created a new global variable since "steering" is a "systemlock" and all of them are supposed to be stored globally. It assigned $steering* a dummy value because all variables have to be assigned something when initialized. (As the comments state).

Here's the kRISK for the following simple program:
```
if false {
  lock steering to heading(10,0).
}
```
```Assembly
, jump +21, 
@0001, pushscope 1 0, 
@0002, push _KOSArgMarker_, 
@0003, push _KOSArgMarker_, 
@0004, push opcodetest, 
@0005, push null, 
@0006, call run(), 
, jump +40, 
@0010, push $steering*, 
@0011, exists, 
@0012, br.true +3, 
@0013, push 28, 
@0014, store $steering*, 
@0025, pushscope 1 0, 
@0026, argbottom, 
@0027, push False, 
@0028, br.false +12, 
@0040, popscope 1, 
, pop, 
, EOP, 
@0007, pop, 
@0008, pop, 
@0009, popscope 1, 
```
"@0014, store $steering*" is the reason that happens. 


When I replaced the OpcodeStore with an OpcodePop, it stopped happening. But I don't know what kind of side effects there might be.

I'd be happy to work on these issues if you want. I understand the general system now. I have some knowledge of these types of things. And it's a large part of why I'm interested in this project, and why I spend all day on this. I also used this project a lot and ran into a lot of these weird behaviors and I think they can be fixed.

**Comment by evandisoft** [comment]
Also, I'd love to chat with some of the maintainers about this stuff, and the project in general!

**Comment by evandisoft** [comment]
I didn't fully understand the "trigger" system when I made that big comment. But in a simple test, with the problem "if" statement disabled, with a `lock steering to heading(90,0). run steeringtest.`, where `steeringtest` calls a steeringtest2, it locks steering seemingly properly in each file and appears to return back to being locked by the original.

**Comment by evandisoft** [comment]
So I figured out that the attempt to remove the trigger in "RestorePointers" doesn't work. The trigger remains. The `item.Value.Value` in the `if (item.Value.Value is int)` is actually `UserDelegate(cpu=kOS.Safe.Execution.CPU, entryPoint=21, Closure=System.Collections.Generic.List`1[kOS.Safe.Execution.VariableScope],
   KOSDelegate())`

So it doesn't remove the trigger that is associated with the system lock. But it does remove the global variable. The trigger that remains then calls the global $steering* variable, but since the old global $steering* variable from the 'test_bug.ks' context is removed and since the global $steering* variable saved in "savedPointers" is not added back in, it calls an undefined variable as a function.
