### ISSUE TITLE
Add a function to recompile a file

### ISSUE THREAD

**Issue by Mindeufair** [KSP-KOS/KOS#2365]
The first big program I did on that mod is a file explorer, but it loss a part of its utility because when I modifie a file, I have to quit and manually restart the explorer, because it can't recompile the file.

So do you can add a function to recompile a file during the running of a program, or to "forget" the already compiled ones ?

PS : sorry for my english if it is not really good, I'm french.

**Comment by Dunbaratu** [comment]
What might make the most sense is a second version of runpath that has a "force compile" option.  The hard part about trying to add it to the existing runpath() is that runpath() is *already* a varying-number-of-arguments command because it passes the arguments to the program.  So there's nowhere to put the optional argument that won't end up being interpreted as an argument to the program itself.

In the meantime, for a workaround, what happens if you use the "compile" command instead of "run"?  Will it recompile a new KSM file if run a second time, and can you run that KSM file?  Let me know if that also has the same problem.

**Comment by Mindeufair** [comment]
Yes, a second version of runpath() is probably much better than what I said.

Anyway I will try your idea, thanks ^^

**Comment by Mindeufair** [comment]
But I ask me, how the mod keeps in memory the programs already opened and compiled, do it use a sort of liste ? Is there a way to see it, or to clean it ?

**Comment by Dunbaratu** [comment]
This is the current way it works, although there has been a lot of discussion about changing it, and this might not permanently be like this:

When you run a program from the interpreter, that starts a new "program context".  The interpreter and the program it runs are two different "program contexts" that don't share any code.  When the program you run ends, its "program context" gets thrown away (which is why you can't call function built in a program after that program ends and you're back in the interpreter - those functions are deleted at that point.)

But, when you run a program from *another program* instead of from the *interpreter*, that's different.  When you run a program from *another program*, then the second program lives inside the *same* "program context" as the program that ran it.  The compiler appends the second program's instructions to the end of the first program's list of instructions, so they form one concatenated list.  That is why the first program can jump into functions the second program created, and thus the second program can behave like a library for the first program.

But that also means that it's not desirable to re-compile the second program when it's run again from the same parent program, because in addition to taking time, that would end up appending its compiled content a second time, bloating the list if the RUN statement is in a loop, OR it would require a system by which chunks of compiled instructions can be relocated so the old copy could be deleted, the empty space reclaimed, and the new copy could be appended to the end again.  Such a system doesn't currently exist (it means having to make entry points for functions re-locatable after they move to a new spot in the instruction list).

A lot of this may end up changing eventually.  There is talk of getting rid of the system in which all programs run from a parent program live in the same list, and instead going to a system where each program is just a separate list so they can be deleted or moved no problem.  But for *now*, that's not something supported.

**Comment by Mindeufair** [comment]
Okay, thank you very much for these explanations

**Comment by Mindeufair** [comment]
So, that worked ! Thank you for your time and your help ^^
