### ISSUE TITLE
ship:patches documentation is either misleading or is bugged

### ISSUE THREAD

**Issue by ddejohn** [KSP-KOS/KOS#2406]
I'm unsure if this is a bug with `ship:patches` or if the documentation is incorrect/misleading, hence the title.

**To reproduce:** get in an orbit with multiple patches, then `print ship:patches.`

This returns a list of all of the ship's patches like so:
```
LIST of n items:
[0] = "ORBIT of <unnamed>"
[1] = "ORBIT of <unnamed>"
[2] = "ORBIT of <unnamed>"
.
.
.
[n-1] = "ORBIT of <unnamed>"
```
[From the docs](https://ksp-kos.github.io/KOS/structures/vessels/vessel.html#attribute:VESSEL:PATCHES), I don't think this is the intended behavior:

"The list of orbit patches that describe this vessel’s current travel path based on momentum alone with no thrusting changes. If the current path has no transitions to other bodies, then this will be a list of only one orbit. **If the current path intersects other bodies, then this will be a list describing the transitions into and out of the intersecting body’s sphere of influence.**"

Emphasis mine. The list of patches returned contains no useful information beyond the number of patches. It is only through the use of patch suffixes that any information can be gleaned.

**Comment by Dunbaratu** [comment]
There's no bug in ``orbit:patches``.  It's doing its job correctly and acting as described.  It's a list of orbits that describes the transitions.  The fact that you have to look at suffixes within the items of the list to see that isn't wrong.  The TOSTRING of an object (what you get when you PRINT it) is never intended to be the canonical list of all its fields.  It's a summary of just a small subset of what's in the object.

That being said, an argument could easily be made that the name of the SoI body is one of the things that always belongs in the TOSTRING() of an Orbit.  But that's a far cry from claiming this is a bug or incorrect documentation.  That would be an enhancement.  ("Enhancement" = "What is there now is correct, but it needs to do more to be more useful.")

What's happening is that when an orbit patch comes from an actual object currently in orbit right now, it gets the body name populated into the TOSTRING result.  When an orbit patch comes from a hypothetical future, then it does not (because under the hood, the API provided by Squad makes that name harder to get to in that case).

It could be done, though.  Because although the orbit patch itself has no name in this case (for some reason you'd have to ask SQUAD about), it does mention which body it is orbiting, so the name could be indirectly found and copied up to the orbit object.
