### ISSUE TITLE
constant:g different from what ksp uses internally

### ISSUE THREAD

**Issue by plonk75** [KSP-KOS/KOS#2409]
In kOS 1.1.5.2 running in KSP 1.4.5, `constant:g` returns a value of 6.7384E-11, which does not match the value KSP seems to use during its calculations. This resulted in my calculated SMAs of LKOs beeing about 20m off the value KSP's map was showing via `vessel("_name_"):orbit:semimajoraxis`, and a slightly off orbital period (some 1/100s per orbit). 
Using the value from KSP (e.g. sun:mu/sun:mass) yields results, that pretty much match those of KSP.

How to reproduce in a terminal screen:
```
print constant:g.
6.67384E-11
print body("sun"):mu/body("sun"):mass. // "sun" can be changed to the name of any celestial body
6.67408E-11
```
According to https://en.wikipedia.org/wiki/Gravitational_constant#Modern_value KSP is using the "better" value of G. 
Althoug the error is small, it affects all my calculations based on the calculated SMA, and accumulates when used to calculate a sequence of multiple maneuvers without KSP's maneuver nodes.

Wouldn't it make sense to always get this value directly from KSP during some init phase, so it's always consistent with KSP?

**Comment by Dunbaratu** [comment]
> Wouldn't it make sense to always get this value directly from KSP during some init phase, so it's always consistent with KSP?

Of course it would.  You know what else would make sense?  If Squad actually documented where the heck it IS in their system so I can use their value instead of a hardcoded literal.

Back when I first added Constant:g this is exactly what I was trying to do, taking the attitude that it doesn't matter if the game's idea of g is right or wrong - the game's idea of g is what is being used inside the Kerbal universe, so it's the value scripts need.

And I could never find it in Kerbal's classes.

If you know where the heck they put it, then I can use it from the game.

**Comment by Dunbaratu** [comment]
I suppose if they won't expose their "G" directly, I could always do what you did - derive it from some randomly chosen body's mu and mass - do that during initialization and store the result.

**Comment by plonk75** [comment]
Oh. That was quick. Thank you, guys! Looking forward for the next release.
@Dunbaratu : I didn't mean to smart-ass around by suggesting the obvious. I'm a sw-dev myself (but not a  KSP modder), and I know that it can be annoying when people do that. Sorry if the remark spontaneously raised your blood pressure. Otoh, now this issue is probably fixed for good. :D Thank you!
