### ISSUE TITLE
Expose 'g' (lowercase) through constant:

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2413]
We expose G (uppercase, Newton's Universal Gravatational Constant) through the ``constant:G`` technique.
We do this because the game's idea of G might be a bit off from a textbook's idea.  The official standard value according to NIST keeps changing every few years as better measurements get made.  And it's the game's idea that matters in kOS, not the value you read from a textbook or website.  I recently made a PR that calculates it from the game itself.

But we don't expose g (lowercase, acceleration due to gravity at sea level on Earth/Kerbin).

We probably should expose it, for the same  reason - because the value the game uses is what matters in things like ISP calculations, not the value that may be printed in this textbook or that.

One problem with implementing this is kOS's case-insensitive nature, and backward compatibility.  We already called Newtons' gravitational constant by the name ``constant:G`` so we can't call accel at sea level ``constant:g`` because that's the same "spelling".

**Comment by plonk75** [comment]
That's an excellent idea! To solve the naming dilemma: a very common notation for earth's standard gravitational acceleration is g0. 

I think there's some confusion out there, since g0 is, opposed to G, not really a constant, but more of a convention and kind of "for earth(ling) use only". If I understand correctly, it only "sneaks in" to KSP via the ISP of engines. And exposing exactly this g0 to kOS would help reducing the confusion which value to choose.

When searching the internet for "the right value" in a KSP context, I've found some different points of view, stating values from 9.80665 to 9.82. The first can be found in the KSP Wiki (https://wiki.kerbalspaceprogram.com/wiki/Specific_impulse), while e.g. many forum posts (and my old scripts, too) refer to kerbin:mu/kerbin:radius^2 (=9.81), without considering centrifugal forces. Btw, the KSP Wiki has been updated in August 2017 (formely stating 9.81m/s^-2).

Inspired by this issue, and the uncertainty which value to use, I decided to try and get the value from kOS somehow, and learned that it is no as simple, as it might seem. You get different results depending on what you look at, just like during my internet inquiries. You can take the masses, distances and rotations and calculate a value from that. E.g.: 
```
local surfVelEquator is 2 * constant:pi * kerbin:radius / kerbin:rotationperiod. // [m/s]
local gPoles is kerbin:mu / kerbin:radius^2. // 9.81 [ms^-2]
local gEquator is gPoles - surfVelEquator^2 / kerbin:radius. // 9.75899184596805 [ms^-2]
local g45 is gPoles - (cos(45) * surfVelEquator)^2 / kerbin:radius. // 9.78449592298402[ms^-2]
```
While I'd use this way to calculate actual g-forces, it turns out, that this has apparently nothing to do with the value intertwined in the engines' ISP. Further, I don't expect the difference is due to earths tiny oblateness - since it is tiny (I maybe wrong).  
So, to get this g0 from the engines, I've built a "spacecraft" by slapping a couple of engines and a kOS processor  onto a tank, and measure fuelflow, massloss and maxthrust while burning an engine in vacuum. 
While at it, I wanted to eliminate another magic number, the fuel density of 5kg/unit, which proved plausible. The experiment results in values for g0 around 9.806, with some outliers (Dawn Ion Engine and Ant LF Engine, see attached .csv file). Obtaining some stats from OpenOffice gives a median of 9.806678..., which is pretty close to the commonly accepted earth value of 9.80665. 
This is the value I'd use, if there's no "better", or "better matching KSP" value at hand. Sadly, to get it, it seems one has to do engine burns in vacuum.

So, that's why in my opinion the g0 value to expose as a kOS constant should be that of 9.80665. But now I wonder, if it is actually exposed to mods. Calculating G from Mu during mod initialisation is easy, but I imagine burning an engine is not. And since it is "hidden" in the ISP, I can imagine that it's possibly not even explicitly required for KSP's internal calculations. 

In case anyone wants to verify or modify, you'll find attached a zip containing the experiment, consisting of an all stock except kOS spacecraft to be cheated into a high orbit, the script (g0.ksp), and the results I get on my machine, KSP 1.4.5 / kOS 1.1.5.2 (g0_report.csv). 
The script outputs a file named `g0_report.csv` for use in a spreadsheet application. 
**Caution**: The script overwrites an existing file at `"0:/g0-report.csv"`.

Hope this post is of any use. Corrections are of course very welcome.

[KSP_g0.zip](https://github.com/KSP-KOS/KOS/files/2799193/KSP_g0.zip)

Earthlings' sources:
https://en.wikipedia.org/wiki/Standard_gravity
https://en.wikipedia.org/wiki/Gravitational_acceleration
http://www.braeunig.us/space/propuls.htm#Isp
[leaving out non english sources]

Kerbals' sources:
https://wiki.kerbalspaceprogram.com/wiki/Specific_impulse#Definition
https://wiki.kerbalspaceprogram.com/index.php?title=Specific_impulse&action=history
the KSP Forum

**Comment by Dunbaratu** [comment]
Unlike gravitational constant, the g0 value is actually in the games' PhysicsGlobals.  I don't need to guess the value they're using because they expose it.
