### ISSUE TITLE
ship:maxthrust is broken in latest release

### ISSUE THREAD

**Issue by Defaultldentity** [KSP-KOS/KOS#2422]
It looks like SHIP:MAXTHRUST now returns thrust at zero air pressure, instead of thrust at current pressure as it's used to be and supposed to be in the docs.

```
print ship:maxthrust.
214.999984741211
print ship:maxthrustat(0).
214.999984741211
print ship:maxthrustat(body:atm:altitudepressure(altitude)).
168.421600341797
```

**Comment by firda-cze** [comment]
Looks like I broke it when modifying [`EngineValue`](https://github.com/KSP-KOS/KOS/blob/84780d58e56204cecedc4ed472cfc47dfcbd29fb/src/kOS/Suffixed/Part/EngineValue.cs#L263) because I did not know about [`VesselUtils.GetMaxThrust`](https://github.com/KSP-KOS/KOS/blob/84780d58e56204cecedc4ed472cfc47dfcbd29fb/src/kOS/Utilities/VesselUtils.cs#L105) using `double atmPressure = -1.0` as some kind of special value with undocumented meaning. (Or did I miss some note?) It is passed to [`GetIsp`](https://github.com/KSP-KOS/KOS/blob/84780d58e56204cecedc4ed472cfc47dfcbd29fb/src/kOS/Suffixed/Part/EngineValue.cs#L285) which passes it to `engine.atmosphereCurve.Evaluate((float)staticPressureAtm)` and I have no idea what that does with `-1.0`.

P.S.: I am strongly against such *special values*, it should have been either `double? atmPressure = null` or `double atmPressure = double.NaN` (voting for the first, it is obvious: optional argument).
