### ISSUE TITLE
homeconnection:isconnected() throws nullref when ship is "debris" type.

### ISSUE THREAD

**Issue by Defaultldentity** [KSP-KOS/KOS#2443]
homeconnection:isconnected() crashes when there is no ModuleCommand on the ship, regardless of having antennas. Instead it should probably return false (or true, if having an antenna connection - questionable tho).

### Reproduce:

1. KSP 1.6.1, start_on_archive = false, CommNet enabled, CommNet connection manager is active

2. Build a ship of a sinlge part (any kOS module, KR-2042 in my case). Put the following boot script:
```
core:doevent("open terminal").
print homeconnection. // works just fine
print homeconnection:isconnected(). // this fails
```

3. Launch. The output is as this:
```
Connection: ""
Object reference not set to an instance of an object
At 1:/boot/_test.ks, line 3
print homeconnection:isconnected().
      ^
Called from [Boot sequence], line 1
run "/boot/_test.ks".
    ^
```

**Comment by Dunbaratu** [comment]
### Debris Type:

I did some testing of different edge cases and the conclusion I've drawn is this:  The problem is triggered by the vessel being of type "Debris", NOT by the probe core or lack thereof (the probe core just has the side effect of changing whether the vessel is "Debris" or not when it's created on the launchpad).

Here's a test case that proves this:

- Build this craft: 1 battery, 1 omni-antenna, 1 kOS probe core, 1 Mk1 command pod WITHOUT a crew member on board (so the vessel is uncontrollable, uncrewed).
- In the VAB, select the boot file onboard that is mentioned above in the first post of this issue.
- Launch
- You do NOT get the error.  It works fine.
- Rightclick the Mk1 command pod, select "rename vessel", and change the vessel category from "ship" to "debris" type.  Leave the name alone - just change the type.
- Cause a reboot by leaving the scene and then reloading the ship (you don't have crew, so you can't directly command a reboot.)
- Now you get the error.
- Rightclick the Mk1 command pod, select "rename vessel", and change the vessel category back from "debris" to "ship" again.
- Cause a reboot by leaving the scene and then reloading the ship (you don't have crew, so you can't directly command a reboot.)
- Now you do NOT get the error.

The error only happens when the ship is categorized as "debris" type.

**Comment by Dunbaratu** [comment]
I'm going to change the title of the issue, to reflect this testing result.

**Comment by Dunbaratu** [comment]
@Defaultldentity : Technically, if you want it to be possible for a connection to exist on a "debris" vessel, it's literally impossible for us to do that because it's a "feature" of Stock Comms that all debris vessels lack the properties needed to participate in the Commnet system.  (They're null because the stock game won't populate them for debris.)  However, we can at least catch the case and prevent it from throwing a nullref error when it happens so your script can detect the lack of connection and not crash.
