### ISSUE TITLE
Wrong conversion for PartModuleField values using Robotic Parts

### ISSUE THREAD

**Issue by lucaelin** [KSP-KOS/KOS#2531]
Trying to set the PartModuleFields for the DLCs robotic parts (ie. Target Angle), causes values to be clamped between 0 and 100 and rounded to the nearest integer. This is wrong for most sliders in the new DLC.

Cause of the issue seems to be https://github.com/KSP-KOS/KOS/blob/d6258fad1c4a35e2fa3b885e3fc0879b9c140ca3/src/kOS/Suffixed/PartModuleField/PartModuleFields.cs#L174

`UI_FloatRange` claims that its range is always 0 to 100 with a step-size of 1.

Ignoring the clamp entirely seem to fix the issue and still cause values to be properly converted to the UIs possible values, maybe Squad moved the logic from the UI to the actual API, causing this step to be unnecessary on kOSs side?

**Comment by Dunbaratu** [comment]
There was something in their release notes that mentioned changes to sliders on the part action windows, but it was unclear from their one-sentence description in the changelog just how that affects things.  But yes something did change there.

**Comment by Dunbaratu** [comment]
> maybe Squad moved the logic from the UI to the actual API, causing this step to be unnecessary on kOSs side?

Unfortunately no.  I tried disabling that line, and while it allowed the DLC's robotic parts to work fine, it broke OTHER stock things by letting you cheat your way outside the slider range (so the UI is *not* enforcing it elsewhere universally - just the robotic parts are).  For example, after disabling this line I did a test where I set a stock torque wheel's "Wheel Authority" slider to 10000 (it normally goes from 0 to 100), and it totally let me.  Then I could spin a ship to any orientation I like, even on Kerbin, although it took a lot of electricity.  IN other words, the attempt to set the slider to 10000 actually worked, and had the effect of making my torque wheel 100x more powerful than it was supposed to.

So it's not a real solution.  The frustration is that the robot parts just completely broke the rules of how the UI fields work, and they won't care since the UI isn't supposed to be how you interface with the API.  It's just what we do because we are trying not to hardcode a special module for each and every part in the game.
