### ISSUE TITLE
Compiled Kerboscript won't execute "compile" and "runpath"

### ISSUE THREAD

**Issue by mrbandler** [KSP-KOS/KOS#2560]
Hi there,

I am currently working on a Kerboscript Compiler for the CLI, called [**ksc**](https://github.com/mrbandler/ksc). This is mainly so that I don't have to switch back and forth between VS Code and KSP.

Now I wanted to create a feature where I can execute Kerboscripts via the CLI to program compilation and deployment scripts in Kerboscript itself. As all that jazz (https://ksp-kos.github.io/KOS/commands/files.html#file-i-o) is available in Kerboscript.

Sadly, it won't work... I took inspiration on the integration test setup (https://github.com/KSP-KOS/KOS/blob/develop/src/kOS.Safe.Test/Execution/BaseIntegrationTest.cs) with the Noop middleware to the shared objects.

The script executes normally, prints, functions and all other features work but not the stuff that I really need, that is the "COMPILE", "RUNPATH", etc.

My code: https://github.com/mrbandler/ksc/blob/develop/kOS.Cli/Execution/Executer.cs

Is my setup completely wrong, and what is missing?

Thanks in advance!

Greetings,
mrbandler

**Comment by cahe7cb** [comment]
The problem with the `COMPILE` command probably arise from the fact that it currently depends on behavior provided by the KSP engine, specifically it depends on the type initialization executed here: https://github.com/KSP-KOS/KOS/blob/305e22005daea88f4e78ed71b09d10ce550647ff/src/kOS/Module/kOSProcessor.cs#L822

So, with the lack of this initialization, your program is most likely throwing an exception that is being caught here: https://github.com/KSP-KOS/KOS/blob/305e22005daea88f4e78ed71b09d10ce550647ff/src/kOS.Safe/Execution/CPU.cs#L1353

A second problem is that the `COMPILE` command yields the CPU in order to execute asynchronous I/O operations and the method for checking if the CPU is yielded is currently not accessible: https://github.com/KSP-KOS/KOS/blob/305e22005daea88f4e78ed71b09d10ce550647ff/src/kOS.Safe/Execution/CPU.cs#L554

You could try manually initializing the type data that mentioned in the beginning and since it's not possible to query if the CPU is yielded by an I/O operation, the only way would be to blindly call the `Update` methods, for example:

```
do
{
    _shared.UpdateHandler.UpdateObservers(0.1f);
    _shared.UpdateHandler.UpdateFixedObservers(0.1f);
    System.Threading.Thread.Sleep(100);
}
while (_shared.Cpu.InstructionsThisUpdate > 1);
```

But I imagine you will still run into other problems for the `RUNPATH` and etc. functions, as other parts of the code were also not made to be run outside of the KSP engine.

**Comment by mrbandler** [comment]
Sorry, that was my mistake, I already implemented a separate `COMPILE` command for the CLI where I initialized these lines:
```csharp
Opcode.InitMachineCodeData();
CompiledObject.InitTypeData();
SafeSerializationMgr.CheckIDumperStatics();
```
It just bailed on me on the compile case, as I was not using the `CPU` to compile, just the `ScriptHandler`. I should have known that that's the issue. After I added it it worked flawlessly.

I also added the **blindly** call to the update methods, as I don't see it as a big deal in this case, as kOS receives these to execute Kerboscripts from Unity, I am just emulating as best as possible.
After I added this, the `RUNPATH` worked also.

@cahe7cb Thank you very much, I'll close the issue.
