### ISSUE TITLE
Switching keyboard focus from terminal to world takes an extra mouse click

### ISSUE THREAD

**Issue by Brainsample** [KSP-KOS/KOS#2567]
- Launch any scripted ship.
- Left click in the kOS terminal, to put keyboard focus on it.
- Left click the SAS button on the navball.

Observe: Keyboard focus is now in-world, but SAS did not change.
Expected: SAS changes immediately.

Not all UI elements are affected, for example: Hiding the navball works with one click.

**Comment by Brainsample** [comment]
Here's another repro, with ksp 1.7.3.2594 and kOS 1.1.8.0

=======

- Attach a hinge to a scripted ship, and launch.
- Left click the kOS terminal, so it has keyboard focus.
- Try right-dragging in-world, to move the camera.
Observe: The camera doesn't move.

- Right click the hinge.
Observe: The PAW appears, but the autostrut and nametag buttons are missing.

- Left drag the "Target Angle" slider a couple of times.
Observe: The green bar responds, but the hinge itself doesn't move.

- Left click the "Target Angle" slider.
Observe: On mouse down, the slider goes to the clicked value.
On mouse up the slider snaps back to the actual position of the hinge, and the world gets focus.
Also, the missing buttons appear in the PAW.

- Left click the "Target Angle" slider to a low value.
- Left click the "Target Angle" slider to a high value.
- While the hinge is still traversing, click the kOS terminal again.
Observe: The "Current Angle" field in the PAW stops updating as soon as the kOS terminal has focus.

=======

I guess the desired behaviour is when focus changes on mouse down (left or right).

**Comment by Dunbaratu** [comment]
This isn't really under my control.

Unity doesn't TELL kOS about the mouse click unless some other part of the system didn't consume it first.  When you click on a part like the hinge, that part tells Unity "I have already consumed this mouseclick event.  You don't have to tell anyone else about it.  It's done with".  After that Unity won't tell kOS the mouse click happened.

**Comment by Brainsample** [comment]
Hi Dunbaratu,

Thank you for the detailed explanation. I'm relatively new to KSP and kOS, and I don't know where all the happy little mistakes live. :) In this case it is probably best to report on the KSP bug tracker. First I'll do some more research, looking for issues that are clearly not related to kOS.

For example this repro, I might as well post it here:

- Right click a hinge (as an example).
- Click "#" to allow numerical entry.
- Click on a numerical entry field.

Observe: The Autostrut and Nametag buttons disappear from the PAW, and the clicked field does not gain keyboard focus.

- Click the same numerical entry field.
- Edit the field.
- Commit by pressing ENTER.

Observe: The edit is successful, the missing buttons reappear after pressing ENTER.

- Click on a different numerical entry field.

Observe: The same bug occurs again.
However, if we click on the same numerical entry field, it works as expected.

**Comment by Dunbaratu** [comment]
The PAW refusing to update the values when the PAW isn't fully enabled is KSP's fault, not mine.  I have a bug report about it to them.  The actual field under the hood is also not updated.  They put a lot of their field updating code directly in the GUI making it impossible for mods to read it when their GUI isn't active.

**Comment by Dunbaratu** [comment]
This isn't as simple as you're making it out to be.  This isn't about keyboard focus.  It's about KSP's controls locking system that locks out controls at a higher level abstraction than "this key was pressed".  For example, there's a bit flag that says "can't turn on SAS", and a bit flag that says "Can't steer ship" and a bit flag that says "Can't adjust throttle", etc.  THOSE are what is preventing these things from happening until you click outside the kOS terminal.  Unity isn't a full-fledged windowing system that deals with keyboard focus in a fancy stacked window way.  It relies on the underlying game maker to deal with a lot of event clashes.  If KSP wants the "T" key to mean "turn on SAS" and kOS wants the "T" key to mean "type a letter 'T' into the terminal", it's not sufficient to merely have kOS say "I saw that a KeyEvent for 't' happened, so I will consume that so the game doesn't see it, because kOS doesn't get a guarantee that it saw the key *first*.  the main game might see it first, and
the main game might not be handling it using the GUI system at all but rather by directly reading the keyboard itself.

Thus the only way for the kOS terminal to block out the main game from thinking that "T" means turn on SAS (and "W" means pitch down ,and so on) is for it to use the KSP control locks to turn all those things off.  Then when you click outside the terminal, it can get rid of that lockout.

The reason it sometimes works and sometimes doesn't is that not every control in the game is part of the control lock system.  Only those things that happen to be also keyboard activated (like SAS) are.

So the reason SAS doesn't work when you click on it the first time is that kOS had to disable the SAS control *in general* in order to assure the "T" key doesn't turn it on, which then also means the mouseclick won't turn it on either.
