### ISSUE TITLE
LOCK can break built-in identifiers like HEADING

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2596]
I just saw a new user learning kOS stuff do this in JonnyOThan's twitch-plays-ksp stream:
```
lock heading to steering(90,90).
```
(A mistake.  It should have been ``lock steering to`` not ``lock heading to``).

The nasty thing is that this left the core in a broken state requiring reboot - because it LET them clobber the built-in identifier HEADING() with this new user-defined function (the lock), which meant the built-in HEADING() was no longer reachable and could  never be used again after that.

Essentially, LOCK shouldn't be allowed to be used with a built-in identifier like HEADING.

**Comment by JonnyOThan** [comment]
Turns out locking ‘r’ also messes up the R() function

**Comment by JonnyOThan** [comment]
And we just discovered you can lock body names too!

```
lock mun to minmus.
set target to mun. // actually minmus!
```

**Comment by nuggreat** [comment]
I was recently reminded of this issue by a conversation on the kOS discord and so felt I should copy a proposed solution to this issue that was also mentioned in said discord but never made it to the github issue tracker.

Make a parser rule that triggers a syntax error should someone try to assign one identifier used for builtin functions or the bound vars that are GET only as part of a variable declaration.  More or less make something like this `SET max TO 12345.`, `LOCAL max IS 12345.`, `GLOBAL max IS 12345.`, or `LOCK max TO 12345.` throw a syntax error.

An exception for bound vars that are GET/SET would need to exist but in that case making them only usable with `SET foo TO bar.` would work to prevent masking.

In a similar vain due to how the steering manager works with the cooked steering control vars `STEERING`, `THROTTLE`, `WHEELSTEERING`, and `WHEELTHROTTLE` they should have a similar but different rule where they can only be locked.

Lastly due to the breaking change that such rules represent it was also proposed that we should include a compiler directive similar to `@LAZYGLOBAL OFF.` to allow older scripts that did use such names for vars to still be compiled and run albeit with a warning of some kind.
