### ISSUE TITLE
kOS aborts program at random times, starts again when throttle is on.

### ISSUE THREAD

**Issue by rockysnow7** [KSP-KOS/KOS#2608]
At seemingly random points throughout the flight, the kOS program returns the message `Program aborted.` and shuts down the program.
When I turn on the throttle, it turns the program back on but sometimes repeats the problem multiple times in one flight.

As I cannot find the source of the problem and I have found very little online about it, I haven't tried anything to solve it.

I expect the program to run until the end of the file, but it ends before that point.

I have attached the file as a .txt.
[mr.txt](https://github.com/KSP-KOS/KOS/files/3562882/mr.txt)

Edit: After turning on throttle, it gave the error `Argument is out of range. Parameter name: startat.` ... `error might really be internal.`

**Comment by Dunbaratu** [comment]
I can't get your link "mr.txt" to work.  it just keeps reloading this page itself, not the file you meant to attach.

**Comment by Efratror** [comment]
```lock throttle to 1.
lock steering to up.
stage.

until ship:bounds:bottomaltradar > 10000 {
  lock steering to up.
}

set fO to 0.
until ship:bounds:bottomaltradar > 35000 {
  lock steering to heading(90, 110-(ship:verticalspeed/10)).

  if fO = 0 {
    list engines in engList.
    for eng in engList {
      if eng:flameout {
        stage.
        set fO to 1.
      }
    }
  }
}
lock throttle to 0.

wait until eta:apoapsis < 20.
lock throttle to 1.

until orbit:periapsis > 70000 {
  lock steering to heading(90, 10).
}
lock throttle to 0.

set target to body("Mun").
sas on.
set sasmode to "target".

wait until eta:apoapsis < 1.
lock throttle to 1.

```

**Comment by Dunbaratu** [comment]
I don't know the cause of the message, but this could be a problem right here:
```
    list engines in engList.
    for eng in engList {
      if eng:flameout {
        stage.
        set fO to 1.
      }
    }
```
During ``list engines in engList`` it builds up a list of all the engines on the ship.  Presumably some of those engines are in the bottom stage.

When iterating over the loop of all those engines, you execute ``stage.``, which can detach some of those engines from the ship before you finished iterating over them.

Don't ``stage`` during the for-loop.  Remember the fact that you wanted to stage in a boolean, then perform the stage just after the loop if that boolean is true.  (Alternatively, just immediately ``break`` from the loop as soon as you stage, if you already decided that one flamed out engine is enough to make you want to stage, then you don't need to know about the other flamed out engines so can just stop the loop there.)

Also, there's a lot of things about that script that are abusing kOS's poor cpu, but they are probably not causing the error - just making it use CPU time wastefully.  Those are:

```
until ship:bounds:bottomaltradar > 10000 {
  lock steering to up.
}
```
That is a bad thing because the loop has no slowdown, even though the relevant thing you are measuring (bottomaltradar) cannot possibly change until a physics tick has passed (so giving it a ``wait 0.`` won't effectively change anything about how it behaves but will make it tax the system less as it will only check as often as the value could actually change:

Also it locks steering to UP, again and again and again, when it could just lock it up above and have the same effect.

(the same is true of this:)
```
until orbit:periapsis > 70000 {
  lock steering to heading(90, 10).
}
```

Also, unless you expect your ship dimensions to change, you can just save ``ship:bounds`` once into a variable then use that variable, and it saves a lot of kOS execution load.  It only needs to be recalculated if you know the ship bounds has grown or shrunk (like if you have staged away some parts).  kOS is doing some ugly work under the hood every time you invoke the ``:bounds`` suffix.  You'd rather avoid doing that work again and again if you can.  Only re-run ``:bounds`` when you expect the bounding box to have changed.

**Comment by rockysnow7** [comment]
Sorry, I only just saw this message.
All of this is super useful (thank you!) - I'll try this :D
