### ISSUE TITLE
[Feature] Implement User Classes / Structures

### ISSUE THREAD

**Issue by jonnyboyC** [KSP-KOS/KOS#2610]
I think there could be a lot of value in adding user defined class / structure to the language. I think think there are benefits for experienced users for generating libraries and shared functionality. I think python may prove to be the best template to imitate.

## Example Usage

This might be an example usage.

```
// class / structure declaration
STRUCTURE Foo {

    // constructor method, not sure what makes most sense for keyword
    CREATE {
        PARAMETER self, bar.

        set self:bar to bar.
    }

    // structure suffix, possible alternative reuse function keyword
    SUFFIX baz {
        PARAMETER self.

        print("hi").
    }
}

local struct is Foo(10).
struct:baz().
// hi

set struct:bar to "something else".
set struct:notCreated to 5.
```

## Grammar / Keywords

From the above example I think this would the appropriate grammar. Of note, the create and suffix function would only be applicable within a structure block. Additionally, structure would be declarable either locally or globally. 

```
// ..

// base tokens
CREATE      -> @"create\b";
SUFFIX      -> @"suffix\b";
STRUCTURE   -> @"structure\b";

// ..

// restrict structure block to only accept create and suffix statements
struct_block -> CURLYOPEN (declare_create_clause | declare_suffix_clause)* CURLYCLOSE;

// ...

// follow convention of function
declare_struct_clause -> STRUCTURE IDENTIFIER instruction_block EOI?;
declare_suffix_clause -> SUFFIX IDENTIFIER instruction_block EOI?;
declare_create_clause -> SUFFIX IDENTIFIER instruction_block EOI?;

// ...

// structure can be global or local
declare_stmt   -> 
  // declare|global|local are all optional for function and parameter,
  // but mandatory for declaring an identifier.  This was the only
  // way to get the LL(1) parser to understand that without barfing on
  // ambiguity.
  (   
      declare_parameter_clause |
      declare_function_clause |
      declare_lock_clause |
      declare_struct_clause |               // new
      (
          (
              (DECLARE (LOCAL|GLOBAL)?) |
              (LOCAL|GLOBAL)
          )
          (
              declare_parameter_clause |
              declare_function_clause |
              declare_identifier_clause |
              declare_struct_clause |       // new
              declare_lock_clause
          )
      )
  );
```

## Semantics
Semantically I believe classes should act very similar to the pseudo classes you can make right now. The above example should roughly be translatable to the follow code.

```
// class / structure declaration
function Foo {
    PARAMETER bar.

    local instance is lex().
    set instance:bar to bar.
    set instance:baz to baz@:bind(instance).

    // structure suffix, possible alternative reuse function keyword
    local function baz {
        PARAMETER self.

        print("hi").
    }

    return instance.
}

local struct is Foo(10).
struct:baz().
// hi

set struct:bar to "something else".
set struct:notCreated to 5.
```

The key difference between the above and a structure instance would lie in lexicon. Internally I believe it would work to have the store be a dictionary but remove the lexicon suffixes leaving only the indexer / getSuffix over the base structure. I think the name of the structure could be used for `:TYPENAME` and `:ISTYPE` suffixes. Currently, I'm not sure if it make sense to do something in order to avoid name collisions with built in types. I think the create function should act identical to any other functions. So it should be detected in prior to the rest of script and be able to be made into a delegate.

This is mostly a first stab at what this might look like. I wouldn't mind feedback on the design.

**Comment by Dunbaratu** [comment]
The hard thing about OOP in kerboscript has always been the lack of compile-time enforcement of type.  Adding compile-time enforcement of type makes the compiler a LOT smarter (meaning a hell of a lot more code to implement the compiler, making it into a project of its own.)

If sticking with kOS's late runtime-binding of things, that limits the kinds of class implementations you can do.  It's not impossible, but it basically means you have to go with the "template instance" style.  How that works is this:  A class is just another generic object.  There is no such thing as a definition of a type being different from an instance of a type.  The definition of a type IS the fact that you have made one dummy instance of that type.  With this model, to make a new instance of a type means its actually using the default dummy instance and treating it as a template to copy from.  To make a derived type B of a base type A actually means "copy A's dummy instance, then run this code to change these things about it, and we'll call that new thing B.  B is now a new dummy instance I will copy from later when making objects of type B."

In your example above, that would mean that ``STRUCTURE Foo`` actually creates a Delegate called Foo under the hood that returns a LEX (as you describe) and the CREATE keyword actually would mean "Run the Delegate Foo, which will return a new object similar to itself".

With that thinking there would be no need for the CREATE syntax - the "constructor" would just be the bare code inside the STRUCTURE's braces - thus simplifying the confusion over what order things happen in in OOP definitions (i.e. when you declare ``int aaa = 12;`` in the class definition, but then during the constructor you say ``aaa = 20;``, does constructing an instance of this end up meaning aaa becomes 12 for a brief moment then turns into a 20 a moment later, or does it just become a 20 and spend no time being a 12?  Answer depends on how smart the compiler is.  If the CREATE section is removed, then the answer is simply "the fields get built in the order you see the code happening."

(To be honest, the KSP2 announcement has limited how much I am willing to put into massive infrastructure changes to kOS that would take months, instead making me think about what a new kOS-like might be like if done from the ground up.  One of the things that makes infrastructure refactors hard to do in kOS is the legacy of syntax ideas that need to keep being supported (like the weird way LOCK and FUNCTION are *almost* but *not quite* the same thing - that makes things slightly messy and causes some spaghetti code in OpcodeCall.) Anything done here toward OOP would have to be easy to layer on top of what we already have.  I think your proposal might be doable in that style since it's really just LEX with alternate syntax.)

**Comment by jonnyboyC** [comment]
Yeah I think the general thought process would be make it in such a way that it would be mostly syntax over the pattern that exists now. So in that case simply generating a delegate to produces a lex of a particular shape.

As you mentioned, to do compile time checking would require significant compiler changes that I don't think make sense for the current codebase. Essentially, I think you leave everything as runtime checks only if suffixes exists on the structure.

I suppose the big question would what are your thoughts on potential changes to kOS you would consider in a transition to KSP 2? Are you mostly thinking under the hood cleanup / refactoring or do you have other thoughts.

**Comment by Dunbaratu** [comment]
On the question of KSP2, I hear that the new versions of Unity they're using are drastically different from the legacy Unity KSP1 uses.  They may be so different that it may become necessary to totally wipe kOS and start fresh.  Obviously until more details come out it will be impossible to tell if that's true.  I have some ideas rattling about my head about infrastructure I'd like to do differently if a totally new codebase is required.  Not just the OOP stuff but deeper stuff under the hood, like getting rid of the distinction between LOCK and FUNCTION by essentially getting rid of LOCK entirely, and making the in-game terminal into a full terminal emulator that "acts like" it's the same thing as a telnet terminal, rather than having it dive deep into kOS's other structures.  (i.e. kOS only talks to it using character escape codes).  And having a more complete distinction between the not-Unity code and the Unity code (make the kOS fake computer be a standalone thing with an "update me now please" hook routine that Unity could call from a FixedUpdate, or something not-unity could call from its own routine.)  Lots of ideas swimming in my head about what a kOS sequel for KSP2 might be like if it turns out kOS code can't really port over well.

Now, if it turns out kOS code CAN port over to KSP2 well, then that opens up a new question, which is should it have a redo from scratch anyway?
