### ISSUE TITLE
Fond message breaks KSP

### ISSUE THREAD

**Issue by Domi1993** [KSP-KOS/KOS#2635]
I use kOS 1.1.3.0 on KSP 1.3.0 when i start it there is showing up a useless Message about Terminalfonts. I need to click it away before KSP is loaded when i try to close it to late, it stay there and makes the game unplayable.

How i can remove this Useless and Annyoing Message from kOS?

I just seen that 1.1.9.0 has removed it (but can you do the same for the 1.1.3.0?)

**Comment by Dunbaratu** [comment]
Actually pick a font and it should go away.  (During a flight, use the kOS toolbar icon and select a font.)
The message occurs because the user hasn't selected a font and it's still using a fallback default choice.  (Either that or something isn't being saved right if you have selected one and its still showing up.)

**Comment by Dunbaratu** [comment]
If you can't seem to make the message go away, then find this file in your installation:

Filename: GameData/kOS/Plugins/PluginData/kOS/config.xml

And find this line inside that file:

```
    <string name="TerminalFontName">_not_chosen_yet_</string>
```

And change it to this instead:

```
    <string name="TerminalFontName">Choose Font</string>
```

**Comment by Domi1993** [comment]
Thank you for your help
The Config.xml was broken (only NULL Symbols)

I deleted it and started KSP to generate a new one, and selected a font now it's gone.
