### ISSUE TITLE
Loading .dds files fails on MacOS

### ISSUE THREAD

**Issue by rrs42** [KSP-KOS/KOS#2642]
kOS version 1.2, KSP 1.8.1.

kOS is failing to load .dds files, and logging many of the following in KSP.log:

> [LOG 12:02:41.585] kOS: Exception in LoadTextureDXT: System.IO.DirectoryNotFoundException: Could not find a part of the path "/Users/xxxx/Games/KSP_181/GameData/kOS/Plugins/..\\..\\/kOS/GFX/dds_terminal-icon-open.dds".

The problem is that '..\\..\\' in the middle of the path works on Windows but does not work on. MacOS (or Linux). 

If I make a symlink named '..\\..\\' in the kOS plugin directory and point it to the GameData directory kOS works as expected. (Though it has to be created after KSP launches or else KSP gets stuck scanning for mods.)

**Comment by Dunbaratu** [comment]
Alright.  I accepted a PR from someone because it allegedly fixed the problem where KSP's own DDS loading routines were broken on some systems, but that PR introduced the hardcoded separator.  I thought that Mono's file opening routines could handle either kind, as part of being cross-platform, but apparently not.  I will change it out to forward slashes and see if that helps, as those do work in a cross-platform way on Windows and everyone else.

**Comment by Dunbaratu** [comment]
Fixed by PR #2643
