### ISSUE TITLE
Missing Documentation For ResetTrim and KillRotation In Flight Controls

### ISSUE THREAD

**Issue by jonnyboyC** [KSP-KOS/KOS#2652]
I was in the process of poking around the KOS source noticed these two methods [here](https://github.com/KSP-KOS/KOS/blob/develop/src/kOS/Suffixed/FlightControl.cs#L261-L280) are not documented on the [raw controls doc page](https://ksp-kos.github.io/KOS_DOC/commands/flight/raw.html#ship-control-neutralize).

**Comment by Dunbaratu** [comment]
I was digging through ancient history in the git logs and I think these suffixes simply pre-date the universal dictionary-based suffix system we did with ``AddSuffix`` and were missed when converting everything to ``AddSuffix``.  because they never were in the list of ``AddSuffix`` calls in ``InititalizeSuffixes``, they never got noticed when going through the lists to make Sphinx documentation.

I think the fix is not JUST to document them, but also to move them into ``InitializeSuffixes`` and have them use ``AddSuffix`` properly like everything else (and also document them).

**Comment by Dunbaratu** [comment]
Upon further investigation, I don't really want to document these because what I say would probably be wrong.  They appear to do nothing, as far as I can tell.  Also, the entire concept of 'setting trim' may need a massive overhaul.  The reason resetting trim does nothing is that setting trim in the first place does nothing - it's trying to use "trim" on the autopilot controls which does nothing, as trim only matters when it's done on the pilot setting.

**Comment by Dunbaratu** [comment]
In the end, I think I'm going to entirely remove these two suffixes.  They literally don't do anything.  They look like stub code that was put there in order to be fleshed out later, and they never got completed.

The 3rd similar suffix, NEUTRALIZE, which I am keeping does do something, however the mechanism it uses is so oddball it made me want to refactor this code a bit. 

These suffixes use a system that pre-dates the proper new suffix system, and the way Neutralize works is uuugly.
