### ISSUE TITLE
Stage:resources Workaround

### ISSUE THREAD

**Issue by MSpyker** [KSP-KOS/KOS#2654]
I understand that KOS pulls data for `Stage:Resources`from KSP, which somehow is corrupted, but could there not be another option to get the same data. It should be possible right?

**Comment by nuggreat** [comment]
`stage:resources` does not get corrupted instead KSP it's self has a very simplistic set of rules for what parts are in a stage and said simplistic rules do not agree with most peoples intuition because most peoples intuition does not use a simple set of associations.

As for workarounds they do exist and involve walking the part tree to build what engines tie to what tanks your self, but it is not something kOS will do for you.
