### ISSUE TITLE
[Feature Request] Add an "execute" Built-in function

### ISSUE THREAD

**Issue by Mindeufair** [KSP-KOS/KOS#2663]
In some programs I did, I use a terminal interface between the user and recursives program, it could be very usefull to add a function which can directly execute string as instructions to have a deepest interaction with the program. Currently it's possible to do it by saving the string in a file and run it, but I noticed that it take a long time for the mod to opn a file, so it's not very optimized.

If I'm not clear, I'm thinking of a function like the "exec" one in python.

Thanks in advance for reading and answering (and hopefully for implementing my idea) :)

**Comment by nuggreat** [comment]
Even if there was a built in function for executing a string it would only be slightly faster than saving a string to a file and running the string because it takes time for kOS to compile your code into it's internal set of OPcodes that run on the internal VM.  The only thing you would save with an built in exec function would be the file IO and that only happens when you write out your temp file to the archive and won't happen if you write it to the local volume on the kOS core executing your program.  There are other problems that I don't know if you have discovered with trying to save out string to a file and then run it which can sneak up on you hence why currently the only recommended way to do that is through the lib_exec found [HERE](https://github.com/KSP-KOS/KSLib/blob/master/library/lib_exec.ks) and even the it comes with the warning of "Avoid if at all possible".

**Comment by Mindeufair** [comment]
Thank you for that answer (quicker than mine xp), in fact I didn't see the lib_exec, and I didn't think to save my temp files in a local Kos volume, so you helped me a lot ^^
Once more thank you
