### ISSUE TITLE
[Feature Request] Expose IDiscoverable properties of vessels to detect asteroid classes

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-KOS/KOS#2669]
https://kerbalspaceprogram.com/api/interface_i_discoverable.html

In "twitch plays ksp" we have no way to know the class of an asteroid.  That's a pretty niche usage, but any kind of automated system that wants to go out and grab an asteroid will probably want to know its class first!

**Comment by Dunbaratu** [comment]
Hmm.  I never worked with Asteroids in kOS.  Does the normal Vessel interface work for them?  Because IDiscoverable does not appear to say anything other than the name, type, and mass. (i.e it doesn't say the thing's orbital or positional information?).

If I could say "an asteroid is a vessel, but it has a few additional suffixes beyond the standard ones vessels have" that would work fine.  But if the game won't let you get your "hands on" the vessel object for an asteroid, such that I have to treat asteroids as their own separate class, it gets uglier.

**Comment by JonnyOThan** [comment]
Yes, adding a few extra suffixes to asteroids would be great.  You can set them as targets and they appear to work just like other vessels except querying their mass returns 0.

The IDiscoverable has a property named DiscoveryInfo that has the info that I want. In particular the size property which seems to indicate the asteroid’s class.

**Comment by Dunbaratu** [comment]
In that case I think the simplest solution to present to scripts would be to NOT make a new class for asteroids, and instead say that an asteroid is a vessel, and all vessels have a class field you can query, and if it's a non-asteroid vessel then querying its class will return something like "VESSEL" instead of "A", "B", "C", "D", "E", or "F".
