### ISSUE TITLE
Escaped quotes in string literal are not unescaped

### ISSUE THREAD

**Issue by thexa4** [KSP-KOS/KOS#2672]
The syntax allows using quotes in a string by prepending it by another quote: https://github.com/KSP-KOS/KOS/blob/develop/src/kOS.Safe/Compilation/KS/kRISC.tpg#L91

This works during parsing but when you try to print the following string: `"foo""bar"` it will show `foo""bar` instead of `foo"bar`.

Is this expected behavior?

**Comment by Dunbaratu** [comment]
I had no idea the regex for strings was allowing that formation.  It looks like it was lifted directly from some other language's string definition, especially with the option for a preceding "@" like C# uses.  (That part of the system pre-dates me and I don't think I ever had a call to edit the regex for strings since then, so I never scrutinized that regex that closely.)
