### ISSUE TITLE
executing a node from another script

### ISSUE THREAD

**Issue by MathewUlanowski** [KSP-KOS/KOS#2679]
I have a script that creates a node to increase or decrease apoapsis or periapsis in accordance to the two parameters that it takes in which are ending apoapsis and ending periapsis inside this program it runs another script that executes the node it doesn't throw an error but for some reason it goes from the few hundred meters per second required to boost the orbit to several thousand meters per second in an instant ive tested both scripts without connecting them to each other and they work fine the node execution does its job the node maker creates the node but it goes all haywire if it tries to execute here's my code.

[Issue Scripts.zip](https://github.com/KSP-KOS/KOS/files/4273849/Issue.Scripts.zip)

**Comment by vvpisarev** [comment]
Which values of Ap and Pe do you pass there?
The `changeOrbit` script does km->m conversion. Can it be that you just call the script with `ship:apoapsis` and `ship:periapsis` as parameters, so that it happily tries to boost them to several Mm?

**Comment by MathewUlanowski** [comment]
> Which values of Ap and Pe do you pass there?
> The `changeOrbit` script does km->m conversion. Can it be that you just call the script with `ship:apoapsis` and `ship:periapsis` as parameters, so that it happily tries to boost them to several Mm?

No values are actually passed from one script to the other the change orbit script creates two nodes either at periapsis or apoapsis and then it hands it off to the execute node script witch as it sounds executed nodes it has no knowledge of the program calling it.

**Comment by nuggreat** [comment]
Your mistake in in how you are constructing the nod.  You are setting the mode time to `TIME:SECOND + thing`  the problem here is that `TIME:SECOND` will return the seconds as seen on the clock for UT.  What you want is `TIME:SECONDS` the s on the end of seconds is important.  what is happening is that your script is setting the node to be near the start of your save file.  The large time gap between the current time and the node causes your engines to light as the ETA is negative.  Also the reason the DV vector goes nuts is because of how KSP handles tracking the expended DV of a node and when the node is far in the future or far in the past then a slight burn will cause massive swings in the indicated DV.

**Comment by MathewUlanowski** [comment]
thank you for the assistance. that seems to have fixed the issue.
