### ISSUE TITLE
Have LOCK STEERING disable SAS.  Also give screen warning if SAS turns on.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#2688]
This is from a discussion on the discord channel about the problem where new users don't realize that SAS interferes with LOCK STEERING.  The manual mentions it several times, but it would be better if the mod was more active about mentioning it, and trying to stop it.

This is the proposal as it stands now:

1 - If SAS is on, at the moment a LOCK STEERING command first starts,  Make LOCK STEERING turn it off for you, with a short quick screen message stating it has done so.  Do not bother trying to remember the state the player had SAS in.  Don't bother trying to restore SAS to its previous state when the steering unlocks, because the player could have toggled it while steering was locked and that's a PITA to track.

2 - During the time that LOCK STEERING is in effect have SteeringManger keep checking the SAS state.  If the SAS gets turned on again (by script or by the player's manual action), allow it to do so, but do issue a screen message about it so the player understands why they're seeing the steering go all haywire.  The message could be something like "SAS and kOS STEERING are fighting!".  Have it fade on and off while the state is happening (repeat the message every X seconds, with a fade-out of X-1 seconds).
If the SAS is only turned on momentarily for a few ticks, then turned back off again by script, then the message should not show.  To accomplish this have some kind of timer that only starts the message after the state of SAS & LOCK STEERING has been happening for a second or so.

**Comment by totallyEl3ktrik** [comment]
I think the first option would be better.

**Comment by Dunbaratu** [comment]
It wasn't two options.  It was proposed as "do both these things".

**Comment by cahe7cb** [comment]
I personally prefer that kOS would throw an error if anything that may mess with its steering is detected but that's only because I've never found any use for having SAS and steering locking together on the same craft and also because I find it hard to define an automatic behavior in such scenario.

If someone does have an actual use case in having both SAS and steering lock they would have to deal with the message appearing on their screen. If the displaying of the message is delayed then craft would be already going haywire when the message appears (maybe) leaving no time for the player to turn SAS off manually.

For that I think it's a good idea to have a `STEERINGMANAGER` property that would define this behavior, like "default", "auto" and "strict". Where "default" is the "ignore" behavior that we currently have, "auto" is described by your proposal and "strict" would make kOS throw an error and abort the program instead of just showing a warning.

**Comment by nuggreat** [comment]
Yes there are use cases for SAS and lock steering to be on at the same time and because I do have such a use that and because i have such a use the short likely sub 1 second delay on the message was planed.  Also it does take time for SAS and locked steering to build the feedback as they fight each other so a short delay won't be to much of a problem and if it is then the person will know for next time.

The other problem with a very strict setting is for cases where some one has
```SAS ON.
UNLOCK STEERING.```
as the script shuts down and it would be very annoying to get unnecessary warning messages as in that instance SAS and locked steering don't have time to fight each other.

**Comment by Dunbaratu** [comment]
Yes, the intent behind the small delay before giving the message is so that the relatively minor case where SAS and LOCK STEERING are only on together briefly for one or two 'ticks' doesn't raise a complaint.  The message is mostly so people stop posting the same question over and over about what steering is so "broken" and making it spin randomly.  It would only turn on after a second or so, which is about the time the steering would start getting all wonky.  It's so people see an explanation of why it's behaving like it is.

**Comment by Dunbaratu** [comment]
I think after a few months, I've leaned toward wanting a solution in which it just warns the user with a message, rather than actually doing anything about it.  After a short delay (for the scenario where SAS is turned off in the tick before steering is locked), have it maintain a message on screen that stays up until the situation is fixed.  I know how I can do this (keep a message on screen and make it go away the moment I want to) with KSP's built in message system, since I just did it in another PR.  (you can dynamically change the display time after putting the message out there, so I can give it a long delay, then zero out the time remaining field when I want the message to go away.)
