### ISSUE TITLE
Unitsystem

### ISSUE THREAD

**Issue by kontiko** [KSP-KOS/KOS#2692]
It would be great if the standard kos functions/ parameters would use the standard si units for it return value or the unit would be mensioned in the Documentary

**Comment by RCrockford** [comment]
Can you give examples of where this is not the case?

**Comment by kontiko** [comment]
it's using kN and Tons instead of Newton and kg

**Comment by nuggreat** [comment]
Even if that did significantly affect calculations relying on force and mass and it doesn't,  kOS has used kN and Tons so long that it could very well be a breaking change to someone if they where altered.  Also the units where chosen because that is how KSP presents force and mass to the player and keeping that consistent is important for people new to such things.

**Comment by kontiko** [comment]
I see your point
