### ISSUE TITLE
config.xml TerminalFontDefaultSize continually overwritten with smaller value

### ISSUE THREAD

**Issue by Dreamjammer** [KSP-KOS/KOS#2711]
Inside config.xml, if you try to set TerminalFontDefaultSize to 24 (which, on my high DPI monitor, is about the equivalent of 12 on a typical monitor), it keeps changing it down to 20, which is just a bit short of being comfortable to read.

kOS in general is difficult to use on this monitor due to it ignoring KSP's UI scale setting, but that's another issue... I can script around it for my own UI screens, but I scale them based on Config:defaultFontSize, which is being clamped as noted above. :(  Fixing this would at least keep my own scripts' windows readable.

**Comment by Dunbaratu** [comment]
That code was written before 4k monitors were really a thing.  I agree the range needs to be increased.  

Do you have the ability to compile the mod?  I can show you where the value is clamped in the code.  It might be a while before I can get a new release out.

There are two places to edit in the code, both of them in the file src/kOS/Suffixed/Config.cs:

Line 65: - edit the "30f" to something bigger:
```
            AddSuffix("DEFAULTFONTSIZE", new ClampSetSuffix<ScalarValue>(() => TerminalFontDefaultSize, value => TerminalFontDefaultSize = value, 6f, 30f, 1f));
```

Line 75: - edit the "20" to something bigger:
```
            AddConfigKey(PropId.TerminalFontDefaultSize, new ConfigKey("TerminalFontDefaultSize", "DEFAULTFONTSIZE", "Initial Terminal:CHARHEIGHT when a terminal is first opened", 12, 6, 20, typeof(int)));
```
(Interestingly, it turns out these two lines disagree with each other.  The script clamps it to 30, while the save file clamps it to 20.)


I do not have a 4k monitor to test this on.  What looks like a reasonable max size to clamp (not a reasonable size to play necessarily, just a value so big that any bigger and it could really mess up the display and prevent you from clicking on other windows to fix the mistake of setting it that big.)

**Comment by Dunbaratu** [comment]
There's a third place - where the terminal itself has the Up/Down size buttons in src/kOS/Screen/TermWindow.cs 
Line 895,896:
```
            if (GUI.Button(fontHeightMoreButtonRect, "+", customSkin.button))
                postponedCharPixelHeight = Math.Min(24, charHeight + 2);
```

And in  src/kOS.Safe/Encapsulation/TerminalStruct.cs:
Line 23:
```
        protected const int MAXCHARPIXELS = 24;
```

If nothing else, this shows that there really needs to be one universal place they all pull their values from.  The same thing shouldn't be in 5 places in the code.

**Comment by Dreamjammer** [comment]
Hah, yeah... the wiki is likewise confused, alternately claiming the max value 20 or 30 in different places, e.g. https://ksp-kos.github.io/KOS/structures/misc/config.html?highlight=terminalfontdefaultsize#attribute:CONFIG:DEFAULTFONTSIZE

Whereas the +/- buttons on the UI limit it to 24.

I think anything up to 48 is reasonable. Beyond that it'd start getting silly...
