### ISSUE TITLE
UNSET does throw error in contrast to the docs claiming that it fails silently

### ISSUE THREAD

**Issue by scimas** [KSP-KOS/KOS#2752]
As the title says, per docs, UNSET is not supposed to throw error if it cannot find the variable we are trying to unset or fails for other reasons. But it does throw an error:
```
set myvar to 1.
unset myvar.
unset myvar.
Object reference not set to an instance of an object
```
Either the docs need to be updated or this is a bug. Tested on KSP 1.8.1, kOS v1.2.1.0

**Comment by Dunbaratu** [comment]
That's a bug then.  "Object reference not set to an instance of an object" isn't one of kOS's known exceptions it's trying on purpose to throw because it caught something that's the script's fault.  It's the C# code under the hood causing a null ref error.  Both the kOS deliberate errors and any bugs in its C# code bubble up to the same try/catch and get printed to the terminal.

It may be a good idea for that try/catch to differentiate kOS's own deliberate errors from bug errors like this (i.e. does it derive from base class KOSException or not) so it can change how it prints them, but that's a topic for another time.
