### ISSUE TITLE
PR: a 2 argument flavor of the TIME function

### ISSUE THREAD

**Issue by mgalyean** [KSP-KOS/KOS#2767]
I'm respectfully requesting a two timestamp scalar argument version of TIME function.  If two args are given to TIME it would return the real span of time between the two scalar time values without adding an extra day to ETAs, otherwise, if given only one argument, it keeps doing what it is doing for all the old code out there that is already coded to treat the TIMESPAN struct delivered by TIME in its peculiar non-timespan non-timestamp way when the scalar arg is an ETA

**Comment by Dunbaratu** [comment]
I've read this paragraph about 10 times and I still can't understand what you mean.

Can you try to clarify what you mean?

**Comment by nuggreat** [comment]
At a guess this is based around the fact that if you call `TIME(0)` and then call the `:DAY` or `:YEAR` you will get a return of `1` as which is correct for a the KSP year/day/hour/min/sec as displayed in the upper left.  Thus at a guess the request is for a second argument so that when passed something like `TIME(0,FALSE)` the `:DAY` or `:YEAR` suffixes would return `0` instead of `1` and thus shift the formatting to match an ETA style as apposed to a date style.

**Comment by JonnyOThan** [comment]
I don’t think the proposal should be implemented. Another way to solve this problem is just to rename `timespan` to `timestamp` and then introduce a real `timespan` type with the proper semantics.

IMO it’s a really bad idea to introduce two different semantic meanings for the same type, because the consumers of the type have to know which it is.  Arguably vectors already operate like this, but at least their internal value doesn’t have to change depending on whether they represent a point or a vector. For the timespan case, you either need to offset the internal value by 1 day and 1 year, or have a flag internally that marks which it is.

**Comment by Dunbaratu** [comment]
So is the real complaint that the timespan display uses start-at-one counting for days instead of start-at-zero counting?

That's not a feature of the data in the TIMESPAN.  That's a feature of how that data is converted for display.  The fix could be as simple as having a flag on TIMESPAN for how it spits out the year/day/hour/minute/second fields.

What's actually stored in the TIMESPAN is just the seconds.  Everything you see is calculated on the fly when you ask for it.  Kind of like how "Unix time" works.

**Comment by Dunbaratu** [comment]
@mgalyean, @nuggreat, @JonnyOThan - could you please look at PR #2805 which I just made, and tell me if you think it solves the problem in this issue?

I didn't do it the way it was requested but I think this solves the problem you had, @mgalyean.

**Comment by JonnyOThan** [comment]
I think this addresses the issue, but I don't think it's the right change to make.  This adds complexity and potential for bugs rather than reducing it.  I think the *best* solution is to introduce a new type (TIMESPAN and TIMESTAMP, a la .NET's TimeSpan and DateTime).  Another half-measure might be to add something like a :STOPWATCH suffix akin to :CALENDAR but prints the zero-based duration.

**Comment by Dunbaratu** [comment]
I don't think we think the same way.  To me .NET's insistence on pretending that absolute time and relative time are two different concepts is the more messy and convoluted design pattern.  I have always hated it.  You don't do that with any other type of quantity.  i.e. "I have 7 apples" and "I have 7 more apples than Mary" are using the exact same kind of "7".

**Comment by JonnyOThan** [comment]
I think the key is in whether the "value" vs "delta" has a meaningful semantic distinction and whether your code benefits from enforcement of that distinction.

In the codebase where I work, we have separate types for point3d and vector3d, and you are forbidden by the compiler from ever adding two point3ds together.  The type system works *with* you on this, because subtracting two point3ds from each other gives you a vector3d, and adding a vector3d to a point3d returns a point3d, etc.  .NET does this same with DateTime and TimeStamp fairly well.

Your apple example doesn't quite capture the problem because adding apples together still makes sense.  Adding timestamps to each other should always be an error,  just like adding positions to each other should be an error.

**Comment by Dunbaratu** [comment]
I honestly don't understand the real-world distinction you are trying to draw here.  Points *are* vectors - from the origin to a spot in space.  Timestamps *are* timespans from epoch to now.  You could *maybe* argue there is such a thing as absolute time if your calendar started at the big bang, kind of like how Kelvin starts at absolute zero, but that's not what TimeStamps do.

**Comment by JonnyOThan** [comment]
Does it make sense to add my position to your position? No.  Does it make sense to add October 15th to April 4th?  No.  These are semantic problems, even though the underlying datatype might support the operation.  But a well-designed language or library would forbid them.  This ban might cause the programmer some issues if they want to do something unusual, but the language/library should provide conversion mechanisms for extreme cases.

Your comment belies what I'm getting at: when you add two "values" together (e.g. points or dates), the result depends on what your concept of zero is.  But when you add two "deltas" together (vectors or timespans) the result does not depend on the concept of zero.

**Comment by Dunbaratu** [comment]
> Does it make sense to add my position to your position?
Yes.  A position is always communicated using a reference frame and is therefore relative to an origin.

>  Does it make sense to add October 15th to April 4th
Yes.
October 15th is a certain *distance into the year*, as is April 4th.

**Comment by Dunbaratu** [comment]
I don't agree with your claims about position not being vectors, but I'm beginning to see the point about dates because of how much of complex ugly mess the calendar is.  (Not because time can't be viewed as relative - it can - but because the calendar system is an ugly mess.  "April 4th" doesn't mean the same thing every year, because how far into the year that is changes depending on whether there was a February 29th that year or not.

**Comment by Dunbaratu** [comment]
Looking more into whether Kerbal would have the same problem, it kind of does.
In the Kerbal system years are not an exact multiple of days, much like with Earth.  But looking into it, it's every 12 years an 'extra' day appears on Kerbal rather than 4-ish as on Earth.  Instead of leap years, what Kerbal does is just jump-cut to the next day, truncating the last day partway through to start the year on a fresh day.

**Comment by Dunbaratu** [comment]
Didn't mean to close - hit the wrong button.

**Comment by Dunbaratu** [comment]
So, I think this gets rid of the problem without creating the myth that dates and timespans are different concepts when they're not: remove the flag from the class.  The class itself has no memory of the flag.

But instead make different suffixes for the different formats.  That drills home the point that the difference is pure nomenclature for how you *describe* time, and not actually a real difference in what time actually means.

**Comment by mgalyean** [comment]
Yes, this is a good work-around

**Comment by mgalyean** [comment]
My references to TIME and TIMESPAN being different is based on how many different libraries and languages deal with it.  A time value is a point, referenced to some zero point typically, but a span is a duration.  I get the argument that given epoch, all times are "spans" but I think that overgeneralizes.  Words mean things and "span" has a meaning.  It is the difference between a number printed on a ruler, and the distance between 2 numbers printed on a ruler.  But no reason to beat a dead horse, the flag does the trick.  People will never agree on everything, no worries

**Comment by mgalyean** [comment]
I can't think of a more sublime difference than the difference between relative and absolute :D

**Comment by Dunbaratu** [comment]
>  Words mean things and "span" has a meaning.

I may go with the timespan vs timestamp change after all, even though I remain unmoved in my disagreement with both of your arguments that claim absolute measures and relative measures are two different things.  In the case of time, there's an additional cultural hurdle that doesn't exist for points vs vectors.  That cultural hurdle is that our society uses outdated ones-based nomenclature for timestamps but more modern zero-based nomenclature for timespans, and mixing the two nomenclatures is ugly and needs clear rules about which nomenclature you end up with when you mix the two.  It's nothing like the difference between adding a point to a vector, and more like solving the math problem "(four score and seven) * (2.1)".  One of those is going to have to go through a nomenclature mapping to be in the same reckoning as the other, and it's important to have a consistent answer which nomenclature you expect to get back out of that operation.

**Comment by Dunbaratu** [comment]
@mgalyean and @JonnyOThan :  I have another PR that does this the two-class way instead if you want to have a look at it.  It's this one -> #2837

That PR has documentation edits that should explain how to use it.

I want to get a release out soon so I may just hurry up and merge this in a day or two if I don't get feedback approving or disapproving it.

**Comment by nuggreat** [comment]
The section "Kerbal Calendar Differs From Earth's" fails to mention mention how the days per year differ between kerbin's year and earth's year it only says there is a difference.

In the suffix tables for `timeStamp` and `timeSpan` the entries for the `:HOUR` and `:DAY` suffixes you note only one range or inputs but down in the expanded description you note two possible ranges of inputs.  In this case ether both ranges should be mentioned or no range should be mentioned in the table.

There is also a mistake in the description of `:DAY` of the `timeSpan` structure the numeric range as listed is `(1-426) or (1-356)` but the text says it starts at 0.

For `timeSpan` the entries the suffixes `:DAYS`, `:HOURS`, and `:MINUTES` in both the suffix table there is a listed input range for the suffixes which contradicts the expanded description.

There is also a capitalization difference in the for the word "total" between how it is used in `:DAYS`, `:HOURS`, and `:MINUTES` vs how it is used for `:SECONDS`.  In the first 3 it is all caps "TOTAL" where as for `:SECONDS` it is simply "Total" which also matches how it is typed in for the `timeStamp` structure.  This difference exists in both the suffix tables and in the expanded descriptions.

Those are the only things that jumped out at me looking through the documentation as I can't speak to the validity of the code.

On a side note I look forward to being able to remove chunks of code in KSlibs `lib_num_to_formatted_str.ks` library and just use the `timeSpan` constructor for a lot of time related work it is doing.

**Comment by Dunbaratu** [comment]
Thanks @nuggreat  - I just pushed a commit with documentation edits from your feedback.
