### ISSUE TITLE
HASPARENT not working for Box structures

### ISSUE THREAD

**Issue by NerdNath** [KSP-KOS/KOS#2822]
//Make a gui to cause the problem

set myGUI to gui(200,200).

set mySBOX to myGUI:ADDVBOX().
set fillerLabel to mySBOX:ADDLABEL("Test").

myGUI:SHOW.

//causes an error saying Box has no HASPARENT suffix despite HASPARENT being a
//suffix that theoretically should be inherited from Widget
if mySBOX:HASPARENT { 
  myGUI:HIDE.
}

**Comment by Dunbaratu** [comment]
As far as I can tell, the documentation has been wrong all along, because ``Widget:HASPARENT`` doesn't exist anywhere in the C# code.  The documentation file (``widget.rst``) claims the suffix exists but it is not there in the actual implementation in C#.

It's not just that BOX lacks it.  All Widgets lack it.  It looks simple enough to implement but I'm surprised it went this long without anyone trying to use it.
