### ISSUE TITLE
bare scalars are not serializable 

### ISSUE THREAD

**Issue by nuggreat** [KSP-KOS/KOS#2824]
When used bare scalars report they are not serializable and thus will thrown an error when used in a `WRITEJSON()` call.  But when wrapped in a `LIST()` they serialize just fine.  Which seems a bit inconsistent to me as I would expect them to serialize just fine bare if they can also be serialized when in a list.
```
LOCAL testVar IS 0.
WRITEJSON(LIST(testVar), "1:/working.json").//will work fine
WRITEJSON(testVar, "1:/broken.json").//will crash
```

**Comment by Dunbaratu** [comment]
It turns out that to fix this requires all Primitive types be serializable (BooleanValue, StringValue, etc) since I can't multiply inherit in C# and to make it seralizable I have to inherit singly from SerializableStructure but it already inherits from Primitive - so I need to make Primitive inherit from SerializableStructure.
