### ISSUE TITLE
Cooked Steering should rotate along shortest path to target orientation

### ISSUE THREAD

**Issue by Arrowstar** [KSP-KOS/KOS#2832]
In "cooked steering", the vehicle both knows where it is currently and where it wants to be.  However, if your roll is at 350 degrees and you specify a 0 degree roll, the vehicle will generally go the long way around (350 deg to 0 deg) instead of the short way around (350 deg -> 360 == 0 deg).  

Cooked steering in kOS should be improved such that the vehicle recognizes how to rotate around each axis in order to achieve the desired result.  No rotation about any axis should be more than 180 degrees.  A simple way of implementing this might be to define all "error" angles in the PID controller w.r.t. the current orientation.  

I'm happy to provide additional information if needed, please just ask.

**Comment by nuggreat** [comment]
I have never seen the kOS steering manager do what you describe in my experience it has ALWAYS rolled along the shortest distance.

**Comment by Dunbaratu** [comment]
I'm going to have to see this in action.  The description you gave doesn't match with what I've seen when I use it.  That either means something weird is going on in your install, or it means I haven't understood your description.

**Comment by mgalyean** [comment]
I would actually suspect the opposite.  On more than one occasion I'm confident I've seen the steering mgr take the shortest path in a rotation when it clearly wasn't the fastest nor most efficient path given the pre-existing angular velocity (i.e. would have been better to have just kept rotating the way it was, turning though the opposite point, then stopping at the target; rather than braking and reversing direction to take the shortest path)

**Comment by Arrowstar** [comment]
I just tried to recreate the problem I thought I observed in the original issue and could not.  I don't think this is actually an issue.  Whatever was causing what I was seeing was probably not related to the cooked steering implementation.  Closing.
