### ISSUE TITLE
Allow kOS to control MAPVIEW focus, filter, commnet visibility, etc

### ISSUE THREAD

**Issue by mgalyean** [KSP-KOS/KOS#2834]
When recording videos of automated sequences it would be great if the script could control more aspects of the mapview; like having BODY be the focus instead of the craft while time warping 100 orbit, turning off the CommNet xmas lights, and filtering to only display the vessel types of interest.

**Comment by nuggreat** [comment]
I don't see how this is useful in stock kOS as we don't have camera control so being able to change filter settings is of little use.

**Comment by JonnyOThan** [comment]
I’m on the fence - stock kos can turn mapview on or off, but nothing else. It feels natural that additional mapview controls could be added. However you need kos-camera to even turn the camera, so I could also see the argument that it should be added there.

**Comment by nuggreat** [comment]
I have only ever used the `MAPVIEW` var to trigger changes in vecdraws depending on if the mapview is on or off so having it exposed is usefull.  The only other use I see for it is as part of a script signaling it needs user input such as setting a target or making a maneuver node.  Thus the limited get/set in base kOS makes sense but I don't see much point to a small expansion to the feature set though a large one does make a bit more sence.  But at that point better to fold it into the existing camera addon than make it a base kOS feature.

**Comment by mgalyean** [comment]
Camera control doesn't matter here because I'm talking about focus on the MAPVIEW screen.  The body or vessel that is placed at the center of the screen.  There is no "camera" that I'm aware of in mapview

**Comment by JonnyOThan** [comment]
Er, there is definitely such thing as a camera in map mode and it functions almost identically to the one in flight mode.

I’m working on adding this functionality to kos-camera, so someone should close this one.

**Comment by mgalyean** [comment]
Well, there may be a camera, but it is far more limited than in flight view.  To the point that it isn't even obvious it exists.  What does "chase" or "locked" or "free" even mean in flight view?  But you are the one looking right at the code so I defer.  Thanks for looking into the additions, much appreciated

**Comment by Dunbaratu** [comment]
@JonnyOThan If adding this to kos-camera, don't forget the ability to pick a part on a vessel to aim the camera at (even if the underlying KSP API calls are different for this, from a kOS script point of view it feels similar (point camera at this thing, where "this thing" might be a Part or might be a Vessel or might be a Body.)

**Comment by JonnyOThan** [comment]
@Dunbaratu hm, that seems weird to me. The map camera can focus on bodies, vessels, and maneuver nodes.  If you set the target to a part, would you expect it to just focus on the vessel that contains that part?  I think maybe it should just throw an error.

**Comment by Dunbaratu** [comment]
What I mean is this;  The call to rotate the camera works both in flight and on map.  The call to zoom the camera works both in flight and on the map.  The call to translate the camera (which is what is happening when you aim it at a new body or a new part or a new vessel) only working on map and not flight view would be an exception to this pattern.

**Comment by Dunbaratu** [comment]
> this definitely feels more right to me, since if you read a field after setting it you should generally get the thing you just set, and weird things would probably start happening if I silently changed parts to vessels.

My proposal doesn't add this problem.  It already existed and you already would have had to deal with it anyway because while you can focus on a body or a maneuver node on the map you can't in the flight view.  So what happens when you set the focus to a body on the map, then switch to flight view? It's no longer a valid thing to focus in that mode.  It's the same problem as focusing on a Part in flight view then switching to map view.  Whatever solution you come up with for "script said to focus on a body but we can't do that now in flight view" can also be applied to "script said to focus on a part but we can't do that now in map view".

It's possible you might just have to remember two different focus targets - one for map and one for flight - since the game itself remembers them both (try it - focus on a specific part, then in the map focus on a body.  toggle between map and flight and it does remember which you were looking at as it toggles between the two - so it does remember both separately in the stock game somehow).

There's two possible solutions I see:

(A) Just have one call but use the context for which is being affected (if you set ``:FOCUSOBJECT`` while on the map view then the script is setting the map camera focus, and if you set ``:FOCUSOBJECT`` while on the flight view you're setting the flight camera focus.

(B) Have two different calls, one for setting ``:MAPFOCUSOBJECT`` and one for ``:FLIGHTFOCUSOBJECT``.  But, importantly, they both work the same way with the only difference being what is and isn't a valid type to pass in.

I guess the thing I was most arguing *against* was the view that telling the camera to aim at an object is somehow a feature that only exists on the map view.  It's not.  It exists in flight view too its just that the target objects are ship parts instead of bodies.

**Comment by JonnyOThan** [comment]
Ah I see the contention.  But I have a different solution: the map camera and flight camera are two different structures, just like they are in the underlying API.  But they’ll share many of the same suffixes.

I might not have went with that approach if it were not for the fact that the existing camera access is through `addons:camera:flightcamera` - that is, it’s explicitly dealing with the flight camera, not whatever the current active camera happens to be.

**Comment by Dunbaratu** [comment]
I'm going to close this because it's more in the remit of the kOS-Camera addon mod, which @JonnyOThan is addressing there.
