### ISSUE TITLE
SHIP:AVAILABLETHRUST only gives available thrust for liquid fuel engines.

### ISSUE THREAD

**Issue by ACH1980** [KSP-KOS/KOS#2843]
As mentioned above the `SHIP:AVAILABLETHRUST` only gives me the available thrust for the liquid fuel engines. 

How I figured out? I had a script that locks the throttle to a given TWR and somehow it was way too high. Then I thought what would happen if I remove the solid fuel booster and then it calculated the same throttle and the TWR matched nearly perfect!

**Comment by Dunbaratu** [comment]
Question - is the solid booster firing when you query AVAILABLETHRUST or are you looking at it while it's not engaged yet?

If it's not including the solid booster even though the solid booster is firing then it's a new problem.
If it's not including the solid booster while it's not firing yet, then that's an already known thing.

**Comment by Dunbaratu** [comment]
Also, I need to see the ship design.  Because I never had this problem before and it may be something specific that only happens in some cases.

**Comment by ACH1980** [comment]
Yeah. The booster is firing. Please standby for ship design as for an image I need to go into WLan as my internet is very slow and it would take much time to send without WLan...

**Comment by ACH1980** [comment]
![20210116182426_1](https://user-images.githubusercontent.com/39656381/104818841-49811880-582a-11eb-822b-77336a2fcfbb.jpg)
![20210116182525_1](https://user-images.githubusercontent.com/39656381/104818842-4b4adc00-582a-11eb-9ddb-5cbc68e68ace.jpg)
![20210116182530_1](https://user-images.githubusercontent.com/39656381/104818845-4c7c0900-582a-11eb-9597-82cd70546f05.jpg)
![20210116181643_1](https://user-images.githubusercontent.com/39656381/104818847-4dad3600-582a-11eb-94c1-d62c80e83ec9.jpg)
![20210116181657_1](https://user-images.githubusercontent.com/39656381/104818848-4f76f980-582a-11eb-9563-a5de1d04bb3f.jpg)


So the first one is the script I wrote - don't be confused that it's called launch_to_orbit but ends at 10km, it's not done yet and I'm working on the first part.
The second and third one display the rocket flying and in the lower left you can see the TWR calculated from KER, which is pretty accurate. 
And in the other two you can see the rocket design - radial mounted items are mounted on both sides no matter of their sizes.

And when I remove the SFBs it's working fine it's holding almost exactly 1.05 TWR as intended.

**Comment by nuggreat** [comment]
Nothing is wrong with `SHIP:AVAILABLETHRUST` instead your problem is that you didn't account for the fact that the throttle only controls the liquid fuel engines but your code is written as if it can also control the solid fuel engines.  As about half your thrust is coming from the SRBs the script is calculating you as having a TWR of about 2 so it goes to half throttle.  This results in an actual TWR change is less than what you intended because half throttle still gives you about 0.5 TWR from the liquids and you still get about 1.0 TWR from the solids thus your net TWR is about 1.5.  So unless you split the thrust from the SRBs and the liquid fuel engines and calculate how much thrust change in the liquid engines you need to alter the total to the desired value it will never balance on the thrust you want.

In the future if a post includes code post the code as text not as a screen shot.

As for the code it's self, kOS does have the `:MAG` suffix on vectors should you want the magnitude of a given vector.  kOS does support `x^y` should you wish to do power calculations.  And lastly never have locks in a loop, the reason why that locks have a lot of complex C# code that executes when the given lock gets created and that complex code can lag your game should it execute to frequently.  Generally speaking it is considered good coding practice in kOS to avoid using `LOCK x TO y` unless you absolutely need to do so, which in the vast majority of cases should only be when you are locking `STEERING`, `THROTTLE`, `WHEELSTEERING` or `WHEELTHROTTLE` so you can control that element of your craft.

**Comment by ACH1980** [comment]
Ah thx. That's what I've overseen 🙈
