### ISSUE TITLE
Special variable TIME is being returned as TimeSpan instead of TimeStamp

### ISSUE THREAD

**Issue by eminterrupted** [KSP-KOS/KOS#2850]
Just starting to play around with the new release, and ran into an issue with the TIME variable. I have a script that updates a display with a field for the current game time. Prior to v1.3.0.0, this was done using the following statement:

`PRINT time:clock.`

After updating to v1.3.0.0, this now fails with the following error:

```
PRINT time:clock.
GET Suffix 'CLOCK' not found on object TIMESPAN(19323264.616226)
__________________________________________
           VERBOSE DESCRIPTION
GET Suffix 'CLOCK' not found on object TIMESPAN(19323264.616226)
An attempt was made to get a suffix called:
    clock
from an object of type:
    TimeSpan
when that object does not have that
suffix usable in that way.
Possible causes are:
  - No TimeSpan ever has a clock suffix.
  - There is such a suffix, but it can't be used
      with a get operation.
  - There is such a suffix on some instances
      of TimeSpan, but not this particular one.
__________________________________________
__________________________________________
At interpreter, line 16
PRINT time:clock.
      ^
```

Converting time:seconds to a TimeStamp then getting the clock suffix works, but if I am reading the [updated documentation](https://ksp-kos.github.io/KOS/structures/misc/time.html?highlight=clock#TIMESTAMP:CLOCK) right, the TIME variable should be returning a TimeStamp already vs. a TimeSpan. I'm not sure if this is a bug with TIME or a documentation bug.

**Comment by Dunbaratu** [comment]
Yeah that's wrong.  Thanks for catching it.

**Comment by Dunbaratu** [comment]
I'll probably put out a kOS v1.3.1.0 then before I announce it.

**Comment by Dunbaratu** [comment]
There's a few other places where constructors are expecting a TimeSpan instead of a TimeStamp that need fixing too - VelocityAt, PositionAt, etc.  Note to self: I need to find all instances of TimeSpan constructors and analyize them carefully.  I thought it wasn't really be used anywhere internally and only 'seconds' was being used as a number, but it turns out it totally was used in a few places that should change to TimeStamp.  TIME() isn't the only affected function.  I'll look at it tomorrow.  I was going to look tonight because I thought it was a 5 minute fix but the need to look everywhere else too makes it a bit more than I trust myself to do while sleepy.

**Comment by eminterrupted** [comment]
Awesome, thanks for the quick reply, and I appreciate all you do!
