### ISSUE TITLE
KosProp Monitor (input character in mfd don't work)

### ISSUE THREAD

**Issue by Massetstephane** [KSP-KOS/KOS#2861]
hi !
There a bug in mfd terminal with the plugins kOSPropMonitor. (using rasterprop mfd)
button work, but it's impossible to write something on the screen.

the error: 
Exception:MissingMethodException:void
Kos.screen.TermWindows.ProcessOneInputChar(char,kos.UserIO.TelnetSingletonServer,bool).

the log file 
[KSP.log](https://github.com/KSP-KOS/KOS/files/5871853/KSP.log)

**Comment by StoneBlue** [comment]
Could this post be related? vOv
https://forum.kerbalspaceprogram.com/index.php?/topic/98801-release-final-kospropmonitor-iva-kos-monitor/&do=findComment&comment=3898680

**Comment by Massetstephane** [comment]
Yes no problem if can help someone
Steph.

Le mar. 26 janv. 2021 à 12:57, StoneBlue <notifications@github.com> a
écrit :

**Comment by JonnyOThan** [comment]
This is an incompatibility between kOSPropMonitor and the new version of kOS.  KPM is calling ProcessOneInputChar via reflection, but the signature of that function changed in KOS 1.3 (added an extra bool parameter).

@Dunbaratu : in the interest of compatibility, you could provide an overload with the same signature as the old one, if there is a a reasonable default value for the new parameter.

Otherwise, this issue needs to be raised on the kospropmonitor bug tracker.  Or downgrading to the previous version of KOS will also work around it.

**Comment by Massetstephane** [comment]
hi ! 
ok thank, I'm back in kos 1.2.1.
I also posted on the GitHub kOSPropMonitor , same information.
I hope **dsonbill** continues to update it.
steph.

**Comment by Dunbaratu** [comment]
@JonnyOThan - this is the new new signature in kOS:
```
public bool ProcessOneInputChar(char ch, TelnetSingletonServer whichTelnet, bool allowQueue = true, bool forceQueue = true)
```
and this is the call in KosPropMonitor, from looking at the github page:
```
processor_shares[current_processor_id].Window.ProcessOneInputChar(command, null);
```
When I added the additional ``bool`` parameter, I specifically made it use defaults so calling it the old way would still work.  Calling it with two args as the code chose, or three args as the error message posted here shows, should both work as far as I can tell.  But apparently C# does its arg defaulting at compile-time, not at runtime, so the previously compiled kOSPropMonitor DLL is hardcoded to expect 3 parameters exactly, even when the code calls it with two.  (the defaulted extra 3rd parameter must be happening at compile-time and then the call is built hard-coded to expect an exactly 3-arg call to exist.)

This is news to me.  I expected arg defaulting to occur at runtime or at least at load-time, so that using default args would be *identical* in functionality to having two different variants of the call, one that calls the other.  But apparently it's not, when the caller was already previously compiled.

**Comment by Dunbaratu** [comment]
@JonnyOThan  or @Massetstephane if I give you a link to a recompiled kOS.DLL file on my google drive, can you test it for me and verify for me that it fixes the problem?

**Comment by Massetstephane** [comment]
hi !
I also have the tools to recompile but I'm not a sufficient level to use the code provided in GitHub, so yes I'd like to test your KOS version, it's a change on the KOS plugging or on that of KOSpropMonitor? I use two actively at the moment, I'm doing some kind of autopilot.
I think it is preferable to try to modify KOSpropMonitor instead of KOS, by what KOS evolves. everyone uses it while KOSpropMOnitor and less use.
_(I hope the translator worked well)_
steph

**Comment by JonnyOThan** [comment]
Yeah, I could test it today.

**Comment by Dunbaratu** [comment]
@Massetstephane  - I've sent you the link as a private message on the KSP forum
@JonnyOThan  - I've sent you the link on Discord.

Report findings here on the github issue.

**Comment by JonnyOThan** [comment]
Confirmed that I could repro the issue with KOS 1.3.2 and KPM 1.7.1.

The private build does *not* fix the issue - it looks like KPM is looking for a function that returns void.  Was the return type also changed?

**Comment by Massetstephane** [comment]
Yes tested , and again it's seem as the same error !
`MissingMethodException: void kOS.Screen.TermWindow.ProcessOneInputChar(char,kOS.UserIO.TelnetSingletonServer,bool)
kOSPropMonitor.kPMCore.Type (System.Char ch) (at <30ead3a6ce004400a7bd1a06d5f99b3d>:0)
kOSPropMonitor.kPMCore.ProcessKeyEvents () (at <30ead3a6ce004400a7bd1a06d5f99b3d>:0)
kOSPropMonitor.kPMCore.OnGUI () (at <30ead3a6ce004400a7bd1a06d5f99b3d>:0)`

[KSP.log](https://github.com/KSP-KOS/KOS/files/5882842/KSP.log)

steph.

**Comment by Dunbaratu** [comment]
> 
> 
> Confirmed that I could repro the issue with KOS 1.3.2 and KPM 1.7.1.
> 
> The private build does _not_ fix the issue - it looks like KPM is looking for a function that returns void. Was the return type also changed?

But .. but.. arrrg these rules around one DLL calling another are so ridiculously arbitrary.

It's entirely legal to call a method as if it was void even though it has a return value.  that just means it throws the return value away and ignores it.  The kOS mod itself does that all over the place with ProcessOneInputChar(), and there's literally only one place it bothers looking at the return value.

**Comment by Dunbaratu** [comment]
So reading up on this, again this is apparently another thing where C# does the logic at compile time not runtime.  At *compile time* when you call a method that returns a value, but you call it as if it was void (don't read the return value) it recognizes the need to build in one more instruction that will pop the return value and throw it away.  If you compiled it while the return type was advertised as being void, then the compiler does not build that "pop the return value" logic in there because it didn't expect there to be one.  That's why at load time the DLL is insistent that void methods stay void or they don't count as a match.

**Comment by JonnyOThan** [comment]
Confirmed the new version works correctly.
![screenshot5](https://user-images.githubusercontent.com/9804078/106062808-28cb8500-60ac-11eb-89e7-1052897d6ea6.png)

**Comment by Massetstephane** [comment]
Perfect !!
[here](https://youtu.be/DvmIUWLPoF0) a video to show the modified mfd and special kos mfd
Aset MFD are now animated buttons, knob for brightness, added some details in mfd mu, and visual enhancement on mfd text page. (added special frequency radio page,  Buttons grp page, etc)
steph.
