### ISSUE TITLE
doAction("disengage servo lock"). seems to be broken

### ISSUE THREAD

**Issue by sVaterlaus** [KSP-KOS/KOS#2871]
Whenever I run `doAction("disengage servo lock").` on one of the Breaking Ground hinge parts, it does unlock the hinge, but it does not reveal the `target angle` and `traverse rate` fields. Whereas actually clicking the button to unlock the hinge does reveal those fields.

This seems like a serious issue as being able to lock and unlock robotic parts is a requirement for custom landing gear or parts that need to hold their angle under aerodynamic load.

I don't know if it's a KOS problem or a limitation of the Breaking Ground parts.

**Comment by Dunbaratu** [comment]
It's an annoying limitation baked into the Breaking Ground parts - their fields never update unless the part action window is open.  They embedded too much of the basic functionality of the parts in the GUI instead of underneath in the main game, so mods that bypass the GUI like kOS have no hope of reading the values.

**Comment by sVaterlaus** [comment]
Shoot. =(

Alrighty, thanks. That's a bummer.
