### ISSUE TITLE
WARPTO returns nothing when it could return whether or not a WARP was initiated

### ISSUE THREAD

**Issue by mgalyean** [KSP-KOS/KOS#3013]
Apparently there is some threshold for the arg to WARPTO to actually initiate a warp.  Because scripts often want to wait until a warp rate increase actually occurs prior to waiting or the warp to complete and settle the current situation makes the logic after calling WARPTO overly complex as the code can't tell if a warp was actually inititated.  If the code only waits until warp has settled, it may continue before a valid warp has even initiated, but if it waits for a warp to occur, it apparently can wait forever currently in some cases.

If it returned a boolean or something to indicate whether a warp was initiated or not it would really clarify the script code and make it more reliable.  Currently I'm waiting for RATE to increase, with a timeout.

Short of a kOS change, the docs need to specify what the minimal timespan into the future WARPTO will respond to.

Or maybe there is a bug where it simply doesn't initiate a warp on occasion for mysterious reasons and because I'm working with smallish spans I can't tell the difference.

**Comment by nuggreat** [comment]
`WATPTO()` is a wrapper on a call to the KSP API which returns nothing after being called.  Therefor any detection of warp initiation would require halting the script's execution for several ticks after the warp call so that kOS could check if warping actually started happening.  As to minmum thresholds again call to the API we do not know what limits exist within the function, what they are or if they are the same in all cases.

**Comment by mgalyean** [comment]
Well, darn.  I'll close this out then.  What a strange thing.  I'll do some testing and see if I can characterize any min limits on the args and if I come up with something viable will put in issue for docs then.  Thanks for the info
