### ISSUE TITLE
nonexistent

### ISSUE THREAD

**Issue by Mad1flin2** [KSP-KOS/KOS#3050]
I copied the script from the quickstart and kos acted like it didn't exist.

**Comment by nuggreat** [comment]
How exactly did you copy the script and what did you do to check it exists.

**Comment by Mad1flin2** [comment]
I copied the script, opened notepad and pasted it, then went to the archive and ran it.

**Comment by nuggreat** [comment]
If that is exactly what you did then there are a few possible things that might have caused an issue.

First and least likely you simply forgot to save the file to the archive.

Second you didn't have the correct file name.  This is often caused by the file extension where a user has saved the file as `somefile.ks` but because notepad is "helpful" and you where not using the saveAS function your file actually got saved as `sonefile.ks.txt`,  if this is the case then your run command would need to be `run somefile.ks.txt` to actually run the file presuming the working directory is currently set to the archive.  Something similar applies if you had saved the file as `somefile.txt` as kOS will only automatically run files with the `.ks` extension if you do not supply an extension as part of the run command.

The simplest check for both of these is the `LIST.` command as it shows the full name of all files in the current working directory as well as telling you what the current working director is.

**Comment by Mad1flin2** [comment]
I don't think I did anything wrong, but I can record a video of what I did if that helps.

**Comment by nuggreat** [comment]
Recording a video that I can review for where you might be making the mistakes could help.  The key things I would need to see opening the archive folder from the root KSP folder as well as viewing the files in detailed file view with the file types viable,  Naturally I will also want to see the commands you are trying to type in the terminal as well as what errors kOS is responding with.

The reason why I on the other hand am more sure that you have been making some mistake is because you are the one of only a small handful of people who have had issues with the archive and in all other cases it has been user error.  There is a remote chance that your OS has messed up the premissions of the archive but that is remote
