### ISSUE TITLE
`:VARNAME` get-only suffix on structure 

### ISSUE THREAD

**Issue by darthgently** [KSP-KOS/KOS#3066]
This suffix would return the variable name.

The use cases are as varied as uses for the kos tag field on parts.  Creating a lex indexed by foobar:varname would allow creating simulation variable dependency trees, tracking previous values of the variable for derivation and integration, auto labeling variable dumps to logs, and meaningful default label names in GUIs and terminals.  All with far less verbosity than otherwise and would self document the code to a high degree. 

Data maintenance/update function references for the variable could be stored in a varname indexed lex, change listeners could be registered. A lot of lock-ish similar and other logic, but more flexible, could be customized only for specific variables without the overhead of having it there for all variables.  

So, sort of analogous to a "kos tag" for variables, but more flexible as the "tag" is just the variable identifier and the scripter provides the lex, as complicated or as simple as they want to make it, indexed by that variable

**Comment by darthgently** [comment]
Oops, forgot anonymous would return whatever kos uses internally for it stringified

**Comment by nuggreat** [comment]
Tying to understand what exactly you are asking for because to me at first read doing something like `PRINT foo:VARNAME` means I would expect "foo" to get printed to the terminal as that is indeed the name of the var used, so why not just do `PRINT "foo"` and save my self some effort.

The closest I can get to something that might be useful would be able to reach past the variable and add some additional data to the underlying thing being reference by the var that then always follows the reference regardless of what name the var the reference is held in uses.  But even this I don't see as adding anything useful that can't be done by a user either by extending there lexicons by one additional key value pair or by simply passing in the relevant identifiers when they call for logging.

**Comment by darthgently** [comment]
The multiple reference to the same underlying variable is a good point.
How about a suffix that is a lex on the underlying var where the restrictions on keys for suffix names would not exist and entire trees could hang there. Yeah I know there other ways to do things, but given that approach we'd all be assembler still.  The lex would only be instantiated when first assigned to so no overhead in the normal case other than a placeholder

**Comment by darthgently** [comment]
What got me going on this was the need for a syntax that is more data driven for simulation updates and I want to attach dependencies to the vars.  I want to be able to pass a single var to a function and have that function have easy access to all the baggage

**Comment by darthgently** [comment]
A normal lex would work, most of the time one just wants to value of `foo` and having coffee bloat from accessing `foo["value"]` in 9 out of 10 cases is hard to read and maintain

**Comment by nuggreat** [comment]
To me this sounds like it would be solved by simply building out a lexicon holding all data relevant to the simulation and then passing it to the functions that make up the simulation as needed.  Or yet just having all relevant data in local vars within the simulation's scope and do away with a holding structure beyond the scope of the simulation it's self.  One doesn't always need the data structures and this really feels like a case of adding more complexity to a complex thing in an effort to simply things which usually doesn't work.

**Comment by darthgently** [comment]
While I welcome the push back, the simulation was just one of many use cases I listed. I prefer terser, more readable, more easily maintained code than the alternatives you mention.  No worries.  I'll just close it
