### ISSUE TITLE
kOS refuses to let go on CPU poweroff.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#359]
To recreate:

Make a program that does this at any point during a flight:
```
LOCK STEERING TO UP.
wait 1000.
```

Then run it, let the steering settle to its new orientation, then power off the CPU itself via the new applauncher panel, and turn it back on again.

Now when you try to manually steer the ship you can do it a little bit but you're fighting a force that wants to recenter you.  When you let go of the controls, the ship rotates back to the steering setting it had when kOS module was still on.  There appears to be NO way to undo this.  ```lock steering``` and ```unlock steering``` don't help.  Powering it off and on again does not help.

I discovered it via the applauncher, but I suspect the problem is connected more to the new changes to the steering system and would also happen if you rightclicked the part and powered it down.

**Comment by austinjames314** [comment]
Aha! This bug has absolutely doing my head in. I thought I was doing something wrong, but it turns out it's a bug all along.
 Please fix this! I basically can't get anything to work, because as soon as the kOS module loses power on the night side, it's basically broken from then on. Then because steering wont respond, I can't point the solar panels at the sun, and things go downhill from there.

**Comment by Dunbaratu** [comment]
Is this still happening in 0.15.5?  I know piloting went through a bit of a redesign but if this is still a problem then this really needs to be dealt with.

**Comment by austinjames314** [comment]
I just triple checked: Yes it's 0.15.5. Downloaded the new version a few hours ago.

I'm 99% sure it's the same thing. The difference to the steps in the first post above are, that I'm powering off either due to running out of electric charge, or via the right click menu of the part. (If it matters, it's a probe core that I added the kOS Module to, due to the kOS parts not staying attached).

I've tried 'UNLOCK STEERING.' a few times to no effect. Saving and re-loading seems to fix the problem up until the next power-off.

**Comment by austinjames314** [comment]
While futzing around trying to get my probe to rotate 90 degrees, I think I just managed to reproduce this without losing power or shutting down (Oh yeah, I think the 'SHUTDOWN' command also triggers this bug. I don't know at what point it started though, so I'm sorry to say I can't say what I did to cause it. I'll post more if I notice anything specific.

**Comment by go1dfish** [comment]
I've been running into this sort of behavior on a script that lock's steering to a variable at startup and changes that variable throughout the flight to new direction instances created from HEADING(..) or NODE:DELTAV:VEC:NORMALIZED:DIRECTION

Also experience it on manually triggered poweroff/shutdowns.  Running latest kOS in 0.90

**Comment by austinjames314** [comment]
I don't know, I think #490 is just a PID tuning issue, rather than a bug per se. But yeah manual poweroffs of the kOS module consistently cause the steering to get permanently locked.

**Comment by go1dfish** [comment]
One other thing to note in my case, I am toggling sas on and off in between variable changes without a relock on steering.

**Comment by Wercho** [comment]
Running out of EC on the ship (and thus powering off the kOS terminal) while a lock steering command is active also triggers the bug, which is how I ran into it.
