### ISSUE TITLE
Unable to view terminal window

### ISSUE THREAD

**Issue by xyztdev** [KSP-KOS/KOS#37]
Sometimes I will accidentally drag the kos window off of the screen. After this, I cannot access the kos window anymore.

I must reinstall the plugin to fix the problem; this is very annoying.

To reproduce, drag the kos window rapidly off the screen when not in fullscreen.

**Comment by Dunbaratu** [comment]
I am now of a different opinion than I was before.  I now think that it's wrong to constrain the window to the edges of the screen, because having a window hanging "half off" the screen is a thing you want to do temporarily to look at something underneath it.

I'd like to have this closed as a "won't fix" if that's okay with you, @erendrake.
