### ISSUE TITLE
LOCK STEERING broken for RCS-only (no torque) ships.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#389]
Problem described here:

http://forum.kerbalspaceprogram.com/threads/68089-0-25-kOS-Scriptable-Autopilot-System-v0-15-0-2014-11-16?p=1548099&viewfull=1#post1548099

**Comment by soulsource** [comment]
While I don't know how to fix this, I can meanwhile tell you where the bug probably sits:
The if-block starting at line 170 of Utilities/SteeringHelper.cs

If I understand that code correctly, it currently approximates the maximum possible torque for pitch/yaw of each RCS block by simply multiplying its maximum thrust with the distance to the COM, what is a reasonable approximation for very long ships.
Nevertheless, the contribution of RCS blocks to roll adjustments is completely neglected.

While I don't know how to fix stuff, as I have no idea about C# and even less about the KSP plugin API, I can outline how I would improve (not fix - a fix would require to treat yaw and pitch separately) that calculation:
I'd try to extract vectors for all possible thrust directions of the RCS block, and the direction of the ships roll axis. Then, for each RCS thrust direction, I'd calculate the magnitude of the cross product and of the dot product between thrust direction and roll axis, and add them to the corresponding torque variables (of course: cross product means roll torque, dot product means pitch/yaw torque).

**Comment by soulsource** [comment]
I "fixed" the issue for my own build. Basically, for reasons I don't fully understand, the RCS blocks need to be accessed as PartModule instead of using the RCSModule part type. I also tried to improve the torque prediction slightly, but it's still just a rough approximation, assuming a fully pivoting RCS nozzle... The GetTorque function anyhow has some additional issues (like not taking into account the position of reaction wheels - Huygens-Steiner theorem), if I understand it correctly, so being less than fully exact here will probably not hurt.

As I'm new to git, it might take a few hours until I figure how to fork the KOS repositoy and to submit a pull request, but be assured that you'll see one soon.

**Comment by soulsource** [comment]
Ok, pull request sent.

**Comment by soulsource** [comment]
Commit d8aed05a78745ae0675f89d4e99a3004c874c2c9 brings checks for thruster fuel availability (per part, as not all thrusters need to use the same fuel(s) if mods altering the fuel system are installed), and only takes thruster ports into account that aren't disabled (either individually or globally by using the RCS toggle). 
Commit 05cf4ea1cd7ff263e0729ca3ca14f424ea42c83e should now give the correct torque values (they are the same as those output by Mechjeb, if that's a measure).

**Comment by hvacengi** [comment]
Closed via #1118
