### ISSUE TITLE
Missing texture png

### ISSUE THREAD

**Issue by eos101** [KSP-KOS/KOS#434]
Complete noob here.

having an issue with KOS v 0.15.2.

I tried installing to ksp/gamedata file, seemed to work fine until i try to open the GUI, I'm informed that "Some or all kOS textures were not found". I've checked out the texture folder and they're all there (as far as i can tell). I also tried moving the GFX file over to pluggindata as some have suggested to no avail, I have also individually placed each folder in corresponding folders i,e parts to parts and so on

I'm getting desperate, i have trawled the net for solutions and surprisingly have not found any.

**Comment by spil-peter-forgacs** [comment]
im having the same problem but i cant seem to fix it

screenshot](https://cloud.githubusercontent.com/assets/2805461/7277189/dba9932c-e90e-11e4-848a-252a75832d5b.png)
this is the screenshot

**Comment by TheBlueAmazingDragon** [comment]
i seem to be having the same problem
this is the screenshot
[screenshot](https://cloud.githubusercontent.com/assets/11232163/7277280/78fb1d58-e90f-11e4-8420-f4d0f331dc9b.png)

**Comment by hvacengi** [comment]
@TheBlueAmazingDragon I just installed from scratch and have had no issue like this.  Can you share your log file ("ksp.log" in the same folder as the "ksp.exe" executable)?  Also, is the screenshot from "[ksp directory path]/GameData/kOS/GFX/"?  If every thing is in the correct installed location, I'd suggest opening a new issue since it looks like this closed issue was a problem with installing to the right folder.  I'm going to test on my game locally, but my first reaction is that it sounds like kos is in the wrong folder.

**Comment by hvacengi** [comment]
I just ran a quick test, and installing in the wrong folder will cause the error in the screenshot I'm attaching at the bottom.  If this is the error you have received, make sure you install the mod so that the GFX folder is located at "[ksp directory path]/GameData/kOS/GFX/".

![screenshot1](https://cloud.githubusercontent.com/assets/2975036/7278215/fa6d2de6-e8e1-11e4-87a4-3a1623beca64.png)

**Comment by TheBlueAmazingDragon** [comment]
file:///E:/Soma/kerbal/ksp/Kerbal%20Space%20Program/KSP.log
my kos is in Kerbal Space Program\GameData\kOS_Scriptable_Autopilot_System-0.17.1\GameData\kos\gfx
also i have a few other mods : bdarmory, kerbal foundries and tweakscale

**Comment by hvacengi** [comment]
There you go.  Wrong folder.  move the "kos" folder (and it's contents) so that it is inside the first "GameData" folder.  Your other mods should follow a similar trend.  You should never have a 2nd "GameData" folder in the chain, and rarely should you have a folder named for the zip file it came from.

**Comment by TheBlueAmazingDragon** [comment]
Ok thanks, i was wondering if that was right because none of my other mods did that, its fixed now
