### ISSUE TITLE
Compare Part

### ISSUE THREAD

**Issue by andrey-zakharov** [KSP-KOS/KOS#501]
I've failed with simple case:
```
SET p to ship:rootpart.
print p.
print ship:rootpart.
print (p = ship:rootpart).
```
with 
> print ( p = SHIP:ROOTPART ).
>          ^
> [LOG 16:04:42.266] System.NullReferenceException: Object reference not set to an instance of an object

Ok. lets check it by UID:
```
print ( p:UID = SHIP:ROOTPART:UID ).
```

Wuah:
> print ( p:UID = SHIP:ROOTPART:UID ).
>               ^
> 
> [LOG 16:05:14.893] System.NotImplementedException: Can't operate types System.UInt32 and System.UInt32

**Comment by erendrake** [comment]
Confirmed that this script does cause the problem. 

@Dunbaratu the error is in the function because the node that gets popped is apparently null? looked at the visit code and what gets pushed is an expr. 

actually the following fails as well. i am no longer thinking that this is a simple equality issue. 

    print body("kerbin") = body("kerbin").

    [LOG 07:23:06.351] System.NullReferenceException: Object reference not set to an instance of an object
  at kOS.Function.FunctionPrint.Execute (kOS.SharedObjects shared) [0x00000] in <filename unknown>:0 
  at kOS.Function.FunctionManager.CallFunction (System.String functionName) [0x00000] in <filename unknown>:0 
  at kOS.Execution.CPU.CallBuiltinFunction (System.String functionName) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Compilation.OpcodeCall.Execute (ICpu cpu) [0x00000] in <filename unknown>:0 
  at kOS.Execution.CPU.ExecuteInstruction (kOS.Execution.ProgramContext context) [0x00000] in <filename unknown>:0 
  at kOS.Execution.CPU.ContinueExecution () [0x00000] in <filename unknown>:0 
  at kOS.Execution.CPU.Update (Double deltaTime) [0x00000] in <filename unknown>:0

**Comment by erendrake** [comment]
and the fragment. 

    [Log]: Code Fragment
    File                 Line:Col IP   opcode operand
    ----                 ----:--- ---- --------------------- 
    interpreter history    18:5   0055 push null 
    interpreter history    18:5   0056 call run() 
    interpreter history    20:5   0057 push $eq 
    interpreter history    20:16  0058 push kerbin 
    interpreter history    20:16  0059 call body() 
    interpreter history    20:33  0060 push kerbin 
    interpreter history    20:33  0061 call body() 
    interpreter history    20:26  0062 eq 
    interpreter history    20:26  0063 store 
    interpreter history    21:7   0064 push $eq 
    interpreter history    21:7   0065 call print() 
    interpreter history    23:12  0066 push kerbin 
    interpreter history    23:12  0067 call body() 
    interpreter history    23:29  0068 push kerbin 
    interpreter history    23:29  0069 call body() 
    interpreter history    23:22  0070 eq 
    interpreter history    23:22  0071 call print() <<--INSTRUCTION POINTER--
                            0:0   0072 EOF

**Comment by Dunbaratu** [comment]
@erendrake - not it's not null on the stack - here's the proof that that's not it:
```
set k1 to body("kerbin").
set k2 to body("kerbin").
print k1:name.  // No error here - works fine and prints "Kerbin".
print k2:name.  // No error here - works fine and prints "Kerbin".
print k1:name = k2:name. // No error here - works fine and prints "True".
print k1 = k2. // Throws the Null reference exception.
```
There must be a bug in what the EQ opcode is doing when comparing a Structure to a Structure.

I suspect fixing this must be intertwined with also fixing issue #459

**Comment by Dunbaratu** [comment]
I've split out the Part:UID problem into a separate issue #504 so I could solve the equality issue separately.
