### ISSUE TITLE
RemoteTech integration is broken

### ISSUE THREAD

**Issue by geoffromer** [KSP-KOS/KOS#515]
The RemoteTech integration feature does not seem to be working: my scripts cease executing as soon as the ship loses its connection to KSC. I'm running RemoteTech 1.6.0 and kOS 0.15.5. I can provide more details if it will help, but my impression from the forums is that this breakage is not hard to reproduce.

**Comment by Dunbaratu** [comment]
What I saw in the forums was hints that it works with an older version of RemoteTech.  That whatever the problem is, it's something that started happening not because of anything kOS changed, but because of something RemoteTech just changed in their most recent release.

Not sure if that helps, but it might give people somewhere to start looking for the cause.  Look for what  recently changed over at RemoteTech and see if we have to change anything at kOS to match up with it.

**Comment by SirDiazo** [comment]
The remotech 1.6 changelog from a few days ago states that remotech changed their external API.

Probably simply a matter of point kOS at the new methods.

**Comment by geoffromer** [comment]
This is probably expected, but FWIW I've just confirmed that the handling of signal delay is also broken: commands from kOS scripts are delayed as though they were issued from KSC rather than being executed locally on the craft.

**Comment by erendrake** [comment]
@geoffromer that is the expected behavior when kOS cannot find the remotetech api. which is has in this case.
