### ISSUE TITLE
kOS, AGX, and RemoteTech on the same install

### ISSUE THREAD

**Issue by SirDiazo** [KSP-KOS/KOS#519]
Okay, for Action Groups Extended I am now looking at making it work with RemoteTech.
That is straightforward, and off-topic.

However, if a player has all 3 mods installed, what is the desired behavior? (kOS, AGX and RT)

I know kOS has a RemoteTech button, should I be changing what AGX does based on the state of that button?

Actually, is there any documentation of how kOS integrates with RemoteTech I could maybe use as a start point?

I'm asking the basic "how it should work" question here, I'm not looking at code yet, still need to know how it is supposed to look from the player's perspective.

**Comment by erendrake** [comment]
Im sorry i missed this @SirDiazo. I actually have been tempted to remove the "RT" toggle from kos because i dont actually see a good reason right now for anyone to turn it off. We have pretty poor documentation around the integration and that is an issue that needs to be fixed. 

the import parts of the RT API we use are:
* When there is no RT connection to a command post, and its an unmanned craft. You cannot issue commands
* When there is no RT connection to the KSC, but the craft is manned. You cannot access the archive
* When issuing commands to a remote terminal, those commands are delayed by the RT signal delay, if that is turned on in the remote tech config.

overall, the only thing i would say for AGX is that modifying or triggering action groups shouldnt be possible when there is no connection. the reason i say that modification should be disabled is that is information you are sending to the craft about configuration. kOS users could be running a script and triggering an action group that you are reconfiguring and that would break the wall. 

actually i guess you could delay triggering action groups by the signal delay too. that would be pretty neat :)

Sorry again that this fell through the cracks

**Comment by Dunbaratu** [comment]
I dislike the statement:

"modifying or triggering action groups shouldnt be possible when there is no connection",

and would prefer it be:

"modifying or triggering action groups shouldnt be possible **via manual controls** when there is no connection **and the craft is unmanned**."

A kOS script that was run prior to losing connection and is therefore still running after the connection is gone should be still allowed to execute "AG15 ON."

Similarly, a manned vessel should still be able to do it too.

**Comment by erendrake** [comment]
@Dunbaratu you are right, i managed to confuse myself :) fixed it

Now that i think about it there will be no way for @SirDiazo to know the difference between kOS triggering his API and some other mod triggering it that is not obeying RT limits. At least he could tell its an API call vs manual user input

**Comment by Dunbaratu** [comment]
Yeah that's a messy problem.

In general, not just for AGX mod.  It's the same problem we had for a long time with RT.  Any mod that wants to disable USER input tends to also disable our inputs too because it can't detect the difference in how things are being done.

**Comment by SirDiazo** [comment]
Yes, I've been pondering this.

While it is AGX specific and would require adding more code to kOS to support it, the best solution is to have AGX expose 2 API calls, one that checks RT for delay (user input) and one that executes immediately (running script). (Or expose one API call with a flag for which type of situation we are in.)

In order to support RT I've had to go and add those two API calls anyway so they exist on the AGX side of things, it's just a question of how to make kOS aware of the fact that AGX now has 2 api calls. (Assuming this is the solution decided upon.)

**Comment by erendrake** [comment]
Well, you know we could just have an optional delay param on the call to AGX, 

* if the delay is specified AGX uses it
    that way kOS and other mods can determine the correct delay from looking at RemoteTech and its own status     

* if the delay is not specified, AGX decides
    instant unless remotetech is around

**Comment by SirDiazo** [comment]
Actually, i was thinking and kOS calculates the delay anyway doesn't it? It would have to in order to pass a delay value to AGX

If so, just use the one API call to execute the action after the delay, just have the delay internal on the kOS side.

Note that I'm assuming that kOS does this anyway for action groups if AGX is not installed so it would be a reasonably easy way to do this. If not, it is not a huge deal to add a "action on delay" API call to the AGX side of things.

**Comment by erendrake** [comment]
That works for me.

**Comment by abarbe-** [comment]
From my observations, it looks like kOS and AGX behave great together currently; is that a sign that this discussion should get closed / these issues were discussed to resolution elsewhere?

**Comment by SirDiazo** [comment]
Yes, as far as I am aware things are working okay.

I plan to test a kOS/AGX/RT setup soon as I'm not sure all three play nice, but that's over here in ticket #1246 

Closing this thread as I think any further discussion should be in #1246
