### ISSUE TITLE
Construct GeoCoordinates from position

### ISSUE THREAD

**Issue by geoffromer** [KSP-KOS/KOS#522]
It would be awfully handy to be able to construct a GeoCoordinates object from an arbitrary position vector. This isn't a showstopper since I can always do the math myself, but it does tend to clutter up the code (especially with no support for user-defined functions).

**Comment by Dunbaratu** [comment]
Agreed.  I'm unsure if it should be a geocoordinates constructor or just a way to obtain latitude and longitude as suffixes and you make a geocoorinates of it yourself.  But one way or the other, it should be made possible.

**Comment by geoffromer** [comment]
Latitude and longitude are rarely useful in isolation, so I'd argue this shouldn't take the form of separate latitude and longitude suffixes; if it's a suffix it should be a single suffix that returns a geocoordinates structure. However, I'm (less strongly) inclined to say it shouldn't be a suffix, but a geocoordinates structure. For one thing, geocoordinates is a more specific type, and it seems messy for a generic type like vector to refer to a more specific one. For another, the result of this operation would implicitly depend on where and when you execute it, which makes it like a lot of geocoordinates operations, but unlike any existing vector operation (AFAIK), so it fits in a lot better with geocoordinates.

(Sorry, I'm an API design nerd. I'll try to control myself.)

**Comment by Dunbaratu** [comment]
I'd prefer ```set pos to someVector:GEOPOSITION.``` over ```set pos to geoposition(someVector).```.

This is simply because of a thing you might not realize about the underlying layout of the kOS code.  Function calls like geoposition(someVector) are using a sort of older technique I'd like to see go away some day - of built-in functions that only deal with multiple overloaded variants by some ugly trickery under the hood.  Until true overloading is possible, I'd rather not do it that way.  

(The problem with function prototype overloading is that the kOS CPU can't tell how many arguments you've passed to a built-in function.  IF you say func(c,b,a) or func(a), it can't see the difference after popping 'a' off the stack as to whether or not it needs to pop more args off or stop there  (there's no 'bottom of args' marker or count of how many args on the stack for these type of built-in functions).  (This is why there's two constructors for vecdraws, vecdraw() and vecdrawargs() They had to be named different in order to work.))

Because the overloading doesn't work well, that's why I'd prefer a vector suffix to overloading the geocoordinaes construcor.

**Comment by Dunbaratu** [comment]
I just started implementing this (it looked easy) and I've changed my mind - **neither** the constructor function **nor** the vector function are the right place for it.  The *right* place for it is really the **Body**.  I had been trying to pass the method a body, as in: ```vec:geoposition(Body("kerbin")).``` (Because you want to know the body you are projecting the position down onto.  Just because the position is in the SOI of Kerbin doesn't mean you can't calculate its longitude above the Mun's surface if you want.)   Then it occurs to me that it's really a function of the body itself.  It's not "ask the vector to tell me it's position relative to a body"  It's "ask the body to tell me the latitude/longitude of a position in space above it".

So now I'm going to make it a suffix of body.  Like so:  ```set gPos to Kerbin:Geoposition(aVector)```.

**Comment by geoffromer** [comment]
I completely agree that it belongs with the body. I didn't bring that up because the rest of the geoposition API just implicitly refers to the current SOI body, and I thought it'd be better to be consistent with that. If that whole magical implicitness thing is up for discussion, though, it'd be nice to avoid implicitly depending on the current _time_ as well. In practice, that's more likely to be a problem than the dependency on the body, because I'm more likely to want to talk about the geocoordinates of my future position (e.g. my impact site) than to want to talk about geocoordinates on some other body.

So could GEOCOORDINATESOF take a time parameter?

**Comment by Dunbaratu** [comment]
hmm.  "what will the geocoordiantes of this position be at some arbitrary future time T"...  That's not bad.  There already is a sort of predictive API for vessel location (which, by the way, I need to get around to moving into a method suffix instead - those functions like POSITIONAT were written before suffixes could be methods), so a similar one for geocoordinates might be smart.

I'd suggest making the future time prediction a separate issue, though.  This issue didn't mention future predictions originally so within the remit of THIS issue, I think the pull request I already did solved it and this issue can be closed when it's merged in.

A new, second issue, asking for the future time predictions, would be a cleaner way to manage it.

**Comment by geoffromer** [comment]
Sure, sounds good.
