### ISSUE TITLE
ENGINE:THRUSTLIMIT being clamped to 0..1 instead of 0..100

### ISSUE THREAD

**Issue by NaridaL** [KSP-KOS/KOS#538]
Setting ENGINE:THRUSTLIMIT expects a percentage, but the passed value is being clamped to 0..1, rendering it pretty useless.
I've traced the issue to the following commit:
https://github.com/erendrake/KOS-1/commit/73661a1eb39f9bd392413d9d314c1af45143f62c#diff-8f94cb2f0d2ce25080591180a75f3360L23

**Comment by Dunbaratu** [comment]
I am of the opinion that this is an error in SQUAD's design.  They made the ranges for throttle scaling inconsistent with themselves, varying depending on what you're using them for.  FlightCtrlState.MainThrottle expects [0..1], while ModuleEngine.thrustPercentage is a percentage from [0..100].

Both are presented to the USER in the UI as if they were percentages from 0..100, but only one of them actually is in the code.  The code should have been just as consistent with itself as the UI was, but squad chose otherwise.

Ideally I'd prefer it if we could scale THRUSTLIMIT to the range 0..1 by scaling it internally under the hood, so it *would* be correct to clamp to 0..1 in kerboscript because under the hood we'd multiply it by 100 before giving it to the API, and divide it by 100 when reading it from the API.

In other words, the fix would be to make THRUSTLIMIT actually work on the same range as THROTTLE, rather than change the clamping rule and exposing the ugly inconsistency to the scripts.

Notice I keep saying that I "would" say that's the right answer and I'd "like" that to be the right answer, rather than saying it *is* what we will do.

Here's why we probably can't do that, sadly:  The alternate way to set thrustlimit is to set it via PartModules as a SETFIELD() call.  When you do that, you can't escape from the fact that the limit is really ranged [0..100] in SQUAD's thinking, because thrustPercentage is actually a KSPField you can manipulate directly.  Wih KSPFields,, there is a one-to-one mapping between the UI's displayed value and the actual real value under the hood.  KSPFields don't provide a way to massage the value with a sort of "ToUserRange" or "ToAPIRange" conversion or anything like that.

So the underlying range of [0..100] *IS* exposed to the kerboscript via GETFIELD and SETFIELD, and we can't change that.

That's why I'd say, reluctantly, that we should probably make THRUSTLIMIT be ranged from 0..100 even though it makes it inconsistent with THROTTLE, because otherwise we make it inconsistent with **itself** depending on which kOS API calls are used to get at it, and that's even worse.

**Comment by Dunbaratu** [comment]
closed because #559 was pulled.
