### ISSUE TITLE
Error detaching a kOS-enabled part from a vessel

### ISSUE THREAD

**Issue by Gaiiden** [KSP-KOS/KOS#555]
Full details in [forum thread](http://forum.kerbalspaceprogram.com/threads/68089-0-90-kOS-Scriptable-Autopilot-System-v0-15-5-2015-1-3?p=1711892&viewfull=1#post1711892).

Basically, anytime something is decoupled and contains a kOS module it's impossible to run a script on it until you reload the craft

Tested on 0.90 w/ latest 0.15.5 release

**Comment by Dunbaratu** [comment]
Is the problem re-creatable with a vanilla KSP part instead of having added kOSProcessor to another part with ModuleManager?

**Comment by Gaiiden** [comment]
I assume by "vanilla KSP part" you're referring to the ones that come with kOS?

**Comment by Dunbaratu** [comment]
Yes.  Using ModuleManager to add the kOSProcessor to a part that we didn't expect it to be on can cause behaviors we have a hard time tracing down.

**Comment by DarrenNine** [comment]
I have the same issue, first noticed in a modded install, here's logs and a short vid.

https://www.youtube.com/watch?v=k74kgx83on4&feature=youtu.be
http://www.mediafire.com/download/bzju70j56q6o0yr/kOS_Logs.zip

After that I made a clean stock install with just kOS and AGX and the same thing happens using the same craft in the vid.

**Comment by Dunbaratu** [comment]
I'm going to add the following important note to the description of the problem, after I played around with it a bit:

If you have two kOS computers on the vessel, with the decoupler somewhere between them such that after the decoupling there will be one on each half of the vessel, then this bug only happens to one of them - the other one is fine.  It seems to only occur on the one that's part of the "new" vessel, not the one that's part of the "old" vessel.

When a vessel breaks into two parts (either from undocking or from a decoupler or from a catastrophic collision), then where there was once one vessel there are now two.  The way this is accomplished is to detach the "branch" of the parts tree at the break-off spot, removing it from the original vessel,  And then that sub-tree of parts that starts from there becomes a brand new vessel, with its root part being the part that was adjacent to the break-off spot.

This bug only happens on the new "branch" ship, not the original ship.

I suspect the cause is the fact that something in the orphaned CPU is probably still referring to its original parent vessel, and this isn't being updated properly to refer to the new vessel that just got made.

That would also explain why leaving the scene and then coming back to it fixes the problem.  When it packs up the ships into "storage", and then rebuilds them back again, doing so resets the CPU's idea of which vessel it's a part of.
