### ISSUE TITLE
Alternative color scheme HSV

### ISSUE THREAD

**Issue by erendrake** [KSP-KOS/KOS#619]
with the docking vecdraw and the new highlights I have feel a need for a different color scale. I have experience with HSV and so i think ill implement it. its a cylindrical projection of the RGB scale 

![image](https://cloud.githubusercontent.com/assets/486486/6398701/91dc3aea-bdaa-11e4-8be9-6493596f36c5.png)

http://en.wikipedia.org/wiki/HSL_and_HSV

sample algorithm 

http://www.splinter.com.au/converting-hsv-to-rgb-colour-using-c/

**Comment by Dunbaratu** [comment]
I hope you're just planning on making new suffixes to the existing color object rather than making a second kind of color object, which would be a pain.  It's better to only have one kind of color so places in the code that expect a color don't have to make two cases all over the place.  I'd say keep the RGBA color as the actual color under the hood ,as it's what Unity is expecting, and just make an alternate constructor to make an RGBAColor given HSV values.

I'm really not a fan of HSV for a variety of reasons, (I don't like how it gets mangled when converting into RGB, which is a color cube rather than a color sphere and causes the values of the HSV tuple to no longer be orthogonal to each other (i.e.brightness is limited by what you chose for hue and saturation).

**Comment by erendrake** [comment]
It will be its own color type that likely extends the RGBA type to add new suffixes, everywhere else in the system we would use the RGBA type. 

With many visualizations is it helpful to show relationships with hue while varying something like saturation to show magnitude or change, this scale removes the burden of calculating the rgb values that keeps hue fixed. I think this would be especially useful for vecdraw or the new highlight feature :)

**Comment by Dunbaratu** [comment]
Why does it have to be a separate type?  Is the conversion HSV- > RGB a one-way only operation so you need to retain the HSV values?  If there exists a reverse operation RGB -> HSV then you can just store the values internally as RGB and just provide the conversion back out via H, S, and V suffixes.  Then we only have one sort of color type.
(For example, you can make a Direction or rotation a number of different ways, but once you make it then internally it's always turned into a Quaternion).

**Comment by erendrake** [comment]
I have a few reasons for making HSV its own type

* the internal structure if RGBA and HSVA are pretty similar, 4 floats. I would have to throw some kind of type variable or enum in to decide which it is and that is more smarts than i like constructors to have or i would have to make RgbaColor's constructor non-public and add static builders with names for the color spaces otherwise i would always worry about calling the correct constructor. That doesnt seem like it buys me anything that a derived class doesnt. 
* RGBA is what many people will use because they are more familiar with that scale, i dont want to make that experience more confusing. 
* The HSV type is a proper super set of the RGB because everything eventually gets converted to RGB so it logically makes sense as a derived type.
* I wanted to override the ToString() to contain HSV information, this looks to be the cleanest way to me

**Comment by Dunbaratu** [comment]
Of all those reasons, only the last one about ToString makes any sense to me.
The whole point of me asking if here is a perfect mapping back and forth between RGB and HSV is that if there is, then you don't *need* to store HSV values to make it *appear* to be HSV in the public access properties and methods.  The whole idea of needing to flip the meaning of the 4 floats isn't true.  You pick one of the two system, store the values that way no matter what, and then make your Get/Set properties perform the conversion to give the illusion of the other system.

Thus all color objects have BOTH the set of :R, :G, :B suffixes AND  the set of :H, :S, and :V suffixes, regardless of how they got constructed.

**nitpick** : HSV is emphatically NOT a superset of RGB if the mapping is two-way.  For it to be a superset there'd have to be a color that can only be expressed in HSV that can't exist in RGB.

**Comment by Dunbaratu** [comment]
(oops closure of issue was accidental - clicked the wrong "comment" button.)

**Comment by erendrake** [comment]
I do not want to have every color projections to exist in the same structure, if i did want that i would have put them together. I dont think that having all color dimensions is appropriate for one structure because they are all special tools that manipulate color for different reasons. eventually we would end up with the RGBAHSVCYMKLAB color class and that is not an exciting prospect

**Comment by Dunbaratu** [comment]
Imagine this scenario: I have a color made wih RGB.  I'd like to see what it's equivalent HSV values are.  I have to create an HSV object to do that because you made the HSV class smarter than the RGB class.  But if I want to go the other way around I don't.  HSV knows how to pretend to be RGB, but RGB doesn't know how to pretend to be HSV.

You've implemented it in a way so as to make RGB irrelevant, because everything RGB can do, HSV can do better.  They aren't equal citizens to each other.

**Comment by erendrake** [comment]
RGBA is not irrelevant, it is the base type and all of the color bindings goto it rather than HSV. HSV is an alternative. the same as a CYMK or any other alternative scheme. would it make you happier if the HSV type could not display RGB values?

**Comment by erendrake** [comment]
I saw this today so i thought i would share.

![image](https://cloud.githubusercontent.com/assets/486486/6511843/a89b68fa-c32c-11e4-8d60-fe2b85f6a265.png)
