### ISSUE TITLE
New Feature: Make diskSpace parameter of KOSProcessor module tweakable

### ISSUE THREAD

**Issue by ZiwKerman** [KSP-KOS/KOS#653]

**Comment by hvacengi** [comment]
Looks like this may also eliminate the need for #573 which is good since I haven't spent any time working on my suggestion anyways.  I'm compiling the source to check a fix for another issue anyways, I'll check out this new option at the same time.  I think I'd recommend closing #573 at the same time as this issue.  At the very least the multipliers can always be changed if the need arises in the future.

**Comment by ZiwKerman** [comment]
Solved and merged
