### ISSUE TITLE
Can't open terminal

### ISSUE THREAD

**Issue by JDTiger** [KSP-KOS/KOS#699]
I Downloaded kOs today and apparently when I build a craft with an SCS an rightclick the module, it doesn't show me the options to open the Terminal or toggle power.

Hope someone can help me, greets JD_Tiger
(I posted this also in niveks KOS github, but i think this is more up-to-date)

**Comment by ZiwKerman** [comment]
You need to launch first, then click on the kOS icon in the upper right corner - it will open a list of all terminal windows in your craft.

**Comment by ZiwKerman** [comment]
Like so 
![screen shot 2015-03-31 at 14 40 22](https://cloud.githubusercontent.com/assets/11242352/6920041/ee0d90ca-d7b3-11e4-86cc-edc92c629731.png)

**Comment by JDTiger** [comment]
Nope, nothing...
with either of the SCS...

**Comment by ZiwKerman** [comment]
Can you post your log here? It seems that kOSProcessor module did not start properly, maybe some errors from the log may indicate the source of the problem

**Comment by JDTiger** [comment]
https://drive.google.com/open?id=0BypxFvfIp362YnhQbHhwcTVaOXM&authuser=0

**Comment by ZiwKerman** [comment]
Cannot access - share it please.

**Comment by JDTiger** [comment]
sorry, long time sinceusing of googledrive :D 
https://drive.google.com/file/d/0BypxFvfIp362YnhQbHhwcTVaOXM/view?usp=sharing

**Comment by ZiwKerman** [comment]
This is odd, but KOS.dll was never loaded. Can you reinstall latest release of KOS from this github? 
https://github.com/KSP-KOS/KOS/releases/latest

**Comment by JDTiger** [comment]
wasn't even in the Folder :D

**Comment by JDTiger** [comment]
Works now...
Thanks

**Comment by DavidB1024** [comment]
Hello, I just installed KOS and have the samen problem... Tried switching between 32 bits/64 bits KSP, did a fresh install of KSP with KOS.
My other mods are: MechJeb2 and Environmental Visual Enhancements

**Comment by dgalide** [comment]
hello guys, i've the same problem.. i reinstalled 3 times and no terminal ! do i have to install something ? for the moment i put GameData in the ksp directories, i can see and install the control module but on right click i just have 'electricity'..

**Comment by Efratror** [comment]
Have you installed kOS in the following path: `/Kerbal Space Program/GameData`?

GameData is a map inside the KSP installation folder and could you upload a log?

**Comment by dgalide** [comment]
hum yeah, here the path "/Kerbal.Space.Program/GameData/kOS/" 
how do i get the logs ?

**Comment by Efratror** [comment]
in the game type `alt+F2` and copy the contents

**Comment by dgalide** [comment]
[log.txt](https://github.com/KSP-KOS/KOS/files/518385/log.txt)
here complete logs. Thank you for your rapidity !

**Comment by dgalide** [comment]
that's what i have on right click
![screen shot 2016-10-09 at 5 30 58 pm](https://cloud.githubusercontent.com/assets/16493495/19221575/4c4c169e-8e46-11e6-88ed-454448b3bdf4.png)

**Comment by Efratror** [comment]
It seems like there is something wrong with ksp it self, when reading the logs it produces around 1100 lines of error's and warning messages, mainly about the `.cfg` files. So try re-installing ksp.

**Comment by TDW89** [comment]
@dgalide It looks like you have KSP version 1.0.2 installed and are trying to run mods intended for version 1.1.2
Either Update your version of KSP or look back thorough the release versions of any mods you want to use for the correct ones. (Which I think would be V0.17.2 for KOS)

Lots of new stuff has been added since then so you are best off updating KSP though.

**Comment by dgalide** [comment]
ok i'll reinstall ksp. thanks guys for your help

**Comment by Dunbaratu** [comment]
I wonder if we need this following tidbit in some kind of FAQ that is prominent and easy to notice:  "If you can't get the terminal to open, please don't automatically report it as being the "same" problem as someone else who had the same thing happen based just on that symptom alone.  It's a common side effect experienced by any error that happens to occur during a particular window of time.  Check the error logs first and see if it's the same thing their error logs showed during their bug report.  If it's not the same,, then open a new issue for it instead."

Not to berate you, @dgalide:  the fact that you did a search first to see if the issue already exists is a good thing and I wish more people did that.  It's just that in this particular case, we get a lot of "this bug didn't get fixed like you said it did..." because of how this particular symptom is just a side effect of a thousand other possible causes.

The actual problem doesn't directly cause the terminal not to be accessible.  It's just that it not being accessible is the default if the mod never gets far enough along to finish its initializations where it sets up that part of the interface.  Any error that gets thrown any time before it gets that far will prevent it from reaching those steps.

**Comment by Efratror** [comment]
I think its a good idea to build some kind op faq section on the wikipage. But maybe it's time to take it one step further and set up an forum specifically for kOS not only for issues in the code but also for helping each other out with writing scripts, installation problems and other kOS related things. Because at this point  there isn't really a way for us users to communicate with each other. Aside for this github page.

**Comment by TDW89** [comment]
Like [this](https://www.reddit.com/r/Kos/)? :-P

**Comment by Efratror** [comment]
Damm, google never showed me this when I searched kOS. Thanks @TDW89

**Comment by TDW89** [comment]
@Dunbaratu would the reddit be a good thing to add to the list of links on the github front page?

**Comment by oli28syko** [comment]
Hi everyone.

So still no solution? I have everything updated and still I cannot install the mod...

**Comment by hvacengi** [comment]
@oli28syko are you sure that you're using the correct release for your version of KSP?  Pay very close attention to which version of KSP is listed as being supported on the release page: https://github.com/KSP-KOS/KOS/releases 

The previous issues were related to the KSP version.  Or do you mean that you are looking for an update to somehow clarifying that a version mismatch will result in the pop up menu breaking?
