### ISSUE TITLE
Short script brings game into a corrupt state.

### ISSUE THREAD

**Issue by janismac** [KSP-KOS/KOS#712]
I wrote a program that somehow brings the game into a corrupt state. I dont understand what's going wrong. But I managed to reduce the code to the following while still reproducing the issue.

    set warp to 4.
    wait 1.
    set warp to 0.
    stage.
    until 1=2
    {
        set ship:control:mainthrottle to 1.
    }

I made a ZIP with the necessary files and instructions to reproduce the problem.
Link: https://dl.dropboxusercontent.com/u/109177254/bugreport.zip

The following problems occur after that setup:
* Quicksave is not possible
* Timewarp on rails is not possible (where it should be)
* In Orbit Map, the blue trajectroy of the rocket is missing
![screenshot](https://cloud.githubusercontent.com/assets/2456759/6973685/c05f539a-d98c-11e4-8162-d225c3c2cfe4.png)

**Comment by erendrake** [comment]
Thank you for your report! we will take a look at this soon

**Comment by Dunbaratu** [comment]
The relevant part of it is the screenshot claiming "Cannot warp faster than 1x while moving over terrain"... Huh?  At 172km up?  How weird.

I remember some point ages ago, hearing one of the KSP devs answer a question about why on earth we can't just instantly warp from 10000x down to 1x?  The necessity of slowly passing through all the warp states on the way often makes people miss their intended moments.

And it was something about how the game needs to have a moment to reset things and find itself after each change and if the change was too much all at once it somehow barfs at that.

So I wonder... is that rule only being enforced by KSP in the user interface and NOT in the KSP API?  Are mods capable of changing warp speeds faster than a user can manually, and is that invoking a problem?

A test to see if this is the problem is to replace the instant warp changes with steps that force a physics tick between them, like so:

```
set warp to 4.
wait 0.0001.
set warp to 3.
wait 0.0001.
set warp to 2.
wait 0.0001.
set warp to 1.
wait 0.0001.
set warp to 0.
wait 0.0001.
```
anyway, it's just a random guess - I could be barking up the wrong tree.

If that makes the problem go away, then maybe it means kOS needs to somehow queue up the changes and spread them out between updates.  (each update only allowing warp to change by plus or minus one toward the goal value.)
