### ISSUE TITLE
log command does not respect disc size

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#724]
how to reproduce:
1. let this program run or quite a while
```
set i to 0.
until abort {
  print i.
  log i to log.
  set i to i + 1.
}
list files.
```
2. press abort button
3. now you will see a file on your disk bigger than the disk itself.
P.S.
because it is possible to log kOS code this trick could be used to exceed available disk space.

**Comment by erendrake** [comment]
you are a sneaky bugger :)

**Comment by erendrake** [comment]
shoot me an email, erendrake@gmail.com. if you are testing you might as well have a more recent release :)

**Comment by Dunbaratu** [comment]
> bigger than the dick itself.

Whoa there, easy fellah.

**Comment by Dunbaratu** [comment]
Hmm I think fixing this would be best designed by addressing it at a much lower level of the system than just the "log" command.  The bug is a natural outcome of the fact that we only check file size when making a brand new file, not when growing the size of an existing one.  So if the new file's contents are known in one big go, as happens with a copy or something like the text editor's memory string buffer being dumped into a file all at once, we can get file size checking right.  But when the file's contents are being appended to a bit at a time, we aren't checking the size on each write operation.

Rather than fix it in "log", I'd rather see "log" calling some primitive "append to file" operation, and the primitive "append to file" would be responsible for the check.  (That way we've already solved it for any future enhancements we don't know about yet that might also write files that way.)

**Comment by abenkovskii** [comment]
@Dunbaratu Yes I always think that the generic way is the right one.

**Comment by abenkovskii** [comment]
Strange. There is an "append to file" function, `log` command uses it and I can't find a bug in it.

**Comment by abenkovskii** [comment]
1. I regret I looked into this code. It needs refactoring:
GetByName: https://github.com/KSP-KOS/KOS/blob/4e2a68c13f360816a9ae2931ee0d69e5d1df4bec/src/kOS.Safe/Persistence/Volume.cs#L49
Does exactly the same as FileSearch: https://github.com/KSP-KOS/KOS/blob/4e2a68c13f360816a9ae2931ee0d69e5d1df4bec/src/kOS.Safe/Persistence/Volume.cs#L190
2. I found the source of the problem:
The line `file.StringContent = file.StringContent + textToAppend` actually alters the original file: https://github.com/KSP-KOS/KOS/blob/develop/src/kOS.Safe/Persistence/Volume.cs#L102

**Comment by abenkovskii** [comment]
Ok. May be "I regret" was too rude. But things like this or [this](https://github.com/KSP-KOS/KOS/blob/develop/src/kOS/Screen/KOSToolBarWindow.cs#L482) (it assumes the value can be null and then [a couple of lines later](https://github.com/KSP-KOS/KOS/blob/develop/src/kOS/Screen/KOSToolBarWindow.cs#L572) compleately ignores the safe check) annoy me.

**Comment by Dunbaratu** [comment]
The second one is worth complaining about, the first one is different, because they're in two different methods that only happen *at the moment* to be called in such a fashion that the first gets called before the second.  

There's a principle that a method shouldn't have its integrity be too dependent on the fragile assumption of knowing how and when the user of it will call it, even if that user of it is yourself.  Treat yourself as if you were just as likely to be ignorant of your own design as anyone else would be.  It's the same principle as the one that says to use those XML document comments for your own API for yourself to call in the same way you would for somebody else to call.  You never know when someone else will take over for you, and you never know how forgetful your future self will be.

When I took over most of what marianoapp was doing, the lack of explanatory documents in the compiler and opcode system made it a bit painful to work out what was going on some of the time.  I could see *what* the code was doing, but not *why*.  A very common thing I was saying to myself was "This looks weird to me.  Is that because I don't understand the design, or because the design has a flaw?"  Some explanatory comments would have helped resolve a lot of those quicker.

**Comment by abenkovskii** [comment]
What about GetByName and FileSearch?
> There's a principle that a method shouldn't have its integrity be too dependent on the fragile assumption of knowing how and when the user of it will call it

Then `ThrowIfInvalid` should not depend on the assumption that it will be called after `ProcessItem`

**Comment by abenkovskii** [comment]
I'm going to try fixing this and #985.
