### ISSUE TITLE
infinity RAM

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#725]
While having a limited disc space kOS computer seems to have infinitely large RAM. So I can just store my code in a giant global list and than use log to temporarily load certain parts of it to my "hard drive".

**Comment by abenkovskii** [comment]
```
set result to list().
set i to 0.
until i > 30000 {
  print i.
  result:add(i).
  set i to i + 1.
}
print "list length: " + result:length.
```

**Comment by Dunbaratu** [comment]
I think some classic old-school UNIX terminology could be handy here when describing the issue:
The memory that a process "owns" can be divided into 3 sections:

  - "text area" - the part of the memory where the machine language program is kept.  (despite the term, it has nothing to do with "text" as in ASCII or Unicode).
  - "heap space" - the part of the memory where the user-managed, random-access chunks of memory are kept ("user-managed" from the OS's machine language point of view.  As far as the OS is concerned, even something like a Java program is still just a user program managing its own memory, because from the OS's point of view, the "user program" it's seeing is the JVM.).
  - "stack area" - the local vars that are rigidly enforced to follow a stack structure.

The reason for the split was because the OS itself can manage those 3 kinds of things differently.  (i.e the "text area" tends to get populated once up front with one large chunk of contiguous content (when you load the program file) and then stay fixed like that for a long time, while the "heap" tends to get dynamically messed with in little pieces all willy-nilly, while the stack tends to be more static toward the "bottom end" and more dynamic toward the "top end".  These differences mean that what would be an optimal memory management algorithm for one would be pretty poor for the others)

Anyway, the rambling point I'm getting to is that kOS is doing something a bit analogous to that, albeit much more high-level and abstracted.

The "text area" is the program context's List<Opcode> structure.
The "heap area" is the CPU's global dictionary.
The "stack area" is the smaller dictionaries stored per-scope in the "above stack".

Now, to get to my actual point:
The "text area" is easy to restrict.  We can put a max size on the List<Opcode> (it sort of has a hidden one already, in the form of labels that have to fit in 4 digits, so you can have instruction 0000 through 9999 and then it might barf on instruction 10000 not fitting into the naming scheme - I'm not sure because I haven't tried yet).

But the other two are a LOT harder to restrict.  In your example script above, "result" lives in the global "heap" as a *single* variable, because we're just borrowing C#'s own stuff and not dropping down all the way to byte-by-byte manipulation.  So as far as kOS thinks of it, "result" is just one single item.  It's a single variable.  It happens to be a single variable of type ListValue(), which in turn contains inside it a C# List&lt;object&gt; but the point is that kOS isn't counting how large it is.

And adding that support would be waaaay expensive.  It would mean having to track how *big* the objects in the heap (and the stack) are, not just counting how many of the individual identifiers you have.  A single identifier might refer to a rather big object, as is happening in your example script.

I'm inclined to say "don't fix it".  Just because it's not a simple fix, it would incur some runtime expense to do it, and doing a lot of effort to make kOS *less* powerful seems like the exact opposite of how we should be spending our time.

**Comment by abenkovskii** [comment]
@Dunbaratu It all depends on an answer to one simple question: have you ever exceeded the 10,000 bytes limit? If not or not by another 100,000 bytes there there is nothing to worry about because no one will really benefit from abusing this feature.

**Comment by abenkovskii** [comment]
Now I dislike the idea of limiting the RAM. (Though it can probably be done by with wrapping everything with `Encapsulated`: #334)
