### ISSUE TITLE
[enhancement] setboot and list boot commands

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#760]
This issue was split from #758.

**Comment by ZiwKerman** [comment]
CPU always tries to run file named "boot.ks" from local volume on startup and this behaviour is hardcoded and  buried quite deep. That is why I did not change it when I was doing a UI pass for boot files.

One possible workaround is to overwrite the boot.ks file with the file you need, but you don't need a separate command for it.

**Comment by erendrake** [comment]
@ZiwKerman so do you think adding some file tools like #754 would make this moot? i guess you could do most of it with rename.

**Comment by ZiwKerman** [comment]
Yes, i think #754 will also solve this one too

Basically `setboot to xxx` would equal `make copy of xxx as boot` executed on core's local volume

**Comment by hvacengi** [comment]
We could, in theory, revise the boot script code so that the cpu reads the processor's bootFile field in order to use it.  But I think that the `copy ... as ...` method would be more consistent with what a user would expect on a traditional computer, that is to say the computer will always look for the same file to boot from.  If the copy command could be modified to all `copy ... [to ...] [as ...]` with `to` or `as` being optional then there would be only one command to remember, with two natural keywords to remember to specify how you would like to copy. How extensible is the language for adding multiple clauses/keywords?  

(I wasn't sure if I should put this here or in #754 , it's a little of both).

**Comment by abenkovskii** [comment]
@hvacengi So why don't create a two copies of this message than?

**Comment by abenkovskii** [comment]
Closing it. Implementing #754 is sufficient.
