### ISSUE TITLE
list volumes in produces a list of structure 

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KOS#774]
Possibly related to #757 
```
list volumes.
Volumes
ID     Name                            Size
-------------------------------------------
0      Archive                           -1
1*                                    10000
2                                     10000

list volumes in volList. print volList.
LIST of 3 items:
   [ 0]= Structure
   [ 1]= Structure
   [ 2]= Structure
```
other than the list length being the same none of the data is useful. There is no way to get information like size, free space or volume name in a script readable fashion using the list command.

**Comment by abenkovskii** [comment]
1. it is #731 and it will be fixed in the next release (the code is already changed in dev branch). 
2. despite being undocumented volumes actually have suffixes. Look [dev branch](https://github.com/KSP-KOS/KOS/blob/develop/src/kOS.Safe/Persistence/Volume.cs) [master branch] (https://github.com/KSP-KOS/KOS/blob/master/src/kOS.Safe/Persistence/Volume.cs#L45)
