### ISSUE TITLE
(enhancement) Python-like "for i in range(begin, end, step)"

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#808]
Similar to this issue: #40
It would be nice if instead of this:
```
set i to 0.
until i >= n
{
  do stuff.
  set i to i + 1.
}
```
I could just type:
```
for i in range(n)
{
  do stuff.
}
```

**Comment by abenkovskii** [comment]
Just in case you don't know: Python has 3 versions of range function:
1. range(begin, end, step)
2. range(begin, end) // step defaults to 1
3. range(end) // from 0 to end
P.S. In python 3 `range` returns an iterable to not to waste memory
P.P.S. It should probably be easy to add this feature because `for item in container` is already implemented in kOS.

**Comment by Dunbaratu** [comment]
While this is nice, I'd prefer it if we FIRST implement the basic low-level 3-part C-like for loop so users have the full power of that, and then add nice euphamistic high level alternatives later.

I get annoyed at having to do basic counting loops with UNTIL instead of a nice 3-part FOR.

The low-level 3-part loop is a good underlying versatile tool that can do everything, although a bit less nice to look at.  Implementing it gives people *everything* in one easy step (for us).  Then we can layer nicer syntax atop it as we go.
