### ISSUE TITLE
Unsetting target.

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KOS#863]
There is no documentation on unsetting target (that I could find).
```
unset target.  // does nothing.
set target to " ". // throws an exception.
set target to false. // throws an exception.
set target to body. // this works but is not documented.
```

**Comment by Dunbaratu** [comment]
IMO this should be fixed thusly:  We make a special static instance of IKosTargettable called NoneTarget.  When you set the bound varaible ``TARGET`` to something invalid, it should set it to NoneTarget.

i.e. this line from VesselTarget:
```
        public static void SetTarget(IKOSTargetable val)
        {
            if (val.Target != null)
            {
                SetTarget(val.Target);
            }
            else
            {
                throw new Exception("Error on targeting " + val);
            }
        }
```
Instead of throwing an exception, it should set the target to NoneTarget there.
(Note, val.Target == null whenever the thing you set the target to is not an IKosTargettable (the place this is called from does an "as IKosTargettable" operation, so if it's a string, integer, whatever, it comes through as null).

**Comment by surge9000** [comment]
You can close this. Unset a target with:
set TARGET to "".

Actually any non-existant target works, e.g. set TARGET to "blafoobarblabberdydoo".
To be honest, the syntax isnt the best, but eh.. there are bigger fish to fry...
