### ISSUE TITLE
[bug] Variables with names starting with "not" interpreted as "NOT <rest of var>"

### ISSUE THREAD

**Issue by kaufman-bryce** [KSP-KOS/KOS#900]
SET note TO "some text".
    PRINT note.
    Undefined Variable Name 'e'.
    PRINT notasdasd.
    Undefined Variable Name 'asdasd'.

Relevant sections of stack trace: 

    1/planeautopilot.ks    91:9   0753 push $<argstart>
    1/planeautopilot.ks    91:18  0754 push $e 
    1/planeautopilot.ks    91:18  0755 not <<--INSTRUCTION POINTER--
    1/planeautopilot.ks    91:18  0756 call print() 

    interpreter history    70:1   0877 push $<argstart> 
    interpreter history    70:10  0878 push $asdsdsd 
    interpreter history    70:10  0879 not <<--INSTRUCTION POINTER--
    interpreter history    70:10  0880 call print()

This will occur with any variable name starting with NOT. Does not occur with variable names starting with OR or AND.

**Comment by Dunbaratu** [comment]
Confirmed.

The reason it happens with 'not' and not with 'and' or 'or' is that in order for the parser to "pick" that interpretation it has to be valid syntax.  'Not' is a unary operator so that *print not e* would potentially be valid.  Whereas *print and e* wouldn't be because 'and' is binary and needs another expression on its left side.

The real question is, why is TinyPG's lexer being dumb and not taking the longest valid string when tokenizing, like lexxers usually do?  I'll have to see about that.

**Comment by Dunbaratu** [comment]
Addressed with PR #901
