### ISSUE TITLE
mean anomaly is in radians

### ISSUE THREAD

**Issue by ghost** [KSP-KOS/KOS#927]
maybe this is intended and there's a reason i'm not aware of. docs mention all attempts were made to give everything in degrees...this might be one that was missed.

obt:meananomalyatepoch is 0 at periapsis -> ~2pi where i'd expect 0 at periapsis -> ~360

i'm learning as i go and that had me banging my head on the wall for a while!

**Comment by Dunbaratu** [comment]
Okay that's definitely wrong.
I mean it's right, scientifically, to use radians for things as they are mathematically better, but kOS has established the pattern that all angles should be done with degrees everywhere because it's more newbie-friendly, and to have one weird exception case to that rule is wrong.

**Comment by liasdf** [comment]
yeah, that's all that bit me was the inconsistency. heck, it's less characters to type 360/obt:period anyway, so i'm not surprised if no one uses that member ever. since there's no :meananomaly member now, maybe deprecating it and introducing orbit:meananomaly (in degrees) is a good idea? atepoch seems superfluous since epoch is always t+0.
