### ISSUE TITLE
MAXTHRUST and AVAILABLETHRUST only account for sea level thrust

### ISSUE THREAD

**Issue by space-is-hard** [KSP-KOS/KOS#940]

**Comment by SirDiazo** [comment]
I'm not sure what AVAILABLETHRUST means in kOS, but the new math for MAXTHRUST can be found here:

http://forum.kerbalspaceprogram.com/threads/117668-KSP-1-0-ISP-Engine-Values?p=1883077&viewfull=1#post1883077

**Comment by Dunbaratu** [comment]
AVAILABLETHRUST means taking into account the thrust limiter setting.

**Comment by erendrake** [comment]
the engineadapter code is a little strange so ill take this one.

@SirDiazo thanks for the formula :)

**Comment by Dunbaratu** [comment]
From what I heard, the new formula has the throttle affecting it in a new very indirect way, so is it no longer linear scaling from 0% to MAXTHRUST?  If that stopped being linear then we would probably also need to provide users with some sort of adaptive formula - thrustatthrottle(0.75) for example.

**Comment by WazWaz** [comment]
I'm using this for now:

```
declare function MaxShipThrust
{
	LIST engines IN engs.
	local mth to 0.
	for eng in engs {
		if eng:SLISP > 0 {
			set mth to mth + eng:MAXTHRUST*eng:ISP/eng:SLISP.
		}
	}
	return mth.
}
```

**Comment by hvacengi** [comment]
I have this working in my development branch for normal rocket engines but not for jets.  I don't know how much time I'll have tomorrow to work on this due to a deadline at work, but if any one else would like work from where I am, I can push to my personal branch.  I feel like I'm close on the jets, it looks like I'm calculating their thrust to be pretty close to (if not exactly) twice the actual value, but I don't want to just assume that dividing by 2 is the answer.
