### ISSUE TITLE
strings returned by :allevents and :allactions are unusable.

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KOS#947]
would it be possible to have kOS return a list of just the event or action names in a module.
At the moment :allevents gives a list of string where each string is in the format `(callable) <event name> , is KSPEvent`

As far as I can tell this means that you cant write a script that is un-awair of the event name.
In some situations it would be useful to be able to do this eg. running all experiments with:
```
for experiment in ship:modulesnamed("ModuleScienceExperiment") {
 for event in experiment:allevents {
  experiment:doevent(event).
 }
}
```
possible solutions: allevents could either return a list of structures (so it maintained it's printed appearance in the terminal)  but have a suffix that was just the event name, or a list of  strings that were just the event names.

**Comment by erendrake** [comment]
because you are right that `:ALLFIELDS` has less utility when you are trying to call a field directly doing something like 

    SET bar TO SHIP:PARTS[0]:GETMODULE("FOO").
    bar:DOEVENT(bar:ALLEVENTS[0]).

Would it be better if you could do 

    SET bar TO SHIP:PARTS[0]:GETMODULE("FOO").
    bar:DOEVENT(bar:ALLEVENTS[0]*:NAME*).

**Comment by Dunbaratu** [comment]
I thought of making an event into an object when I first implemented this.  The reason I didn't go for it was because of the annoying way the menus work, where the GUI changes constantly and replaces an event with the opposite event for some toggleable things.  That makes it so that an event is only valid the moment you see it - you can't save a handle to the event and use it later because it can go away by then from the UI, and we're trying to adhere to the rule that we don't second-guess why other mods have removed a thing from the GUI - once they have, it's immediately disallowed to be called.  Allowing handles to live on so they could be called after the event is removed from the GUI menu would violate that.

**Comment by TDW89** [comment]
Would adding a `:visible` suffix as well as a `:name` suffix work? That way kos could throw an exception if the suffix can't be used and the user could write in protection for it.

**Comment by Dunbaratu** [comment]
didn't auto-close when PR was merged.
