### ISSUE TITLE
set Vector:Direction changes magnitude to 1.0

### ISSUE THREAD

**Issue by StrangeBeing** [KSP-KOS/KOS#952]
The docs state that "Vector:DIRECTION" SET
"Tells the vector to keep its magnitude as is but point in a new direction...".

In 17.2 it looks like the magnitude of the resulting vector is being normalized.
This happens:

SET t to V(10, 0, 0).
SET t:DIRECTION TO UP.
PRINT t:MAG.

prints 1.000...

**Comment by hvacengi** [comment]
Thanks for the report.  It looks like we simply applied the rotation to a new unit vector and forgot to multiply by magnitude during a code refactor.  I've made an edit and will test it later today.  If it works as I expect, I'll upload the modifications.  The fix should make the next release.

**Comment by hvacengi** [comment]
Everything worked fine in testing.  I should point out that due to the nature of floating point math, you loose some level of precision whenever you modify a value.  So in the example you provided above, kOS printed the value as something like 9.9999967 (not the exact print, I closed the game before posting this, but you get the idea).
