### ISSUE TITLE
file identifier not updated at rename

### ISSUE THREAD

**Issue by liasdf** [KSP-KOS/KOS#955]
i think that's what's going on anyway. to reproduce:

create a file in archive foo.ks: print "foo".
create a file in archive bar.ks: print "bar".
create a file in archive test.ks: copy foo from 0. copy bar from 0. rename foo to exe. run exe. delete exe. rename bar to exe. run exe.
load up some vessel, copy test and run it.

expected output:
foo
bar

actual output:
foo
foo

run bareword continues to refer to the old script, even though it's deleted. the same sequence of commands from test.ks does work if run interactively.

it's causing me some headaches...i want to keep the current running sequence in a known file name, so reboot or reloading continues where left off. i'm struggling for a workaround since run has to use a bareword.

**Comment by abenkovskii** [comment]
duplicate: #719

**Comment by liasdf** [comment]
i should say i'm struggling for a "better" workaround -- right now i delete exe (the renamed file) and reboot, which causes (assuming i'm in rt range) a lookup of the next sequence script, copy, rename. that works ok, but rebooting right when the launch clamps release...it scares me. :)

**Comment by liasdf** [comment]
dang it i looked and didnt see it. thanks.

**Comment by abenkovskii** [comment]
@liasdf 
I know how it works. It's rather weird in the current kOS version. It's too complex to explain.
Try creating a file "exe_wrapper":
```
run exe.
```
and then using `run exe_wrapper.` instead of `run exe.`
It will work fine in a range of simple cases.
Alternatively you can use lib_exec: https://github.com/KSP-KOS/KSLib/blob/master/library/lib_exec.ks:
```
execute("run foo.").
execute("run bar.").
```
It covers all special cases I can think off.
P.S. `execute("run exe."). delete exe. rename bar to exe. execute("run exe.").` will **NOT** do what you want. File names should differ in order for it to work.
P.P.S. KSLib repository contains other libraries you might want to use too.

**Comment by liasdf** [comment]
nice! having a wrapper should work fine thank you!

i do like the libs, but for gameplay sake i really want to grind it out on my own. i'm also doing ro/rp-0 and trying to stick to 5k per volume...i could runn libs for functions and delete but that feels too cheaty.
