### ISSUE TITLE
Bug with `print at`

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#967]
![screenshot2](https://cloud.githubusercontent.com/assets/11031560/7503690/4f426d60-f44d-11e4-8bb3-58a546418cc6.png)
Every time the last character that `print at` prints is in the bottom right corner it moves the text on the terminal up by one line. It's something wrong in the code that warps the line if it's too long.
In fact I don't understand why we warp lines in `print at`:
![screenshot0](https://cloud.githubusercontent.com/assets/11031560/7503837/231c5d3a-f44e-11e4-8d45-fb2ec4643600.png)

**Comment by abenkovskii** [comment]
Discovered it while testing my lib_gui_box.

**Comment by Dunbaratu** [comment]
In a typical terminal window, when the cursor is at the end of the line and you print one character out, it wraps the cursor to the next line.  If that line is the last one, then it has to scroll a new empty line into existence to keep the cursor from going off-screen.  That's fairly typical terminal behavior.

I'm more wanting to make print at consistent with print, and get it to properly wrap lines, rather than getting it to NOT wrap them, which is the reason it's currently got bugs with printing strings that go off the right edge.

**Comment by abenkovskii** [comment]
It means that I won't be able to print a box surrounding the whole terminal.
![screenshot3](https://cloud.githubusercontent.com/assets/11031560/7504770/71fc267c-f455-11e4-9462-77fd3a64cb6f.png)
I'll have to either not print at the right most column or not print at the bottom line

**Comment by Dunbaratu** [comment]
Correct, but given the desire to keep things the same with the telnet terminal, I don't think it CAN be fixed.  It's an extremely common feature of terminals.

**Comment by abenkovskii** [comment]
I'll mention it in the documentation of lib_gui_box then.
