### ISSUE TITLE
Null ref when trying to rename a file to empty string

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#969]
![screenshot7](https://cloud.githubusercontent.com/assets/11031560/7505129/2dcfc686-f458-11e4-9f1d-d3f8858e3400.png)
It's one of situations that throw an exception that doesn't explain anything.

**Comment by hvacengi** [comment]
I haven't looked into the code, but is it possible that kOS treats empty strings as nulls?  Or at least it doesn't distinguish between an error with a null string vs an error with an empty string?

**Comment by Dunbaratu** [comment]
This may be connected to #974 - because I think some OS's don't allow a filename to be a zero-length string (Unix probably does, as it tends to allow just about any string you can think of as long as it doesn't have '/' in it) , but I doubt Windows lets you do that.)

So it's probably just a special case of the same problem as #974 - you're not getting a very good error message when opening the filename failed.

**Comment by Dunbaratu** [comment]
I suspect so strongly that this is the exact same problem as #974, that since I reassigned that to @erendrake, I'm assigning this to him as well.  If he finds that it's not the same issue, he can assign it back to me.

**Comment by Dunbaratu** [comment]
@erendrake -don't forget to check on this too, it's the same problem as #974
