### ISSUE TITLE
PART:CONTROLFROM seems to be un-settable.

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#978]
The docs say you can do:
```
set part:controlfrom to true.
```
But the CONTROLFROM suffix is defined as a get-suffix, not a set-suffix in PartValue.cs, so it won't let you do that.

Strangely, the code that executes when you try to merely READ the CONTROLFROM suffix looks like it's trying to SET that part to be the controlFROm part the moment you query it, leading to baffling side effect behavior.

**Comment by abenkovskii** [comment]
```
            AddSuffix("CONTROLFROM", new NoArgsSuffix(ControlFrom));
```
```
        private void ControlFrom()
        {
            var dockingModule = Part.Modules.OfType<ModuleDockingNode>().First();
            var commandModule = Part.Modules.OfType<ModuleCommand>().First();

            if (commandModule != null)
            {
                commandModule.MakeReference();
            }
            else if (dockingModule != null)
            {
                dockingModule.MakeReferenceTransform();
            }
            else
            {
                Part.vessel.SetReferenceTransform(Part);
            }
        }
```
From this I assume that the expected usage is `part:controlfrom().` to set a part to control from and no way to get the part you are controlling from.

**Comment by SirDiazo** [comment]
If this is supposed to replicate the "Control From Here" event in a part's right click menu, only parts with ModuleCommand and ModuleDockingNode should be allowed to do so and the ELSE in the above code should not be there.

If the intention is that any part can act as the control from here part, including something like an engine, then the above code is fine.

**Comment by abenkovskii** [comment]
From docs:
>
Part:CONTROLFROM
Access:	Get only  <-- notice this?
Type:	boolean

but:
>
Set to TRUE to cause the game to do the same thing as when you right-click a part on a vessel and select “control from here” on the menu.

There is definitely something wrong with this suffix. Both in docs and in the code.

**Comment by abenkovskii** [comment]
![screenshot6](https://cloud.githubusercontent.com/assets/11031560/7538955/6b449fb4-f5ac-11e4-839a-085f164a3c6e.png)
I get the same error on every part. Even if the control can be switched to the part using "control from here".
https://www.dropbox.com/s/50fhqbe2o7eydpt/conrtrolbug.txt?dl=0

**Comment by xeger** [comment]
It sounds like the consensus fix is to do two things:

1. This property should become a get/set boolean that queries or sets control
2. When setting, eliminate the `else` case per @abenkovskii's suggestion and ensure that kOS control-setting is limited to parts with modules that can receive control via UI

Is that correct?

**Comment by hvacengi** [comment]
I been working on this issue.  The error message made no sense as a kOS error, but the stack trace revealed it was an issue with LINQ.  These two lines guarantee an exception every time:
```
            var dockingModule = Part.Modules.OfType<ModuleDockingNode>().First();
            var commandModule = Part.Modules.OfType<ModuleCommand>().First();
```
`First()` throws whenever the collection is empty and since one of the two collections should always be empty, the reference setting code is never reached.  I'm switching the calls to `FirstOrDefault()` which I suspect was the original intention since that's how most of the rest of the code handles null checks.

Before I submit my PR, I might as well address the other comments in this thread as well.  Do we want to change this to be both get-able and set-able?  Right now, this just behaves as a no-argument/no-return function.  I propose selecting between these options:
1. fix the LINQ error, but otherwise keep the function-like behavior as it is now.
2. part:controlfrom becomes a set/get suffix which accepts and returns a boolean value (as @xeger identified above)
3. keep the function-like behavior that it currently has, but add a set/get suffix to vessel `vessel:controlfrom` which will accept and return a PartValue or the part selected as the control part.
In all cases, parts that do not contain a docking or command module would throw an exception.

I mention point two because the control is really a vessel feature, not a part feature.  It would allow the user to query the control part for the vessel, rather than having to walk the part tree querying each part that could have control.  And keeping the function on the part would still mimic the behavior of the stock menu (which does not hide the "control from here" button when you select a new part to control from).

Let me know what the preference is and I'll get it into a PR.  I've figured out how to determine what part is being used as the control part, so it's just a matter of writing the code and debugging.

**Comment by hvacengi** [comment]
I just thought of one problem with making `controlfrom` into a traditional set suffix: how do you handle setting to `false`?  Do we default back to the vessel's root part, or just throw an exception saying you can only set to true on a part itself, and that you must set to true on another part to change the setting?

Another thought: Technically, the root part doesn't need to be a command or docking part, it can be a lot of different parts.  We should probably allow setting the root part to be the controlled from, even if it is a normally invalid part type.

**Comment by xeger** [comment]
You make some very solid arguments in favor of fixing the current get behavior and then adding `vessel:controlfrom(Part)`; it follows the principle of least surprise and has no weird corner cases. I'd vote for that option.

As for the root part, I forget whether the root part can be controlled-from via the UI; if so, there's no reason not to allow it. (I haven't played much with settable root parts since the VAB gained control over them...)
