### ISSUE TITLE
Incompatiblity with KSP V1.0.2

### ISSUE THREAD

**Issue by joannplano2005** [KSP-KOS/KOS#982]
I installed the lastest KOS Scriptable Autopilot System to KSP V1.0.2. KSP reported that the KSPAIPIExtension.dll file was incompatible.

**Comment by Dunbaratu** [comment]
Yeah, that's sort of dumb because that check is a lie.  What it really means is "This DLL doesn't explicitly mention that it IS compatible", but it reports that as if it means "This DLL explicitly mentions that it is NOT compatible" which isn't the same thing.

The message SHOULD be saying "This DLL doesn't advertise any PROMISE that it is compatible because it claims to have been compiled for an older version.  Sometimes such DLLs still work anyway but you have been warned.".

And this is one of the cases where it does still work anyway.

The message can be ignored for now.  It works.  In the next release it should go away.  There is a new KSPAPIExtensions out there, but the kOS release was made before that existed to be bundled with the ZIP.

**Comment by abenkovskii** [comment]
There actually **IS** a bit of incompatibility: #983

**Comment by Bear67** [comment]
I ran into the problem of not having the most current KSPAPIExtensions.dll in the KOS plugin directory (or rather not having it there at all since the DLL is in the EL Plugin Directory). And was getting an Exception Error code that KOS was looking for version 1.7.3.0 even though 1.7.4.0 was loaded elsewhere and was halting the game from launching. But after coping it from the EL plugin directory to the KOS plugin directory, game launches no problem.

**Comment by hvacengi** [comment]
I think that this was resolved in one our previous releases, at least I think that when I install from ckan on 1.0.4 I don't get the error any more.  This issue should be able to be closed.
