### ISSUE TITLE
Strange incompatibility with Procedural Parts.

### ISSUE THREAD

**Issue by yump** [KSP-KOS/KOS#983]
When I install Procedural Parts 1.1 and kOS 0.17.2 concurrently, this happens:

![screenshot0](https://cloud.githubusercontent.com/assets/2214413/7548410/f24cb224-f5cc-11e4-84d6-26ebdeb549e8.png)

No other mods are installed.  I tested this with a fresh copy of my stock snapshot.

**Comment by abenkovskii** [comment]
> No other mods are installed.

* Technically it's a lie: you also have KSPAPIExtensions (shipped with kOS) and  Module Manager.
* I don't have this problem:
![screenshot2](https://cloud.githubusercontent.com/assets/11031560/7549050/01824c42-f62f-11e4-8e68-fa9601fa0306.png)
* It looks like the only difference between our installations is that I manually updated KSPAPIExtensions because it complained about incompatibility with ksp 1.0.2

1. Download the latest KSPAPIExtensions.dll https://github.com/Swamp-Ig/KSPAPIExtensions/releases
2. Replace your GameData\kOS\Plugins\KSPAPIExtensions.dll with it
3. Report if it solves a problem

P.S. The updated KSPAPIExtensions will be included into next kOS release

**Comment by yump** [comment]
Yep, that fixed it.

**Comment by abenkovskii** [comment]
BTW
1. Thanks for your report.
2. Sometimes it's a good idea to attach not only a screenshot but also <your_ksp_path>\KSP_Data\output_log.txt to the bug report.
