### ISSUE TITLE
`print abc.blarg.` prints "abc.blarg"

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KOS#986]
![screenshot2](https://cloud.githubusercontent.com/assets/11031560/7512702/68c86c98-f4b7-11e4-9e77-9814bdde263f.png)
https://www.dropbox.com/s/rwngwqzxup8es5s/abc_blarg.txt?dl=0 
It's one of "shouldn't work at all but is working" things. Another example: #253

**Comment by Dunbaratu** [comment]
I don't see this as being that important.

It's basically happening because the regex `[a-z0-9_]+\.[a-z0-9_]*` is the pattern for a bareword filename, which gets treated like a literal string in quotes so you can do stuff like ``copy foo.ks to 1.`` instead of having to say ``copy "foo.ks" to 1.``  So fixing it without breaking that would be a horrible mess.

**Comment by erendrake** [comment]
I agree.
