### ISSUE TITLE
MODIFIED and CREATED don't work on files.

### ISSUE THREAD

**Issue by akrasuski1** [KSP-KOS/KOS#988]
According to kOS documentation, FileInfo structure has, amongst others, :MODIFIED and :CREATED suffixes. But when I try to use them on any file (from local volume necessarily, due to bug #757), kOS throws: "GET Suffix "CREATED" not found on object test.ks". Other suffixes are okay (:size, :name, :filetype).

Thanks to abenkovskii, we know that there are no such suffixes in C# code:
https://github.com/KSP-KOS/KOS/blob/6b7d217b11dfed690da105d369083d1a1da1c220/src/kOS.Safe/Encapsulation/FileInfo.cs#L32

So this is either bug in documentation, or lack of implementation.

**Comment by erendrake** [comment]
@akrasuski1 Thanks for finding this, i think it is a error in documentation. i had started to add it and then it felt really odd to be asking the question in real world time and then it didnt make any sense to show in game time because time is such a mutable thing in KSP.

there is also the fact that for many files we simply dont track these dates.

@akrasuski1 do you think they would be very useful to have?

**Comment by akrasuski1** [comment]
In most cases they are useless. What I needed them for, was this: I wanted to have a check that recompiles the file if and only if .ks was modified later than .ksm was, because it takes long time. Without proper string comparison I wouldn't be able to do this even with suffixes in question; but it would be nice if we have some Unix-like timestamp available as number. Or is there another way to do what I wanted?
