### ISSUE TITLE
Documentation error: ENCOUNTER returns object of type ORBIT

### ISSUE THREAD

**Issue by kaufman-bryce** [KSP-KOS/KOS#996]
The documentation for `ENCOUNTER` says that it will return either the special string "None" or an object of type BODY. In practice, it is instead returning the orbit patch of the encounter (which is more useful anyway).

**Comment by baloan** [comment]
Hm, strange. I just hit a breaking change in encounter while regression testing the mission toolkit. I can't find ENCOUNTER in the doc at http://ksp-kos.github.io/KOS_DOC, just information about PATCHES.
```
print encounter.
ORBIT of <unnamed>
```
instead of "Minmus" which worked in ancient times.
Is this legacy functionality?
What is the seminal way to identify the encounter body on a node trajectory?
While setting up a trajectory to Minmus is easy, checking whether there is a Mun encounter enroute is not.
![minmus encounter](https://cloud.githubusercontent.com/assets/651799/7596203/4eacb254-f8ec-11e4-935f-75097bb3f98b.PNG)

**Comment by kaufman-bryce** [comment]
At the moment, you can can use `ENCOUNTER:BODY`.

**Comment by Dunbaratu** [comment]
The PR was merged a while ago but apparently never auto-closed the issue.
